### PR TITLE
community/imagemagick6: security upgrade to 6.9.10.37

### PR DESCRIPTION
**Pull request by J0WI**
See also https://github.com/alpinelinux/aports/pull/6869

### CODE REVIEW

**Comment by J0WI** [comment]
Only required by `community/ruby-rmagick` (#6871)

**Comment by J0WI** [comment]
@jirutka the list of vulnerabilities here is really scary. Could you please review a backport this?

**Comment by andypost** [comment]
It needs backport, https://abi-laboratory.pro/?view=timeline&l=imagemagick shows some ABI changes
but I bet they too small
```
>>> No soname differences for imagemagick6.
>>> No soname differences for imagemagick6-doc.
>>> No soname differences for imagemagick6-dev.
```

**Comment by andypost** [comment]
Commited to master 7265f5c6

**Comment by J0WI** [comment]
@andypost could you please backport this to all stable branches?

**Comment by andypost** [comment]
@J0WI I have no access

**Pull request closed without merging**
