### PR TITLE
main/icu: upgrade to 64.2

### PR DESCRIPTION
**Pull request by J0WI**
A lot of packages needs to be rebuilt against this.

### CODE REVIEW

**Comment by maxice8** [comment]
According to `apk info -r icu-libs`

icu-libs-63.1-r0 is required by:
firefox-62.0.3-r4
qt5-qtbase-5.12.1-r1
slop-7.4-r0
maim-5.5.3-r0

**Comment by maxice8** [comment]
missing python on depends apparently

**Comment by J0WI** [comment]
Fixed.

**Comment by ncopa** [comment]
This breaks ABI so we need rebuild everything that depends on:
````
so:libicudata.so.63
so:libicui18n.so.63
so:libicuio.so.63
so:libicutest.so.63
so:libicutu.so.63
so:libicuuc.so.63
````

**Comment by ncopa** [comment]
@J0WI we would like to get in touch with you. can you please send an email to @clandmeter or me?

**Comment by J0WI** [comment]
> This breaks ABI so we need rebuild everything that depends on:

Will you bump them after merging this? It would conflict with other PRs when I touch all packages here.

**Comment by ncopa** [comment]
> > This breaks ABI so we need rebuild everything that depends on:
> 
> Will you bump them after merging this? It would conflict with other PRs when I touch all packages here.

Yeah, i think i can bump them. probably easiest that way.

**Comment by ncopa** [comment]
fixed with 334ebffde9dec34becdd628ad56007699e98ea81

**Pull request closed without merging**
