### PR TITLE
main/duplicity: upgrade to 0.8.04 and move to python3

### PR DESCRIPTION
**Pull request by kr0k0**

### CODE REVIEW

**Comment by kr0k0** [comment]
In this step we should also remove the python2 packages "py2-monotonic", "py-boto" and "py2-fasteners".

**Comment by maxice8** [comment]
rename the py- packages in one commit to py3- and then do the changes to make them py3- in another commit.

**Comment by maxice8** [comment]
Example: https://gitlab.alpinelinux.org/alpine/aports/merge_requests/169

**Comment by kr0k0** [comment]
Thanks maxice8!
Is done.

**Pull request closed without merging**
