### PR TITLE
unmaintained/llvm7: move from community

### PR DESCRIPTION
**Pull request by J0WI**
https://lists.llvm.org/pipermail/llvm-announce/2019-May/000083.html

### CODE REVIEW

**Comment by Ikke** [comment]
Fails with:

> \>\>\> llvm7-libs*: Running split function libs...
> mv: can't rename '/home/buildozer/aports/main/llvm7/pkg/llvm7/usr/lib/llvm7/lib/libLLVM-7.so': No such file or directory

**Comment by Ikke** [comment]
According to ncopa, this is an ABI breaking change, so all dependencies need to be rebuilt.

**Comment by ncopa** [comment]
we upgraded to llvm8 instead. I suppose we could upgrade llvm7 and remove the other commits?

7.1 breaks ABI so we'd need to rebuild anything linked to libLLVM

**Comment by ncopa** [comment]
I get this build failure:
````
>>> llvm7-libs*: Running split function libs...
mv: can't rename '/home/ncopa/aports/community/llvm7/pkg/llvm7/usr/lib/llvm7/lib/libLLVM-7.so': No such file or directory
````

**Comment by J0WI** [comment]
Are there any packages left depending on LLVM7?

**Comment by Ikke** [comment]
@J0WI atm, only bpftrace

> testing/bpftrace/APKBUILD
> 9:makedepends="cmake llvm7-dev llvm7-static clang-dev clang-static

**Comment by J0WI** [comment]
`bpftrace` have been updated to llvm8, so llvm7 can be removed.

**Pull request closed without merging**
