### PR TITLE
testing/advancemame: Upgrade to 3.8

### PR DESCRIPTION
**Pull request by tanertas**

### CODE REVIEW

**Comment by andypost** [comment]
btw it looks there's *3.9* version http://www.advancemame.it/history

**Comment by tanertas** [comment]
Maybe for upcoming release. There's no such distribution release for 3.9.

Btw, the big brother is here: #4167 but didn't get merged yet somehow.

**Comment by andypost** [comment]
Yep, there's no such release on GH https://github.com/amadvance/advancemame/releases
Testing and gonna commit

**Comment by tanertas** [comment]
Would you make a review on  #4167 too? I first submit it six months ago.

**Pull request closed without merging**
