### PR TITLE
main/http-parser: upgrade to 2.9.0

### PR DESCRIPTION
**Pull request by misery**

### CODE REVIEW

**Comment by ncopa** [comment]
Seems like it breaks ABI:
````
ncopa-edge-x86_64:~/aports/main/http-parser$ checkapk
--- filelist-http-parser-old    2018-12-28 16:51:06.702308351 +0000
+++ filelist-http-parser        2018-12-28 16:51:06.705641699 +0000
@@ -1,5 +1,5 @@
 .PKGINFO
 usr/
 usr/lib/
-usr/lib/libhttp_parser.so.2.8
-usr/lib/libhttp_parser.so.2.8.1
+usr/lib/libhttp_parser.so.2.9
+usr/lib/libhttp_parser.so.2.9.0
usr/lib/libhttp_parser.so.2.9:    SONAME               libhttp_parser.so.2.9
usr/lib/libhttp_parser.so.2.9.0:    SONAME               libhttp_parser.so.2.9
>>> No soname differences for http-parser-dev.
````

Everything linked against `libhttp_parser.so.2.8` (`apk list --depends so:libhttp_parser.so.2.8`) needs to be rebuilt.

**Comment by tcely** [comment]
TravisCI timed out

**Comment by timbru31** [comment]
What’s the status @tcely ? Have you tried rebasing and/or restarting Travis? :)

**Comment by andypost** [comment]
@ncopa this is a blocker for nodejs updates and travis will not pass because each node package takes ~45m to build but the whole travis run limited by 50m

**Comment by andypost** [comment]
It needs rebase again

**Comment by andypost** [comment]
Travis has not enough time to rebuild both nodejs packages

**Comment by timbru31** [comment]
A rebase should enable Drone builds, maybe those won't time out. @ncopa / @misery

**Comment by misery** [comment]
Drone works

**Comment by misery** [comment]
Well, too late? 

https://git.alpinelinux.org/aports/commit/?id=da25a5be5b33f233119e11f4a9124262b6b8a757

**Pull request closed without merging**
