### PR TITLE
community/erlang: upgrade to 19.3

### PR DESCRIPTION
**Pull request by vorce**
I'm not sure how to test this properly. Any pointers for that would be appreciated. Thanks.

### CODE REVIEW

**Comment by leitao** [comment]
It seems that all the checks passed, but when I ran on my system, I go tthe following error:

`>>> erlang: Entering fakeroot...
>>> WARNING: erlang*: APKBUILD does not run any tests!
    Alpine policy will soon require that packages have any relevant testsuites run during the build process.
    To fix, either define a check() function, or declare !check in $options to indicate the package does not have a testsuite.
>>> erlang: Entering fakeroot...
/usr/bin/abuild: cd: line 2356: can't cd to /home/alpine/aports/community/erlang/src/otp_src_19.1
>>> ERROR: erlang*: package failed
>>> ERROR: erlang: all failed
>>> erlang: Uninstalling dependencies..`

**Comment by vorce** [comment]
Hmm, ok. I will take a look and see if I can fix that.

**Comment by Shizmob** [comment]
@leitao: That seems odd, as 19.1 is not referenced anywhere in the updated APKBUILD, `$builddir` being set to `src/otp_src_19.3`... are you sure you have the correct APKBUILD?

**Comment by vorce** [comment]
Yeah I'm having troubles reproducing the error locally.

**Comment by leitao** [comment]
Right, my fault here. I am sorry for the noise. I am ok with this change!

**Comment by vorce** [comment]
Do you want me to squash these commits?

**Comment by Shizmob** [comment]
Yes, preferably!

**Comment by vorce** [comment]
Done :)

**Comment by Shizmob** [comment]
Thanks, merged!

**Pull request closed without merging**
