### PR TITLE
testing/nss_wrapper: new aport

### PR DESCRIPTION
**Pull request by mterron**
https://cwrap.org/nss_wrapper.html
A wrapper for the user, group and hosts NSS API

### CODE REVIEW

**Comment by mterron** [comment]
This is verified working on multiple environments (bare metal Alpine, Docker on Alpine, Docker on Windows, Hyper-V, VMWare and VirtualBox VMs and even Docker playground).

There's some oddity in the CI environment that segfaults while running tests, I'm unable to duplicate in any environment I have access to.

**Comment by mterron** [comment]
Here's a Dockerfile I've been using to try to replicate the issue:

```dockerfile
FROM alpine

RUN apk add build-base abuild \
	&& adduser -D builder \
	&& adduser builder abuild

COPY APKBUILD /home/builder/nss_wrapper/
COPY nss.h /home/builder/nss_wrapper/

RUN chown -R builder: /home/builder/*

USER builder

RUN cd ~/nss_wrapper \
	&& abuild-keygen -a -n \
	&& abuild checksum \
	&& abuild -r
```

**Comment by dimon222** [comment]
I tried to run build on my Docker for Windows, but received same segmentation fault errors.
Using alpine:latest with /edge/ repositories and updated to latest with "apk update && apk upgrade"

**Comment by mterron** [comment]
> 
> 
> I tried to run build on my Docker for Windows, but received same segmentation fault errors like in CI/CD.
> Using fresh/clean alpine:latest with /edge/ repositories and updated to latest with "apk update && apk upgrade".
> 
> Any chance some dependency missing? Or maybe some breaking change introduced in "edge" repos?
> 
> PS: dockerfile fails on checksum

I managed to reproduce just by pulling alpine:edge instead of alpine:latest. Some edge package must be causing the issue. Will investigate more.

**Comment by mterron** [comment]
Checking the Release Notes for musl, 1.1.20 introduced changes to getaddrinfo however musl 1.1.20 works fine and 1.1.21 breaks the tests
```
musl-1.1.20 - September 4, 2018

    This release introduces the ability to replace/interpose the allocator
    (malloc) subject to certain restrictions, adds an experimental m68k port,
    and makes notable improvements to stdio (application-provided buffers),
    getaddrinfo (AI_ADDRCONFIG, support for IPv4-only kernel configurations),
    the dynamic linker (safety against dlopen of libraries using initial-exec
    TLS model, reclaiming unused memory on FDPIC archs, better dladdr results),
    and handling of default thread stack size (pthread_setattr_default_np now
    works more reliably). 
```

**Comment by dimon222** [comment]
@mterron possibly fixed in master branch of musl and will be okay with next release.
Found this
http://git.musl-libc.org/cgit/musl/commit/?id=ad795d56ba3fb9d69f524ee676e3b1e2355cceb7

**Comment by mterron** [comment]
> 
> 
> @mterron possibly fixed in master branch of musl and will be okay with next release.
> Found this
> http://git.musl-libc.org/cgit/musl/commit/?id=ad795d56ba3fb9d69f524ee676e3b1e2355cceb7

Yes, I thought that was the one (mainly basedon the `[k+1]` part).

How do we go from here? The PR is fine, except that musl in edge has a bug. Should I disable the checks or wait for musl > 1.21 to be released and incorporated into Alpine?

**Comment by Ikke** [comment]
@fabled Can we backport that fix for musl, or should we wait for a new musl release?

**Comment by mterron** [comment]
@Ikke  My concern is that it seems like a regression on musl as 1.1.20 passes the test harness with no errors.
I tried (unsuccessfully) to get in touch with the musl guys on IRC. Do you guys have a good channel to raise this?

**Comment by mterron** [comment]
@Ikke  My concern is that it seems like a regression on musl as 1.1.20 passes the test harness with no errors.
I tried (unsuccessfully) to get in touch with the musl guys on IRC. Do you guys have a good channel to raise this?

**Comment by TBK** [comment]
I have been in contact with Rich Felker before via the MUSL Mailing List - https://www.musl-libc.org/support.html & https://www.openwall.com/lists/musl/

**Comment by tcely** [comment]
@mterron Does the recent upgrade to `musl 1.1.22` resolve the tests? https://github.com/alpinelinux/aports/commit/c36e066edfd9f4c4c86f6c4b69bab21d58e914cc

**Comment by mterron** [comment]
@tcely no, still broken same way. It has to be those getaddrinfo changes on musl. I have no way to debug that.

**Comment by tcely** [comment]
@mterron Ok. It looks like those fixes will need to be patched into musl, I'll take a look into that when I have free time.

**Comment by mterron** [comment]
Please ignore this PR as there are fundamental issues between nss_wrapper and musl

**Pull request closed without merging**
