### PR TITLE
main/tzdata: upgrade to 2019a

### PR DESCRIPTION
**Pull request by J0WI**
https://mm.icann.org/pipermail/tz-announce/2019-March/000055.html

### CODE REVIEW

**Comment by J0WI** [comment]
Please consider backporting this package. Alpine 3.6 is still on 2017a. This is critical when validating security certificates.

**Comment by ncopa** [comment]
> Please consider backporting this package. Alpine 3.6 is still on 2017a. This is critical when validating security certificates.

It would be good if you could file an issue on https://bugs.alpinelinux.org for things that needs to be backported. I normally don't read all github comments before tagging new releases, but I do look over the issues on bugs.a.o.

**Comment by J0WI** [comment]
> It would be good if you could file an issue on https://bugs.alpinelinux.org for things that needs to be backported.

Unfortunately the ability to create issues as guest have been disabled recently. I'm not convinced to register there too.

**Comment by tcely** [comment]
I created https://bugs.alpinelinux.org/issues/10202 for this PR.

**Comment by tcely** [comment]
It looks like at least `edge` has been updated in: https://github.com/alpinelinux/aports/commit/65c2c2ffbfdbb3663a6e9ec476183a5c90467c62#diff-e39254f7a81874241c6826b4ee193488

**Pull request closed without merging**
