### PR TITLE
testing/py-yuicompressor: new aport

### PR DESCRIPTION
**Pull request by itoffshore**
[YUI Compressor](https://yui.github.io/yuicompressor/) is a JavaScript and CSS minifier written in Java.

https://pypi.python.org/pypi/yuicompressor

### CODE REVIEW

**Comment by jirutka** [comment]
This package installs `/usr/bin/yuicompressor`, so py2- and py3- are conflicting (see [this](https://wiki.alpinelinux.org/wiki/APKBUILD_examples:Python#Multiversion_package_with_executables))…

**Comment by itoffshore** [comment]
ok - let me merge what has been pulled & make a new PR to fix it

**Comment by jirutka** [comment]
Well, this has been already merged. ;)

**Comment by itoffshore** [comment]
well spotted - fixed in https://github.com/alpinelinux/aports/pull/938 ;o)

**Pull request closed without merging**
