### PR TITLE
 testing/php7-gmagick: upgrade to 2.0.5_rc1, add check, modernize

### PR DESCRIPTION
**Pull request by andypost**
Very useful would be great to promote to contrib

@vakartel please check, this extension works better then `php7-imagick` and has less dependencies

### CODE REVIEW

**Comment by andypost** [comment]
```
FAILED TEST SUMMARY
---------------------------------------------------------------------
Test annotate image [tests/gmagick-006-annotateimage.phpt]
```

**Comment by andypost** [comment]
Installing `ghostscript-fonts` allowed to pass tests but
```
(1/1) Installing ghostscript-fonts (8.11-r1)
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n021003l.afm owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/s050000l.afm owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n019023l.afm owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n019004l.afm owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n022003l.pfb owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n019003l.afm owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n021023l.afm owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n022004l.afm owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n022024l.pfb owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n021024l.afm owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n022023l.pfb owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n019024l.pfb owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n021004l.afm owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n022004l.pfb owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n019004l.pfb owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n022023l.afm owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n021003l.pfb owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n019003l.pfb owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n021024l.pfb owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n022024l.afm owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n022003l.afm owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n021004l.pfb owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n019024l.afm owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n019023l.pfb owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/n021023l.pfb owned by libwmf-0.2.8.4-r3.
ERROR: ghostscript-fonts-8.11-r1: trying to overwrite usr/share/fonts/Type1/s050000l.pfb owned by libwmf-0.2.8.4-r3.
```

**Comment by andypost** [comment]
Broken test excluded with comment to Redmine https://bugs.alpinelinux.org/issues/8619

**Comment by andypost** [comment]
Looks now it's ready
```
$ git grep -P '^depends=$' |wc -l
417
$ git grep -P '^depends=""$' |wc -l
1092
```

**Comment by TBK** [comment]
LGTM 👍

Please accept this PR after https://github.com/alpinelinux/aports/pull/3519

**Comment by andypost** [comment]
@TBK let's get this in first so you can rebase it @2873 on it?

**Comment by TBK** [comment]
Sure we can do that.

**Pull request closed without merging**
