### PR TITLE
community/inkscape: upgrade to 0.92.2

### PR DESCRIPTION
**Pull request by tmpfile**

### CODE REVIEW

**Comment by fabled** [comment]
make check fails with:
```
make[1]: Entering directory '/home/tteras/aports/community/inkscape/src/inkscape-0.92.2/po'
rm -f missing notexist
srcdir=. /usr/bin/intltool-update -m
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE ?PACKAGE_NAME}?/ at /usr/bin/intltool-update line 1071, <CONF> line 1203.
make[1]: *** [Makefile:750: check] Error 255
make[1]: Leaving directory '/home/tteras/aports/community/inkscape/src/inkscape-0.92.2/po'
make: *** [Makefile:1471: check-recursive] Error 1
```

**Comment by tmpfile** [comment]
It was a problem with intltool. The perl-regexp patch was incomplete.
Can you merge https://github.com/alpinelinux/aports/pull/2278 and try again?

**Comment by fabled** [comment]
Applied the referenced intltool fix. inkscape build makes more progress now, but still fails in `make check`.

**Comment by tmpfile** [comment]
Can you share what's the error?
Travis just outputs that "The log length has exceeded the limit of 4 MB."
Another reason I'm excited for the new CI suite you have planned for 3.7.

**Comment by fabled** [comment]
After applying:
```
-checkdepends="bash"
+checkdepends="bash py-lxml"
```

[inkscape.log](https://github.com/alpinelinux/aports/files/1328397/inkscape.log)

**Pull request closed without merging**
