### PR TITLE
Modernize main

### PR DESCRIPTION
**Pull request by tmpfile**

### CODE REVIEW

**Comment by jirutka** [comment]
Could you please share the script you’ve used to update these packages?

**Comment by tmpfile** [comment]
Of course.
Notice that I decided to modernize only packages that still had md5sums because I understand those are the ones that are most outdated. But the script could be run on all packages if you want (and also on community and testing).

```
#!/bin/sh
# git clone https://github.com/tmpfile/aports
# cd ./aports/main/
# git checkout -b modernize-main
for dir in $(grep -l md5sums $(find . -name APKBUILD) | sed 's/\/APKBUILD//')
do
        cd $dir
        sed -i 's/_builddir/builddir/g' APKBUILD
        sed -i 's/ || return 1//g' APKBUILD
        sed -i 's/|| return 1//g' APKBUILD
        sed -i 's/[ \t]*$//' APKBUILD
        sed -i ':a;N;$!ba;s/ \\\n\n/\n/g' APKBUILD
        sed -i 's/[ \t]*$//' APKBUILD
        abuild checksum
        git commit -a -m "${dir//./main}: modernize APKBUILD"
        cd ..
done
# git push origin modernize-main
```

**Comment by nmeum** [comment]
I would personally prefer if those commits would be squashed into a single one with the commit message `main/*: modernize APKBUILDs` or something similar to that. Otherwise it pollutes the commit log imho.

**Comment by tmpfile** [comment]
Closing in favor of https://github.com/alpinelinux/aports/pull/5509

**Pull request closed without merging**
