### PR TITLE
testing/rclone: upgrade to 1.49.5

### PR DESCRIPTION
**Pull request by SuperSandro2000**

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
When I tested this locally I always got this:
````
$ abuild build
# github.com/rclone/rclone
loadinternal: cannot find runtime/cgo
````
Not sure why. Anyone any idea?

**Comment by Cogitri** [comment]
Hm, I think that warning is normal for us

**Comment by SuperSandro2000** [comment]
Maybe someone should take a look at this if it is fatal or can be ignored in abuild.

**Comment by Cogitri** [comment]
I don't really know Go, maybe you could ask over on IRC?

**Pull request closed without merging**
