### PR TITLE
community/py3-factory-boy: drop py2

### PR DESCRIPTION
**Pull request by maxice8**
@ddevault

### CODE REVIEW

**Comment by maxice8** [comment]
This will break py-django-oscar which depends on serveral py2- only packages.

**Comment by ddevault** [comment]
Do you have a patch for py-django-oscar?

**Comment by maxice8** [comment]
Nah, that package needs to convert 4 or 5 py2- only packages to py3- for it to be transfered

**Comment by maxice8** [comment]
all of them py-django-* stuff

**Comment by maxice8** [comment]
Packages for django-oscar

py3-django-extra-views
py3-django-haystack
py3-django-phonenumber-field
py3-django-sorl-thumbnail
py3-django-treebeard
py3-django-widget-tweaks

**Comment by maxice8** [comment]
These need to be merged to add the requires py3- dependencies to django-oscar

#10706
#10707
#10708 
#10709 
#10710 
#10711

**Pull request closed without merging**
