### PR TITLE
community/vulkan-headers: upgrade to 1.1.119

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
@PureTryOut

**Comment by PureTryOut** [comment]
Please don't do just this package, also upgrade `community/vulkan-loader` and `community/vulkan-tools`. Otherwise stuff will break.

**Comment by maxice8** [comment]
On Sun Aug 18, 2019 at 10:09 AM Bart Ribbers wrote:
> Please don't do just this package, also upgrade `community/vulkan-loader` and `community/vulkan-tools`. Otherwise stuff will break.
> 

Updated

**Comment by PureTryOut** [comment]
Thanks, LGTM!

**Pull request closed without merging**
