### PR TITLE
main/imagemagick: security upgrade to 7.0.8-44

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
Flaky test results in CI, aarch64 passed in https://cloud.drone.io/alpinelinux/aports/2524/3/1

**Comment by andypost** [comment]
> FAIL: tests/validate-formats-disk.tap 1 
on aarch64

**Comment by J0WI** [comment]
@rnalrd why did you revert the source url in 094b10c7c7d0ff9eb2bcb5ec4a5f88445dc03823?
Old versions are not archived in the upstream url, so rebuilds will fail.

**Comment by rnalrd** [comment]
This was an oversight. With stable branches looks like we have no other choice than use GH mirror.

**Comment by rnalrd** [comment]
Merged

**Pull request closed without merging**
