### PR TITLE
community/virtualbox-guest-modules-vanilla: upgrade to 5.2.22

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by gena01** [comment]
Looks like a variation of this PR has been committed by @ncopa (also upgraded to 6.0.0)

**Comment by andypost** [comment]
@J0WI still makes sense to rebase to add `check()`

**Comment by J0WI** [comment]
Rebased

**Comment by ncopa** [comment]
fixed with c93151cf8f66ecdcc92fd46b5f73ef404d1c5b94

thank you!

**Pull request closed without merging**
