### PR TITLE
community/libreoffice: Support more languages

### PR DESCRIPTION
**Pull request by albap**

### CODE REVIEW

**Comment by clandmeter** [comment]
If you don't bump pkgrel, nothing will happen. (see travis log).

**Comment by clandmeter** [comment]
please squash commits

**Comment by albap** [comment]
I use github interface and don't know how to squash.
Searching on stackoverflow I found that there's a new feature from March 2016 that lets you squash.
https://stackoverflow.com/questions/35948131/github-squash-commits-from-web-interface-on-pull-request-after-review-comments
If you select the Squash and Merge option all should be fine.
Does it work?

**Comment by clandmeter** [comment]
We do not use the github interface, nor do we use the github git repository.
This is also mentioned in the github index page: 
**Readonly mirror of aports (http://git.alpinelinux.org/cgit/aports)** 

If you want to contribute to aports, you will need to have a build environment to test build your patches/PR's. If you are not able to set this up, the its better to create an issue on our bug tracker and request the prefereer changes.

**Pull request closed without merging**
