### PR TITLE
libsemanage, minor fixes to libse*

### PR DESCRIPTION
**Pull request by tych0**
Hi,

Towards the end of eventually getting policycoreutils into alpine, here's libsemanage, and some fixes that make the symlinks in /usr/lib/* valid in some other packages.

Thoughts welcome.

### CODE REVIEW

**Comment by ncopa** [comment]
for the `ln` fixes, we could depend on `coreutils` (~5.4MB) instead of `python` (~39.7MB).

**Comment by jirutka** [comment]
IMHO `ln --relative` is not needed at all, just use relative path as the first argument to `ln`.

**Comment by ncopa** [comment]
That is what we currently do but apparently it does not work.

**Comment by ncopa** [comment]
i just pulled in coreutils as build time dep. Thanks!

**Comment by tych0** [comment]
Thanks @ncopa!

**Pull request closed without merging**
