### PR TITLE
community/rspamd: upgrade to 1.9.1

### PR DESCRIPTION
**Pull request by TBK**

### CODE REVIEW

**Comment by TBK** [comment]
@bratkartoffel https://github.com/rspamd/rspamd/blob/master/contrib/DEPENDENCY_INFO.md and Rspamd itself is under Apache-2.0.

**Comment by bratkartoffel** [comment]
The DEPENDENCY_INFO.md lists the licences of the dependencies, not the package itself. Thus I think that only Apache-2.0 should be listed as licence in APKBUILD.

**Comment by TBK** [comment]
Ask @jirutka the reasoning.

**Comment by jirutka** [comment]
IIRC these dependencies are bundled with rspamd, so they have to be included in the license info.

**Pull request closed without merging**
