### PR TITLE
community/xe-guest-utilities upgrade to 7.11.0

### PR DESCRIPTION
**Pull request by ianbashford**
Updated to latest version - no details from upstream

### CODE REVIEW

**Comment by Ikke** [comment]
@sdrik Can you review this?

**Comment by sdrik** [comment]
@Ikke I didn't have any XenServer related activities during the last few years, so I can't really review this PR. In fact, if I'm still listed as a maintainer for this aport, that shoud be fixed...

Anyway, this PR is a simple version bump, so I guess it should be ok.

**Comment by Ikke** [comment]
@sdrik Thanks. It was mostly because this was a major upgrade, so I wanted to verify it would not unexpectedly break something.

@ianbashford Are you willing to take over maintainership for this package?

**Comment by ianbashford** [comment]
Yeah I'd be happy to -- I'll modify the PR shortly and update my details in the APKBUILD... should be this evening

**Comment by ianbashford** [comment]
Done - should be good to go but let me know if you have any other questions

**Comment by Ikke** [comment]
I'll fix it myself, but when you do a version upgrade, `pkgrel` should be set to 0 again.

**Pull request closed without merging**
