### PR TITLE
libvpx: Update to 1.7.0

### PR DESCRIPTION
**Pull request by strfry**
Version Bump, touch dependent packages, changed source URL to Github Release (because "official" tarball is kinda broken)

### CODE REVIEW

**Comment by strfry** [comment]
Note that this build fails because it triggers a rebuild of firefox, which exceeds the maximum build time of travis-ci

**Comment by refacto** [comment]
Tried building libvpx from your branch, it probably needs some extra makedepends?
https://gist.github.com/refacto/052d4e1cb48a78ed7e163698c53dbfe4

**Comment by strfry** [comment]
Darn, i noticed that dependency but didn't realize to add it to the APKBUILD.
Should be done now :)

**Comment by ncopa** [comment]
lets go for 1.8.0 now (#6384). Sorry for taking so long.

**Pull request closed without merging**
