### PR TITLE
main/poppler: upgrade to 0.80.0

### PR DESCRIPTION
**Pull request by maxice8**
- [x] cups-filters
- [x] inkscape
- [x] kitinerary
- [x] libreoffice
- [x] pdfgrep
- [x] texlive

### CODE REVIEW

**Comment by Cogitri** [comment]
Testing libreoffice

**Comment by Cogitri** [comment]
https://gist.github.com/0226082f7f46c32ecbf79d78eb050f6d libreoffice fails

**Comment by maxice8** [comment]
Downgraded mdds, can you try building libreoffice again ?

**Comment by Cogitri** [comment]
Libreoffice works

**Comment by maxice8** [comment]
@ncopa

**Comment by ncopa** [comment]
```
extension/internal/pdfinput/pdf-input.cpp:322:61: error: 'std::__cxx11::basic_string<char>' is not an accessible base of 'const GooString'
148s
5879	     Glib::ustring filename = _pdf_doc->getFileName()->c_str();
148s
5880	                                                             ^
```

**Comment by maxice8** [comment]
Can't reproduce locally, inkscape compiles fine on x86_64

**Comment by rnalrd** [comment]
@maxice8 if you rebase I would push it. We know have vulnerable version of poppler and needs to be upgraded.

Thanks!

**Comment by maxice8** [comment]
On Fri, 20 Sep 2019 03:23:34 -0700
Leonardo <notifications@github.com> wrote:

> @maxice8 if you rebase I would push it. We know have vulnerable
> version of poppler and needs to be upgraded.
> 
> Thanks!
> 

Rebased and pushed, be warned that there were some failures on CI that
i couldn't reproduce. So when this is merged please ping me on
#alpine-devel so i can keep an eye on #alpine-commits and b.a.o to see
if anything fails on the actual builders.

**Pull request closed without merging**
