### PR TITLE
main/syslog-ng: upgrade to 3.13.2

### PR DESCRIPTION
**Pull request by adrianguenter**
Supersedes and fixes #2722 

I've enabled tests, but some (5 of 49) currently fail, so I made check() fail gracefully (with `|| return 0`) for now. I'll look into patching them for r1.

### CODE REVIEW

**Comment by kaniini** [comment]
NAK.  system librabbitmq should be used.

**Comment by adrianguenter** [comment]
@kaniini 10-4, coming right up.

**Comment by adrianguenter** [comment]
@jirutka is it preferable that I open a new PR or should I just push another commit here?

**Comment by adrianguenter** [comment]
Closed in favor of #3206

**Pull request closed without merging**
