### PR TITLE
testing/perl-convert-pem: new aport

### PR DESCRIPTION
**Pull request by timlegge**

### CODE REVIEW

**Comment by timlegge** [comment]
> LGTM although i don't like having a 3k loc patch

Me either.  It basically deletes the outdated included Test Module and allows the default tests to run.  The patch process runs automatically but I suppose I could have deleted the offending directory in the prepare

**Comment by maxice8** [comment]
IMO it is better to have that in prepare()

**Comment by timlegge** [comment]
> IMO it is better to have that in prepare()

Will do, need to wait on some PRs to get dependencies anyway

**Comment by maxice8** [comment]
You can have a single PR for multiple packages if one depend on another, just have them on separate commits

**Comment by timlegge** [comment]
> You can have a single PR for multiple packages if one depend on another, just have them on separate commits

Wish I had known that several weeks ago :-(

**Comment by Ikke** [comment]
`perl-crypt-des_ede3` is currently missing as dependency.

**Comment by timlegge** [comment]
> `perl-crypt-des_ede3` is currently missing as dependency.
> 
> _edit:_
> I just pushed #7274

sorted out the dependency issues.  Thanks

**Pull request closed without merging**
