### PR TITLE
community/fractal: enable on x86

### PR DESCRIPTION
**Pull request by J0WI**
#11605 #11634

### CODE REVIEW

**Comment by ncopa** [comment]
I had to disable it again due to:
```
4.2.1/output/target/release/deps/liblmdb_sys-4413bc529a1449a0.rlib(mdb.o): in function `mdb_node_search':
          /home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/cargo-home/registry/src/github.com-1ecc6299db9ec823/lmdb-sys-0.8.0/lmdb/libraries/liblmdb/mdb.c:5322: undefined reference to `__stack_chk_fail_local'
          /usr/lib/gcc/i586-alpine-linux-musl/9.2.0/../../../../i586-alpine-linux-musl/bin/ld: /home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/liblmdb_sys-4413bc529a1449a0.rlib(mdb.o): in function `mdb_reader_pid':
          /home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/cargo-home/registry/src/github.com-1ecc6299db9ec823/lmdb-sys-0.8.0/lmdb/libraries/liblmdb/mdb.c:2661: undefined reference to `__stack_chk_fail_local'
          /usr/lib/gcc/i586-alpine-linux-musl/9.2.0/../../../../i586-alpine-linux-musl/bin/ld: /home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/liblmdb_sys-4413bc529a1449a0.rlib(mdb.o): in function `mdb_env_setup_locks':
          /home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/cargo-home/registry/src/github.com-1ecc6299db9ec823/lmdb-sys-0.8.0/lmdb/libraries/liblmdb/mdb.c:4901: undefined reference to `__stack_chk_fail_local'
          /usr/lib/gcc/i586-alpine-linux-musl/9.2.0/../../../../i586-alpine-linux-musl/bin/ld: /home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/liblmdb_sys-4413bc529a1449a0.rlib(mdb.o): in function `mdb_env_copythr':
          /home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/cargo-home/registry/src/github.com-1ecc6299db9ec823/lmdb-sys-0.8.0/lmdb/libraries/liblmdb/mdb.c:9090: undefined reference to `__stack_chk_fail_local'
          /usr/lib/gcc/i586-alpine-linux-musl/9.2.0/../../../../i586-alpine-linux-musl/bin/ld: /home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/liblmdb_sys-4413bc529a1449a0.rlib(mdb.o): in function `mdb_env_open2':
          /home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/cargo-home/registry/src/github.com-1ecc6299db9ec823/lmdb-sys-0.8.0/lmdb/libraries/liblmdb/mdb.c:4434: undefined reference to `__stack_chk_fail_local'
          /usr/lib/gcc/i586-alpine-linux-musl/9.2.0/../../../../i586-alpine-linux-musl/bin/ld: /home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/liblmdb_sys-4413bc529a1449a0.rlib(mdb.o):/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/cargo-home/registry/src/github.com-1ecc6299db9ec823/lmdb-sys-0.8.0/lmdb/libraries/liblmdb/mdb.c:5013: more undefined references to `__stack_chk_fail_local' follow
          /usr/lib/gcc/i586-alpine-linux-musl/9.2.0/../../../../i586-alpine-linux-musl/bin/ld: /home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/fractal_gtk-bf4a1c93d75fb2cb: hidden symbol `__stack_chk_fail_local' isn't defined
          /usr/lib/gcc/i586-alpine-linux-musl/9.2.0/../../../../i586-alpine-linux-musl/bin/ld: final link failed: bad value
          collect2: error: ld returned 1 exit status
```

**Comment by Cogitri** [comment]
Ah sorry, should've disabled stack protector for x86 :/

**Comment by Cogitri** [comment]
Ah, you can still do this, just do something like this:

```
	case "$CARCH" in
		x86)
			export CFLAGS="$CFLAGS -fno-stack-protector"
			;;
	esac
```

**Comment by J0WI** [comment]
> Ah, you can still do this, just do something like this:

#11689

**Pull request closed without merging**
