### PR TITLE
testing/php7: upgrade to 7.1.4

### PR DESCRIPTION
**Pull request by andypost**
Bug fix release http://php.net/archive/2017.php#id2017-04-13-2

### CODE REVIEW

**Comment by andypost** [comment]
@vakartel Here's just upgrade on top of http://patchwork.alpinelinux.org/patch/3338/

**Comment by vakartel** [comment]
@andypost 
In patchwork3338 I also fixed depends_dev, depends_doc, pecl()-depends, added correct replaces* for coexist with php5, removed compatibility with php7.1 naming, and added disabling pcre-jit on s390x.

So It's more complex than just version bump.

**Comment by jirutka** [comment]
@vakartel And more importantly broken it even more with incorrect usage of `replaces`…

**Comment by vakartel** [comment]
@jirutka 
You asked to move php7 (7.1) from testing to community. So I made a PR #1305

**Comment by fabled** [comment]
@vakartel I know of https://patchwork.alpinelinux.org/patch/3338/ but it did not apply as is, can you please follow up on top of this, as this applied and looked a step forward. Thanks.

**Comment by vakartel** [comment]
@fabled Now it does not matter. Because testing/php7 would be removed soon #1305

**Pull request closed without merging**
