### PR TITLE
community/elixir: upgrade to 1.6.3

### PR DESCRIPTION
**Pull request by gmile**

### CODE REVIEW

**Comment by gmile** [comment]
Looks like a travis hiccup? This is what I'm seeing from travis logs:

> (1/19) Installing g++ (6.4.0-r7)
> ERROR: g++-6.4.0-r7: IO ERROR

**Comment by nmeum** [comment]
Tests fail on x86: http://build.alpinelinux.org/buildlogs/build-edge-x86/community/elixir/elixir-1.6.3-r0.log do happen to have any idea how that test failure could be fixed?

**Comment by gmile** [comment]
@nmeum can you please point me to the specific line with failure here http://build.alpinelinux.org/buildlogs/build-edge-x86/community/elixir/elixir-1.6.3-r0.log?

I searched for the `failures` in the log, all seems good. Apart from a couple of warning I don't see a failure. Sorry if I am missing something.

**Comment by nmeum** [comment]
The test seems to have passed now. The old log was overwritten should have copied the corresponding lines. Might have been a race condition.

**Pull request closed without merging**
