### PR TITLE
testing/postgis: upgrade to 2.5.2

### PR DESCRIPTION
**Pull request by oninoshiko**
PostGIS has to be bumped to 2.5.2 to support Proj 6.

### CODE REVIEW

**Comment by maxice8** [comment]
Commit title doesn't follow the norm

`<repo>/<package>: upgrade to <version>`

**Comment by oninoshiko** [comment]
Fixed.

**Comment by maxice8** [comment]
the second commit as well `<repo>/<package>: restrict from x86`

**Comment by oninoshiko** [comment]
That should fix both the commits. Sorry about that!

**Comment by oninoshiko** [comment]
Because https://github.com/alpinelinux/aports/pull/8814 ends up doing the same thing, I propose we close this request and just integrate that.

**Comment by maxice8** [comment]
#8814 was merged

**Comment by oninoshiko** [comment]
testing/postgis: Closing as redundant.

**Pull request closed without merging**
