### PR TITLE
main/ansible: upgrade to 2.8.4

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by tcely** [comment]
I typically use "security upgrade" for these commits and list the CVE numbers in the commit message too.

**Comment by maxice8** [comment]
It is not a security upgrade it is a normal upgrade that happens to have positive security implications. 

Security upgrades happen where normal upgrades don't happen, the stable branches.

**Comment by tcely** [comment]
Check the git log for "security upgrade" you will find many commits just like this one.

**Comment by maxice8** [comment]
> Check the git log for "security upgrade" you will find many commits just like this one.

That is very nice but it is still a normal upgrade that ends up having security implications that is properly tagged into a security upgrade on backports.

**Pull request closed without merging**
