### PR TITLE
community/py-sqlparse: upgrade to 0.3.0

### PR DESCRIPTION
**Pull request by andypost**
Ref https://github.com/andialbrecht/sqlparse/blob/master/CHANGELOG#L16

PS: required for pgcli https://github.com/dbcli/pgcli/blob/master/setup.py#L21

### CODE REVIEW

**Comment by andypost** [comment]
@tboerger Looks other dependencies are not requiring strictly 0.2 version

**Comment by maxice8** [comment]
`mycli` has 'sqlparse>=0.2.2,<0.3.0',

**Comment by tboerger** [comment]
I will try to get back to the packages I have built asap to update them, then it should be fine.

**Comment by andypost** [comment]
@maxice8 good catch, I think to add patch with 3 last commits from https://github.com/dbcli/mycli/commits/master/setup.py

**Comment by andypost** [comment]
I manually checked #8798  and it works perfect with 0.3 version so they should be commited altogether

**Comment by andypost** [comment]
pgcli also works for me after upgrade, @tboerger I think all 3 PRs are ready

**Pull request closed without merging**
