### PR TITLE
main/email: add check and openssl dependency

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
Btw.: this code looks unmaintained and upstream is no longer available.

**Comment by clandmeter** [comment]
Im ok with removing this. Seems upstream does not want to provide proper releases.

upstream: https://github.com/deanproxy/eMail

**Comment by andypost** [comment]
@clandmeter can you commit it? this is only leftover from parent issue

**Comment by ncopa** [comment]
fixed with c2ac0e6df64d71833dfffe422df8113d291a8e13. I dont know why the github bot does not pick up those and close them for us?

**Pull request closed without merging**
