### PR TITLE
testing/etckeeper: moved from github due to the updated TOS

### PR DESCRIPTION
**Pull request by HRio**
More info here:
 https://joeyh.name/blog/entry/what_I_would_ask_my_lawyers_about_the_new_Github_TOS/
 https://joeyh.name/blog/entry/removing_everything_from_github/

### CODE REVIEW

**Comment by HRio** [comment]
Travis can not handle that snapshot() must be done as well. This needs manual build testing.

Any suggestion for a better way than snapshot() to handle fetching from git?

**Comment by HRio** [comment]
can this change be reviewed? as the version currently in testing/ fails to build from source due to that Joey Hess is not on github anymore.

**Comment by HRio** [comment]
upstream cgit server handles snapshot generation, so changed to that.

**Comment by HRio** [comment]
seems this was handled by fa0a5dbf864038261be4c415e5a9d8881945e4e2 today....

**Comment by jirutka** [comment]
Superseded by #1203.

**Pull request closed without merging**
