### PR TITLE
main/clang: add clang-extra-tools subpkg

### PR DESCRIPTION
**Pull request by russkel**
Compile the extra tools for clang.

### CODE REVIEW

**Comment by russkel** [comment]
Can the max job time be increased on TravisCI?

**Comment by maxice8** [comment]
The drone-ci passes, which covers x86_64 so i wouldn't worry about that

**Comment by russkel** [comment]
@ncopa Hi, any thoughts on this?

**Comment by russkel** [comment]
https://gitlab.alpinelinux.org/alpine/aports/merge_requests/2249

**Pull request closed without merging**
