### PR TITLE
testing/py-frozendict: new aport

### PR DESCRIPTION
**Pull request by DaikiMaekawa**
`frozendict` provides an immutable dictionary in Python.

See for more detail. https://github.com/slezica/python-frozendict

### CODE REVIEW

**Comment by Ikke** [comment]
Welcome @DaikiMaekawa,

Thanks for your contribution. New packages in Alpine Linux should start in the testing repo, and then, if they are stable, can be moved to community.

Can you update the PR to move it to testing?

Thanks, Kevin

**Comment by DaikiMaekawa** [comment]
@Ikke Addressed your comment.

**Comment by prspkt** [comment]
At this point I would advise against merging multi-version Python packages. A simple Python 3 paclage would suffice.

**Comment by Ikke** [comment]
@DaikiMaekawa Is python2 support required for this package? Because we are about to deprecate python2.

**Comment by DaikiMaekawa** [comment]
@Ikke Well, my private project still rely on python2, but yeah I know what you mean. I'm OK to remove python2 stuff from this PR as we also maintain own aports locally.

**Pull request closed without merging**
