### PR TITLE
testing/py-pandas: Remove double package() call

### PR DESCRIPTION
**Pull request by sgerrand**
💁 Removes the duplicated function definition in the `APKBUILD` file.

### CODE REVIEW

**Comment by maxice8** [comment]
I think it is better to remove the first definition

**Comment by sgerrand** [comment]
> I think it is better to remove the first definition

For what reason?

**Comment by maxice8** [comment]
Looks more correct, doesn't install unnecessary LICENSE file and leaves installing the files in the _py functions

**Comment by sgerrand** [comment]
:bow: @maxice8: Done. ♻️

**Pull request closed without merging**
