### PR TITLE
main/libxvmc: upgrade to 1.0.12

### PR DESCRIPTION
**Pull request by jjsearle**

### CODE REVIEW

**Comment by prspkt** [comment]
`main/libxvmc` [introduces](https://travis-ci.org/alpinelinux/aports/builds/589835465#L853) `usr/include/X11/extensions/vldXvMC.h` which is also provided by `main/xorgproto` and creates a collision since the same file is now provided by two different packages. Please make sure to amend this PR according to [this](https://github.com/alpinelinux/aports/pull/11664).

**Comment by jjsearle** [comment]
Thanks for the heads up. What would you like me to do? It looks like you are removing it in the xorgproto pr @prspkt

**Comment by prspkt** [comment]
@jjsearle simply add one more commit to this PR with the changes from [here](https://github.com/alpinelinux/aports/pull/11664/commits/bcb21759a0f22d594bdd0cad101ad415154adbba).

**Comment by jjsearle** [comment]
@prspkt understood, I have committed the requested change.

**Comment by maxice8** [comment]
Duplicate of https://gitlab.alpinelinux.org/alpine/aports/merge_requests/121

**Pull request closed without merging**
