### PR TITLE
main/imagemagick: Add build for PerlMagick packages

### PR DESCRIPTION
**Pull request by timlegge**
Build the PerlMagick perl modules of imagemagick

### CODE REVIEW

**Comment by timlegge** [comment]
@maxice8, @ncopa, @tcely any possibility of movement on this one?  The trouble with imagemagick as you may have noticed is the frequent releases remove the previous release archive and the tests fail every other release so if this is eventually accepted it needs to get in shortly after a release is announced by Imagemagick on a release that will actually build completely. 

I can build permagick as a separate package but as its a sub package of imagemagick this makes sense to me.

The other option is to point to the github releases as those archives stay around.

Tim

**Comment by ncopa** [comment]
Can we simply move the `usr/lib/perl5` instead of installing it twice?

Something like:
````sh
_perlmagick() {
	pkgdesc="PerlMagick Perl Modules for ImageMagick"
	mkdir -p "$subpkgdir"/usr/lib
	mv "$pkgdir"/usr/lib/perl5 "$subpkgdir"/usr/lib/
}
````
￼

**Comment by timlegge** [comment]
Probably.  I will give it a shot and test it in my use case.

Tim

**Comment by timlegge** [comment]
> Can we simply move the `usr/lib/perl5` instead of installing it twice?
> 
> Something like:
> 
> ```shell
> _perlmagick() {
> 	pkgdesc="PerlMagick Perl Modules for ImageMagick"
> 	mkdir -p "$subpkgdir"/usr/lib
> 	mv "$pkgdir"/usr/lib/perl5 "$subpkgdir"/usr/lib/
> }
> ```

@ncopa I made those changes but had to increment the imagemagick version because they don't keep previous imagemagick  releases at https://www.imagemagick.org/download/releases/ according to the site github is the official mirror which does keep past releases around.


Tim

**Pull request closed without merging**
