### PR TITLE
main/imagemagick: security upgrade to 7.0.8.38

### PR DESCRIPTION
**Pull request by J0WI**
https://github.com/ImageMagick/ImageMagick/issues/1523

Closes #6550 and #6696

### CODE REVIEW

**Comment by J0WI** [comment]
https://github.com/ImageMagick/ImageMagick/issues/1529

**Comment by andypost** [comment]
btw Previous version pass tests https://github.com/alpinelinux/aports/pull/6696

**Comment by J0WI** [comment]
Checks are passing with `7.0.8.36`.

**Comment by J0WI** [comment]
:ping_pong: @ncopa since this package has so many vulnerabilities (see #6870) it would be worth to recompile all stable branches against an updated version. It's [not clear](https://abi-laboratory.pro/index.php?view=timeline&l=imagemagick) if `7.0.5.10` from `3.6-stable` is ABI compatible to `7.0.8.36`, but existing packages should still compile against the new version.

**Comment by J0WI** [comment]
Downgraded due https://cloud.drone.io/alpinelinux/aports/1239/5/1

**Comment by J0WI** [comment]
Fixed in 7df5214032cb542c8a6d010a17ef78d6ebb0abca

**Pull request closed without merging**
