### PR TITLE
main/openssh: add check()

### PR DESCRIPTION
**Pull request by andypost**

### CODE REVIEW

**Comment by andypost** [comment]
TBD rework patches

**Comment by jirutka** [comment]
Build failed due to outdated patch file.

**Comment by andypost** [comment]
On arm8 tests still fail with
```
test_utf8: ..................
regress/unittests/utf8/tests.c:27 test #19 "utf8_badarg"
ASSERT_INT_EQ(len, -1) failed:
         len = 1
          -1 = -1
make[1]: *** [Makefile:221: unit] Aborted (core dumped)
make[1]: Leaving directory '/mnt/main/openssh/src/openssh-7.6p1/regress'
make: *** [Makefile:586: tests] Error 2
>>> ERROR: openssh: check failed
```

**Comment by andypost** [comment]
Looks tests require server running
```
/home/travis/build/alpinelinux/aports/main/openssh/src/openssh-7.7p1/ssh-keygen -q -t ed25519 -N '' -C 'test-comment-1234' -f /home/travis/build/alpinelinux/aports/main/openssh/src/openssh-7.7p1/regress/t12.out
run test connect.sh ...
ssh connect with failed
failed simple connect
make[1]: *** [Makefile:206: t-exec] Error 1
make[1]: *** Waiting for unfinished jobs....
```

**Comment by andypost** [comment]
I think it still makes sense

**Comment by tcely** [comment]
The check function was added in https://github.com/alpinelinux/aports/commit/a027feb82fee234ba3b3a8ff0a947651005b6a33 by @J0WI.

**Pull request closed without merging**
