### PR TITLE
python 3.6.0

### PR DESCRIPTION
**Pull request by scadu**

### CODE REVIEW

**Comment by jirutka** [comment]
I’ve removed commit “main/python3: rebuild against new version of python3” – I assume that it was here by accident – and “main/boost: fix checksums” – changes in already released tarballs are suspicious (especially on SourceForge) and we should not just overlook it. I’ve notified ncopa to look at it.

**Comment by clandmeter** [comment]
I just found out that many python packages were still build against 3.5 in edge.
How did you generate the list of python packages that needed to be upgraded?

**Comment by jirutka** [comment]
IIRC I generated it with SQL query on aports DB. Could you please name some pkgs that were not rebuilt, so I can check how are they different and what went wrong?

**Comment by jirutka** [comment]
Actually, it's PR by scadu, so more likely he somehow generated the list and I just checked it using SQL query? Don't really remember. :/

**Comment by scadu** [comment]
@jirutka I used the script provided by @ncopa. I will share it here once I have an access to my machine.

**Comment by clandmeter** [comment]
You can find a list of packages in aports which i bumped today.

**Comment by scadu** [comment]
@clandmeter Here is the [script](https://gist.github.com/scadu/db1549a1b0afaca7b49e202ded0c9160).

**Pull request merged**
