### PR TITLE
main/zfs: upgrade to 0.7.3

### PR DESCRIPTION
**Pull request by gmile**

### CODE REVIEW

**Comment by rgdoliveira** [comment]
Seems that abuild failed to fetch the tar.gz from github

`
>>> zfs: Fetching https://github.com/zfsonlinux/zfs/releases/download/zfs-0.7.3/zfs-0.7.3.tar.gz
>>> zfs: Checking sha512sums...
zfs-0.7.3.tar.gz: FAILED
sha512sum: WARNING: 1 of 1 computed checksums did NOT match
`

Can you try to rebase this patch to force another Travis build? I'm not sure if there is an easier way to retrigger the build

**Comment by gmile** [comment]
@rgdoliveira I just force-pushed, thanks for the heads up. Looks like sha from my original commit was not correct, hopefully I got it right with the force-pushed commit

**Comment by rgdoliveira** [comment]
@gmile not sure if you know, but you can run `abuild checksum` and it will generate the sha automatically for you.

**Comment by gmile** [comment]
@rgdoliveira interesting, I didn't know about abuild. I run macOS where I do the following:
```
$ wget https://github.com/zfsonlinux/zfs/releases/download/zfs-0.7.3/zfs-0.7.3.tar.gz
$ shasum -a 512 -t zfs-0.7.3.tar.gz
```
Then I manually copy-paste the new version and sha into APKBUILD.

Is there a better process?

**Comment by rgdoliveira** [comment]
@gmile hm, maybe in your case you could setup a container with an Alpine and build the packages inside the container

**Pull request closed without merging**
