### PR TITLE
community/plasma*: move from testing

### PR DESCRIPTION
**Pull request by PureTryOut**

### CODE REVIEW

**Comment by PureTryOut** [comment]
CC @Cogitri. I'm moving `xdg-desktop-portal` and `pipewire` to community, are you ok with that?

**Comment by Cogitri** [comment]
Sure, would've needed to do that soon anyway to move GNOME.

**Comment by PureTryOut** [comment]
CC @fabled I've moved `testing/fwupd` to `communty/`, is that alright with you?

CC @pickfire I've moved `testing/ttf-hack` to `community/`, is that alright with you?

**Comment by pickfire** [comment]
Yes

**Comment by maxice8** [comment]
Merged, moved a few other stuff as well that was required. Next time use `aports-lint` to find packages in upper repos

**Pull request closed without merging**
