### PR TITLE
main/samba: upgrade to 4.11.0

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by ncopa** [comment]
Looks like they are using glibc internals (`__compar_fn_t`).
```
../../source4/dsdb/samdb/ldb_modules/count_attrs.c: In function 'get_sorted_attrs':
8738	../../source4/dsdb/samdb/ldb_modules/count_attrs.c:225:41: error: '__compar_fn_t' undeclared (first use in this function)
8739	  225 |  qsort(attrs, n_attrs, sizeof(char *), (__compar_fn_t)strcasecmp_ptr);
8740	      |                                         ^~~~~~~~~~~~~
8741	../../source4/dsdb/samdb/ldb_modules/count_attrs.c:225:41: note: each undeclared identifier is reported only once for each function it appears in
8742	../../source4/dsdb/samdb/ldb_modules/count_attrs.c:225:55: error: expected ')' before 'strcasecmp_ptr'
8743	  225 |  qsort(attrs, n_attrs, sizeof(char *), (__compar_fn_t)strcasecmp_ptr);
8744	      |                                                       ^~~~~~~~~~~~~~
8745	      |                                                       )
8746	../../source4/dsdb/samdb/ldb_modules/count_attrs.c: In function 'count_attrs_search_callback':
8747	../../source4/dsdb/samdb/ldb_modules/count_attrs.c:316:11: error: '__compar_fn_t' undeclared (first use in this function)
8748	  316 |          (__compar_fn_t)strcasecmp_ptr);
8749	      |           ^~~~~~~~~~~~~
8750	../../source4/dsdb/samdb/ldb_modules/count_attrs.c:316:25: error: expected ')' before 'strcasecmp_ptr'
8751	  316 |          (__compar_fn_t)strcasecmp_ptr);
8752	      |                         ^~~~~~~~~~~~~~
8753	      |                         )
```

**Comment by ncopa** [comment]
This is needed to fix build error:

```diff
diff --git a/source4/dsdb/samdb/ldb_modules/count_attrs.c b/source4/dsdb/samdb/ldb_modules/count_attrs.c
index b0d1b22..29f1b94 100644
--- a/source4/dsdb/samdb/ldb_modules/count_attrs.c
+++ b/source4/dsdb/samdb/ldb_modules/count_attrs.c
@@ -222,7 +222,7 @@ static const char **get_sorted_attrs(TALLOC_CTX *mem_ctx,
 		attrs[i] = a;
 	}
 
-	qsort(attrs, n_attrs, sizeof(char *), (__compar_fn_t)strcasecmp_ptr);
+	qsort(attrs, n_attrs, sizeof(char *), (int (*)(const void *, const void *))strcasecmp_ptr);
 	return attrs;
 }
 
@@ -313,7 +313,7 @@ static int count_attrs_search_callback(struct ldb_request *req,
 			}
 
 			qsort(found_attrs, msg->num_elements, sizeof(char *),
-			      (__compar_fn_t)strcasecmp_ptr);
+			      (int (*)(const void *, const void *))strcasecmp_ptr);
 
 
 			/* find and report duplicates */
```

**Comment by ncopa** [comment]
We also need to fix the subpackage splitting:
```
....
>>> samba-server-libs*: Running split function _server_libs...
mv: can't rename '/home/ncopa/aports/main/samba/pkg/samba/usr/lib/samba/libnon-posix-acls-samba4.so': No such file or directory
>>> ERROR: samba-server-libs*: _server_libs failed
```

**Comment by J0WI** [comment]
Meanwhile there is #11950

**Pull request closed without merging**
