### PR TITLE
community/mpd: enable Audio CD support

### PR DESCRIPTION
**Pull request by macmpi**
mpd built-in feature since ver 0.17 (2012/06/27): just enable feature and add relevant dependency

Tested OK on Pi device (armhf)

### CODE REVIEW

**Comment by Cogitri** [comment]
Thank you for the PR. It looks good to me, but could you please rebase the PR on master?

**Comment by macmpi** [comment]
Thank you for feedback.
Can't rebase from GitHub right now, but resolved conflict: fine for you?

**Comment by Cogitri** [comment]
Ah, no, a merge commit isn't OK. You'll have to rebase instead, you can do `git pull --rebase <alpine remote> master`

**Comment by macmpi** [comment]
I'm only on GithHub Web interface now, so can't rebase by CLI.
Alternatively, I can re-form another PR altogether from master, notify and cancel that one: ok?

**Comment by Cogitri** [comment]
Well, you can also do that, but it'd really be best if you just rebase the thing when you're on the CLI again

-------- Original Message --------

**Pull request closed without merging**
