### PR TITLE
testing/mitmproxy: upgrade to 4.0.3

### PR DESCRIPTION
**Pull request by fabaff**

### CODE REVIEW

**Comment by misery** [comment]
mitmproxy requires python3 now. And some other libs.

**Comment by nmeum** [comment]
> mitmproxy requires python3 now. And some other libs.

@fabaff could you adjust your PR accordingly?

**Comment by andypost** [comment]
4.0.4 released

**Comment by andypost** [comment]
@fabaff it needs rebase

**Comment by andypost** [comment]
trying to fix in https://github.com/alpinelinux/aports/pull/4548

**Pull request closed without merging**
