### PR TITLE
testing/msitools: new aport

### PR DESCRIPTION
**Pull request by misery**
Also fix libgcab as msitools requires a valid .pc file

### CODE REVIEW

**Comment by misery** [comment]
Well.... ci malfunction? It does not install the previous build libgcab 0.7-r1

(32/59) Installing libgcab (0.7-r0)
(33/59) Installing libgcab-dev (0.7-r0)

**Comment by jirutka** [comment]
Hm, this is a second case since yesterday where it looks like mirror nl.alpinelinux.org is outdated. I'll take a look.

**Comment by jirutka** [comment]
Hm, no, this is a different issue, you’ve updated libgcap in this PR. It really should pick aport built in the previous step, but does not for some reason.

**Comment by misery** [comment]
Should I split the PR?

**Comment by ncopa** [comment]
I have merged the libgcab already so you can probably just rebase this PR and `git push -f`. I think libtool is needed in the makedeps and one of the tests failed in my env.

**Pull request closed without merging**
