### PR TITLE
main/alpine-mirrors: Added new mirror in Japan

### PR DESCRIPTION
**Pull request by Flast**
Note that we are scheduled to power outage at 21/Oct/2017 - 22/Oct/2017.

Please feel free to contact us `tsukuba-ftp-servers _at_ tsukuba.wide.ad.jp`.

### CODE REVIEW

**Comment by ncopa** [comment]
````
curl: (7) Failed to connect to ftp.tsukuba.wide.ad.jp port 80: Host is unreachable
````
I wonder if the power came back?

**Comment by Flast** [comment]
I'm sorry for that. The service is stopped because of storage corruption. I'll comment when the service is back.

**Comment by Flast** [comment]
Hi there,
The service is now functional.

**Comment by jirutka** [comment]
This has been already merged. Thanks for your contribution!

**Pull request closed without merging**
