### PR TITLE
community/ttf-cantarell: upgrade to 0.111

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
@Cogitri wanna take it ?

**Comment by Cogitri** [comment]
Sure, thanks! :)

**Comment by TBK** [comment]
@maxice8 I am assuming it means @Cogitri wants to adopt it. Could I get you to update maintainer info?

**Comment by maxice8** [comment]
On Fri, May 24, 2019 at 05:19:12PM -0700, TBK wrote:
> @maxice8 I am assuming it means @Cogitri wants to adopt it. Could I get you to update maintainer info?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7686#issuecomment-495818626

updated

**Pull request closed without merging**
