### PR TITLE
community/osinfo-db-tools: upgrade to 1.5.0

### PR DESCRIPTION
**Pull request by maxice8**
@ncopa

### CODE REVIEW

**Comment by TBK** [comment]
Any tests?

**Comment by maxice8** [comment]
On Fri, May 24, 2019 at 07:46:04PM -0700, TBK wrote:
> Any tests?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7646#issuecomment-495831319

No testsuite

**Comment by TBK** [comment]
New release out 1.5.0 with test suite - https://gitlab.com/libosinfo/osinfo-db-tools/blob/master/NEWS

**Comment by maxice8** [comment]
On Fri, May 24, 2019 at 08:43:54PM -0700, TBK wrote:
> New release out 1.5.0 with test suite - https://gitlab.com/libosinfo/osinfo-db-tools/blob/master/NEWS
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7646#issuecomment-495841268

Working on updating it.

**Pull request closed without merging**
