### PR TITLE
[WIP] Build the kernel with clang

### PR DESCRIPTION
**Pull request by martell**
WIP - ignore this for now.

### CODE REVIEW

**Comment by martell** [comment]
```
CC      mm/memory.o
/home/travis/build/alpinelinux/aports/main/linux-vanilla/src/linux-4.14/arch/x86/xen/mmu_pv.c:1326:18: error: 
      fields must have a constant size: 'variable length array in structure'
      extension will never be supported
                DECLARE_BITMAP(mask, num_processors);
                               ^
1 error generated.
```

We probably need llvm 6 or 7 preferably 7 for this.
4.14 seems to build as vanilla here at least 
https://github.com/ClangBuiltLinux/continuous-integration

**Comment by J0WI** [comment]
clang 6 is pending here: #5639

**Comment by J0WI** [comment]
Meanwhile 7 is the default version for clang/llvm. LLVM 8 is here: #7500

**Comment by Cogitri** [comment]
It currently doesn't seem like this is feasible in the near future with a vanilla kernel.

**Pull request closed without merging**
