### PR TITLE
community/sci-py: update to 1.2.1

### PR DESCRIPTION
**Pull request by kopytjuk**
Raise scipy to 1.2.1

### CODE REVIEW

**Comment by Ikke** [comment]
@kopytjuk Please have your commit message include the repo this package is in, like:

> community/sci-py: update to 1.2.1

See the [contributing](https://github.com/alpinelinux/aports/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request-pr) documentation for more information.

This also includes the description in the PR, which makes it easier to triage the PRs.

Thanks.

**Comment by kopytjuk** [comment]
> @kopytjuk Please have your commit message include the repo this package is in, like:
> 
> > community/sci-py: update to 1.2.1
> 
> See the [contributing](https://github.com/alpinelinux/aports/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request-pr) documentation for more information.
> 
> This also includes the description in the PR, which makes it easier to triage the PRs.
> 
> Thanks.

Hi, thank you for your advice - I don't know what I am doing wrong - my build is not working on edge-aarch64 - it stops after 1h of processing ...

**Comment by Ikke** [comment]
@kopytjuk Can you try to restart that specific build? (should be a restart button on the top right if you look on the drone.io page).

**Comment by kopytjuk** [comment]
> @kopytjuk Can you try to restart that specific build? (should be a restart button on the top right if you look on the drone.io page).

It looks like I don't have the rights to press the "restart" button again, it is grey for me

**Comment by Ikke** [comment]
For me as well. Can you try to amend the last commit and then force push? That should restart the CI as well.

**Comment by kopytjuk** [comment]
> For me as well. Can you try to amend the last commit and then force push? That should restart the CI as well.

Restarting did not help ... who can we ask for support?

**Comment by andypost** [comment]
Basically it takes more then 1h for aarch64 https://cloud.drone.io/alpinelinux/aports/779/3/2

**Comment by kopytjuk** [comment]
> Basically it takes more then 1h for aarch64 https://cloud.drone.io/alpinelinux/aports/779/3/2

How I can accelerate the process? The compilation takes time ...

**Pull request closed without merging**
