### PR TITLE
testing/php7-pecl-swoole: enable ppc64le and s390x via libucontext

### PR DESCRIPTION
**Pull request by andypost**
Trying approach from https://github.com/swoole/swoole-src/issues/2692#issuecomment-518059106

### CODE REVIEW

**Comment by andypost** [comment]
I see no dependency on `libucontext` in build env

**Comment by maxice8** [comment]
did you add -lucontext ?

**Comment by andypost** [comment]
@maxice8 does it make sense to add only for this 2 arches or for all?

**Comment by maxice8** [comment]
only for these 2 arches

**Comment by andypost** [comment]
Sadly locally in `chroot` still getting the same
```
[~/aports/testing/php7-pecl-swoole]$ abuild check
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/andypost/aports/testing/php7-pecl-swoole/src/swoole-4.4.3/modules/swoole.so' (tried: /home/andypost/aports/testing/php7-pecl-swoole/src/swoole-4.4.3/modules/swoole.so (Error relocating /home/andypost/aports/testing/php7-pecl-swoole/src/swoole-4.4.3/modules/swoole.so: unsupported relocation type 7), /usr/lib/php7/modules//home/andypost/aports/testing/php7-pecl-swoole/src/swoole-4.4.3/modules/swoole.so.so (Error loading shared library /usr/lib/php7/modules//home/andypost/aports/testing/php7-pecl-swoole/src/swoole-4.4.3/modules/swoole.so.so: No such file or directory)) in Unknown on line 0
Extension 'swoole' not present.
>>> ERROR: php7-pecl-swoole: check failed
```

**Comment by andypost** [comment]
I was missing `;;` at the end of line(
```
$ abuild check

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.3
Built => Aug  9 2019 10:51:39
coroutine => enabled
ucontext => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1c  28 May 2019
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

**Comment by andypost** [comment]
@maxice8 are you ok with this changes?

**Comment by maxice8** [comment]
Can't test on ppc64le and s390x

**Pull request closed without merging**
