### PR TITLE
main/uwsgi: add php plugin support

### PR DESCRIPTION
**Pull request by MorphBonehunter**
There are 2 package requests open and i thould i could fullfill them:
https://bugs.alpinelinux.org/issues/6602
https://bugs.alpinelinux.org/issues/7061
The changes extend the uwsgi with two new packages:
* uwsgi-php5
* uwsgi-php7

### CODE REVIEW

**Comment by jirutka** [comment]
Please fix the commit message (amend and force push), uwsgi is in main, not testing.

**Comment by MorphBonehunter** [comment]
sorry...first contribution...to much copy & paste from contribution guide...

**Comment by rnalrd** [comment]
pkgrel needs +1

**Comment by rnalrd** [comment]
I actually I took care of it, also slightly modified commit message so that bugs got resolved automatically

Thanks!

**Comment by MorphBonehunter** [comment]
So this means that uwsgi will never get php support because of the do live in different repos?
So this should definitely mentioned in the contribution guide (can not find this somewhere).

**Comment by jirutka** [comment]
> So this means that uwsgi will never get php support because of the do live in different repos?

Yeah, it looks like that. We may consider moving uwsgi to the community repository.

> So this should definitely mentioned in the contribution guide (can not find this somewhere).

Agree. You’d also know it from CI, if it didn’t failed due to missing `check()` function before even trying to build it. I’ve already reverted this bad decision in d903a94387dd251b043b8b50c57095d0ef498f38, partially as a reaction to this incident.

**Pull request closed without merging**
