### PR TITLE
community/sox: modernize

### PR DESCRIPTION
**Pull request by maxice8**
- Enable tests
- Enable -static package
- Fix license

### CODE REVIEW

**Comment by Ikke** [comment]
Seems like the split for the static subpkg is not working properly:

> \>\>\> WARNING: sox-dev*: Found static archive on usr/lib/libsox.a but name doesn't end with -static

> \>\>\> sox-static*: Preparing subpackage sox-static...
> /usr/bin/abuild: cd: line 2293: can't cd to /home/buildozer/aports/community/sox/pkg/sox-static: No such file or directory
> \>\>\> ERROR: sox-static*: prepare_package failed

**Comment by maxice8** [comment]
https://github.com/alpinelinux/abuild/pull/72

**Comment by maxice8** [comment]
Worked around it by declaring -static before -dev

**Comment by Ikke** [comment]
@maxice8 This is currently failing on s390x:

> Assertion failed: b (hcom.c: makecodes: 290)
xargs: './sox' terminated by signal 6
/home/buildozer/aports/community/sox/src/sox-14.4.2/src/.libs/lt-sox FAIL formats: can't open input file `intermediate.hcom': premature EOF
*FAIL* channels=1 "u8 in wav" <--> "hcom".

**Pull request closed without merging**
