### PR TITLE
Updated testing/google-authenticator package

### PR DESCRIPTION
**Pull request by fabn**
Updated package and moved back to testing repository.

### CODE REVIEW

**Comment by jirutka** [comment]
Do you use this package? Does it work?

**Comment by fabn** [comment]
Yes, we use that into a docker VPN image to provide two factor authentication for VPN users, see linked issue.

Various people was using its previous build successfully and now all new image builds are broken because it was moved to unmaintained.

I updated the package to the latest version and it still works, so it would be nice to have it back in testing.

**Comment by jirutka** [comment]
Okay, then we should move it directly into the community repository. I’ll change it when merging.

**Comment by fabn** [comment]
Good, thanks.

**Comment by jirutka** [comment]
This package doesn’t have a maintainer. Are you willing to claim yourself as a maintainer?

**Comment by fabn** [comment]
Ok, I can do that.

**Comment by jirutka** [comment]
Great, then please update this PR.

**Comment by jirutka** [comment]
Merged, thanks for your contribution!

**Comment by fabn** [comment]
Thanks to you

**Pull request closed without merging**
