### PR TITLE
non-free/unifi: new aport

### PR DESCRIPTION
**Pull request by TBK**

### CODE REVIEW

**Comment by rnalrd** [comment]
I've checked the Unifi Controller EULA: we aren't allowed to redistribute this software

_YOU MUST READ AND AGREE TO THE TERMS OF THIS EULA BEFORE USING, DOWNLOADING OR INSTALLING ANY SOFTWARE._

[snip]

_You shall not directly or indirectly do any of the following:_

[snip]

_copy, reproduce, broadcast, transmit, republish, distribute, modify, prepare derivative works of, perform, publicly perform or display the Software or any Content in any way without the prior written consent of Ubiquiti and its applicable licensors;_

**Comment by TBK** [comment]
I made the package after reading this on https://community.ubnt.com/t5/UniFi-Wireless/Unifi-Controller-software-license/m-p/1744454#M194230

**Comment by rnalrd** [comment]
**non-free** does not actually package the software, so may be we're not violating the "redistribute" thing. But the user does not get the chance to read the EULA and agree to it.
I can't find a clear indication on the thread above about this requirement, but may be it's just me not seeing it.

**Comment by TBK** [comment]
To my understanding it is the same with the RPM package, but will have to check.

**Comment by clandmeter** [comment]
Ive taken a look at this aport and gave it some thought (and discussed it internally).
Because I had to modify a lot of it i decided to commit my local version which is based on yours.

Thanks for your contribution and hope you dont mind me stepping in.

**Comment by TBK** [comment]
@clandmeter Thanks for finishing it :D 👍

@rnalrd To answer license question. The rpm version does not ask the user to approve the license.

**Pull request closed without merging**
