### PR TITLE
community/nxapi: fix depends / paths & move to testing

### PR DESCRIPTION
**Pull request by itoffshore**
* `/usr/bin/nxtool` is a wrapper for `/etc/nginx/nxapi/nxtool.py`
(using `/usr/bin/nxtool.py` directly will mean `python` error traces will not be shown)
    
* this version of `nxtool` requires '`fielddata=true on [id]`' under elasticsearch `5.x` which is not recommended:
    
    https://www.elastic.co/guide/en/elasticsearch/reference/5.5/fielddata.html
    
    (see [nxtool-ng](https://github.com/nbs-system/nxtool-ng) for better support under ES `5.x` which I will add in a subsequent `PR`)
    
* if you run `nxapi` in a separate container to nginx edit the value in `/etc/nginx/nxapi/nxapi.json` for:
    
    `rules_path`

### CODE REVIEW

**Comment by kaniini** [comment]
@itoffshore py2-elasticsearch is stuck in testing.  it needs to be moved first.

**Comment by itoffshore** [comment]
@kaniini - yes thank you - just going to test `nxtool` a little bit more to confirm it all works ok - then also move `py-elasticsearch` in this PR

**Comment by itoffshore** [comment]
it made more sense to move `nxapi` back to `testing` with all the depends being there too. 

* this `PR` will build once https://github.com/alpinelinux/aports/pull/1925 is pulled.

**Comment by nmeum** [comment]
Looks good except for commit 33d23a50d83d556e507e7c9b76b6bb932aa0b082 could you seperate the commit moving nxapi back to testing and the commit fixing the dependencies / paths?

**Comment by itoffshore** [comment]
@nmeum - the community `=>` testing move is split into a separate commit

**Comment by itoffshore** [comment]
as the conflicts were unresolvable - I've made a new `PR` https://github.com/alpinelinux/aports/pull/3025

**Pull request closed without merging**
