### PR TITLE
main/freeswitch: Trigger rebuild after updated ldns package

### PR DESCRIPTION
**Pull request by sergey-safarov**

### CODE REVIEW

**Comment by ncopa** [comment]
Why does freeswitch need to be rebuilt after ldns update? are ther other packages that needs to be rebuilt?

**Comment by sergey-safarov** [comment]
because 'ldns' not provides more `libldns.so.2`. Now provides `/usr/lib/libldns.so.3`
```
/ # apk add freeswitch
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  so:libldns.so.2 (missing):
    required by: freeswitch-1.8.7-r0[so:libldns.so.2]
/ # 
```

**Comment by sergey-safarov** [comment]
> are ther other packages that needs to be rebuilt?

Think need to rebuild all other depended packages. But I not know command to get list of packages that use `ldns`.

**Comment by maxice8** [comment]
apk search --rdepends --quiet --origin so:libldns.so.2 returns nothing only freeswitch and libreswan have it on makedepends

**Comment by ncopa** [comment]
> because 'ldns' not provides more `libldns.so.2`. Now provides `/usr/lib/libldns.so.3`

Indeed. I wonder when that change happened? Must have been in 16b7234d95adf0e83952001d0348d83a134e461e. Scary that they break ABI in a patch release. (1.7.0 -> 1.7.1).

```
/ # apk list --depend so:libldns.so.2
freeswitch-1.8.7-r0 x86_64 {freeswitch} (MPL-1.1)
```
Seems like it is only freeswitch that needs rebuild.

**Comment by sergey-safarov** [comment]
https://github.com/alpinelinux/aports/pull/10574 fix of this PR

**Pull request closed without merging**
