### PR TITLE
community/quassel: upgrade to 0.13.1

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by Ikke** [comment]
@J0WI This also needs an -openrc subpkg

**Comment by J0WI** [comment]
Are the necessary steps somewhere documented?

**Comment by Ikke** [comment]
@J0WI 

There is a default_openrc function, so usually it's just enough to declare `$pkgname-openrc` as a subpackage. But as this is a meta package with a core and common components, I was not sure if the default dependencies would make sense.

**Comment by J0WI** [comment]
Fixed in 2c1d00d4f2e00bd37f8e35b7aea97d9f2fd5ead9

**Pull request closed without merging**
