### PR TITLE
community/mtd-utils: upgrade to 2.1.1

### PR DESCRIPTION
**Pull request by oliv3r**
Version bump of mtd-utils

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>

### CODE REVIEW

**Comment by maxice8** [comment]
Commit title is wrong

**Comment by oliv3r** [comment]
> Commit title is wrong

hah, I was only checking to see if the test where actually running on the CI, but it's fixed :) thanks

**Comment by maxice8** [comment]
> hah, I was only checking to see if the test where actually running on the CI

So not supposed to be merged now ?

**Comment by oliv3r** [comment]
> > hah, I was only checking to see if the test where actually running on the CI
> 
> So not supposed to be merged now ?

As all tests have passed, and the previous change about tests not working is resolved, yes, why not!

**Pull request closed without merging**
