### PR TITLE
[3.9] main/gd: modernize and add security patches

### PR DESCRIPTION
**Pull request by J0WI**
Backport of #6517

### CODE REVIEW

**Comment by J0WI** [comment]
:ping_pong: @clandmeter

**Comment by andypost** [comment]
Sounds it needs bsckport

**Comment by J0WI** [comment]
cc @ncopa

**Comment by J0WI** [comment]
@rnalrd could you to review this please?

**Comment by J0WI** [comment]
Fixed in 2af60a5c6e7e457381ff31c346871e7c51812cfa, thanks!

**Pull request closed without merging**
