### PR TITLE
community/bcc: move from testing

### PR DESCRIPTION
**Pull request by acj**
This also moves libbpf because it's a dependency.

### CODE REVIEW

**Comment by kaey** [comment]
Would be great to split package into subpackages before moving to community.
`bcc-tools`, `bcc-doc`, `bcc-tools-doc`, `py-bcc`, maybe `bcc-dev` but I'm not sure if tools require c headers or not. This way other tools which only depend on libbcc (bpftrace for example) will not install stuff user is not interested in.

**Comment by acj** [comment]
Thanks for the feedback. `bcc-*doc` should be easy to do. The others may be difficult to separate, but I'll give it a try.

**Comment by acj** [comment]
Subpackage changes are in #9937.

**Comment by acj** [comment]
Closing this until the subpackage PR lands.

**Pull request closed without merging**
