### PR TITLE
Upgrade and move apache-ant and jetty-runner to the community repo

### PR DESCRIPTION
**Pull request by jirutka**

### CODE REVIEW

**Comment by ncopa** [comment]
You cannot move those to `main` because they depend on `openjdk8` which is in `community`. We can move them to `community` though.

**Comment by jirutka** [comment]
@ncopa Ah, you’re right, I’ve updated the PR and moved them to the community repo instead of main.

**Comment by ncopa** [comment]
maybe also fix commit message which still say "move to the main repo" while it actually moves to `community`

**Comment by jirutka** [comment]
Sorry, fixed.

**Comment by ncopa** [comment]
applied. Thanks!

**Pull request closed without merging**
