### PR TITLE
community/openjdk7: security upgrade to 7.231.2.6.19

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by ncopa** [comment]
This fails on at least ppc64le:
```
# Running javac:                                                                                                        
/home/ncopa/aports/community/openjdk7/src/icedtea-2.6.19/bootstrap/jdk1.6.0/bin/javac -J-XX:ThreadStackSize=1664 -J-XX:-
PrintVMOptions -J-XX:+UnlockDiagnosticVMOptions -J-XX:-LogVMOutput -J-Xmx512m -J-Xms512m -J-XX:PermSize=32m -J-XX:MaxPer
mSize=160m -g -Xlint:all -Xlint:-path -source 7 -target 7 -encoding ascii -Xbootclasspath:/home/ncopa/aports/community/o
penjdk7/src/icedtea-2.6.19/openjdk.build-boot/classes -sourcepath /home/ncopa/aports/community/openjdk7/src/icedtea-2.6.
19/generated.build:../../../../src/solaris/classes:../../../../src/share/classes -d /home/ncopa/aports/community/openjdk
7/src/icedtea-2.6.19/openjdk.build-boot/classes @/home/ncopa/aports/community/openjdk7/src/icedtea-2.6.19/openjdk.build-
boot/tmp/sun/sun.security.util/.classes.list.filtered       
Annotation processing got disabled, since it requires a 1.6 compliant JVM                                               
----------                                                                                                              
1. ERROR in /home/ncopa/aports/community/openjdk7/src/icedtea-2.6.19/openjdk-boot/jdk/src/share/classes/sun/security/uti
l/Optional.java (at line 196)                               
        return Optional.ofNullable(mapper.apply(value));                                                                
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Type mismatch: cannot convert from Optional<capture#5-of ? extends U> to Optional<U>   
----------                                                                                                              
1 problem (1 error)make[6]: *** [/home/ncopa/aports/community/openjdk7/src/icedtea-2.6.19/openjdk-boot/jdk/make/common/R
ules.gmk:254: .compile.classlist] Error 255                                                                             
rm /home/ncopa/aports/community/openjdk7/src/icedtea-2.6.19/generated.build/sun/security/util/Resources_zh_HK.java      
make[6]: Leaving directory '/home/ncopa/aports/community/openjdk7/src/icedtea-2.6.19/openjdk-boot/jdk/make/sun/security/
util'                                                                                                                   
make[5]: *** [Makefile:77: all] Error 1                                                                                 
make[5]: Leaving directory '/home/ncopa/aports/community/openjdk7/src/icedtea-2.6.19/openjdk-boot/jdk/make/sun/security'
make[4]: *** [Makefile:102: all] Error 1               
make[4]: Leaving directory '/home/ncopa/aports/community/openjdk7/src/icedtea-2.6.19/openjdk-boot/jdk/make/sun'
make[3]: *** [Makefile:253: all] Error 1                                                                                
make[3]: Leaving directory '/home/ncopa/aports/community/openjdk7/src/icedtea-2.6.19/openjdk-boot/jdk/make'             
make[2]: *** [make/jdk-rules.gmk:93: jdk-build] Error 2                                                                 
make[2]: Leaving directory '/home/ncopa/aports/community/openjdk7/src/icedtea-2.6.19/openjdk-boot'                      
make[1]: *** [Makefile:251: build_product_image] Error 2
make[1]: Leaving directory '/home/ncopa/aports/community/openjdk7/src/icedtea-2.6.19/openjdk-boot'
make: *** [Makefile:2737: stamps/icedtea-boot.stamp] Error 2                                                            
>>> ERROR: openjdk7: build failed      
```

@mksully22 do you think you can help with this?

**Comment by mksully22** [comment]
Looks like failing on all architectures :(

**Comment by J0WI** [comment]
There is something wrong. The `Optional` has been introduced with Java 8.

**Comment by Cogitri** [comment]
Maybe you could put this on Gitlab? I don't really want to merge something with CI failing everything :/

**Comment by q66** [comment]
I'm getting the same issue introducing openjdk7 for bootstrapping in Void; previous release works okay.

**Comment by J0WI** [comment]
I haven't found any suspect commit upstream, did you?

**Comment by q66** [comment]
i haven't found anything helpful

**Comment by J0WI** [comment]
This has been fixed in the recent release, but the `java-gcj-compat` package is currently broken in edge. It works for me in 3.10.

**Comment by J0WI** [comment]
The issue on edge seems to be fixed

**Comment by Cogitri** [comment]
CI still fails:

```
1. ERROR in /home/buildozer/aports/community/openjdk7/src/icedtea-2.6.20/openjdk-boot/jdk/src/share/classes/sun/security/util/Optional.java (at line 196)

return Optional.ofNullable(mapper.apply(value));
Type mismatch: cannot convert from Optional<capture#5-of ? extends U> to Optional<U>
```

**Pull request closed without merging**
