### PR TITLE
community/php7: upgrade 7.0.21

### PR DESCRIPTION
**Pull request by andypost**
Security release http://php.net/archive/2017.php#id2017-07-06-1

### CODE REVIEW

**Comment by andypost** [comment]
the same question with 5.x http://php.net/ChangeLog-5.php#5.6.31

**Comment by jirutka** [comment]
Please rebase it against current 3.6-stable (I’ve fixed Travis issue).

**Comment by andypost** [comment]
why 3.6? it has php 7.1 and only 3.5 has 7.0

**Comment by jirutka** [comment]
Sry, I meant 3.5-stable.

**Comment by andypost** [comment]
rebased

**Pull request closed without merging**
