### PR TITLE
testing/emulationstation: Rebuild against boost-1.67

### PR DESCRIPTION
**Pull request by tanertas**

### CODE REVIEW

**Comment by andypost** [comment]
Latest rebuild on aarch64 fails http://build.alpinelinux.org/buildlogs/build-edge-aarch64/testing/emulationstation/emulationstation-2.7.1-r1.log

**Comment by tanertas** [comment]
Thanks for report. Probably related with these:

https://github.com/opencv/opencv/issues/7600
https://github.com/imagemin/optipng-bin/issues/97

**Comment by andypost** [comment]
So needs https://github.com/opencv/opencv/commit/bdaab1cee59d20916fb659fa37186af9e39da076.patch  & decide how neon support make optional

**Comment by tanertas** [comment]
@andypost  Can you try again after #5013 ?

**Comment by andypost** [comment]
now build passed, does it still needs rebuild cos in edge x86_64 
```
/ # ldd $(which emulationstation) 
	/lib/ld-musl-x86_64.so.1 (0x7f944895b000)
	libboost_system-mt.so.1.67.0 => /usr/lib/libboost_system-mt.so.1.67.0 (0x7f9447efd000)
	libboost_filesystem-mt.so.1.67.0 => /usr/lib/libboost_filesystem-mt.so.1.67.0 (0x7f9447ce2000)
```

**Pull request closed without merging**
