### PR TITLE
testing/tpm2-tools: upgrade to 4.1_rc1

### PR DESCRIPTION
**Pull request by asac**

### CODE REVIEW

**Comment by asac** [comment]
FYI: I fixed build failure due to refactored tpm2-tss package alongside this version upgrade. thanks for reviewing and landing this...

**Comment by asac** [comment]
@Cogitri mind rubberstamping this one? Also let me know if I shall rather have some other 'maintainer' to be my primary contact for tpm related landings in future etc... sorry, still not 100% sure about the right practices of alpine maintainership. Thanks!

**Comment by Cogitri** [comment]
Heya,

why do you want to upgrade to a release candidate? Can't we wait for the next stable release? :)

**Comment by asac** [comment]
@Cogitri well, current package fails to build from source from what I understand due to the refactoring of the tpm2-tss source package ... also 4.1_rc1 has a patch I upstreamed that I would love to have back without maintaining a downstream fork and third, thought this is testing/edge and in my experience 4.1rc1 is better than latest 4.0. Thanks!

**Comment by Cogitri** [comment]
Fair enough. Please add this rationale to the commit msg so future contributors know why this change has been done.

**Comment by asac** [comment]
@Cogitri ok pushed improved commit-msg with rational.

**Pull request closed without merging**
