### PR TITLE
community/ghc: upgrade to 8.6.5

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by Ikke** [comment]
@clandmeter Do you know why ghc-bootstrap cannot be found, while it should be provided by the existing ghc?

**Comment by J0WI** [comment]
I reverted the architecture change for now.

**Comment by J0WI** [comment]
:ping_pong: @mitchty

**Comment by Ikke** [comment]
Current failure is due to large log output

**Comment by J0WI** [comment]
@mitchty is not available, could this be reviewed by someone else?

**Comment by J0WI** [comment]
ping @ncopa

**Comment by Ikke** [comment]
Compiling this locally, waiting for it to finish.

**Comment by Ikke** [comment]
@J0WI There were test failures:

SUMMARY for test run started at Fri Aug  9 19:05:59 2019
 0:06:27 spent to go through
    6525 total tests, which gave rise to
   25307 test cases, of which
   18833 were skipped

      28 had missing libraries
    5827 expected passes
      85 expected failures

       0 caused framework failures
       1 caused framework warnings
       0 unexpected passes
     529 unexpected failures
       5 unexpected stat failures
Full test result log here:
http://tpaste.us/yPQg

**Comment by J0WI** [comment]
Thanks for posting your results. I'm now able to reproduce with both, LLVM 5 and 8, but I haven't found a solution so far.

**Comment by Cogitri** [comment]
What's the status of this?

**Comment by J0WI** [comment]
Any help is welcome. Otherwise we have to disable the tests.

**Comment by Cogitri** [comment]
Hm, sadly I don't have a clue about Haskell, have you been in contact with upstream already?

**Comment by XVilka** [comment]
What about skipping 8.6.x versions and go for 8.8.1 directly?

**Comment by J0WI** [comment]
> What about skipping 8.6.x versions and go for 8.8.1 directly?

That version doesn't even compile.

**Comment by XVilka** [comment]
Many distributions support [8.8.1](https://repology.org/project/ghc/versions) now.

**Comment by J0WI** [comment]
8.8.1 needs at least https://gitlab.haskell.org/ghc/ghc/merge_requests/1622.patch to build. But I'm getting the same linker issue as with 8.6.5

**Comment by ncopa** [comment]
the fix-testsuite.patch is missing

**Comment by J0WI** [comment]
I've added the missing patch and rebased. Let's see if it builds.

**Comment by ncopa** [comment]
I got the following errors in checks when building on my dev machine:
```
Unexpected stat failures:
   perf/compiler/parsing001.run    parsing001 [stat too good] (normal)
   perf/haddock/haddock.base.run   haddock.base [stat too good] (normal)
   perf/haddock/haddock.Cabal.run  haddock.Cabal [stat too good] (normal)
   perf/compiler/T5631.run         T5631 [stat too good] (normal)
   perf/should_run/T9203.run       T9203 [stat too good] (normal)

Framework warnings:
   .  T13701 [numfield-no-expected] (No expected value found for bytes allocated in num_field check)


```

**Comment by ncopa** [comment]
actually, there are a whole lot of unexpected errors

**Comment by rlefevre** [comment]
Lots of testsuite errors are due to the following warning on stderr:
```
+make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```
Based on the comments in `./src/ghc-8.6.5/testsuite/mk/test.mk`, this should be handled by the `+` in `+PYTHON` l.329 of the same file, but for some reason, this does not seem to be enough, at least for failed tests with this warning.

**Comment by rlefevre** [comment]
With https://github.com/J0WI/aports/pull/1, which includes the `MAKEFLAGS` hack, the `stat too good` results added for Alpine and a few more patches backported from mainline, I am down to 8 failed tests and 1 warning:
```
SUMMARY for test run started at Tue Dec 10 00:37:59 2019 UTC
 0:21:27 spent to go through
    6525 total tests, which gave rise to
   25307 test cases, of which
   18830 were skipped

      28 had missing libraries
    6356 expected passes
      85 expected failures

       0 caused framework failures
       1 caused framework warnings
       0 unexpected passes
       6 unexpected failures
       2 unexpected stat failures

Unexpected failures:
   ghci/linking/dyn/T10458.run                    T10458 [bad stderr] (ghci)
   numeric/should_run/T7014.run                   T7014 [bad stderr] (normal)
   rts/T2615.run                                  T2615 [bad stdout] (normal)
   rts/T5423.run                                  T5423 [bad stdout] (normal)
   simplCore/should_compile/T13340.run            T13340 [bad exit code] (normal)
   ../../libraries/base/tests/IO/encoding004.run  encoding004 [bad exit code] (normal)

Unexpected stat failures:
   perf/compiler/T9630.run     T9630 [stat not good enough] (normal)
   perf/space_leaks/T4029.run  T4029 [stat not good enough] (ghci)

Framework warnings:
   .  T13701 [numfield-no-expected] (No expected value found for bytes allocated in num_field check)
```
Also on my system the stat failures sometimes pass, sometimes not.

**Comment by rlefevre** [comment]
A few more modifications pushed into my https://github.com/J0WI/aports/pull/1 PR:
* encoding004 is skipped on Alpine because the tested locales cannot be installed simply
* T13340 & T7014 require gnu grep. Adding it in `makedepends_build` fixes them.
* T5423: patch backported from mainline
* T1200: use `grep -m 1` instead of `| head -n ` to avoid broken pipe
* T2615 and T10458 are skipped because of linking problems I don't understand yet
* T9630 & T4029: not good enough stats tolerance increased

The following tests should most likely be investigated to check that there is not a real problem:
* T9630.run at +22% memory allocation
* skipped T10458: linking problem
* skipped T2615: linker script issue
* T12600: broken pipe 

With all those, the remaining tests pass successfully (1 warning):
```
SUMMARY for test run started at Tue Dec 10 15:53:30 2019 UTC
 0:20:43 spent to go through
    6525 total tests, which gave rise to
   25307 test cases, of which
   18833 were skipped

      28 had missing libraries
    6361 expected passes
      85 expected failures

       0 caused framework failures
       1 caused framework warnings
       0 unexpected passes
       0 unexpected failures
       0 unexpected stat failures

Framework warnings:
   .  T13701 [numfield-no-expected] (No expected value found for bytes allocated in num_field check)
```

**Comment by rlefevre** [comment]
The build fails because of the maximum log size is exceeded:

`The job exceeded the maximum log length, and has been terminated.`

Is there a common way to mitigate this without loosing a way to investigate failures properly?

**Comment by rlefevre** [comment]
Reduced verbosity in https://github.com/J0WI/aports/pull/2.

**Comment by J0WI** [comment]
@rlefevre https://build.alpinelinux.org/buildlogs/build-edge-x86_64/community/ghc/ghc-8.6.5-r3.log

**Comment by rlefevre** [comment]
@J0WI I'm not able to reproduce these results.
I rebased your branch on top of `aports` master and added my less-verbose patch:
```
9a6a7f3a8a (HEAD -> ghc-865-no-verbose) community/ghc: build with lower verbosity level and -j $JOBS
163aec13aa community/ghc: fix testsuite on Alpine Linux
171801fbf6 community/ghc: patch testsuite
b3653867bf community/ghc: add BuildFlavour for cross build
1dd3c45882 community/ghc: LLVM 9
6ffd517a77 community/ghc: upgrade to 8.6.5
2379f03a9a (origin/master, origin/HEAD) main/git: upgrade to 2.24.1
9e312fd75b community/jenkins: upgrade to 2.208
f8805f29ed main/nss: upgrade to 3.48
```
made a `git clean -fdx` then `abuild -r` in `community/ghc`, and I only get 1 warning for the test suite:
```
SUMMARY for test run started at Fri Dec 13 09:42:58 2019 UTC
 0:20:46 spent to go through
    6525 total tests, which gave rise to
   25307 test cases, of which
   18833 were skipped

      28 had missing libraries
    6361 expected passes
      85 expected failures

       0 caused framework failures
       1 caused framework warnings
       0 unexpected passes
       0 unexpected failures
       0 unexpected stat failures

Framework warnings:
   .  T13701 [numfield-no-expected] (No expected value found for bytes allocated in num_field check)
```
I use `alpine:edge` on Docker. Is anyone able to reproduce the errors?

**Comment by rlefevre** [comment]
Apparently this has been merged with tests disabled for now:
https://github.com/alpinelinux/aports/commit/40a6c2612a3c73425bc87790a83162140dea9151

How to proceed now?

**Comment by J0WI** [comment]
I got this one:
```
Unexpected failures:
   concurrent/should_run/T5611.run  T5611 [bad stderr] (normal)
```

**Comment by J0WI** [comment]
Closing due 981a3a5ed59c7564acaf78a59d89f9ae6da214c2

**Pull request closed without merging**
