### PR TITLE
testing/rspamd upgraded to 1.6.3

### PR DESCRIPTION
**Pull request by TBK0000**

### CODE REVIEW

**Comment by TBK0000** [comment]
@ncopa Is there anything I can do to speed up the process?

The tweaks I have made to the build script are a result of this commit:
https://github.com/vstakhov/rspamd/commit/17a6ce2ae11994e60f88e934edf2f62ce799089c

**Comment by tmpfile** [comment]
abuild now runs with `set -e` so we don't need any ` || return 1` now as it's implicit by default.
So you should remove all instances of ` || return 1`.
Apart from that it LGTM.
Thanks

**Comment by TBK0000** [comment]
@tmpfile Fixed 👍

**Comment by fabled** [comment]
Another PR with same goal was merged, can you check what it contains and rebase and create new PR for any other pending changes. Thanks.

**Comment by TBK0000** [comment]
@fabled I have create a PR https://github.com/alpinelinux/aports/pull/2213 to fix an issue with the current build.

**Pull request closed without merging**
