### PR TITLE
community/rcon: move from testing

### PR DESCRIPTION
**Pull request by TBK**

### CODE REVIEW

**Comment by TBK** [comment]
As I recall ncopa mentioned at one point that changes to the license does not warrant a pkgrel bump.

hmm we need docs on when to bump pkgrel.

**Comment by maxice8** [comment]
On Thu, May 23, 2019 at 05:40:54AM -0700, TBK wrote:
> As I recall ncopa mentioned at one point that changes to the license does not warrant a pkgrel bump.
> 
> hmm we need docs on when to bump pkgrel.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/8014#issuecomment-495201740

Won't that prevent the users from recieving an updated package that contains the correct license ?

**Comment by Ikke** [comment]
The revbump is required to update the metadata in the package.

**Comment by TBK** [comment]
> The revbump is required to update the metadata in the package.

Fixed.

**Pull request closed without merging**
