### PR TITLE
add gatttool to bluez-deprecated

### PR DESCRIPTION
**Pull request by sharukins**
gatttool is being build but not installed. Therefore we move the binary to /usr/bin

### CODE REVIEW

**Comment by nmeum** [comment]
Merged. Please squash your commits the next time, prefix your commit message with `main/bluez` and bump the pkgrel.

**Comment by sharukins** [comment]
thanks and sorry, I'm pretty new to this.

**Comment by nmeum** [comment]
No problem, just giving some feedback in case you want to send additional patches in the future. You might also want to check out the development documentation in the wiki if that's the case.

**Comment by sharukins** [comment]
Thanks, I really appreciate the feedback. I should probably also learn how to properly use github ^^
If you allow me one question: would this patch be viable for a backport to 3.6? I would consider this a bugfix, but others might see this as adding a feature.

**Comment by nmeum** [comment]
> If you allow me one question: would this patch be viable for a backport to 3.6?

Probably not, we mostly backport security fixes to the stable branches. But I guess this should be decided by the maintainer (@ncopa).

**Pull request closed without merging**
