### PR TITLE
unmaintained/lxappearance-obconf: move from testing

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Ikke** [comment]
Can you add to the commit message why you move it to unmaintained in this case?

**Comment by maxice8** [comment]
Is it really necessary for the generic reason 66 'no maintainer' ?

**Comment by Ikke** [comment]
Usually something triggers the move to unmaintained. Most of the time if a package is still building fine and there are no new updates or serious problems, we might just keep it where it is.

**Comment by maxice8** [comment]
On Sun, May 12, 2019 at 01:24:10PM -0700, Kevin Daudt wrote:
> Usually something triggers the move to unmaintained. Most of the time if a package is still building fine and there are no new updates or serious problems, we might just keep it where it is.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7826#issuecomment-491626369

It has pending updates and can't be updated until lxqt-build-tools is updated to 0.6.0

if we keep it as is outdated then there should be no problems.

**Pull request closed without merging**
