### PR TITLE
testing/mono: upgrade to 5.18.0.268

### PR DESCRIPTION
**Pull request by TBK**

### CODE REVIEW

**Comment by TBK** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

I successfully build it on my x86_64 box.

**Comment by blattersturm** [comment]
Slow build time may be related to [mono/mono#7167](https://github.com/mono/mono/issues/7167#issuecomment-423821927) which doesn't seem resolved yet.

A patch to back it out might be helpful.

**Comment by TBK** [comment]
@blattersturm I bumped to PR to 5.18.0.268 which builds a lot faster.

**Comment by TBK** [comment]
@ncopa Would it be possible to merge this PR soon?

**Pull request closed without merging**
