### PR TITLE
community/nodejs-current: upgrade to 13.3.0

### PR DESCRIPTION
**Pull request by timbru31**
Changelog: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V13.md#13.3.0 - still on python2, because the tooling of Google is not fully python3 compatible.

### CODE REVIEW

**Comment by Cogitri** [comment]
CI fails on armv7&armhf

**Comment by timbru31** [comment]
Oh indeed. I will check what's wrong.

**Comment by Cogitri** [comment]
Seems to fail still: `gyp: /home/buildozer/aports/community/nodejs-current/src/node-v13.3.0/deps/uvwasi/deps/uv/uv.gyp not found`

**Comment by timbru31** [comment]
Indeed. However, I'm not quite sue how to disable gyp for uvwasi - given it's not defined in the Makefile.

**Comment by Cogitri** [comment]
Oops, misclicked :/

Dunno about gyp either, sorry :c

**Comment by timbru31** [comment]
Superseeded by https://gitlab.alpinelinux.org/alpine/aports/merge_requests/2223

**Pull request closed without merging**
