### PR TITLE
main/mesa: Upgrade to 18.2.8

### PR DESCRIPTION
**Pull request by tanertas**
* Compiles without drmdeps.patch on x86_64. Patch dropped.
* Wayland libs are no longer part of mesa.
* Update musl patchset.

### CODE REVIEW

**Comment by andypost** [comment]
meanwhile https://www.mesa3d.org/relnotes/18.3.0.html

**Comment by HRio** [comment]
@tanertas please rebase. 

This patch https://git.alpinelinux.org/cgit/aports/commit/?id=ff8996cea00e39d93c869434e263268eab704591 in master fixes a Xwayland crash for me with 18.2.6.

**Comment by brebs-gh** [comment]
18.2.8 [is out](https://www.mesa3d.org/).

The fix-includes patch can be reduced, as enclosed:
[musl-fix-includes2.patch.txt](https://github.com/alpinelinux/aports/files/2719638/musl-fix-includes2.patch.txt)

**Comment by tanertas** [comment]
> 18.2.8 [is out](https://www.mesa3d.org/).
> 
> The fix-includes patch can be reduced, as enclosed:
> [musl-fix-includes2.patch.txt](https://github.com/alpinelinux/aports/files/2719638/musl-fix-includes2.patch.txt)

Thanks for comment and patch. PR updated.

**Comment by J0WI** [comment]
See also #5977 for mesa 18.3

**Comment by tanertas** [comment]
Alpine "3.9" released with mesa-18.1.7 (not even 18.1.9). What else we can do to keep this distro up-to-date?

**Pull request closed without merging**
