### PR TITLE
main/boost: upgrade to 1.66.0

### PR DESCRIPTION
**Pull request by andypost**

### CODE REVIEW

**Comment by vakartel** [comment]
to build successfuly just remove last two lines from package() function

[boost.patch.txt](https://github.com/alpinelinux/aports/files/1593125/boost.patch.txt)

**Comment by andypost** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by andypost** [comment]
```
resolver.cpp: In member function 'void ResolveHandler<Proto>::operator()(const boost::system::error_code&, boost::asio::ip::basic_resolver_iterator<InternetProtocol>)':
resolver.cpp:84:21: error: 'boost::system::posix_error' has not been declared
   if(boost::system::posix_error::success == e) {
                     ^~~~~~~~~~~
make: *** [Makefile:227: resolver.o] Error 1
make: *** Waiting for unfinished jobs....
>>> ERROR: anytun: all failed
```

**Comment by andypost** [comment]
<details>
<summary>`wt` build failed</summary>
```
In file included from /mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:10:0:
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client:22:11: error: using typedef-name 'boost::asio::io_service' after 'class'
     class io_service;
           ^~~~~~~~~~
In file included from /usr/include/boost/asio.hpp:69:0,
                 from /mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:8:
/usr/include/boost/asio/io_service.hpp:27:20: note: 'boost::asio::io_service' has a previous declaration here
 typedef io_context io_service;
                    ^~~~~~~~~~
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:613:3: error: invalid use of template-name 'boost::asio::strand' without an argument list
   boost::asio::strand strand_;
   ^~~~~
In file included from /usr/include/boost/asio.hpp:123:0,
                 from /mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:8:
/usr/include/boost/asio/strand.hpp:29:7: note: 'template<class Executor> class boost::asio::strand' declared here
 class strand
       ^~~~~~
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C: In constructor 'Wt::Http::Client::Impl::Impl(boost::asio::io_service&, Wt::WServer*, const string&)':
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:67:7: error: class 'Wt::Http::Client::Impl' does not have any field named 'strand_'
       strand_(ioService),
       ^~~~~~~
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C: In member function 'void Wt::Http::Client::Impl::request(const string&, const string&, const string&, const string&, int, const string&, const Wt::Http::Message&)':
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:127:8: error: 'strand_' was not declared in this scope
        strand_.wrap(boost::bind(&Impl::handleResolve,
        ^~~~~~~
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C: In member function 'void Wt::Http::Client::Impl::asyncStop(boost::shared_ptr<Wt::Http::Client::Impl>*)':
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:136:8: error: 'strand_' was not declared in this scope
       (strand_.wrap(boost::bind(&Impl::stop, shared_from_this(), impl)));
        ^~~~~~~
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C: In member function 'void Wt::Http::Client::Impl::startTimer()':
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:185:8: error: 'strand_' was not declared in this scope
       (strand_.wrap(boost::bind(&Impl::timeout, shared_from_this(),
        ^~~~~~~
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C: In member function 'void Wt::Http::Client::Impl::handleResolve(const boost::system::error_code&, boost::asio::ip::basic_resolver<boost::asio::ip::tcp>::iterator)':
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:224:6: error: 'strand_' was not declared in this scope
      strand_.wrap(boost::bind(&Impl::handleConnect,
      ^~~~~~~
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C: In member function 'void Wt::Http::Client::Impl::handleConnect(const boost::system::error_code&, boost::asio::ip::basic_resolver<boost::asio::ip::tcp>::iterator)':
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:245:3: error: 'strand_' was not declared in this scope
  (strand_.wrap(boost::bind(&Impl::handleHandshake,
   ^~~~~~~
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C: In member function 'void Wt::Http::Client::Impl::handleHandshake(const boost::system::error_code&)':
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:269:3: error: 'strand_' was not declared in this scope
  (strand_.wrap
   ^~~~~~~
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C: In member function 'void Wt::Http::Client::Impl::handleWriteRequest(const boost::system::error_code&, const size_t&)':
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:292:3: error: 'strand_' was not declared in this scope
   strand_.wrap
   ^~~~~~~
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C: In member function 'void Wt::Http::Client::Impl::handleReadStatusLine(const boost::system::error_code&, const size_t&)':
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:350:3: error: 'strand_' was not declared in this scope
   strand_.wrap
   ^~~~~~~
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C: In member function 'void Wt::Http::Client::Impl::handleReadHeaders(const boost::system::error_code&, const size_t&)':
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:413:19: error: 'strand_' was not declared in this scope
         asyncRead(strand_.wrap
                   ^~~~~~~
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C: In member function 'void Wt::Http::Client::Impl::handleReadContent(const boost::system::error_code&, const size_t&)':
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:445:5: error: 'strand_' was not declared in this scope
    (strand_.wrap
     ^~~~~~~
[ 63%] Building CXX object src/CMakeFiles/wt.dir/Wt/Http/Message.o
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C: In member function 'bool Wt::Http::Client::request(Wt::Http::Method, const string&, const Wt::Http::Message&)':
/mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:903:53: error: no matching function for call to 'boost::asio::ssl::context::context(boost::asio::io_service&, boost::asio::ssl::context_base::method)'
       (*ioService, boost::asio::ssl::context::sslv23);
                                                     ^
In file included from /usr/include/boost/asio/ssl/context.hpp:757:0,
                 from /usr/include/boost/asio/ssl.hpp:18,
                 from /mnt/community/wt/src/wt-3.3.8/src/Wt/Http/Client.C:26:
/usr/include/boost/asio/ssl/impl/context.ipp:326:1: note: candidate: boost::asio::ssl::context::context(boost::asio::ssl::context&&)
 context::context(context&& other)
 ^~~~~~~
/usr/include/boost/asio/ssl/impl/context.ipp:326:1: note:   candidate expects 1 argument, 2 provided
/usr/include/boost/asio/ssl/impl/context.ipp:63:1: note: candidate: boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)
 context::context(context::method m)
 ^~~~~~~
/usr/include/boost/asio/ssl/impl/context.ipp:63:1: note:   candidate expects 1 argument, 2 provided
[ 63%] Building CXX object src/CMakeFiles/wt.dir/Wt/Http/Request.o
make[2]: *** [src/CMakeFiles/wt.dir/build.make:6443: src/CMakeFiles/wt.dir/Wt/Http/Client.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:134: src/CMakeFiles/wt.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
>>> ERROR: wt: all failed
```
</details>

**Comment by andypost** [comment]
<details><summary>openimageio fails</summary>
```
[ 88%] Building CXX object src/python/CMakeFiles/PyOpenImageIO.dir/py_imageinput.cpp.o
In file included from /mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_imageinput.cpp:31:0:
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:77:36: error: 'numeric' has not been declared
 const void * python_array_address (numeric::array &data, TypeDesc &elementtype,
                                    ^~~~~~~
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:77:52: error: 'data' was not declared in this scope
 const void * python_array_address (numeric::array &data, TypeDesc &elementtype,
                                                    ^~~~
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:77:67: error: expected primary-expression before '&' token
 const void * python_array_address (numeric::array &data, TypeDesc &elementtype,
                                                                   ^
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:77:68: error: 'elementtype' was not declared in this scope
 const void * python_array_address (numeric::array &data, TypeDesc &elementtype,
                                                                    ^~~~~~~~~~~
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:78:43: error: expected primary-expression before '&' token
                                    size_t &numelements);
                                           ^
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:78:44: error: 'numelements' was not declared in this scope
                                    size_t &numelements);
                                            ^~~~~~~~~~~
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:78:55: error: expression list treated as compound expression in initializer [-fpermissive]
                                    size_t &numelements);
                                                       ^
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:111:51: error: 'numeric' does not name a type
 void py_to_stdvector (std::vector<T> &vals, const numeric::array &arr)
                                                   ^~~~~~~
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:111:66: error: expected unqualified-id before '&' token
 void py_to_stdvector (std::vector<T> &vals, const numeric::array &arr)
                                                                  ^
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:111:66: error: expected ')' before '&' token
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:111:67: error: expected initializer before 'arr'
 void py_to_stdvector (std::vector<T> &vals, const numeric::array &arr)
                                                                   ^~~
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:316:42: error: 'numeric' has not been declared
     bool write_scanline_array (int, int, numeric::array&);
                                          ^~~~~~~
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:316:56: error: expected ',' or '...' before '&' token
     bool write_scanline_array (int, int, numeric::array&);
                                                        ^
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:321:48: error: 'numeric' has not been declared
     bool write_scanlines_array (int, int, int, numeric::array&);
                                                ^~~~~~~
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:321:62: error: expected ',' or '...' before '&' token
     bool write_scanlines_array (int, int, int, numeric::array&);
                                                              ^
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:329:43: error: 'numeric' has not been declared
     bool write_tile_array (int, int, int, numeric::array&);
                                           ^~~~~~~
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:329:57: error: expected ',' or '...' before '&' token
     bool write_tile_array (int, int, int, numeric::array&);
                                                         ^
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:339:59: error: 'numeric' has not been declared
     bool write_tiles_array (int, int, int, int, int, int, numeric::array&);
                                                           ^~~~~~~
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:339:73: error: expected ',' or '...' before '&' token
     bool write_tiles_array (int, int, int, int, int, int, numeric::array&);
                                                                         ^
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:348:29: error: 'numeric' has not been declared
     bool write_image_array (numeric::array &buffer);
                             ^~~~~~~
/mnt/testing/openimageio/src/oiio-Release-1.7.14/src/python/py_oiio.h:348:44: error: expected ',' or '...' before '&' token
     bool write_image_array (numeric::array &buffer);
                                            ^
[ 88%] Linking CXX executable oiiotool
make[2]: *** [src/python/CMakeFiles/PyOpenImageIO.dir/build.make:63: src/python/CMakeFiles/PyOpenImageIO.dir/py_imageinput.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2055: src/python/CMakeFiles/PyOpenImageIO.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 88%] Built target oiiotool
make: *** [Makefile:163: all] Error 2
>>> ERROR: openimageio: all failed
```
</details>

**Comment by andypost** [comment]
finally merged

**Pull request closed without merging**
