### PR TITLE
main/libressl: upgrade to 2.9.1

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
LibreSSL only build is here: https://travis-ci.org/alpinelinux/aports/builds/443906075

**Comment by ncopa** [comment]
We are planning to move back to openssl: See this thread: http://lists.alpinelinux.org/alpine-devel/6308.html

**Comment by J0WI** [comment]
I'm aware of this conversation. However, OpenSSL 1.1 is only in testing and since LibreSSL is still living in edge/main and 3.x/main the packages need to be maintained and backported if necessary.
LibreSSL 2.8.x contains further compatibility enhancements for OpenSSL APIs btw.

**Comment by ncopa** [comment]
I am ok to upgrade libressl to 2.8 and keep it around. But i think we should rebuild all those packages against openssl 1.1 instead of libressl.

**Comment by J0WI** [comment]
Feel free to cherry-pick https://github.com/alpinelinux/aports/commit/7e0263d01479fc4c341cd7dcfa1ee77aff4ff014.
But AFAIK rebuilding against OpenSSL 1.1 can only be done after the package has been moved from `testing` to `main`. Some packages will need further attention for OpenSSL 1.0 vs. OpenSSL 1.1 compatibility or removal of LibreSSL patches.

**Comment by J0WI** [comment]
See e.g. docker-library/httpd#115

**Comment by J0WI** [comment]
@ncopa this is now rebased on top of the transition to `openssl`.

**Comment by fabled** [comment]
We still have a small number of packages held back and linked to libressl due to not supporting openssl 1.1. Do those need rebuild?

**Comment by J0WI** [comment]
There are some pending PRs to remove this dependency:
#5306
#5353
#5620
#5621

**Comment by ncopa** [comment]
> We still have a small number of packages held back and linked to libressl due to not supporting openssl 1.1. Do those need rebuild?

yes.

**Comment by J0WI** [comment]
I just updated the list in https://github.com/alpinelinux/aports/pull/5406#issuecomment-437837365. Some PRs have been superseded.

**Comment by J0WI** [comment]
Shouldn't the [packages depending on libressl](https://github.com/alpinelinux/aports/pull/5406#issuecomment-437837365) be updated before the 3.9 release?

**Comment by andypost** [comment]
As https://github.com/alpinelinux/aports/pull/6226 shows `libssh2-dev` getting dependency on libressl after build

**Comment by ncopa** [comment]
We should use the stable releases, which means that we should use libressl 2.8.3 and not 2.9.0 which is unstable. This means that 2.9.1 will break ABI and require rebuild of everything linked against libressl.

https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.8.3-relnotes.txt

**Comment by J0WI** [comment]
> Use 2.8.3 and rebase.

Done.

**Comment by andypost** [comment]
```
-usr/lib/debug/usr/lib/libcrypto.so.43.0.1.debug
-usr/lib/debug/usr/lib/libssl.so.45.0.1.debug
-usr/lib/debug/usr/lib/libtls.so.17.0.1.debug
+usr/lib/debug/usr/lib/libcrypto.so.44.0.1.debug
+usr/lib/debug/usr/lib/libssl.so.46.0.1.debug
+usr/lib/debug/usr/lib/libtls.so.18.0.1.debug
```

**Comment by ncopa** [comment]
Those need a rebuild:
````
$ apk search --rdepends --quiet --origin so:libcrypto.so.43 so:libssl.so.45 so:libtls.so.17 | sort -u
acme-client
john
libressl
peervpn
racket
remmina
shadowsocks-libev
tlsdate
````

I think I have fixed `remmina` already with 5aba7d2b4943fa3b49e8f704f06de80c2dd0d583. `racket` looks somewhat complicated, but I suspect it can be updated and rebuilt with openssl. Maybe maintainer @jirutka can help us with that?

The others are probably straight forward.

**Comment by J0WI** [comment]
2.9.1 is now stable: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.9.1-relnotes.txt

**Comment by J0WI** [comment]
How to proceed with this? @ncopa @jirutka

**Comment by ncopa** [comment]
I get the following error when trying to rebuild `peervpn`:
````
ERROR: libressl2.9-libcrypto-2.9.1-r0: trying to overwrite etc/ssl/cert.pem owned by ca-certificates-cacert-20190108-r0.
ERROR: libressl2.9-libcrypto-2.9.1-r0: trying to overwrite etc/ssl/openssl.cnf owned by libcrypto1.1-1.1.1b-r1.
````

This needs to be solved before we can merge.

Can we simply remove the cert.pem and openssl.cnf from libressl?

**Comment by J0WI** [comment]
Not sure if `openssl.cnf` will be fully compatible, but `cert.pem` should be fine.

**Comment by J0WI** [comment]
Meanwhile 2.9.2 is out.

**Comment by J0WI** [comment]
:ping_pong: @ncopa

**Comment by J0WI** [comment]
Fixed by 900ea77e7a09bb9f78e5e10f128bd264be5b50a7

**Pull request closed without merging**
