### PR TITLE
Update composer to current stable release

### PR DESCRIPTION
**Pull request by skwashd**
On 21 April composer 1.0.2 was released. beta1 is now ~8 weeks old.

### CODE REVIEW

**Comment by ncopa** [comment]
i fixed the commit message and pushed it. thanks!

**Comment by skwashd** [comment]
@ncopa thanks for that. What is the correct format for commit messages? I'd like to get it right next time.

**Comment by ncopa** [comment]
````
<repo>/<package>: short desc

longer desc which answers the question "why was this change made" if that is not obvious.
if it has fix for specific issue in bugtracker then also add:
fixes #<issuenumber>
````

**Comment by skwashd** [comment]
OK, I'll try to do that next time.

**Pull request closed without merging**
