### PR TITLE
main/soxr: add -static subpackages

### PR DESCRIPTION
**Pull request by Cogitri**
fixes #10531

### CODE REVIEW

**Comment by wader** [comment]
Built the packages locally on edge and they installs fine. But i have some issue using them to build a static ffmpeg binary.

```
$ ./configure --pkg-config-flags=--static  --extra-ldflags=-static --toolchain=hardened  --enable-static --enable-libsoxr
ERROR: libsoxr not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
$ tail ffbuild/config.log
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: filter.c:(.text+0xac8): undefined reference to `omp_unset_lock'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: filter.c:(.text+0xad8): undefined reference to `omp_unset_lock'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../lib/libsoxr.a(filter.c.o): in function `_soxr_safe_rdft':
filter.c:(.text+0x7ec): undefined reference to `omp_unset_lock'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: filter.c:(.text+0x817): undefined reference to `omp_unset_lock'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../lib/libsoxr.a(filter.c.o): in function `_soxr_safe_cdft':
filter.c:(.text+0x8ac): undefined reference to `omp_unset_lock'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../lib/libsoxr.a(filter.c.o):filter.c:(.text+0x8d7): more undefined references to `omp_unset_lock' follow
collect2: error: ld returned 1 exit status
ERROR: libsoxr not found
```
I would guess this is because it can't find OpenMP (soxr built with it by default it seems). There is a libgomp package in alpine but no static files there (not a -dev package either). Is this not a soxr package problem more a lack of libgomp dev/static package? or maybe i'm missing something?

**Comment by Cogitri** [comment]
It's a lack of the libgomp static package. Will open a  PR for that in a bit.

**Comment by wader** [comment]
@Cogitri Ok thanks! ping me here or in the libgomp PR if you want me to test thing

**Comment by Cogitri** [comment]
Seems like you can install `gcc` for now for libgomp.a: https://pkgs.alpinelinux.org/contents?file=*gomp*&path=&name=&branch=edge&repo=testing&arch=x86_64

**Comment by wader** [comment]
Oh thanks! also thanks for showing the content search, very useful. Didnt even notice the contents tab :)

**Pull request closed without merging**
