### PR TITLE
main/ruby: upgrade to 2.6.3

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
> for commit 1d1584a:
should pkgrel from 1 to 2

Yes, same on https://github.com/alpinelinux/aports/pull/7806/commits/e58e47e7c9f00c5f1c495115c6847305f47a7e8d and https://github.com/alpinelinux/aports/pull/7806/commits/fdb9fbc3341ca227c37f2b3ecd9d706ce9a79616. I'll double check my snipped that I'm using to bump pkgrel.

**Comment by J0WI** [comment]
Rebased with fixed pkgrel.

**Comment by ncopa** [comment]
I rebased it and tried to build.

I got a couple of errors (asciidoctor and protobuf at least) due to missing `rdoc`, so I added a patch from upstream.

`ruby-augeas` failed with error that `--no-rdoc` and `--no-ri` are unknown options. I removed those.

`ruby-mathematical` tests fails, so I disabled the tests.

`ruby-pygments` fails with:
```
(5/10) Installing ruby-bundler (2.0.2-r1)                
ERROR: ruby-bundler-2.0.2-r1: trying to overwrite usr/bin/bundle owned by ruby-2.6.3-r1.                   
ERROR: ruby-bundler-2.0.2-r1: trying to overwrite usr/bin/bundler owned by ruby-2.6.3-r1.
```

Maybe we should split out `bundler/bundle` as a subpackage? Or do we simply remove it from makedepends in `ruby-pygments`.

**Comment by J0WI** [comment]
@ncopa I missed the rebuild of `ruby-nokogiri` when I rebased d95b18b. This should also fix `ruby-mathematical`: #10892
Thanks for merging this and pushing the follow up fixes. I'm not sure if `ruby-pygments` will survive the Python 2 sunset. I already tried to patch it for Python 3, but it still does not work for me.

**Comment by ncopa** [comment]
this was merged. thanks!

**Pull request closed without merging**
