### PR TITLE
community/emacs enabled emacs also for aarch64

### PR DESCRIPTION
**Pull request by stef**
ellingtonsantos@gmail.com reports: I already compiled emacs in aarch64 with success.

### CODE REVIEW

**Comment by ncopa** [comment]
Fails here:
````
Loading tooltip...                          
Loading /home/ncopa/aports/community/emacs/src/emacs-25.3/x11/lisp/leim/leim-list.el (source)...
Finding pointers to doc strings...           
Finding pointers to doc strings...done 
Dumping under the name emacs                
**************************************************
Warning: Your system has a gap between BSS and the
heap (291633368 bytes).  This usually means that exec-shield
or something similar is in effect.  The dump may
fail because of this.  See the section about
exec-shield in etc/PROBLEMS for more information.
**************************************************
make[1]: *** [Makefile:740: bootstrap-emacs] Segmentation fault
make[1]: Leaving directory '/home/ncopa/aports/community/emacs/src/emacs-25.3/x11/src'
make: *** [Makefile:398: src] Error 2   
>>> ERROR: emacs: all failed      
````

**Comment by stef** [comment]
hrmpf, thanks, will figure out something. sorry.

**Comment by stef** [comment]
just got this helpful hint:

> It seems a problem with travis using docker to build emacs.
>
> https://github.com/moby/moby/issues/22801
> https://debbugs.gnu.org/cgi/bugreport.cgi?bug=23529
> https://github.com/flycheck/emacs-travis/issues/13
>
> I suggest two tests:
>
> 1) Set  sudo: required in docker or
> 2) Try this line below to disable radomize_va_space.
>
> docker run -it --rm --privileged --pid=host alpine sh -c "echo 0 >/proc/sys/kernel/randomize_va_space"

i just wonder if this is really just a travis bug, but it works on the builders, how can we make travis shutup?

**Comment by jirutka** [comment]
It still fails on aarch64 builder.

http://build.alpinelinux.org/buildlogs/build-edge-aarch64/community/emacs/emacs-25.3-r0.log:
```
Loading /home/buildozer/aports/community/emacs/src/emacs-25.3/x11/lisp/leim/leim-list.el (source)...
Finding pointers to doc strings...
Finding pointers to doc strings...done
Dumping under the name emacs
**************************************************
Warning: Your system has a gap between BSS and the
heap (60016856 bytes).  This usually means that exec-shield
or something similar is in effect.  The dump may
fail because of this.  See the section about
exec-shield in etc/PROBLEMS for more information.
**************************************************
make[1]: *** [Makefile:740: bootstrap-emacs] Segmentation fault
make[1]: Leaving directory '/home/buildozer/aports/community/emacs/src/emacs-25.3/x11/src'
make: *** [Makefile:398: src] Error 2
```

**Comment by stef** [comment]
disabling ASLR is unacceptable. i'll retract this PR.

**Pull request closed without merging**
