### PR TITLE
testing/litespeed: upgrade to 1.4.41 and modernize

### PR DESCRIPTION
**Pull request by joeholden**
Just a WIP - if someone could review the commits and if they look good I'll squash them

### CODE REVIEW

**Comment by andypost** [comment]
@vakartel please review it

@joeholden please squash commits in to upgrade and modernize

**Comment by joeholden** [comment]
Not sure why I set the title to that, that wasn't my intention at all... squashed anyway.

**Comment by andypost** [comment]
@joeholden I'm trying to get why sockets & posix php packages needed, can you clarify?

**Comment by joeholden** [comment]
Sockets is needed for graceful restart from the admin ui, posix is needed for the "compile php" option (useful if supporting multiple versions or don't want to use system php, both common use cases)

**Pull request closed without merging**
