### PR TITLE
testing/clang6: reenable tests

### PR DESCRIPTION
**Pull request by J0WI**
Depends on #5638

### CODE REVIEW

**Comment by J0WI** [comment]
May depend on #6756

**Comment by J0WI** [comment]
@ncopa checks are finally passing :tada: would you like to review this too?

**Comment by ncopa** [comment]
I pushed clang 7 to main. I dont think we need both clang6 and clang7?

**Comment by J0WI** [comment]
creduce is not yet compatible with LLVM/clang 7 (#5640).

**Comment by clandmeter** [comment]
@J0WI 

```
Scanning dependencies of target check-clang
[100%] Running the Clang regression tests
Traceback (most recent call last):
  File "/usr/lib/llvm6/bin/lit", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'lit==0.6.0.dev0' distribution was not found and is required by the application
make[3]: *** [test/CMakeFiles/check-clang.dir/build.make:58: test/CMakeFiles/check-clang] Error 1
make[2]: *** [CMakeFiles/Makefile2:17475: test/CMakeFiles/check-clang.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:17482: test/CMakeFiles/check-clang.dir/rule] Error 2
make: *** [Makefile:4844: check-clang] Error 2
>>> ERROR: clang6: check failed
```

**Comment by J0WI** [comment]
@clandmeter checks are now passing in CI

**Pull request closed without merging**
