### PR TITLE
main/zstd: upgrade to 1.4.4

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by maxice8** [comment]
Duplicate of https://gitlab.alpinelinux.org/alpine/aports/merge_requests/1088

**Comment by J0WI** [comment]
@maxice8 could you apply the url change in your branch?

**Comment by maxice8** [comment]
It isn't my branch but i'll ask @prspkt to apply it

**Comment by prspkt** [comment]
@maxice8 applied url change in https://gitlab.alpinelinux.org/alpine/aports/merge_requests/1088/diffs#1a043581e43f0c9b5ecc0df19dcd21c49517b5c5_8_7

**Comment by maxice8** [comment]
On Thu, 07 Nov 2019 13:01:23 -0800
prspkt <notifications@github.com> wrote:

> @maxice8 applied url change in
> https://gitlab.alpinelinux.org/alpine/aports/merge_requests/1088/diffs#1a043581e43f0c9b5ecc0df19dcd21c49517b5c5_8_7
> 

ack

**Pull request closed without merging**
