### PR TITLE
Upgrade Erlang to 22.0.7 and Elixir to 1.9.1

### PR DESCRIPTION
**Pull request by dunielpls**
This is a PR to upgrade `community/erlang` to version 22.0.7 and `community/elixir` to 1.9.1.

It also adds `erlang-runtime-tools` as a dependency for Elixir, as it seems to be required now.

Note: this commit closes #9132 as it is superseded by this PR. However, this one includes a recent upstream patch the previous PR did not, so it should build cleanly.

### CODE REVIEW

**Comment by dunielpls** [comment]
The failure for `armhf` in Drone seems to have the error cause 'Cancelled' - this build should be fine.

**Comment by maxice8** [comment]
commit titles are wrong

```
<repository>/<pkgname>: upgrade to <pkgver>

$pkgdesc
$url
```

**Comment by dunielpls** [comment]
@maxice8 The commit messages were "community/erlang: bump to patch version 22.0.7" and "community/elixir: bump and add missing dep", I can't see why it has to be "upgrade to <version>" word for word.

But it doesn't matter, it was merged.

**Comment by maxice8** [comment]
> I can't see why it has to be "upgrade to " word for word.

Standard commit title for alpine.

> But it doesn't matter, it was merged.

Someone said this PR was ready to go on IRC and ncopa assumed it was properly reviewed.

**Comment by dunielpls** [comment]
Fair enough - shame it slipped through the cracks.

Thank you for the clarification.

**Pull request closed without merging**
