### PR TITLE
main/jq: add check function

### PR DESCRIPTION
**Pull request by rgdoliveira**

### CODE REVIEW

**Comment by fabled** [comment]
Seems all test cases fail. Any idea why?

**Comment by rgdoliveira** [comment]
Not yet, I need to take a look. 
In ppc64le all tests passed, maybe missing some dependency?

**Comment by fabled** [comment]
```

FAIL: tests/mantest
===================

mktemp: Invalid argument
Your OS does not support mktemp(1) -d

FAIL: tests/jqtest
==================

mktemp: Invalid argument
Your OS does not support mktemp(1) -d

FAIL: tests/onigtest
====================

mktemp: Invalid argument
Your OS does not support mktemp(1) -d

FAIL: tests/shtest
==================

mktemp: Invalid argument
Your OS does not support mktemp(1) -d
```
Maybe needs `checkdepends=coreutils`. But it's weird since busybox mktemp does support `-d`. Looking at `tests/setup` it is calling `mktemp -d -t jqXXXXX`. This is missing one `X` (there should be six of them). Perhaps file upstream bug and ask fixing this?

**Comment by rgdoliveira** [comment]
@fabled you are right. 
We need coreutils in checkdepends to test work. I double-checked it on ppc64le and I had coreutils installed (that's why it worked)

**Comment by fabled** [comment]
We would prefer fixing `make check`. The following patch fixes it, and should be submitted upstream.

```
diff -ru jq-1.5.orig/tests/setup jq-1.5/tests/setup
--- jq-1.5.orig/tests/setup     2015-08-16 04:37:35.000000000 +0000
+++ jq-1.5/tests/setup  2017-09-07 07:07:55.035838903 +0000
@@ -29,7 +29,7 @@
     fi
 }
 trap clean EXIT
-d=`mktemp -d -t jqXXXXX || true`
+d=`mktemp -d -t jqXXXXXX || true`
 if [ -z "$d" ]; then
     echo "Your OS does not support mktemp(1) -d" 1>&2
     exit 1
```

**Comment by rgdoliveira** [comment]
@fabled found a patch already merged upstream that fix our issue. Thanks for reviewing it.

**Comment by ncopa** [comment]
we can just backport https://github.com/stedolan/jq/commit/b7a219a91dc1094022478dd9bc0f60275367ce25

**Comment by rgdoliveira** [comment]
@ncopa that's what I did, thanks!

**Pull request closed without merging**
