### PR TITLE
main/git: Upgrade to 2.14.0

### PR DESCRIPTION
**Pull request by andypost**
Ref https://lkml.org/lkml/2017/8/4/481

### CODE REVIEW

**Comment by andypost** [comment]
Form release notes
> Git can now be built with PCRE v2 instead of v1 of the PCRE
   library. Replace USE_LIBPCRE=YesPlease with USE_LIBPCRE2=YesPlease
   in existing build scripts to build against the new version.  As the
   upstream PCRE maintainer has abandoned v1 maintenance for all but
   the most critical bug fixes, use of v2 is recommended.
So gonna push this update as well

**Comment by andypost** [comment]
> pcre2-dev (missing)
so reverting

**Comment by ncopa** [comment]
I think we should move pcre2 from community to main and use pcre2 for git.

**Comment by andypost** [comment]
now build went fine!

**Pull request closed without merging**
