### PR TITLE
main/nghttp2: Update to 1.33.0

### PR DESCRIPTION
**Pull request by bratkartoffel**

### CODE REVIEW

**Comment by bratkartoffel** [comment]
The integration-tests need go from community. It seems the community repository is not active on travis, I don't know how to fix the build.

**Comment by andypost** [comment]
I'm sure better to remove commit with upgrade to 1.32.1

**Comment by andypost** [comment]
surely package from main can't depend on community (go)

**Comment by bratkartoffel** [comment]
I've updated the PR so that everything is in one commit. The integration tests are commented out for now, until go is moved from community to main. Thanks for pointing out.

**Pull request closed without merging**
