### PR TITLE
testing/py-tox: upgrade to 3.2.1

### PR DESCRIPTION
**Pull request by andypost**
Ref https://tox.readthedocs.io/en/latest/changelog.html

Needed to run selftests, should be moved to main later

### CODE REVIEW

**Comment by andypost** [comment]
```
$ git grep py-tox
main/py-pluggy/APKBUILD:12:#checkdepends="flake8 pytest py-tox"
main/py-virtualenv/APKBUILD:13:#checkdepends="py-tox"
testing/py-pep8-naming/APKBUILD:14:checkdepends="py-tox py-virtualenv"
testing/py-tox/APKBUILD:3:pkgname=py-tox
testing/py-tox/APKBUILD:15:#checkdepends="py-tox"
$ git grep py2-tox
$ git grep py3-tox
testing/py-distro/APKBUILD:13:#checkdepends="py3-tox"
testing/py3-websockets/APKBUILD:13:checkdepends="py3-tox"
```

**Comment by andypost** [comment]
@itoffshore are you ok to upgrade?

**Comment by itoffshore** [comment]
@andypost - yes no problem

I've added a [mapping for future updates](https://release-monitoring.org/project/13221/)

**Comment by andypost** [comment]
Next step is move it to main I guess... but how many packages now using it

**Comment by itoffshore** [comment]
@andypost - nothing depends on it so a [PR to move it to main](https://github.com/alpinelinux/aports/pull/5111)

**Pull request closed without merging**
