### PR TITLE
testing/watchman: upgrade to 4.9.0

### PR DESCRIPTION
**Pull request by andypost**
Upgrade to latest version & attempt to fix build

It needs python & ssl https://facebook.github.io/watchman/contributing.html#getting-started

### CODE REVIEW

**Comment by andypost** [comment]
got a fail locally in tests
```
./test-driver: line 107: 10464 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: tests/art.t
```

**Comment by misery** [comment]
See https://github.com/alpinelinux/aports/pull/2546

**Comment by andypost** [comment]
@misery thanx a lot for pointer, attached patch allowed to pass the test

**Comment by andypost** [comment]
@ncopa please test it on s390x - right now `bser.t` test fails on 4.7.0 http://build.alpinelinux.org/buildlogs/build-edge-s390x/testing/watchman/watchman-4.7.0-r0.log

**Comment by clandmeter** [comment]
I unblocked the builders with 56dba664

**Comment by andypost** [comment]
I see it solved now

**Comment by andypost** [comment]
on s390x `FAIL: tests/bser.t` one test still fail

http://build.alpinelinux.org/buildlogs/build-edge-s390x/testing/watchman/watchman-4.9.0-r1.log

**Pull request closed without merging**
