### PR TITLE
community/kbuild: Enable aarch64 Support

### PR DESCRIPTION
**Pull request by ossdev07**
Added support for aarch64 in APKBUILD by providing patch to enable the support.

### CODE REVIEW

**Comment by ncopa** [comment]
Can you please change commit message to: `community/kbuild: ....`

https://github.com/alpinelinux/aports/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request-pr

Thanks!

**Comment by maxice8** [comment]
Are those 2k loc patches really needed ? can't we just run update_config_sub and update_config_guess ?

**Comment by ossdev07** [comment]
@maxice8 you were right I have updated the APKBUILD as per your suggestion.

**Comment by maxice8** [comment]
The patches are still present

**Comment by ncopa** [comment]
im squashing the commits and removing the patches.

Thanks!

**Comment by ncopa** [comment]
a8ad6aa92e57bf2c9091dbe4ad1e0e3156285cbc

**Pull request closed without merging**
