### PR TITLE
community/x265: Update to 2.9

### PR DESCRIPTION
**Pull request by bratkartoffel**
This PR updates x265 to the latest release.
The "fix_parsecpuname.patch" is now included upstream.

https://x265.readthedocs.io/en/default/releasenotes.html#version-2-9

### CODE REVIEW

**Comment by ncopa** [comment]
This breaks ABI. I think we need rebuild some packages after this upgrade.

````
ncopa-edge-x86_64:~/aports/community/x265$ checkapk
>>> No soname differences for x265.
>>> No soname differences for x265-dev.
--- filelist-x265-libs-old      2018-12-24 14:54:42.166248903 +0000
+++ filelist-x265-libs  2018-12-24 14:54:42.256249311 +0000
@@ -1,4 +1,4 @@
 .PKGINFO
 usr/
 usr/lib/
-usr/lib/libx265.so.160
+usr/lib/libx265.so.165
usr/lib/libx265.so.165:    SONAME               libx265.so.165
````

**Comment by bratkartoffel** [comment]
According to the package info page (https://pkgs.alpinelinux.org/package/edge/community/x86_64/x265) there are no dependants of this package.

I think that the following packages might be using that one, but I'm sure that the list is not complete:
* ffmpeg
* mplayer
* vlc
* gstreamer

**Comment by andypost** [comment]
Probably better check list of required https://pkgs.alpinelinux.org/package/edge/community/x86_64/x265-libs

**Comment by bratkartoffel** [comment]
@andypost Thank your for the hint, I added commits to rebuild the packages.

**Comment by OTLabs** [comment]
3.0 is available now.

**Comment by bratkartoffel** [comment]
Thanks, I'll take a look on the new upgrade.

**Comment by OTLabs** [comment]
Please, take a look as the release notes for 3.0 are available from source:
https://bitbucket.org/multicoreware/x265/src/cb3e172a5f51c6a4bf8adb7953fe53277f5a1979/doc/reST/releasenotes.rst?at=default

Looks like that documentation was not updated so far.

**Comment by prspkt** [comment]
superseded by #6498 - x265 v3.0

**Pull request closed without merging**
