### PR TITLE
community/syncthing: upgrade to 1.0.1

### PR DESCRIPTION
**Pull request by TBK**

### CODE REVIEW

**Comment by TBK** [comment]
The test fails because Travis seems to have issues with IPv6 - https://github.com/travis-ci/travis-ci/issues/8891

**Comment by Ikke** [comment]
@TBK Can you rebase this? Then it will run the drone.io tests as well.

**Comment by TBK** [comment]
@Ikke Done.

Drone CI has the same issue as Travis:
```
14:17:28 FATAL: Starting API/GUI: listen tcp [::1]:0: bind: cannot assign requested address
```

**Comment by Ikke** [comment]
Closing as aports currently already contains 1.0.1. Thanks for your contribution.

**Comment by tcely** [comment]
See https://github.com/alpinelinux/aports/commit/b033ae7fc59f3dbf43cfa546dd0dc9276805e7b0 for `1.0.1.

**Pull request closed without merging**
