### PR TITLE
testing/shiboken: upgrade to 5.11.2

### PR DESCRIPTION
**Pull request by maxice8**
- Uses Qt5
- Uses purely python3
- Has same splitting as Void Linux
- Uses modern style

### CODE REVIEW

**Comment by ddevault** [comment]
LGTM, but py-pyside needs to be updated as well.

**Comment by maxice8** [comment]
On Wed, May 08, 2019 at 07:39:42AM -0700, Drew DeVault wrote:
> LGTM, but py-pyside needs to be updated as well.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7696#issuecomment-490513162

There is a py-pyside package ?

**Comment by ddevault** [comment]
Oh, it's just a local package, it hasn't been upstreamed. My bad.

**Comment by maxice8** [comment]
@ddevault If there is interest i can also package pyside2

**Comment by ddevault** [comment]
No interest from me, I don't need it anymore.

**Comment by maxice8** [comment]
On Wed, May 08, 2019 at 10:29:22AM -0700, Drew DeVault wrote:
> No interest from me, I don't need it anymore.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7696#issuecomment-490577397

Alright

**Comment by andypost** [comment]
Maybe makes sense to provide upgrade path? I mean 
```
provides="shiboken=$pkgver-r$pkgrel" # for backward compatibility
replaces="shiboken" # for backward compatibility
```

**Comment by maxice8** [comment]
@andypost applied

**Pull request closed without merging**
