### PR TITLE
main/alpine-mirrors: add tuna and aliyun mirror

### PR DESCRIPTION
**Pull request by wenerme**
All mirrors is very slow or unable to access from China, aliyun and tuna mian a very good mirror of alpine, this will easy the pain to install alpine from China.

### CODE REVIEW

**Comment by wenerme** [comment]
should i increase pkgrel or version ?

**Comment by tcely** [comment]
@wenerme The `git` history suggests updating `version` is what has been done in the past. When the question is answered by a project member, please would you add a comment in the `APKBUILD` file answering this question?

**Comment by clandmeter** [comment]
We are planning to use a different source for mirrors so please hold this.
Are you the sysop for this mirror?

**Comment by wenerme** [comment]
No, I'm not the sysop of these mirrors, but I use these mirror all the time.

**Comment by clandmeter** [comment]
@wenerme From next release v3.8 and edge we will start to use https://mirrors.alpinelinux.org/mirrors.txt as source. For mirrors to be added a sysop needs to send us an email to alpine-mirrors@alpinelinux.org with mirror details.

We need to have a way to contact with them to be able to add them, so if you want please ask them to do so.

**Pull request closed without merging**
