### PR TITLE
testing/cpd and testing/fgt: new aports

### PR DESCRIPTION
**Pull request by chambbj**
https://github.com/gadomski/cpd
C++ implementation of the Coherent Point Drift point set registration algorithm.

https://github.com/gadomski/fgt
C++ library for fast Gauss transforms.

Note that fgt is required by cpd, hence the combined PR.

### CODE REVIEW

**Comment by chambbj** [comment]
@fabled Sure. I'll do that.

FWIW, I combined them because of this [statement](https://github.com/alpinelinux/aports/blob/master/.github/CONTRIBUTING.md#submitting-a-package-with-new-dependencies).

> When you want to submit a package including its new dependencies to our repository, you should bundle these commits into a single PR. This is needed so our CI will first build the dependencies after which it will build the parent package. Failing to include new dependencies will fail the CI tests.

Maybe it's worth updating the wording if this isn't the preferred practice.

Closing this PR. Will submit new PRs for each of the new packages.

**Comment by chambbj** [comment]
Shoot. Just reread this. You asked for separate commits. Reopening.

**Comment by fabled** [comment]
Yes. Separate commits, one PR is good. Thanks, will look at this in a minute.

**Comment by andypost** [comment]
Somehow hash for the release becomes different now, looks like source package was reuploaded

**Pull request closed without merging**
