### PR TITLE
main/bash-completion: upgrade to 2.9, add -dev subpkg

### PR DESCRIPTION
**Pull request by 3ju**
Upgrade to 2.9 and rework substantially:

    * Modernize (no cd "$builddir").
    * Install "fat" utilities to make the new tests
      work and not break with the simplified command line
      flags of busybox's applets.
    * Remove deletion of conflicting completion files since
      they've been removed from bash-completion.
    * Create -dev subpackage for pkgconf and cmake files.
    * Do not install AUTHORS, CHANGES, CONTRIBUTING.md, README.md.

### CODE REVIEW

**Comment by Cogitri** [comment]
I guess you'll also have to change the packages which expect bash-completion (no -dev) to contain the pkg-config files.

**Comment by andypost** [comment]
Few packages in `main` depends on it like `main/libvirt`, not sure about move

**Comment by 3ju** [comment]
> Few packages in `main` depends on it like `main/libvirt`, not sure about move

Thanks, I moved `py-pexpect` to main in stead.

Fixed makedeps for all packages in main/community/testing.

**Comment by 3ju** [comment]
Seems like the PR builders are unable to use a new package (`bash-completion-dev`) across repos. The revbumped packages in main builds fine, but community and testing is unable to find the new package.

**Comment by Cogitri** [comment]
Yup, that's a known bug in abuild. See https://github.com/alpinelinux/abuild/pull/53

**Comment by Cogitri** [comment]
Uh?

**Comment by 3ju** [comment]
> Uh?

I wanted to rename the branch after I found out moving bash-completion to community was not feasible. No way to change the to-be-merged branch in a Github PR. See #7873

**Pull request closed without merging**
