### PR TITLE
main/imagemagick: security upgrade to 7.0.8-53

### PR DESCRIPTION
**Pull request by timlegge**
Fix rpath issue and upgrade to 7.0.8-53

### CODE REVIEW

**Comment by timlegge** [comment]
@J0WI the build failed on one of the tests.  It is possible that was a one off and rebuilding would work.  I tried to close and reopen to trigger the tests again but only the ci from travis  restarts

**Comment by J0WI** [comment]
`x86_64` already passed on Travis, so this should be ok.
Let's ask @tcely for a review.

**Comment by timlegge** [comment]
Hi

This would fix any future issues

scanelf --recursive --rpath pkg | awk '/home/{print $3;}' | xargs chrpath -d

Tim

**Comment by tcely** [comment]
I would really like to know why DroneCI fails check when TravisCI does not.

**Comment by timlegge** [comment]
me too.  is there a way to run it locally so I ca get some logs

**Comment by tcely** [comment]
> me too. is there a way to run it locally so I ca get some logs

Using https://github.com/alpinelinux/docker-abuild is the easiest way to build it locally in a similar environment.

The DroneCI image is available too and uses this script: https://github.com/alpinelinux/alpine-drone-ci/blob/master/overlay/usr/local/bin/build.sh

`docker pull alpinelinux/alpine-drone-ci:edge-x86_64` will download the image containing that script. Running `build.sh` from that image with appropriate environment variables will let you repeat the CI build locally.

**Comment by timlegge** [comment]
@tcely that was disappointing the docker run --name pr9520 -it -e DRONE_COMMIT_BRANCH=master -e DRONE_PULL_REQUEST=9520 alpinelinux/alpine-drone-ci:edge-x86_64
/ $ build.sh

Builds successfully on my laptop.  Will try the other options

**Comment by timlegge** [comment]
@tcely really not sure what happened but the checks worked last night and I am not really sure why.  Did something change.

@ncopa when you have a minute would you be able to give it a look and commit if it looks good

**Comment by tcely** [comment]
@timlegge I restarted the failed DroneCI build and it passed. I'm still not sure why the check fails some of the time.

**Comment by ncopa** [comment]
Commit message says "security upgrade" but does not mention any CVE or any other information what the security issue is about?

**Comment by J0WI** [comment]
ImageMagick does not publish CVEs for all issues. I added some in #9624

**Pull request closed without merging**
