### PR TITLE
community/py-werkzeug: upgrade to 0.15.2

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Ikke** [comment]
Please mention the repository in the commit message, as it customary for aports.

**Comment by maxice8** [comment]
On Thu, Apr 25, 2019 at 09:49:58PM -0700, Ikke wrote:
> Please mention the repository in the commit message, as it customary for aports.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7327#issuecomment-486924606

Done, also changed for other PRs

**Comment by tcely** [comment]
We typically use the `upgrade to` phrase.

**Comment by maxice8** [comment]
updated this one, but only will do it for new PRs

**Pull request closed without merging**
