### PR TITLE
testing/polybar: depend on i3wm-dev

### PR DESCRIPTION
**Pull request by tcely**
ERROR: unsatisfiable constraints:
  pulseaudio-dev (missing):
    required by: .makedepends-polybar-0[pulseaudio-dev]

### CODE REVIEW

**Comment by tcely** [comment]
@clandmeter edge-x86 appears to have run out of space

**Comment by Ikke** [comment]
@tcely Sorry, didn't saw your PR, and [disabled s390x][commit] already (to get the builders unstuck). 

Could you update the PR to only include the first commit?

[commit]:426454a5a9

**Comment by Ikke** [comment]
> @clandmeter `edge-x86` appears to have run out of space

I just checked, the x86 builder still has enough disk space free.

**Comment by tcely** [comment]
> > @clandmeter `edge-x86` appears to have run out of space
> 
> I just checked, the x86 builder still has enough disk space free.

Now `edge-x86_64` is out of space.

```
+ build.sh
>>> Host system information (arch: x86_64, release: edge) <<<
- Number of Cores: 48
- Memory: 62.643 Gb
- Free space: 0
```

**Comment by Ikke** [comment]
Oh, this is drone.io that is out of space, not alpine builders.

**Pull request closed without merging**
