### PR TITLE
main/syslog-ng: improvements and fixes (replaces main/eventlog)

### PR DESCRIPTION
**Pull request by adrianguenter**
* libevtlog is a part of syslog-ng since 3.11.1 (provides eventlog{,-dev})
* add Linux capabilities support (run syslog-ng as non-root)
* auto-gen conf version number on init service "update" action
* add support and subpkgs for `geoip2` and `mongodb`, `sql`, & `http` dests
* move `redis`, `amqp`, & `python` modules to subpkgs
* move extra utilities and files to `-extra` subpkg
* create `-dev` subpkg
* build `man` pages and create `-doc` and `-extra-doc` subpkgs

```
$ syslog-ng -V (only base package installed)
syslog-ng 3 (3.13.2)
Config version: 3.13
Installer-Version: 3.13.2
Revision: 
Compile-Date: Feb 11 2018 02:41:36
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Available-Modules: syslogformat,afsocket,affile,afprog,afuser,csvparser,confgen,
system-source,linux-kmsg-format,basicfuncs,cryptofuncs,dbparser,afstomp,pseudofile,
graphite,sdjournal,kvformat,date,cef,disk-buffer,add-contextual-data,
map-value-pairs,stardate,snmptrapd-parser,tags-parser,xml,appmodel
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: off

$ syslog-ng -V (all subpackages installed)
syslog-ng 3 (3.13.2)
Config version: 3.13
Installer-Version: 3.13.2
Revision: 
Compile-Date: Feb 11 2018 02:41:36
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Available-Modules: syslogformat,afsocket,affile,afprog,afuser,csvparser,confgen,
system-source,linux-kmsg-format,basicfuncs,cryptofuncs,dbparser,afstomp,pseudofile,
graphite,sdjournal,kvformat,date,cef,disk-buffer,add-contextual-data,
map-value-pairs,stardate,snmptrapd-parser,tags-parser,xml,appmodel,
json-plugin,afmongodb,mod-python,redis,afsql,afamqp,geoip2-plugin,http
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: off
```

### CODE REVIEW

**Comment by tcely** [comment]
@adrianguenter I upgraded `mongo-c-driver` in https://github.com/alpinelinux/aports/pull/3278

Please add `mongo-c-driver-dev` as a dependency instead of pulling the source from github.

**Comment by adrianguenter** [comment]
@tcely `mongo-c-driver` is still in `testing`, causing the Travis build to fail

**Comment by tcely** [comment]
@adrianguenter The build log from my DroneCI setup is at: https://paste.ee/p/Hxr39

**Comment by andypost** [comment]
Needs rebase & filed https://github.com/alpinelinux/aports/pull/5153

**Pull request closed without merging**
