### PR TITLE
Using hub

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Comment by jirutka** [comment]
Could you please write some meaningful subject for your PR…?

**Comment by kaniini** [comment]
this commit is wrong way to do it, because `/run` is a tmpfs.  meaning if you reboot you will lose that directory.

the init script should create the directory instead

**Comment by jirutka** [comment]
The init script already handles /run directory.

**Comment by pickfire** [comment]
But it's ugly that everytime on boot:
```
tor              | * /run/tor: creating directory
tor              | * /run/tor: correcting owner
tor              | * Starting tor ...                                                                          [ ok ]
```
Sorry about that pull request, it's the first time I use `hub`.

**Pull request closed without merging**
