### PR TITLE
community/cbindgen: enable on ppc64le

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by Cogitri** [comment]
966c30eff15a2885de24ff11ed297fcb1a24a02a

**Comment by Cogitri** [comment]
Somehow algitbot doesn't like these :P

**Comment by J0WI** [comment]
> Somehow algitbot doesn't like these :P

Do you know why? It would be great to have this fixed.

**Comment by Cogitri** [comment]
Dunno, it works fine for other PRs, maybe Algitbot just was in maintaince during the time I merged these or something.

**Comment by J0WI** [comment]
Algitbot never worked for me: https://github.com/alpinelinux/aports/pull/5485#issuecomment-432992030

**Comment by Cogitri** [comment]
Huh, weird

-------- Original Message --------

**Pull request closed without merging**
