### PR TITLE
testing/py-mongo: python3 version added, upgrade to 3.7.2

### PR DESCRIPTION
**Pull request by dimon222**

### CODE REVIEW

**Comment by andypost** [comment]
Makes sense to add `check()` cos package has tests https://github.com/mongodb/mongo-python-driver/blob/master/setup.py#L389

But travis reports
```
>>> WARNING: py-mongo: APKBUILD does not run any tests!
    Alpine policy will soon require that packages have any relevant testsuites run during the build process.
    To fix, either define a check() function, or declare !check in $options to indicate the package does not have a testsuite.
```

**Comment by andypost** [comment]
I guess @fabaff agree on upgrade

**Comment by dimon222** [comment]
I'll add tests and see how it goes.

**Comment by andypost** [comment]
Commited 4cae36ba 6f9ec4d2

**Pull request closed without merging**
