### PR TITLE
community/exo: upgrade to 0.12.6

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by ncopa** [comment]
i want to fix webkit2gtk

**Comment by maxice8** [comment]
On Fri, Jun 28, 2019 at 08:26:47AM -0700, Natanael Copa wrote:
> i want to fix webkit2gtk
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/9022#issuecomment-506775273

@Cogitri said there is the possibility of 32bit support on the next version

**Comment by Cogitri** [comment]
I don't have time to implement this rn, but upstream mentioned that it might work with CLang which apparently takes less memory. Please add clang-dev to makedepends, set CC=clang CXX=clang++ and try if it works on 32-bit arches.

**Comment by ncopa** [comment]
I managed to get webkit2gtk built on armhf with gcc. I'm testing it with armv7 and x86 now.

**Comment by Cogitri** [comment]
Huh, doesn't x86 work already? Anyway, thanks for looking into it!

**Pull request closed without merging**
