### PR TITLE
 main/zfs: upgrade to 0.8.0

### PR DESCRIPTION
**Pull request by TBK**
Should we apply this kernel patch https://lkml.org/lkml/2019/5/22/8 until ZFS has come up with another way of providing SIMD acceleration?

https://github.com/zfsonlinux/zfs/issues/8793#issuecomment-495325343
https://github.com/zfsonlinux/zfs/issues/8259

### CODE REVIEW

**Comment by Cogitri** [comment]
I'd opt for applying the patch, other distros do it to and it significantly accelerates some ZFS operations.

**Comment by Cogitri** [comment]
Testing this on my stuff now

**Comment by Cogitri** [comment]
```
>>> WARNING: zfs-vanilla: APKBUILD does not run any tests!
```

**Comment by TBK** [comment]
> ```
> >>> WARNING: zfs-vanilla: APKBUILD does not run any tests!
> ```
> 
> Also, please make zfs-vanilla conflict with spl-vanilla, otherwise they might clash during the upgrade.

Will do. I am working on adding a subpkg for pyzfs (py binding for libzfs) when I get it working I will rebase and push.

**Comment by Cogitri** [comment]
Alright :+1: 

This works on my pool.

**Comment by TBK** [comment]
@ncopa

**Pull request closed without merging**
