### PR TITLE
main/php5: upgrade to 5.6.29

### PR DESCRIPTION
**Pull request by andypost**
Security release http://php.net/archive/2016.php#id2016-12-08-2

### CODE REVIEW

**Comment by if-kenn** [comment]
I see the packages on the edge repository but not 3.4, is that expected?

https://pkgs.alpinelinux.org/packages?name=php5&branch=&repo=&arch=&maintainer=

I have also run `apk upgrade -U -a` to confirm it is not a mirror thing.

Also 3.3 is back at 5.6.27.

**Comment by andypost** [comment]
Yep, they will be in 3.5 when released

**Comment by jirutka** [comment]
Ah, I forgot to backport it to v3.4. Thanks for reminding.

**Comment by jirutka** [comment]
And also backported to v3.3.

**Pull request closed without merging**
