### PR TITLE
community/php7-pecl-oauth: Fix build against PHP 7.3

### PR DESCRIPTION
**Pull request by bratkartoffel**
Relates to #5863

### CODE REVIEW

**Comment by andypost** [comment]
Still needs to hold

**Comment by bratkartoffel** [comment]
Please reopen @andypost

**Comment by TBK** [comment]
@andypost is this ready to be merged?

**Comment by andypost** [comment]
@bratkartoffel please add `re2c` as makedepends because
> configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.

@TBK it looks like could be merged but as I see in build log the resulting binary does not depend on pcre2 (which is php 7.3 requirements which waiting 3.10 release)

**Comment by bratkartoffel** [comment]
@andypost I've added `re2c`

**Comment by andypost** [comment]
LGTG except the real requirement 
http://git.php.net/?p=pecl/web_services/oauth.git;a=blob;f=INSTALL;h=86eeeeb0d7491f935177a8d09975e37677f6d4c3;hb=HEAD tells about `libpcre3` but I see no mention in build log about it (the same about pcre2) so not clear is there dependency at all

**Comment by andypost** [comment]
In buildlog
```
checking pcre.h usability... yes
checking pcre.h presence... yes
checking for pcre.h... yes 
```
but both pcre-dev and pcre2-dev added by dependencies...

**Comment by TBK** [comment]
@andypost The last commit for INSTALL was 2011-01-15 http://git.php.net/?p=pecl/web_services/oauth.git;a=commit;h=4b3af65373fbd4de1dbc41a4a01442294e73f68c .

The renaming of PCRE to PCRE2 was in 2015 https://lists.exim.org/lurker/message/20150105.162835.0666407a.en.html

The only is a mention of PCRE3 I can find is on Debian related distro sites and it redirect to pcre2.

So I would say all requirement are fulfilled and declare the INSTALL files recommendations for outdated.

**Comment by andypost** [comment]
@TBK looking at code http://git.php.net/?p=pecl/web_services/oauth.git;a=blob;f=php_oauth.h;h=a05ce2d82ae5536afb4c30cf720e3838d947f1cb;hb=HEAD#l45 it looks like pcre-dev just needs to be removed because it links to php internals which do switch in 7.3 to `pcre2`, so any of this dependencies are selected by php-dev package which depends on `pcre-dev` now https://pkgs.alpinelinux.org/package/edge/community/x86_64/php7-dev
But that will change in  #5863

**Comment by andypost** [comment]
That's where configure looking for library headers http://git.php.net/?p=pecl/web_services/oauth.git;a=blob;f=config.m4;h=d0fbe53ce064aae2c6639ca127be7921129afec1;hb=HEAD#l13
but there's only one https://pkgs.alpinelinux.org/contents?file=pcre.h&path=&name=&branch=edge&repo=main&arch=x86_64

**Comment by bratkartoffel** [comment]
outdated

**Comment by TBK** [comment]
Merged with dd49d7145529677dcf4d57ac98a100452828e32b

**Pull request closed without merging**
