### PR TITLE
community/ceph: Use $pkgname instead of ceph for subpackages

### PR DESCRIPTION
**Pull request by iggy**
Fix up some variable use per PR feedback

### CODE REVIEW

**Comment by iggy** [comment]
The CI on this package never finishes because ceph is a huge amount of C++ code that takes forever to compile.

**Comment by Cogitri** [comment]
IMO `use $pkgname instead of ceph for subpackages` would be a better commit msg

**Comment by iggy** [comment]
Yeah, the commit message is wonky because I cherry-picked this from another branch that got merged already. It made more sense in that context. I'll see if I can figure out the git-fu to update the commit message.

**Comment by tcely** [comment]
> I'll see if I can figure out the git-fu to update the commit message.

`git rebase -i d3739c9~` then use `reword` instead of `pick`.

**Comment by iggy** [comment]
Updated the commit message and the title of the PR. Thanks for the review.

**Pull request closed without merging**
