### PR TITLE
dhcp: add /sbin/dhclient-script

### PR DESCRIPTION
**Pull request by little-dude**
fix https://bugs.alpinelinux.org/issues/4855

### CODE REVIEW

**Comment by little-dude** [comment]
@ncopa the `/sbin/dhclient-script` starts with `#! /bin/bash`. It works with `#!/bin/ash`, should I add a path for this, since `ash` is the default on alpine?

**Comment by ncopa** [comment]
i'd prefer to use `#!/bin/sh` but then you should also check for bashisms. you can use `checkbashisms` for that

**Comment by little-dude** [comment]
I added a patch to remove bashisms. Thanks for `checkbashisms`, it quite handy :)

**Comment by ncopa** [comment]
very nice. I modified the commit message a bit and pushed it.

Thanks!

**Comment by little-dude** [comment]
Thank you! I'm closing this then.

**Pull request closed without merging**
