### PR TITLE
testing/ripgrep: new aport

### PR DESCRIPTION
**Pull request by misery**
Unit test "regression_25" failed. I added an issue: https://github.com/BurntSushi/ripgrep/issues/448

### CODE REVIEW

**Comment by misery** [comment]
regression_25 fails because of ".gitignore" of aports tree. Any idea how to solve that? :-)

**Comment by misery** [comment]
rust is official in Alpine now.... still "on hold"? :-)

**Comment by misery** [comment]
Ping? Anything new here?

**Comment by clandmeter** [comment]
@jirutka can you elaborate this re-open. i guess it has to do with packaging of rust apps?

**Comment by misery** [comment]
ripgrep works since 2 years now. Is there a progress for packaging rust packages?

**Pull request closed without merging**
