### PR TITLE
community/php7: upgrade to 7.1.4

### PR DESCRIPTION
**Pull request by vakartel**
remove php7 from testing

### CODE REVIEW

**Comment by andypost** [comment]
Is that not late for 3.6?

**Comment by jirutka** [comment]
No, it's not, just opposite. We have to fix php in Alpine before v3.6, because it's messed now.

**Comment by andypost** [comment]
What's left here to accept it?
Soon php 7.2 will be in testing

**Comment by jirutka** [comment]
> What's left here to accept it?

This PR consists of single mega-commit with bunch of unrelated changes, very hard to review…

**Comment by jirutka** [comment]
FYI I've started working on this.

**Comment by jirutka** [comment]
Replaced by #1339.

**Pull request closed without merging**
