### PR TITLE
community/gitea: upgrade to 1.9.5

### PR DESCRIPTION
**Pull request by Bwko**

### CODE REVIEW

**Comment by 6543** [comment]
@clandmeter new version of gitea was released - pleace aprove

**Comment by 6543** [comment]
@Cogitri you seam to be more active tahn clandmeter .. so I'll mention you in the hope to get this done :)

**Comment by Cogitri** [comment]
Sadly I can't merge it right now though due to my laptop being in repair :/

**Comment by 6543** [comment]
@Cogitri thats why i have more than one - and a few live Discs ;) - hope you dont loose data

**Comment by Cogitri** [comment]
Luckily I have it all backed up on my server (Which I'm currently moving to alpinelinux too)

**Comment by 6543** [comment]
@maxice8 @Bwko Thanks! this time it was very fast :+1:

**Pull request closed without merging**
