### PR TITLE
testing/ejabberd: modernize, fix license, split $pkgname-openrc.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
@jprjr

**Comment by TBK** [comment]
I am guessing that libressl.patch can be removed.

**Comment by maxice8** [comment]
removed

**Comment by fcolista** [comment]
```
>>> ejabberd: Building testing/ejabberd 17.09-r4 (using abuild 3.4.0_rc4-r0) started Mon, 27 May 2019 08:44:52 +0000
>>> ejabberd: Checking sanity of /home/fcolista/aports/testing/ejabberd/APKBUILD...
>>> ERROR: ejabberd: libressl.patch exists in sha512sums but is missing in $source
```

**Pull request closed without merging**
