### PR TITLE
main/libuv: remove disable-setuid-test.patch

### PR DESCRIPTION
**Pull request by OTLabs**
- Disable test 137 ipc_closed_handle on Drone for x86*

### CODE REVIEW

**Comment by OTLabs** [comment]
All builds fail on same test, local build passes this test fine, also referred in https://github.com/alpinelinux/aports/pull/7895#issuecomment-494466331 and reported upstream:

```
not ok 137 - ipc_closed_handle
--
952 | # timeout
953 | # Output from process `ipc_closed_handle`:
954 | # Assertion failed in test/test-ipc.c on line 601: status == 0
```

```
FAIL: test/run-tests
--
1180 | ======================================================
1181 | 1 of 1 test failed
1182 | Please report to https://github.com/libuv/libuv/issues
1183 | ======================================================
```

**Comment by TBK** [comment]
We could disable the "broken test" on x86* with:
```
check() {
	cd "$builddir"
	# see https://github.com/libuv/libuv/issues/2307
	case $CARCH in
		x86*) sed -i "s/TEST_DECLARE   (ipc_closed_handle)//g" test/test-list.h;;
	esac

	make check
}
```

**Comment by OTLabs** [comment]
Done. Please, check Drone detection scripting. Thanks!

**Comment by TBK** [comment]
> Done. Please, check Drone detection scripting. Thanks!

LGTM. It could be drone as one sed regex but since it is a "dirty fix" I see no reason to spend more time on it.

**Comment by OTLabs** [comment]
Like now? It is good to me to start learning shell scripting. Thanks for references!

**Comment by TBK** [comment]
> Like now? It is good to me to start learning shell scripting. Thanks for references!
yup ;D

**Pull request closed without merging**
