### PR TITLE
community/fuse-exfat: upgrade to 1.2.8

### PR DESCRIPTION
**Pull request by TBK**
These two packages are duplicates:
https://pkgs.alpinelinux.org/contents?branch=edge&name=fuse-exfat-utils&arch=aarch64&repo=community
https://pkgs.alpinelinux.org/contents?branch=edge&name=exfat-utils&arch=aarch64&repo=community

### CODE REVIEW

**Comment by TBK** [comment]
@awilfox Please review this.

**Comment by awilfox** [comment]
They are the same codebase, but they are not duplicates; `mkfs.exfat` _et al_ do not require FUSE and as such they can be run on a system without FUSE.

Additionally, if someone were brave enough to discount software patents (or live in an area where they do not exist), [there's a kernel module](https://github.com/bkuhn/exfat) for exFAT which would mean FUSE would not be required to mount said, either.

All in all, I'd say the utils should probably be split off of the FUSE package, so that people who only need the `mkfs` or `fsck` do not need to pull in FUSE to use them.  But as my usage of exFAT has gone to virtually nil, I no longer really care either way.

**Comment by TBK** [comment]
@awilfox Thanks for the explanation. I have updated the PR to leave it be.

**Comment by TBK** [comment]
@awilfox I stumpled upon this https://github.com/cryptomilk/kernel-sdfat thought it might be of interest.

**Pull request closed without merging**
