### PR TITLE
testing/cdist: upgrade to 5.1.1

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by maxice8** [comment]
@oxr463

**Comment by oxr463** [comment]
I guess this can be dropped, https://patchwork.alpinelinux.org/patch/4880

**Comment by maxice8** [comment]
Yes, older version that uses git.

**Comment by maxice8** [comment]
Can be closed, merged.

**Comment by J0WI** [comment]
1085e17f7b3d7a1f9f14fead2ad0e5c4cb866174

**Pull request closed without merging**
