### PR TITLE
main/pango: upgrade to 1.43.0

### PR DESCRIPTION
**Pull request by maxice8**
@ncopa

### CODE REVIEW

**Comment by Cogitri** [comment]
Isn't 1.43 unstable?

**Comment by maxice8** [comment]
They don't say anything about stable and unstable on their website or gitlab.

**Comment by Cogitri** [comment]
Pretty sure that if they don't say anything about it they implicitly follow the usual GNOME mantra of uneven point releases being unstable

**Comment by Cogitri** [comment]
See e.g. https://github.com/msys2/MINGW-packages/issues/4830

**Comment by maxice8** [comment]
On Mon, May 06, 2019 at 06:35:00AM +0000, Rasmus Thomsen wrote:
> Pretty sure that if they don't say anything about it they implicitly follow the usual GNOME mantra of uneven point releases being unstable
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7585#issuecomment-489513784

Found it.

```
Overview of changes between 1.25.6 and 1.26.0
=============================================
- New stable release series
- Bugs fixed:
	Bug 595539 - Regressions in rendering certain Thai sequences
```

**Pull request closed without merging**
