### PR TITLE
community/py-hypothesis: upgrade to 4.24.2

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
@ddevault

**Comment by ddevault** [comment]
Do you want to adopt this package?

**Comment by maxice8** [comment]
I wouldn't mind

**Comment by maxice8** [comment]
@ddevault updated to include maintainership change.

**Comment by maxice8** [comment]
Thanks for the quick response and taking care of py-hypothesis.

**Pull request closed without merging**
