### PR TITLE
community/roundcubemail: fetch jsdeps

### PR DESCRIPTION
**Pull request by HRio**
From 1.3.x and forward jsdeps need to be fetched

https://github.com/roundcube/roundcubemail/wiki/Build-from-source#3-install-javascript-dependencies

### CODE REVIEW

**Comment by HRio** [comment]
@jirutka can you have a look on this change? thanks.

**Comment by rnalrd** [comment]
@HRio we allow only abuild to fetch sources. The proper fix is to package any additional dependency and add it to roundcubemail APKBUILD "depends".

Since roundcubemail is in "community" repo these new dependencies need to be committed in the same repo and not into "testing".

Thanks

**Comment by HRio** [comment]
fixed in 91498e87a2d6a142d639fabf5d7f9f583483a041 by @jirutka big thanks!

@jirutka can you cherry-pick your big roundcube improvements (or at least this one) to v3.8 so we can have a working roundcube package in an alpine release again?

**Comment by jirutka** [comment]
@HRio, I've backported 91498e87a2d6a142d639fabf5d7f9f583483a041 (fix JS deps) to 3.8-stable and 3.7-stable. I don't think that the rest of the changes are suitable for backporting into stable branches.

**Comment by HRio** [comment]
@jirutka very good, thanks!

**Pull request closed without merging**
