### PR TITLE
Create no-response.yml

### PR DESCRIPTION
**Pull request by tcely**
https://probot.github.io/apps/no-response/

This is a feature @ncopa wanted when discussing improvements on the mailing list.
https://lists.alpinelinux.org/alpine-devel/6219.html

If using this label, we need one of the owners to add this bot and to merge this PR into the git repository.

### CODE REVIEW

**Comment by Ikke** [comment]
@tcely If I read that request from ncopa, it appears what he wants is the opposite. Not closing when someone did not respond, but add a label when they do respond, so that we know that we need to do something now.

**Comment by tcely** [comment]
This work flow is add a label when a response is required, and have the bot remove that label when the author responds. Closing is optional.

It makes sense to close PRs that go unresponsive in my opinion, but if it's decided we should keep them open that is fine too.

**Comment by Ikke** [comment]
The problem is that a PRs can disappear in the noise when we requested changes and the user then responds. By removing the label in that case, you cannot find these PRs among all other PRs.

If we would add a label in that case, you can now filter the PRs where the user has responded. That's the idea at least.

**Comment by tcely** [comment]
So perhaps we should fork this bot and change it to add a label when the response is seen.

**Comment by tcely** [comment]
In light of https://github.com/probot/no-response/issues/14 we will be better served by our own implementation anyway.

**Pull request closed without merging**
