### PR TITLE
community/networkmanager: upgrade to 1.20.0

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by Cogitri** [comment]
@PureTryOut mind verifying that networkmanager-openvpn is up to speed still?

**Comment by andypost** [comment]
it needs rebase

**Comment by Cogitri** [comment]
Will do

**Comment by maxice8** [comment]
This needs rebasing

**Comment by Cogitri** [comment]
Done. Could someone please test if upgrading to the new NM works? @PureTryOut mentioned that it didn't for him for some reason.

**Comment by Cogitri** [comment]
Well, this has worked for some time for me now, sooooo

**Pull request closed without merging**
