### PR TITLE
testing/go-ipfs: new aport

### PR DESCRIPTION
**Pull request by OTLabs**
https://ipfs.io/
Inter Platnetary File System (IPFS), a peer-to-peer hypermedia distribution protocol

Requieres  #5773  and  #5772  packages.

### CODE REVIEW

**Comment by clandmeter** [comment]
If a PR depends on other PR's you need to merge the commits into a single one.
This will make sure the dependencies will be met.

**Comment by OTLabs** [comment]
Build on arch architectures is failing as gcc unable to find ld.

**Comment by clandmeter** [comment]
I'm sorry but i think I explained it incorrectly, i mean put the commits into a single PR. Sorry about that. 
The build scripts will automatically figure out the build order.

**Comment by clandmeter** [comment]
nice thx, If you cannot fix builds on other archs please disable them.

**Comment by OTLabs** [comment]
Could it be a misconfiguration of drone for arch architectures?

```
# github.com/ipfs/go-ipfs/cmd/ipfs
754 | /usr/lib/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
755 | collect2: fatal error: cannot find 'ld'
756 | compilation terminated.
```

**Comment by Ikke** [comment]
Also make sure all dependencies that go pulls in are fixed. If you just do `go get` it will just get the latest dependencies, which can cause the build to be different each time.

**Comment by OTLabs** [comment]
I have restricted the architectures to x86_64 and x86 only.

**Comment by OTLabs** [comment]
The multihashes presented in https://github.com/ipfs/go-ipfs/blob/master/package.json are the same you see in build log, so the go dependencies are fixed.

**Comment by Ikke** [comment]
gx in the last version looks good, thanks! Now you can apply the same to gx-go.

**Comment by OTLabs** [comment]
Applied glide to gx-go!

**Pull request closed without merging**
