### PR TITLE
community/mpv: update to 0.23

### PR DESCRIPTION
**Pull request by skrzyp**
This update fixes the mpv segmentation faults during exiting or changing volume

### CODE REVIEW

**Comment by skrzyp** [comment]
**NOTE**: #696 must be merged first.

**Comment by skrzyp** [comment]
Sorry for messing up commits' dates - I had to reorder them for Travis to proces `mpv` properly.

Also updates `ffmpeg` in this PR instead of #696, updates `libass` to [fix ABI breakage](https://github.com/libass/libass/releases/)

**Comment by jirutka** [comment]
I’ve merged main/libass update separately in 040177ab5b4ae32aed8638d51c808f5520ec741c.

**Comment by jirutka** [comment]
The updated version of ffmpeg does not install `/usr/bin/ffplay`. Why that happened?

**Comment by skrzyp** [comment]
No idea, maybe they changed default configuration, [see this line from logs](https://travis-ci.org/alpinelinux/aports/builds/189836127#L1030).

**Comment by jirutka** [comment]
So could you somehow enable ffplay?

**Comment by skrzyp** [comment]
`ffmpeg`'s `ffplay` needs SDL2 now, instead of SDL. Updated dependencies, should build completely now.

**Comment by jirutka** [comment]
I’ve merged main/ffmpeg separately in e7b0fa48c929e3fb9d19d9077668140602359797.

**Pull request closed without merging**
