### PR TITLE
[3.8] main/dovecot: security upgrade to 2.3.6

### PR DESCRIPTION
**Pull request by J0WI**
https://dovecot.org/pipermail/dovecot-news/2019-April/000406.html

### CODE REVIEW

**Comment by J0WI** [comment]
:ping_pong: @ncopa
See also #7146 #7147

**Comment by J0WI** [comment]
:ping_pong: since this remains unfixed for a while

**Comment by J0WI** [comment]
Or do I have to :ping_pong: @rnalrd since they already merged #7147?

**Comment by rnalrd** [comment]
Sorry, left it out because I had local build issues. Merged just now.

**Pull request closed without merging**
