### PR TITLE
testing/knot-resolver: upgrade to 3.2.1

### PR DESCRIPTION
**Pull request by tcely**
See https://github.com/alpinelinux/aports/pull/5950 for ideas about better future solutions for DNS root hints file.

### CODE REVIEW

**Comment by J0WI** [comment]
Can this be removed in favor of `community/knot-resolver`?

**Comment by tcely** [comment]
@J0WI I see no reason why I would remove this. The referenced PR is a subset of these changes.

Also, there isn't a `community/knot-resolver` yet. If you are looking to move this apk from testing to community that is a separate discussion.

**Comment by J0WI** [comment]
Oh you're right, the commit message in #5412 was misleading.

**Comment by tcely** [comment]
@andypost The labels should be adjusted since `3.2.0` was committed to `master` recently.

**Comment by tcely** [comment]
@rnalrd please commit this

**Pull request closed without merging**
