### PR TITLE
main/ceph: Move ceph from community

### PR DESCRIPTION
**Pull request by iggy**
Move ceph from community to main

This move should allow us to enable ceph support in Qemu

### CODE REVIEW

**Comment by iggy** [comment]
Build timed out because c++ (and massive project)

**Comment by iggy** [comment]
@fcolista @TBK @sanmai-NL  moving `oath-toolkit` `leveldb` `xmlstarlet` `xmlsec` to main so I can move `ceph` to main so we can turn on `ceph` support in `qemu`

**Comment by tcely** [comment]
Why does qemu require packages in main?

**Comment by ncopa** [comment]
> Why does qemu require packages in main?

Because we support main for 2 years but community for 6 months (latest release). It wouldn't make sense to support a package if we also don't support its dependencies.

**Comment by tcely** [comment]
See also #11839 and #11661

**Pull request closed without merging**
