### PR TITLE
testing/dnsdist: new aport

### PR DESCRIPTION
**Pull request by vincentmele**
testing/dnsdist: new aport

https://dnsdist.org
dnsdist is a highly DNS-, DoS-, and abuse-aware loadbalancer.

### CODE REVIEW

**Comment by jirutka** [comment]
Actually if it doesn't really need root privileges, then it definitely should not be started under root as default, but its separate user.

**Comment by tcely** [comment]
`dnsdist` has `--uid` and `--gid` flags for dropping privileges.
 
Examples are at: https://github.com/tcely/dockerhub-powerdns

**Comment by tcely** [comment]
@vincentmele Please merge the suggested changes. https://github.com/vincentmele/aports/pull/1

**Comment by tcely** [comment]
This can be closed as it is now at least a version behind.

**Comment by ncopa** [comment]
We follow this up in #3321 
Thanks!

**Pull request closed without merging**
