### PR TITLE
main/gegl: upgrade to 0.3.18 and modernize

### PR DESCRIPTION
**Pull request by tmpfile**

### CODE REVIEW

**Comment by rnalrd** [comment]
Can't push it, since GIMP doesn't build with 0.3.18 out-of-the box.

<code>

checking for GEGL... no

configure: error: Package requirements (gegl-0.2 >= 0.2.0) were not met:

Package 'gegl-0.2', required by 'virtual:world', not found

</code>

Can you please provide a PR for GIMP as well?

Thanks!

**Comment by tmpfile** [comment]
https://github.com/alpinelinux/aports/pull/1735

**Comment by tmpfile** [comment]
GIMP 2.9.4 isn't stable?
On the main page they list 2.8.22 as latest.
https://www.gimp.org/

**Comment by rnalrd** [comment]
Yeah, even minor versions are unstable

**Pull request closed without merging**
