### PR TITLE
community/domoticz: upgrade to 4.9700

### PR DESCRIPTION
**Pull request by xpecex**
ref https://raw.githubusercontent.com/domoticz/domoticz/development/History.txt

### CODE REVIEW

**Comment by andypost** [comment]
Needs additional dependencies
```
CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:2048 (message):
  Unable to find the requested Boost libraries.
  Boost version: 1.67.0
  Boost include path: /usr/include
  Could not find the following static Boost libraries:
          boost_thread
          boost_system
```

**Comment by xpecex** [comment]
It seems to be a cmake bug, even with the installed dependencies it does not find them.

I will continue working to find a solution.

**Comment by andypost** [comment]
It needs @clandmeter approval

**Comment by andypost** [comment]
@xpecex it needs rebase because now it depends on openssl

**Comment by andypost** [comment]
@xpecex it needs rebase

**Comment by andypost** [comment]
Looks it was commited by @ncopa in https://github.com/alpinelinux/aports/commit/18e8655f9257e5827e138a466a7d11f28298d5e6

**Comment by xpecex** [comment]
yep okay.

**Pull request closed without merging**
