### PR TITLE
testing/py-pandas new aport

### PR DESCRIPTION
**Pull request by sgerrand**
💁 Packages the Python Data Analysis Library.

http://pandas.pydata.org/

### CODE REVIEW

**Comment by ncopa** [comment]
I had to revert this because it does not create the expected subpackages for some reason and as a result it  causes the builders try to rebuild it every git push. Sorry.

**Comment by ncopa** [comment]
It is also a duplicate #6251

**Comment by sgerrand** [comment]
😞 Thanks for letting me know about the issue. I'll fix the subpackages build today.

**Comment by sgerrand** [comment]
As background, I've been maintaining [an Alpine package for pandas](https://github.com/sgerrand/alpine-pkg-py-pandas) for ~ 2 years. This is the first of hopefully further packages that I'd like to bring into aports.

**Comment by sgerrand** [comment]
Found the issue: the architecture should have been set as "all" rather than "noarch".

**Comment by cgiraldo** [comment]
Hi! I submitted the #6251 pandas aport. 
I didn't find any pandas aports at the time I pull request #6251.

If this PR is finally merged, please, remove "python" from the depends line in order to not depend on python2 for the py3-pandas.

APK line should be:

`depends="py-dateutil py-numpy py-tz" `

**Comment by Ikke** [comment]
The other PR has been merged, so this can be closed.

**Pull request closed without merging**
