### PR TITLE
main/libvpx: upgrade to 1.8.0

### PR DESCRIPTION
**Pull request by timbru31**
This superseeds #4003 and #5269

### CODE REVIEW

**Comment by timbru31** [comment]
Travis timed out, because of `The job exceeded the maximum time limit for jobs, and has been terminated.` - the time is not enough for re-building both Firefox and Firefox ESR.

**Comment by ncopa** [comment]
gst-plugins-good fails to build and may need a patch:

````
gstvpxdec.c: In function 'gst_vpx_dec_post_processing_flags_get_type':
gstvpxdec.c:65:15: error: 'VP8_DEBUG_TXT_FRAME_INFO' undeclared (first use in this function); did you mean 'VP9D_GET_FRAME_SIZE'?
     {C_FLAGS (VP8_DEBUG_TXT_FRAME_INFO),                                                                                                                 
               ^~~~~~~~~~~~~~~~~~~~~~~~                      
gstvpxdec.c:56:29: note: in definition of macro 'C_FLAGS'                                                                                                 
 #define C_FLAGS(v) ((guint) v)                                     
                             ^
gstvpxdec.c:65:15: note: each undeclared identifier is reported only once for each function it appears in
     {C_FLAGS (VP8_DEBUG_TXT_FRAME_INFO),                         
               ^~~~~~~~~~~~~~~~~~~~~~~~                      
gstvpxdec.c:56:29: note: in definition of macro 'C_FLAGS'     
 #define C_FLAGS(v) ((guint) v)                               
                             ^                           
  CXX      libgsttaglib_la-gstapev2mux.lo                               
  CC       libgstvpx_la-gstvp8dec.lo                    
  CC       libgstwavpack_la-gstwavpackcommon.lo         
  CC       libgstvpx_la-gstvp8enc.lo      
  CC       libgstvpx_la-gstvp8utils.lo    
  CC       libgstvpx_la-gstvp9dec.lo                              
  CC       libgstwavpack_la-gstwavpackdec.lo                                                                                                              
  CCLD     smpte_test             
  CC       libgstwavpack_la-gstwavpackenc.lo                                                                                                              
  CC       libgstvpx_la-gstvp9enc.lo                                                                                                                      
  CC       libgstjack_la-gstjackaudioclient.lo                                                                                                            
gstvpxdec.c:68:15: error: 'VP8_DEBUG_TXT_MBLK_MODES' undeclared (first use in this function)
     {C_FLAGS (VP8_DEBUG_TXT_MBLK_MODES),   
               ^~~~~~~~~~~~~~~~~~~~~~~~
gstvpxdec.c:56:29: note: in definition of macro 'C_FLAGS'
 #define C_FLAGS(v) ((guint) v)                                                                                                                           
                             ^                                                                                                                            
  CCLD     libgstcairo.la                                                                                                                                 
  CC       libgstvpx_la-plugin.lo
gstvpxdec.c:71:15: error: 'VP8_DEBUG_TXT_DC_DIFF' undeclared (first use in this function)                                                                 
     {C_FLAGS (VP8_DEBUG_TXT_DC_DIFF),                                                                                                                    
               ^~~~~~~~~~~~~~~~~~~~~                                      
gstvpxdec.c:56:29: note: in definition of macro 'C_FLAGS'      
 #define C_FLAGS(v) ((guint) v)                               
                             ^                                            
gstvpxdec.c:74:15: error: 'VP8_DEBUG_TXT_RATE_INFO' undeclared (first use in this function)
     {C_FLAGS (VP8_DEBUG_TXT_RATE_INFO),                        
               ^~~~~~~~~~~~~~~~~~~~~~~                                    
gstvpxdec.c:56:29: note: in definition of macro 'C_FLAGS'                
 #define C_FLAGS(v) ((guint) v)                                         
                             ^     
````

**Comment by ncopa** [comment]
it needs this: https://github.com/GStreamer/gst-plugins-good/commit/b6e6f1ae73375ef66a5748069843aaed1a83e6a6

and you need run `autoreconf -vif` due to the configure.ac change.

**Comment by ncopa** [comment]
never mind. i have it fixed already.

**Comment by ncopa** [comment]
In addition to the gst-plugins-good build failure:
- libvpx build broke on ppc64le. it needs linux-headers in makedepends
- ffmpeg needed a rebuild too, causing build failures of the other packages who also depends on ffmpeg (vlc, qt5-qtwebengine)
- vlc build failed due to it not yet supports the libvpx 1.8 API.

I think all the above is fixed now

**Pull request closed without merging**
