### PR TITLE
testing/liberasurecode: new aport

### PR DESCRIPTION
**Pull request by ehudkaldor**

### CODE REVIEW

**Comment by ehudkaldor** [comment]
> For [c014944](https://github.com/alpinelinux/aports/commit/c0149441cac8a6fe4dd0a3bee4a81489a3cbdaf8)
> 
> ```
> prepare() is missing default_preapre before ./autogen.sh
> ```

done

**Comment by TBK** [comment]
@ehudkaldor do you need the static libs? if so please add a subpkg: $pkgname-static, if not then add `--disable-static` to configure.
```
>>> WARNING: liberasurecode-dev*: Found static archive on usr/lib/liberasurecode.a but name doesn't end with -static
>>> WARNING: liberasurecode-dev*: Found static archive on usr/lib/libnullcode.a but name doesn't end with -static
>>> WARNING: liberasurecode-dev*: Found static archive on usr/lib/libXorcode.a but name doesn't end with -static
>>> WARNING: liberasurecode-dev*: Found static archive on usr/lib/liberasurecode_rs_vand.a but name doesn't end with -static
```

make test needs to be tab indented instead of space.

**Comment by ehudkaldor** [comment]
done (i think).

add `--disable-static`.

**Comment by ehudkaldor** [comment]
...and rebased to master

**Comment by ehudkaldor** [comment]
why was it closed?

**Comment by ehudkaldor** [comment]
i see. it was accepted.
still learning on the fly

**Comment by TBK** [comment]
Not sure why algitbot did not post a message...

Merged in https://github.com/alpinelinux/aports/commit/bca0f57014d1b128434215f47ff2097404ead978 by @TBK. Thanks for your contribution!

(This pull request has been closed automatically by GitHub PR Closer. If you think that it’s not resolved yet, please add a comment.)

**Pull request closed without merging**
