### PR TITLE
testing/kate & testing/kwrite: new aports

### PR DESCRIPTION
**Pull request by PureTryOut**

### CODE REVIEW

**Comment by PureTryOut** [comment]
For some reason it fails gzipping `kwrite-doc` on aarch64... Not sure what to do about this.

**Comment by Cogitri** [comment]
Seeing how these are both built from the same source maybe it'd make more sense to make kwrite a subpackage of kate?

**Comment by PureTryOut** [comment]
I thought of doing that, but I'm not sure how to split out `kwrite-doc` in that case. I somehow need to tell `default_doc` for `kwrite-doc` to use the doc files of the `kwrite` subpackage rather than the main package.

**Comment by Cogitri** [comment]
I guess you'd need to make a custom doc function then.

**Comment by PureTryOut** [comment]
Obviously, that I understand. But I'm not sure what to do _inside_ that function, as I don't know what `default_doc` would do in there.

**Pull request closed without merging**
