### PR TITLE
community/exim: fix hardcoded bounce_message charset

### PR DESCRIPTION
**Pull request by vakartel**
I changed hardcoded charset from 'us-ascii' to 'utf-8'
to be able to create multilingual bounce messages

### CODE REVIEW

**Comment by ncopa** [comment]
is this sent upstream too?

**Comment by vakartel** [comment]
I'll sent it to upstream later. after I test it

**Comment by ncopa** [comment]
can you please squash them to a single commit?

`git rebase -i`
on the second commit set `f` for `fixup`. (you could also have used `git commit --amend`).

Then `git push -f` to replace the two commits in this PR with your fixed, single, commit.

**Comment by ncopa** [comment]
i fixed the commit message for you. thanks

**Pull request closed without merging**
