### PR TITLE
main/nettle: upgrade to 3.5.1

### PR DESCRIPTION
**Pull request by maxice8**
- [x] aria2
- [x] claws-mail
- [ ] dnsmasq
- [x] epiphany
- [x] filezilla
- [x] freeradius-client
- [x] gnutls
- [x] libfilezilla
- [x] pike
- [x] qemu
- [x] rdfind
- [x] rtmpdump
- [ ] sequoia-sqv
- [x] stoken
- [x] xen

### CODE REVIEW

**Comment by ncopa** [comment]
I think this breaks ABI.

````
--- filelist-nettle-old
+++ filelist-nettle
@@ -1,7 +1,7 @@
 .PKGINFO
 usr/
 usr/lib/
-usr/lib/libhogweed.so.4
-usr/lib/libhogweed.so.4.5
-usr/lib/libnettle.so.6
-usr/lib/libnettle.so.6.5
+usr/lib/libhogweed.so.5
+usr/lib/libhogweed.so.5.0
+usr/lib/libnettle.so.7
+usr/lib/libnettle.so.7.0
````

everything linked to `libhogweed.so.4` and `libnettle.so.6` needs to be rebuilt

**Comment by ncopa** [comment]
````
$ apk search -r -q --origin --exact so:libhogweed.so.4 so:libnettle.so.6 | sort -u
aria2
claws-mail
dnsmasq
epiphany
filezilla
freeradius-client
gnutls
libfilezilla
nettle
pike
qemu
rdfind
rtmpdump
sequoia-sqv
stoken
xen
````

**Comment by maxice8** [comment]
On Fri, Jun 28, 2019 at 08:36:35AM -0700, Natanael Copa wrote:
> I think this breaks ABI.
> 
> ````
> --- filelist-nettle-old
> +++ filelist-nettle
> @@ -1,7 +1,7 @@
>  .PKGINFO
>  usr/
>  usr/lib/
> -usr/lib/libhogweed.so.4
> -usr/lib/libhogweed.so.4.5
> -usr/lib/libnettle.so.6
> -usr/lib/libnettle.so.6.5
> +usr/lib/libhogweed.so.5
> +usr/lib/libhogweed.so.5.0
> +usr/lib/libnettle.so.7
> +usr/lib/libnettle.so.7.0
> ````
> 
> everything linked to `libhogweed.so.4` and `libnettle.so.6` needs to be rebuilt
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/9175#issuecomment-506778620

Oh, yes this definitively breaks ABI both libraries are bumped

nettle-3.4.1-r1 provides:
so:libhogweed.so.4=4.5
so:libnettle.so.6=6.5

nettle-3.5.1-r0 provides:
so:libhogweed.so.5=5.0
so:libnettle.so.7=7.0

**Comment by maxice8** [comment]
sequoia-sqv and dnsmasq need changes to deal with API breakage

**Comment by J0WI** [comment]
See also #9131

**Comment by maxice8** [comment]
That PR has no apparent work on tracking rebuilds of dependent packages,
I'd consider superseded

**Comment by J0WI** [comment]
I didn't add the rebuilds in #9131 because they will likely produce merge conflicts until they get merged (just like in #7806).
I'd like too keep the changes in #9131, especially the flag to compile with AES/SHA hardware acceleration support.

**Comment by maxice8** [comment]
If you say so

**Pull request closed without merging**
