### PR TITLE
main/mesa: upgrade to 18.0.1

### PR DESCRIPTION
**Pull request by vakartel**
- fixed license
- removed mesa-libwayland-egl subpackage. It's handled by wayland now

### CODE REVIEW

**Comment by tanertas** [comment]
Can we combine this with #4107 ?

**Comment by vakartel** [comment]
@tanertas of course if you see something useful in this PR just add it to yours

**Comment by tanertas** [comment]
I combined this PR with 4107. Except libunwind-dev because it needs extra work to enable on all platforms. Thanks.

**Comment by ncopa** [comment]
lets continue this in #4107. Thanks!

**Pull request closed without merging**
