### PR TITLE
community/imagemagick6: security upgrade to 6.9.10-53

### PR DESCRIPTION
**Pull request by J0WI**
Source url changed, because older releases are no longer available on imagemagick.org

### CODE REVIEW

**Comment by J0WI** [comment]
@tcely checks are passing on Travis and locally, but failing on x86_64 Drone CI.

**Comment by tcely** [comment]
@J0WI good enough for now.

It'd be great to know why those tests fail, but I won't hold up this upgrade because DroneCI is failing.

**Comment by J0WI** [comment]
There are pending issues at https://github.com/ImageMagick/ImageMagick/issues

**Comment by J0WI** [comment]
@tcely are there any blockers left to get this merged?

**Comment by tcely** [comment]
@J0WI not in my opinion. You might rebase and document why the check failures are being ignored.

**Comment by J0WI** [comment]
ec69d00c673f9c08d0e0c91af9c84609d794aa12

**Pull request closed without merging**
