### PR TITLE
testing/mawk: new aport

### PR DESCRIPTION
**Pull request by mterron**
mawk is an interpreter for the AWK Programming Language.

Mawk was written by Mike Brennan.

https://invisible-island.net/mawk

### CODE REVIEW

**Comment by mterron** [comment]
Changes requested done.

**Comment by tanertas** [comment]
Probably you'll also need to merge your commits as a single commit.

**Comment by mterron** [comment]
Why??

**Comment by tanertas** [comment]
> Why??

PR's generally merged as a single commit. It doesn't make any sense to reflect all local changes to upstream.

**Comment by mterron** [comment]
Do you have a stylistic guideline anywhere? It has now taking me longer to do this  PR than to build the package. Hardly a way to encourage contributions IMHO.

**Comment by mterron** [comment]
Thanks for the feedback Tanertas!

I’ll leave this PR here in case someone wants to merge it.

For a small community like Alpine, streamlining contributions should be the way to go IMO. AftI tried to contribute twice, I don’t think there’ll be a 3rd time, I will just keep my apks for my own use which is a shame since somebody else could use them.

Cheers

**Comment by tanertas** [comment]
Please don't give up early. I started to contribute with email due to absence of some packages that I use. Then I switched to git. I was using git for just cloning source but now I'm capable of use git in the way that I wasn't before. Now I have 20+ packages  and continuing to contribute. Alpine is one of rare distros that trying to do things simple and right. Small but well growing community.

For instance, if some developer didn't want me to merge all commits as a single one, I wouldn't force myself to do learn how it's done. Just like what doesn't kill you, makes you stronger :)

**Comment by ncopa** [comment]
>> Probably you'll also need to merge your commits as a single commit.

> Why??

Because we want have useful git log. We have 4700+ aports in same git repository and we don't want make the git log more noisy than necessary, because we need the log to troubleshoot existing systems. If something breaks, we need to know what changed, when, by who and why.

Have a look at the example here under. There are 3 commits that doesn't really say anything about what actually happened. If someone was to debug something in the future he would need to take a closer look at those 3 commits to verify that they has nothing to do with the thing he wants to fix - so it slows him down.

````
78e091bdea4c48efb432c5c654fa62075aeb9834 main/linux-vanilla: upgrade to 4.14.67
cf8749dbb8dca83bae340819599feb574a59546f community/php7-gmagick: fix missing ini file and use https
68cc9876d16556f4f8a516a1bb0b9e38c2dc78a2 testing/php7-diseval: new aport
32d8020caa0f544b371879496a2582d31c77ae65 testing/php7-varnish: fix missing ini file
2ee00679c642f6af365e05427dc386c2fa3a0606 testing/php7-protobuf: fix missing ini file
8e6cfd87d7d6473c625358bbaddabb03c951aa8d Fix License and remove empty sections
ce4b48cb11457dcff9c8114f0e5789c56a66e225 community/sparse: upgrade to 0.5.2
ae14d1064c9af1a08f1662dbcdb20b6566c7a491 community/tclap: upgrade to 1.2.2
...
7ccb67807757387933bc57a830b63c0fd80a7d2d testing/hiawatha: fix checksum
db39d570904109ccb8eed0d5ddeb11db2f7e9cba testing/hiawatha: upgrade to 10.8.2 and add -openrc package
8c7573642d0f2a1c2436a7ff6e41e39824f63892 Fix libressl compilation issue.
9b64663228e4c706bea52e43db1151e7a32a88d9 community/perl-par-packer: upgrade to 1.047
3752e537ea15d8b3d4a759c97d0faddf8d3263b9 main/linux-rpi: upgrade to 4.14.66
2a689232c7617d46738596f7ecc45f440c7b44c3 community/podofo: upgrade to 0.9.6
...
e66abfb4c6fece91d29a27037fd31bd23bd279a4 main/icu: fix -dev depends and clarify licenses
0168b1161a6bdaa966c749a556f1e1cee256206c Create APKBUILD
d5c72e68ff49f90d3ca0a40a88c81fe97b9a134e main/python3: Update to 3.6.6
...
````

**Comment by ncopa** [comment]
I merged the commits, and fixed the commit message for you. Thanks!

**Pull request closed without merging**
