### PR TITLE
community/py3-aiohttp: upgrade to 1.1.1

### PR DESCRIPTION
**Pull request by fabaff**
Depends on #454 and #453.

Required by #506.

### CODE REVIEW

**Comment by jirutka** [comment]
This package has been already updated in f0a940643e0382f675a11574a56e1b8743d20ace.

**Comment by fabaff** [comment]
But the dependencies (yarl and async-timeout) are missing...i doubt that f0a9406 will work as expected.

**Comment by jirutka** [comment]
Aha, you’re right, thanks for pointing to it!

**Comment by jirutka** [comment]
I’ve fixed it in 6b8defef2021a135e49853745f6e7c20ab9a7341 and wrote fcolista to be more careful about dependencies of Python packages.

**Comment by fabaff** [comment]
This was easy to say for me here as missed it for the Fedora package too.

**Comment by jirutka** [comment]
I thought that Fedora has somehow automated checks of dependencies for Python packages, don’t they?

**Pull request closed without merging**
