### PR TITLE
testing/bc: new aport

### PR DESCRIPTION
**Pull request by gavinhoward**
https://github.com/gavinhoward/bc
POSIX bc with GNU extensions

### CODE REVIEW

**Comment by rgdoliveira** [comment]
Alpine already has a package called [bc](https://pkgs.alpinelinux.org/package/edge/main/x86_64/bc), maybe you can rename yours? Guess @jirutka and @ncopa can have a better idea.

**Comment by andypost** [comment]
This way will lead to kinda MacOS has `sed` & `gnu-sed`

**Comment by jirutka** [comment]
Can it be used as a drop-in replacement for [GNU bc](https://www.gnu.org/software/bc/bc.html)? So we can rename the current `bc` package (GNU bc) to `gnu-bc` and package this one as `bc`?

/cc @kaniini, @ncopa

**Comment by gavinhoward** [comment]
Yes, it is a drop-in replacement. It does not have fancy math algorithms, so it's slower, but it has the same exact output. It can even run the timeconst.bc script in the Linux kernel build.

**Comment by gavinhoward** [comment]
I am also open to renaming this package.

**Comment by jirutka** [comment]
> …this is inconsistent with other GNU software we package, e.g. GNU sed isn't packaged as gnu-sed either.

That’s just because we don’t have any other `sed` implementation except Busybox `sed`, isn’t it? I’d personally prefer non-GNU as default where possible.

**Comment by gavinhoward** [comment]
I could rename this package now, and we can move the problem of figuring out which bc should be the default to later.

How should I name this package?

**Comment by ncopa** [comment]
I would not mind rename gnu bc to `gnu-bc` and use a BSD licensed `bc` as the default.

> @gavinhoward How should I name this package?

Maybe call it `gavinhoward-bc` or `howard-bc` for now?

**Comment by gavinhoward** [comment]
Package has been renamed to `howard-bc`.

**Pull request closed without merging**
