### PR TITLE
non-free/amd-ucode: remove aport

### PR DESCRIPTION
**Pull request by J0WI**
Seems to be covered by `main/linux-firmware`

### CODE REVIEW

**Comment by HRio** [comment]
@J0WI is `/lib/firmware/amd-ucode/microcode_amd.bin` in main/linux-firmware?

https://pkgs.alpinelinux.org/contents?file=microcode_amd.bin&path=&name=&branch=edge

**Comment by J0WI** [comment]
`main/linux-firmware-amd-ucode` is a sub-package of `main/linux-firmware`

**Comment by HRio** [comment]
yes I see now you are right, so we have non-free in main interesting.

**Comment by J0WI** [comment]
_cc @ncopa who is maintaining this package_

**Comment by J0WI** [comment]
:ping_pong: @ncopa

**Pull request closed without merging**
