### PR TITLE
main/msmtp: upgrade to 1.6.7

### PR DESCRIPTION
**Pull request by TBK**

### CODE REVIEW

**Comment by TBK** [comment]
I am not sure what is going on with CI.

On my machine I have no issue creating msmtp-lang.

Unpacked:
```
usr/
usr/share/
usr/share/locale/
usr/share/locale/de/
usr/share/locale/de/LC_MESSAGES/
usr/share/locale/de/LC_MESSAGES/msmtp.mo
usr/share/locale/fr/
usr/share/locale/fr/LC_MESSAGES/
usr/share/locale/fr/LC_MESSAGES/msmtp.mo
```

**Comment by vakartel** [comment]
I think you have gettext/xgettext installed on your local build system. But on CI it doesn't

So on CI there is no -lang specific data generated
=======================
configure ....
.......
checking for xgettext... no
.......
checking for GNU gettext in libc... no
.......
NLS support ............ : no

**Comment by TBK** [comment]
@vakartel ahh ofc. Thanks 👍

**Comment by nmeum** [comment]
IMHO this does too many things in one commit. You added a -lang subpackages, modernized the APKBUILD, added !check, upgraded the package, …

I think it would be good to do some of that in separated commits

**Comment by TBK** [comment]
@nmeum I have split it into 3 commits.

Would be nice with an official guideline since I have had comments saying to minimize the # of commit and split into more.

**Comment by andypost** [comment]
Filed another upgrade https://github.com/alpinelinux/aports/pull/4663

**Pull request closed without merging**
