### PR TITLE
testing/prometheus-node-exporter: new aport

### PR DESCRIPTION
**Pull request by myhro**
Prometheus exporter for machine metrics: https://github.com/prometheus/node_exporter

### CODE REVIEW

**Comment by andypost** [comment]
Now it builds without CGO https://github.com/prometheus/node_exporter/releases/tag/v0.17.0

**Comment by andypost** [comment]
@myhro please update PR

**Comment by myhro** [comment]
Hi @andypost,

The patch related to disabling Go's `-race` option isn't related to CGO, so this will not change.

In any case, the package was updated. The only thing I didn't understood is why TravisCI is saying `No packages found to be built`. Did I screwed up the PR? Or is it a known issue?

Regards,
Tiago.

**Comment by ncopa** [comment]
@jirutka any clue why TravisCI does not pick up this package?

**Comment by andypost** [comment]
Re-queued and now it picks new package

**Pull request closed without merging**
