### PR TITLE
main/php5-apcu: upgrade to 4.0.11

### PR DESCRIPTION
**Pull request by andypost**
There's 2 fixes http://pecl.php.net/package-info.php?package=APCu&version=4.0.11

### CODE REVIEW

**Comment by jirutka** [comment]
Please follow the common format for upgrade commit message: `$repo/$pkgname: upgrade to $pkgver`:

```
main/php5-apcu: upgrade to 4.0.11

Fixes 2 bugs, see http://pecl.php.net/package-info.php?package=APCu&version=4.0.11
``

**Comment by andypost** [comment]
Thanx a lot for pointer

**Comment by jirutka** [comment]
I'm not giving _pointers_, that would be unsafe, I'm giving just references! ;)

**Comment by andypost** [comment]
@jirutka is there a way to speedup process to accept PRs?

**Comment by jirutka** [comment]
I don't have rights to push into the main repository. I talked with @barthalion yesterday, he's gonna merge it today.

**Comment by jirutka** [comment]
@andypost Could you please change the commit message (and force push then)?

**Comment by Barthalion** [comment]
Merged in 3691713e.

**Pull request closed without merging**
