### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by tcely**
@Ikke @andypost @nmeum @clandmeter @rnalrd @ncopa 

Please fill in the list of who should review what before pushing this file. Thanks.

### CODE REVIEW

**Comment by ncopa** [comment]
I would like that the maintainer for the package does the review.

**Comment by nmeum** [comment]
> I would like that the maintainer for the package does the review.

I would prefer that as well, I don't think that it is a good idea to specify reviewers on a per-repo level. I personally only merge PRs of aports I maintain or use extensively or PRs for aports with simple and obvious changes, everything else should imho be merged and reviewed by the aport maintainer.

**Comment by tcely** [comment]
@ncopa @nmeum To list maintainer in this file for review, I believe they must be added as collaborators first.

The https://probot.github.io/apps/invite-contributors/ could help with this part of the task.

Adding reviewers per repository, then later entries with the maintainer's GitHub account for each package seems like a good compromise here.

**Comment by tcely** [comment]
@nmeum 
> I would prefer that as well, I don't think that it is a good idea to specify reviewers on a per-repo level. I personally only merge PRs of aports I maintain or use extensively or PRs for aports with simple and obvious changes, everything else should imho be merged and reviewed by the aport maintainer.

The reviewer and merger are distinct roles in the current work flow. The aport maintainer doing the merge will not be possible for a fairly large set of packages and arguably should never occur on changes they also authored. It makes a lot of sense for maintainers to review changes authored by others, I'm less convinced about the worth of any review done by the same person who authored the changes. ;-)

**Comment by Ikke** [comment]
I'm not sure if this mechanism is suitable for aports. The idea behind this feature is that you have certain parts of a codebase where you want to make sure certain people review it before it gets merged.

This is not the case for aports. It's not that I need to review aports in testing/community before they should be merged, anyone with push access to those repos can do it. So it would only be annoying for me to receive constant notifications for all these review request. I can only imagine how it would be for the others.

There are 2 types of review regarding aports:

1. Basic aport style/structure
2. Impact on the wider ecosystem, like dependencies, breaking changes, etc.

The package maintainers are mostly involved with the 2nd type of review. So if someone else suggests changes to a package, the package maintainer should be involved with the review as well.

**Comment by oxr463** [comment]
Any progress on this?

>The package maintainers are mostly involved with the 2nd type of review. So if someone else suggests changes to a package, the package maintainer should be involved with the review as well.

As a maintainer, I really don't like spending the time to submit a patch on the mailing list and waiting for weeks to hear back on it, only to find that someone has submitted a PR on Github that gets merged withing days, and then my patch never gets merged.

I didn't have any trouble with this until recently, but now it's happened twice, and it's really annoying to be honest.

Examples,

Patch for bash-completion, https://patchwork.alpinelinux.org/patch/4849
Github PR for the same version, https://github.com/alpinelinux/aports/pull/7873

Patch for cdist 4.10.10, https://patchwork.alpinelinux.org/patch/4790
Patch for cdist 5.0.2, https://patchwork.alpinelinux.org/patch/4880
Github PR for cdist 5.1.1, https://github.com/alpinelinux/aports/pull/8703

**Comment by Ikke** [comment]
We have concrete plans to move to gitlab, where we will try to integrate e-mail submissions as well, then we should not have too much duplicate efforts.

Right now, there are not a lot of people paying attention to the aports mailing list (kudos to the ones wh do).

**Pull request closed without merging**
