### PR TITLE
main/busybox-initscripts: update rpi bluetooth command

### PR DESCRIPTION
**Pull request by joneskoo**
The command hciattach is deprecated in bluez.
Replace the command with btattach.

### CODE REVIEW

**Comment by joneskoo** [comment]
I tested this (uncommented obviously) on my Raspberry Pi Zero W. Installing bluez and uncommenting this line seem to be sufficient to enable built-in Bluetooth.

btattach does not fork. There three lines lines of output from btattach at start which could be discarded but as this needs to be commented out by user to enable, I don't think that's necessary.

**Comment by joneskoo** [comment]
I updated https://wiki.alpinelinux.org/wiki/Raspberry_Pi_3_-_Setting_Up_Bluetooth too.

**Comment by ncopa** [comment]
we also need to update checksum and bump `pkgrel`.

**Comment by ncopa** [comment]
fixed with 760c4286035013366ef0919e2d4f904f09d572f8

**Pull request closed without merging**
