### PR TITLE
testing/traefik: upgrade to 1.7.12 and enable x86 and arm

### PR DESCRIPTION
**Pull request by andypost**
Ref https://github.com/containous/traefik/releases/tag/v1.7.12

### CODE REVIEW

**Comment by tcely** [comment]
The tests run in `check` don't appear to be 32-bit safe. Did this get reported to upstream?

**Comment by andypost** [comment]
I found no reports, and gonna dig first, but @tcely is right about x64 mention in fails

**Comment by andypost** [comment]
@tcely I see that 32bits missing and no idea how it can be solved( please help to report upstream, maybe there's a way to bypass x64 tests on 32 arch

**Comment by TBK** [comment]
Duplicate PR https://github.com/alpinelinux/aports/pull/8029 upgraded with commit https://github.com/alpinelinux/aports/commit/f7ff1b606d040ecd6db56a1dbe861e0a7094cf3b

This PR still has value in enabling more archs.

**Pull request closed without merging**
