### PR TITLE
testing/py2-traceback2: Switch to purely python2

### PR DESCRIPTION
**Pull request by maxice8**
- This is a backport of a python3 module which can be imported as
  traceback
- Enabled tests
- Add missing deps

### CODE REVIEW

**Comment by maxice8** [comment]
@itoffshore

**Comment by Ikke** [comment]
Is it still worth the effort considering python2 will be eol soon? Only `py-testtools` depends on it atm.

**Comment by maxice8** [comment]
Do we plan on removing py-testtools soon ?

**Comment by maxice8** [comment]
well i already did the transition process so there isn't much effort to be done

**Pull request closed without merging**
