### PR TITLE
testing/fuse3: upgrade to 3.2.1; add check

### PR DESCRIPTION
**Pull request by TBK**
py-test is missing a dependency, will make a PR.

### CODE REVIEW

**Comment by fabled** [comment]
Care to fix the build failure?

**Comment by TBK** [comment]
@fabled Yes, I will do it later today.

**Comment by TBK** [comment]
PR with dependency fix - https://github.com/alpinelinux/aports/pull/3917

**Comment by fabled** [comment]
Build still failed. Closing and reopening for new build.

**Comment by fabled** [comment]
Travis did not get the latest pkgs yet. The build failure is:
```
>>> fuse3: Entering fakeroot...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/pytest.py", line 74, in <module>
    raise SystemExit(pytest.main())
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 52, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 163, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/usr/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.6/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 936, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 1086, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 1046, in _preparse
    self._consider_importhook(args)
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 1007, in _consider_importhook
    hook = _pytest.assertion.install_importhook(self)
  File "/usr/lib/python3.6/site-packages/_pytest/assertion/__init__.py", line 75, in install_importhook
    config._assertstate.hook = hook = rewrite.AssertionRewritingHook(config)
  File "/usr/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 54, in __init__
    self._register_with_pkg_resources()
  File "/usr/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 245, in _register_with_pkg_resources
    pkg_resources.register_loader_type(cls, pkg_resources.DefaultProvider)
AttributeError: module 'pkg_resources' has no attribute 'register_loader_type'
>>> ERROR: fuse3*: check failed
>>> ERROR: fuse3: all failed
```

**Comment by andypost** [comment]
3.2.2 is out https://github.com/libfuse/libfuse/releases/tag/fuse-3.2.2

**Pull request closed without merging**
