### PR TITLE
community/py3-multidict: upgrade to 4.0.0

### PR DESCRIPTION
**Pull request by fabaff**

### CODE REVIEW

**Comment by nmeum** [comment]
Did you intentionally upgrade zabbix in the same commit?

**Comment by fabaff** [comment]
No, was unintentionally.

**Comment by nmeum** [comment]
If you move the zabbix upgrade to a seperate pull request I will gladly merge this one :)

**Comment by fabaff** [comment]
This PR is not needed. Looks like that the aport was updated already ignoring this PR..

**Pull request closed without merging**
