### PR TITLE
main/luajit: ppc64: fix r12 TOC issue and remove workaround

### PR DESCRIPTION
**Pull request by gromero**

### CODE REVIEW

**Comment by Shizmob** [comment]
Please bump $pkgrel as well.

**Comment by gromero** [comment]
@Shizmob done

**Comment by Shizmob** [comment]
Could you squash the two commits into one? :P

**Comment by gromero** [comment]
Sorry, my bad...

**Comment by jirutka** [comment]
@gromero How does it look with ppc64le support for 2.1.0_beta3?

**Pull request closed without merging**
