### PR TITLE
main/dwm: Fix emoji titlebar crash

### PR DESCRIPTION
**Pull request by orsonteodoro**
Test case: Open Firefox and go to https://getemoji.com/

### CODE REVIEW

**Comment by nmeum** [comment]
Hi,

Thanks for your contribution. I didn't look at your patch in depth so far but I have also experienced this problem with dwm. Did you suggest this patch upstream?

**Comment by orsonteodoro** [comment]
The fix was recommended by Gaetan Bisson from Arch Linux. https://lists.suckless.org/dev/1610/30720.html on Oct 25, 2016 on their dev mailing list.

**Comment by nmeum** [comment]
So, I have been using this patch with my fork of dwm for the past month and it works fine as is. However, it doesn't render emojis properly it just prevents a crash and I don't know if it breaks any other unicode characters. I would actually prefer a proper upstream fix for this issue instead of committing a patch downstream.

BTW:  Gaetan Bisson himself stated that he didn't understand why dwm crashes in the first places and why his patch fixes this problem.

**Comment by nmeum** [comment]
I am closing this for two reason:

1. This doesn't seem to be a proper fix for the issue
2. This should be fixed upstream, not downstream

**Pull request closed without merging**
