### PR TITLE
testing/parity: new aport

### PR DESCRIPTION
**Pull request by misery**

### CODE REVIEW

**Comment by misery** [comment]
Blocked by: https://github.com/paritytech/parity/issues/5811

Maybe: https://github.com/paritytech/parity/issues/5794

**Comment by Vurich** [comment]
Parity requires `cc` to be on the path, I guess TCC is the most Alpine-y choice for this. Just add a C compiler as a dependency and it should work.

**Comment by misery** [comment]
As you can see in travis build: gcc is already there.

**Comment by fabled** [comment]
```
>>> parity: Checking sha512sums...
parity-1.7.0.tar.gz: FAILED
sha512sum: WARNING: 1 of 1 computed checksums did NOT match
```
Upstream changed distribution tarballs?

**Comment by fabled** [comment]
This is also downloading things from Internet during build:
```
parity-1.7.0.tar.gz: OK
>>> parity: Unpacking /var/cache/distfiles/parity-1.7.0.tar.gz...
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/paritytech/rust-secp256k1`
    Updating git repository `https://github.com/paritytech/wasm-utils`
    Updating git repository `https://github.com/paritytech/rust-rocksdb`
    Updating git repository `https://github.com/paritytech/hyper`
    Updating git repository `https://github.com/paritytech/bn`
    Updating git repository `https://github.com/paritytech/nanomsg.rs.git`
    Updating git repository `https://github.com/paritytech/libusb-rs`
...
```

Trying to make reproducible build without Internet gives:
```
>>> parity: Unpacking /var/cache/distfiles/parity-1.7.0.tar.gz...
error: An unknown error occurred

To learn more, run the command again with --verbose.
>>> ERROR: parity: build failed
>>> ERROR: parity: rootbld failed
```

**Comment by jirutka** [comment]
No, it does not have. We haven't decide how to handle Cargo packages yet.

**Pull request closed without merging**
