### PR TITLE
[3.10] main/mozjs60: security upgrade to 60.8

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
:ping_pong: @Cogitri

**Comment by Cogitri** [comment]
Also, I guess this can be bumped to 60.8?

**Comment by J0WI** [comment]
Sure, just wanted to wait for 13252725899e73878ee6f66f3565beea747cf90f

**Comment by Cogitri** [comment]
👍

**Comment by J0WI** [comment]
69e0a2354226ee7d88d7ad11d7d82295b1ba1f60

**Pull request closed without merging**
