### PR TITLE
Syncthing v0.14.2

### PR DESCRIPTION
**Pull request by zburgermeiszter**

### CODE REVIEW

**Comment by jirutka** [comment]
@7heo please rewrite this package to use glide for resolving dependencies.

**Comment by 7heo** [comment]
@jirutka Will do asap.

**Comment by 7heo** [comment]
@jirutka it's much harder than "expected", because they rely on `go generate` in their build process (that tool is intended for development only, not during build time).

**Comment by jirutka** [comment]
Well, @clandmeter already updated syncthing to 0.14.3 (0a9b332b7e1ee8855c47688142e374b637bbbcef), independently of this PR. But thanks for your contribution anyway!

**Pull request closed without merging**
