### PR TITLE
Bulk change: Update urls to https using HTTPS Everywhere

### PR DESCRIPTION
**Pull request by J0WI**
Not sure if you accept bulk changes, but this can be reproduced by using [this script](https://github.com/EFForg/https-everywhere/tree/4117544090de90167069ecfab1a85dc1eac33303/utils/rewriter), applying [this patch](https://github.com/EFForg/https-everywhere/pull/15747) and removing [this line](https://github.com/EFForg/https-everywhere/blob/4117544090de90167069ecfab1a85dc1eac33303/utils/rewriter/rewriter.js#L78).

### CODE REVIEW

**Comment by ncopa** [comment]
Those who changes the `url=..` will need to bump pkgrel. I'd also like to have 3 commits in this PR, one with the packges in main, one for community and the third for testing repo. We dont need to touch anything in unmaintained.

Also, I would like to have this PR after v3.8 is released. Since this touches so many packages it will fairly quick be outdated and have conflicts, so it might be an idea to close this PR and create a new after v3.8 is out.

Thanks!

**Comment by J0WI** [comment]
Is there already a specific timeline for branching 3.8?

**Comment by tmpfile** [comment]
It's out

**Comment by J0WI** [comment]
@ncopa Thanks, I've rebased my changes and applied some additional patches from https://github.com/EFForg/https-everywhere/issues/15750.
There is also a 4th commit for "non-free", feel free to strip it from this PR.

**Comment by J0WI** [comment]
@ncopa is there a chance to finish this project?

**Comment by ncopa** [comment]
Oh, yes! I think now is a relatively good time to apply this. I think it will create various conflics with the current PRs, so ideally, we should try close as many PRs as possible, then rebase this PR and merge it before the PR queue goes up again.

Is tomorrow is a good day for rebasing and merging this? Then can the builders be busy over the weekend.

**Comment by J0WI** [comment]
Okay, just ping me when you're ready!

**Comment by ncopa** [comment]
I can push this now if you rebase it. Thanks!

**Comment by ncopa** [comment]
@J0WI Would it be possible to have a patch that does not bump pkgrel when only `source` changes? It would reduce number of rebuilds significantly. We only need bump pkgrel when `url` change, because it result in different content of the built package.

**Comment by ncopa** [comment]
I'd also like to exclude `main/linux-vanilla` from this list. It will break the versioned dependencies (which in theory may result in unbootable systems). We can update linux-vanilla next kernel upgrade.

**Comment by ncopa** [comment]
I pushed the non-free.

**Comment by J0WI** [comment]
> Would it be possible to have a patch that does not bump pkgrel when only source changes?

It's to be difficult to filter the changes, but I try to find a solution.

**Comment by J0WI** [comment]
@ncopa there are now two commits for each repo.
The first changes the `source`, but I'm not 100% sure that there is no other change, since some packages use some exotic patterns. Also some urls are not readable by HTTPS Everywhere (e.g. those that use a `$variable` instead of a valid domain). I may submit some follow-up patches for them.
The second change updates all other urls, including `url` and some in `build()`, and bumps the `pkgrel`.
I excluded `main/linux-vanilla` from all changes.

**Comment by ncopa** [comment]
Also, git strips `[...]` from commit message:

````
ncopa-edge-x86_64:~/aports/main$ git log --format=oneline origin/master..
fd68de704d044b4fd695b3bb95e4b60f509fdd7c (HEAD -> master) replace variable in source url
7a1fb1a864c632f3c5f0c0adbd02d30322d18e6b Bulk change: Update urls to https using HTTPS Everywhere and bump pkgrel
0b966e0cc2ff8af16e35fc66095fe1fdc399d1cd Bulk change: Update urls to https using HTTPS Everywhere and bump pkgrel
a4c864fbfd064f97d59ede8bb32571a03d0d6085 Bulk change: Update urls to https using HTTPS Everywhere and bump pkgrel
ac3f6b3ec4ee668b697175f5bdf67a9263eeca23 Bulk change: Update source urls to https using HTTPS Everywhere
8954ef1bf4a23d6b7991c8d6a47a5d20189d2a74 Bulk change: Update source urls to https using HTTPS Everywhere
b3604ce62e1657bd157f4617a112c9e449993697 Bulk change: Update source urls to https using HTTPS Everywhere
````

Those commit messages are not really useful.

**Comment by J0WI** [comment]
I can't reproduce this here, but I'll provide an updated commit message without `[]`.

**Comment by ncopa** [comment]
I pushed the 3 first commits with fixed commit message.

**Comment by ncopa** [comment]
i will not be able to fix any potential build breakages tomorrow and probably not early next week either. I think we need to wait with the url changes :-/

I can maybe only push `testing` repo, but I don't dare push it all at this point.

**Comment by J0WI** [comment]
I've rebased this anyway

**Comment by ncopa** [comment]
The builders are still down after the mess created by pushing this to testing. I don't think I will do the same in community and main. We will have to clean up gradually to avoid full blocking for weeks like this.

**Comment by J0WI** [comment]
@ncopa I'm not sure if I understand you correctly.
Are the builders still busy with building all packages or are there any errors caused by this change? Could you please point me to some examples if so?

I can go through the images alphabetically or so to avoid such huge changes.

**Pull request closed without merging**
