### PR TITLE
community/ceph: Move Ceph from testing repo (along with deps)

### PR DESCRIPTION
**Pull request by iggy**
**Summary**

* move `testing/ceph` to `community/ceph`
* move 'testing/leveldb` to `community/leveldb`
* move 'testing/oath-toolkit` to `community/oath-toolkit`
* Upgrade Ceph to latest release
* Add `radosgw` package back to ceph
* Build `mgr` frontend bits
* Make `community/oath-toolkit` actually compile with newer toolchains

### CODE REVIEW

**Comment by TBK** [comment]
Please make a commit per "action". The default phrasing for moving packages is: `community/ceph: move from testing`

**Comment by iggy** [comment]
I've already done this PR 4 times before. I got lazy.

**Comment by TBK** [comment]
Failing on Travis because: 
> The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by Ikke** [comment]
Commit subjects have a soft limit of 50 characters. 82a26f9 even has 72 characters. The subjects should be concise, while the body can contain more details.

Usually when you use 'and' in a commit subject, it means you are in fact describing 2 commits, though this is not always the case. Sometimes you can just mention that part in the commit body.

Thanks,

**Comment by iggy** [comment]
Can I get a checklist or something that describes all the requirements I have to meet? Doing this 5 different times to meet a seemingly changing set of requirements is wasting everybody's time and just generally making me lean toward keeping my changes outside the main aports tree.

**Comment by Ikke** [comment]
@iggy We're working on improving the documentation and code style requirements, but there is not a single definitive resource right now.

There is [the contributing guidelines][0] and the [apkbuild reference][2]. It also helps to look at existing commits to see how things are being done.

Note that the 50/72 line length limit is a pretty common [git standard][1].

Thanks for keeping up with us.

[0]:https://github.com/alpinelinux/aports/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request-pr
[1]:https://chris.beams.io/posts/git-commit/ 
[2]:https://wiki.alpinelinux.org/wiki/APKBUILD_Reference

**Pull request closed without merging**
