### PR TITLE
community/libdwarf: upgrade to 20190505

### PR DESCRIPTION
**Pull request by maxice8**
- Fix license
- Fix subpkg license
- Split $pkgname-static
- Make dwarf-tools noarch
- Use modern style

### CODE REVIEW

**Comment by maxice8** [comment]
@storedbox

**Comment by storedbox** [comment]
I approve and would like to offer @maxice8 maintainership of this package.

**Comment by maxice8** [comment]
On Tue, May 07, 2019 at 05:05:01AM -0700, David Huffman wrote:
> I approve and would like to offer @maxice8 maintainership of this package.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7639#issuecomment-490051292

Sure

**Comment by andypost** [comment]
btw it fails for s390x https://build.alpinelinux.org/buildlogs/build-edge-s390x/community/libdwarf/libdwarf-20190505-r0.log
```
make: Entering directory '/home/buildozer/aports/community/libdwarf/src/libdwarf-20190505/dwarfgen'
  CXX      dwarfgen-createirepformfrombinary.o
  CXX      dwarfgen-createirepfrombinary.o
  CXX      dwarfgen-dwarfgen.o
dwarfgen.cc: In function 'void bitreplace(char*, Dwarf_Unsigned, size_t, int)':
dwarfgen.cc:169:35: error: 'sbyte' was not declared in this scope
             memcpy(((char *)(op))+sbyte,(const void *)(ip),il);\
                                   ^~~~~
dwarfgen.cc:902:9: note: in expansion of macro 'ASNX'
         ASNX(&oldval,sizeof(oldval),buf,(unsigned)length);
         ^~~~
dwarfgen.cc:169:35: error: 'sbyte' was not declared in this scope
             memcpy(((char *)(op))+sbyte,(const void *)(ip),il);\
                                   ^~~~~
dwarfgen.cc:904:9: note: in expansion of macro 'ASNX'
         ASNX(buf,(unsigned)length,&oldval,sizeof(oldval));
         ^~~~
  CXX      dwarfgen-irepattrtodbg.o
make: *** [Makefile:539: dwarfgen-dwarfgen.o] Error 1
```

**Pull request closed without merging**
