### PR TITLE
testing/py3-pathlib2: New aport

### PR DESCRIPTION
**Pull request by bratkartoffel**
This PR adds python pathlib2, a library to work with filesystem paths in an object-oriented way.

### CODE REVIEW

**Comment by ncopa** [comment]
Do we really need python2 support?

**Comment by bratkartoffel** [comment]
I don't know, I just added the _py2 and _py3 sections just like the other py-packages do.
I don't need python2 support, should I remove it?

**Comment by ncopa** [comment]
Yes please remove python2 support if its not needed.

**Comment by andypost** [comment]
Required to run tests for https://github.com/alpinelinux/aports/pull/5185

**Comment by andypost** [comment]
@ncopa looks better to have both for now https://bugs.alpinelinux.org/issues/9420

**Comment by clandmeter** [comment]
oops, didnt notice this one. Sorry.

**Comment by bratkartoffel** [comment]
As this package is in master now (https://github.com/alpinelinux/aports/blob/master/main/py-pathlib2/APKBUILD), I'll close this PR. Thanks!

**Pull request closed without merging**
