### PR TITLE
testing/netdata: improve shutdown

### PR DESCRIPTION
**Pull request by HRio**

### CODE REVIEW

**Comment by HRio** [comment]
@jirutka can you have a look? thanks

**Comment by jirutka** [comment]
Please read [openrc-run(8)](http://manpages.org/openrc-run/8), use parameter `retry` instead of DIY logic and let OpenRC daemonize the process and handle PID file (i.e. the command should not daemonize itself).

**Comment by HRio** [comment]
@jirutka big thanks, will fix.

**Comment by HRio** [comment]
@jirutka can you have a look again? thanks

**Comment by HRio** [comment]
@jirutka can you have a quick check? thanks.

**Comment by HRio** [comment]
sigh... closing due to 2696e83565eb1857b1200f5850ad4d6b9392cb92

**Pull request closed without merging**
