### PR TITLE
community/scrot: upgrade to 0.9.1, move to community

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Ikke** [comment]
@maxice8 Can you add your motivation why you move scrot from main to community in the commit message for prosperity? (ftr, I don't disagree with it)

**Comment by maxice8** [comment]
done

**Comment by liqa** [comment]
The commit message doesn't tell us where the package is coming from.
I'd suggest `community/scrot: upgrade to 0.9.1, move from main` or `main/scrot: upgrade to 0.9.1, move to community`.

**Comment by maxice8** [comment]
On Sat, Jun 08, 2019 at 05:23:32PM -0700, liqa wrote:
> The commit message doesn't tell us where the package is coming from.
> I'd suggest `community/scrot: upgrade to 0.9.1, move from main` or `main/scrot: upgrade to 0.9.1, move to community`.
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/8634#issuecomment-500175019

There are 2 commits, one moves, one upgrades

**Pull request closed without merging**
