### PR TITLE
community/fractal: enable on x86

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
@Cogitri are the `CFLAGS` passed to rustc?

**Comment by Cogitri** [comment]
They're used by the `cc` create

**Comment by ncopa** [comment]
1. I would prefer to keep the stack protector enabled and fix the linker flags instead.
2. It still fails.:

```
Compiling fractal-matrix-api v4.2.1 (/home/buildozer/aports/community/fractal/src/fractal-4.2.1/fractal-matrix-api)
--
882 | error: Could not compile `gtk`.
883 |  
884 | Caused by:
885 | process didn't exit successfully: `rustc --crate-name gtk /home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/cargo-home/registry/src/github.com-1ecc6299db9ec823/gtk-0.7.0/src/lib.rs --color never --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="v3_16"' --cfg 'feature="v3_18"' --cfg 'feature="v3_20"' --cfg 'feature="v3_22"' --cfg 'feature="v3_22_20"' --cfg 'feature="v3_22_26"' --cfg 'feature="v3_22_27"' --cfg 'feature="v3_22_29"' --cfg 'feature="v3_22_30"' --cfg 'feature="v3_24"' -C metadata=3d0ed6441a09057c -C extra-filename=-3d0ed6441a09057c --out-dir /home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps -L dependency=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps --extern atk=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libatk-cd84da513bae6774.rlib --extern bitflags=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libbitflags-8d2a7a63ac942521.rlib --extern cairo=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libcairo-ca03222d6b5cd4d7.rlib --extern cairo_sys=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libcairo_sys-9f3e615599c7f82a.rlib --extern gdk=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libgdk-a0a6155dd67f0d1e.rlib --extern gdk_pixbuf=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libgdk_pixbuf-f53876651d576834.rlib --extern gdk_pixbuf_sys=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libgdk_pixbuf_sys-b604afd88d4b90c2.rlib --extern gdk_sys=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libgdk_sys-98c8a49ca0f276c7.rlib --extern gio=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libgio-b66fb6586b99bb52.rlib --extern gio_sys=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libgio_sys-830c068e49ac8a13.rlib --extern glib=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libglib-a718c5831ea2745a.rlib --extern glib_sys=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libglib_sys-70d24e1b398c3351.rlib --extern gobject_sys=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libgobject_sys-c08480e6c0fe55e4.rlib --extern gtk_sys=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libgtk_sys-fb3b4a9b7ea3d215.rlib --extern lazy_static=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/liblazy_static-6ea4d5ec97a1f56d.rlib --extern libc=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/liblibc-1c0ce3230c9fa922.rlib --extern pango=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libpango-9c6023460405cee4.rlib --extern pango_sys=/home/buildozer/aports/community/fractal/src/fractal-4.2.1/output/target/release/deps/libpango_sys-03ffda2c79a1ce46.rlib --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
886 | [3/4] Generating org.gnome.Fractal.desktop_fractal-gtk@res_merge with a custom command.
887 | FAILED: fractal-gtk/src/fractal
888 | /home/buildozer/aports/community/fractal/src/fractal-4.2.1/scripts/cargo.sh .. fractal-gtk/src/fractal /home/buildozer/aports/community/fractal/src/fractal-4.2.1/output ''
889 | ninja: build stopped: subcommand failed.
```

**Comment by Cogitri** [comment]
The stack protector doesn't really do anything here though, does it?

The build failure is on rustc randomly failing, as bad as it sounds the only option is to restart the build until it decides to work until we get that fixed :/

**Pull request closed without merging**
