### PR TITLE
main/perl: upgrade to 5.24.0

### PR DESCRIPTION
**Pull request by liqa**

### CODE REVIEW

**Comment by jirutka** [comment]
Please change commit message to: `main/perl: upgrade to 5.24.0` (hint: commit --amend && git push -f).

**Comment by jirutka** [comment]
⚠️ This upgrade will require to rebuild all perl packages that are not noarch! ⚠️

**Comment by liqa** [comment]
is that message for me or something @ncopa and other devs will do when merging the patch?
because I'm not really sure how to do it…

**Comment by jirutka** [comment]
@liqa This message is just a reminder for us, you can ignore it.

**Comment by liqa** [comment]
ah okay thanks
good luck, I wish we can have updated perl soon
lots of work

apk search -q perl |grep -v "doc" |grep -v "dev" |wc -l
601

but minus the noarch ones, I don't know how to check which ones are

**Comment by liqa** [comment]
what if you just bump all pkgrel at once?
apk search -q perl |grep -v "doc" |grep -v "dev"| xargs apkgrel -a

the problem is that it bumps 'noarch' packages too this way

**Pull request closed without merging**
