### PR TITLE
testing/firefox: upgrade to 70.0

### PR DESCRIPTION
**Pull request by timbru31**
Firefox release notes: https://www.mozilla.org/en-US/firefox/70.0/releasenotes/

I assume the `fix-third_party.patch` is no longer needed since the source files now use `let mut param = unsafe { std::mem::zeroed::<libc::sched_param>() };`

### CODE REVIEW

**Comment by J0WI** [comment]
https://www.mozilla.org/en-US/security/advisories/mfsa2019-34/

**Comment by timbru31** [comment]
Thanks, I've added the CVE identifiers

**Comment by J0WI** [comment]
The upgrade has been done in 08fb2f00a4afc171b32ea5026d1d2b24ab28fb8d by @Cogitri, but without the CVE identifiers

**Comment by Cogitri** [comment]
Oh, oops, forgot about those.

-------- Original Message --------

**Comment by Cogitri** [comment]
Sorry, I haven't noticed this one (or maybe we just opened the PRs at about the same time) :/

**Comment by timbru31** [comment]
No worries.

**Comment by timbru31** [comment]
@Cogitri unfortunately, Firefox 70 segfaults for me, did it work for you?

**Comment by Cogitri** [comment]
Yup, works for me (and I know of others for whom it also works). Could you please open an issue for it on Gitlab?

**Pull request closed without merging**
