### PR TITLE
main/readline: upgrade to 8.0

### PR DESCRIPTION
**Pull request by andypost**
Ref http://lists.gnu.org/archive/html/bug-bash/2019-01/msg00064.html

### CODE REVIEW

**Comment by andypost** [comment]
@ncopa it needs to bump lots of dependencies 
```
-usr/lib/libreadline.so.7
-usr/lib/libreadline.so.7.0
+usr/lib/libreadline.so.8
+usr/lib/libreadline.so.8.0
```

**Comment by andypost** [comment]
@ncopa it still needs you POV cos affects a lot

**Comment by ncopa** [comment]
> @ncopa it still needs you POV cos affects a lot

I'm working on this now. Thanks!

**Comment by andypost** [comment]
Fixed with bbadfb1c and the rest

**Pull request closed without merging**
