### PR TITLE
main/py-yaml: upgrade to 5.1

### PR DESCRIPTION
**Pull request by fabaff**

### CODE REVIEW

**Comment by andypost** [comment]
Other packages depends on it
```
community/py-sphinx-autobuild/APKBUILD:10:depends="py-argh py-livereload py-pathtools py-yaml py-sphinx py-tornado py-watchdog py-setuptools"
community/py-watchdog/APKBUILD:10:depends="py-pathtools py-yaml py-argh"
main/ansible/APKBUILD:13:depends="python3 $_py-yaml $_py-paramiko $_py-jinja2 $_py-markupsafe $_py-crypto"
main/py-cliapp/APKBUILD:11:makedepends="py-setuptools py-yaml"
main/py-yaml/APKBUILD:4:pkgname=py-yaml
testing/criu/APKBUILD:12:checkdepends="py-yaml"
testing/py-elasticsearch/APKBUILD:12:#checkdepends="py-requests py-nose py-coverage py-mock py-yaml py-nosexcover"
testing/py-elasticsearch/APKBUILD:13:checkdepends="py-requests py-nose py-coverage py-mock py-yaml" # add nosexcover next release
testing/py-helper/APKBUILD:11:depends="python2 py-yaml"
testing/py-netmiko/APKBUILD:11:depends="openssh-client py-yaml py-paramiko py-scp"
```
Are their compatible with new major upgrade?

**Comment by ncopa** [comment]
Im about to upgrade python to 3.7. i think we can rebuild them all at the same time if a rebuild is needed

**Comment by ncopa** [comment]
looks like i forgot this when upgrading python to 3.7. sorry. :disappointed:

**Comment by ncopa** [comment]
no it was merged. the bot missed it. :smile:

**Pull request closed without merging**
