### PR TITLE
testing/lxcfs: move to community / enable unprivileged containers

### PR DESCRIPTION
**Pull request by itoffshore**
unprivileged `lxc` containers now work with the vanilla kernel:

```
alp64kvm [~]# ps aux|grep 100000
 6273 100000     0:00 init
 6609 100000     0:00 /sbin/syslogd
 6615 100000     0:00 /sbin/getty 38400 console
 6616 100000     0:00 /sbin/getty 38400 tty1
 6617 100000     0:00 /sbin/getty 38400 tty2
 6618 100000     0:00 /sbin/getty 38400 tty3
 6619 100000     0:00 /sbin/getty 38400 tty4
```
also fixes the `initd` depends() in `cgmanager` - enabling the `lxcfs` initd is enough to start all 3 services.

### CODE REVIEW

**Comment by clandmeter** [comment]
Thanks for fixing this!

**Comment by jirutka** [comment]
The `chownmap` script is too slow for bigger containers. I wrote [uidmapshift](https://github.com/jirutka/uidmapshift) utility in Lua for this purpose some time ago, that I'm using on Alpine.

**Comment by itoffshore** [comment]
ok - I will replace `chownmap` with `uidmapshift` later today

**Comment by itoffshore** [comment]
replaced in https://github.com/alpinelinux/aports/pull/311

**Pull request closed without merging**
