### PR TITLE
testing/py-daemonize: new aport

### PR DESCRIPTION
**Pull request by z3ntu**
https://github.com/thesharp/daemonize
Library to enable your code run as a daemon process on Unix-like systems.

### CODE REVIEW

**Comment by fcolista** [comment]
Hi, thanks for your contribution!
Can you please check this points?
> +pkgrel=1
pkgrel should starts from 0.

> +options="!check"
Why check is disabled here? I've tried to add check() and it works without issue.
As last point:
There's no maintainer/contributor.
Even if it is not mandatory for packages in testing, If you want to move this in the next future to the community repository a maintainer is needed.
Once this will be fixed, we will be happy to merge it.
Thanks again!
.: Francesco

**Comment by z3ntu** [comment]
> pkgrel should starts from 0.
Done (I'm getting confused between Arch Linux and Alpine 😄)
> Why check is disabled here? I've tried to add check() and it works without issue.
Running `python3 setup.py test` doesn't actually run any tests (`Ran 0 tests in 0.000s`)
> There's no maintainer/contributor.
Should I add myself as contributor?

**Comment by rnalrd** [comment]
> Should I add myself as contributor?

Yes please, or as a maintainer if you can.

**Comment by z3ntu** [comment]
@rnalrd According to the wiki page being a maintainer means:
* fix bugs in package
* keep it updated. This includes follow upstream announcemt list, rss feed etc and provide updates to Alpine Linux in timely fashion.

I can do that :)

**Pull request closed without merging**
