### PR TITLE
main/libgit2: upgrade to 0.27.0

### PR DESCRIPTION
**Pull request by andypost**
Ref https://github.com/libgit2/libgit2/releases/tag/v0.27.0

### CODE REVIEW

**Comment by TBK** [comment]
All dependent packages needs to be bumped the ABI has changed - https://abi-laboratory.pro/tracker/timeline/libgit2/

**Comment by andypost** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by andypost** [comment]
Was upgraded by @jirutka  in https://github.com/alpinelinux/aports/commit/656d0b047dc744a9bd9541dfa8b07ad60f4ebffc

**Comment by jirutka** [comment]
I had a feeling that I’ve seen a PR for libgit2 upgrade, but when searched for it, GitHub didn’t find it. :(

**Pull request closed without merging**
