### PR TITLE
Fixes for the packages I maintain

### PR DESCRIPTION
**Pull request by leitao**

### CODE REVIEW

**Comment by leitao** [comment]
Jenkins failed because the package does not build for !ppc64le platform.

**Comment by ncopa** [comment]
I'd like to wait with those changes til after 3.6-stable is branched, mostly because it makes it more time consuming to backport security fixes.

http://lists.alpinelinux.org/alpine-devel/5608.html

**Comment by tmpfile** [comment]
@ncopa 3.6-stable is branched, good to merge now?

**Comment by fabled** [comment]
Rebased and applied. Thanks. Interestingly `testing/ndctl` tests are mostly SKIPPED instead of really ran (at least on x86_64).

**Pull request closed without merging**
