### PR TITLE
community/wireguard: update to 20191226

### PR DESCRIPTION
**Pull request by zx2c4**
This follows a reorganzation of WireGuard repos and tarballs after being merged to net-next.

### CODE REVIEW

**Comment by zx2c4** [comment]
CC @ncopa

**Comment by zx2c4** [comment]
Can somebody merge this, please? @ncopa @Cogitri @jirutka

**Comment by clandmeter** [comment]
Hi Jason. Congrats on the recent news.
We have shifted development to https://gitlab.alpinelinux.org/alpine/aports
Would be nice if you could send MR's instead of sending PR's in the future.
I think ncopa can still fetch this one, but that's up to him.

**Comment by ncopa** [comment]
Will take care of this, but may wait and do it together with 5.4.8 kernel when that comes out.

**Comment by kr0k0** [comment]
https://gitlab.alpinelinux.org/alpine/aports/merge_requests/2705

**Comment by zx2c4** [comment]
You forgot to fix up the install_if logic version number in that mr.

**Pull request closed without merging**
