### PR TITLE
testing/gdal: Support PostgreSQL and SQLite drivers

### PR DESCRIPTION
**Pull request by mroutis**
Enable support for the following drivers:

- PostgreSQL
- SQLite

### CODE REVIEW

**Comment by mroutis** [comment]
@nmeum, do you need something else to merge this PR? can I help somehow?

**Comment by mroutis** [comment]
Hi, @Ikke, we decided to use this PR instead of https://github.com/alpinelinux/aports/pull/2850, as it has similar results, could we merge this?
Also, I don't know if @BjoernSchilberg should be notified, as he merged the previous update with GDAL.
Thank you, all!

**Comment by jirutka** [comment]
**Note for maintainers:** This adds a lot of extra dependencies/bloat. Examine if it can be modularized.

**Comment by mroutis** [comment]
@jirutka, indeed, however, it's a pain to find out the driver you need is not included in the package, and you need to compile it from source, taking quite a lot (the travis build took ~34 min.)

We can trim the dependencies to `sqlite-dev` and `postgresql-dev`, as those are the main necessities, based on pull requests.

**Comment by mroutis** [comment]
@jirutka, I modified the PR to just add `sqlite-dev` and `postgresql-dev`, as I didn't find out a way to modularize the package, do you know some other packages modularized to look at them as an example?

I hope this is enough to merge it, if I can help with something more, don't hesitate to ask :)

**Comment by mroutis** [comment]
done, @fabled; squashed and rebased 👍

**Comment by mroutis** [comment]
already at 2.2.3, @chambbj

**Pull request closed without merging**
