### PR TITLE
testing/php7-mongodb: upgrade to 1.4.3

### PR DESCRIPTION
**Pull request by andypost**
https://pecl.php.net/package-changelog.php?package=mongodb&release=1.4.3

### CODE REVIEW

**Comment by andypost** [comment]
locally build failed

**Comment by andypost** [comment]
```
/mnt/testing/php7-mongodb/src/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-stream-tls-openssl-bio.c:58:1: error: static declaration of 'BIO_set_data' follows non-static declaration
 BIO_set_data (BIO *b, void *ptr)
 ^~~~~~~~~~~~
In file included from /mnt/testing/php7-mongodb/src/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-stream-tls-openssl-bio-private.h:27:0,
                 from /mnt/testing/php7-mongodb/src/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-stream-tls-openssl-bio.c:31:
/usr/include/openssl/bio.h:609:7: note: previous declaration of 'BIO_set_data' was here
 void  BIO_set_data(BIO *a, void *ptr);
       ^~~~~~~~~~~~
/mnt/testing/php7-mongodb/src/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-stream-tls-openssl-bio.c:64:1: error: static declaration of 'BIO_get_data' follows non-static declaration
 BIO_get_data (BIO *b)
 ^~~~~~~~~~~~
In file included from /mnt/testing/php7-mongodb/src/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-stream-tls-openssl-bio-private.h:27:0,
                 from /mnt/testing/php7-mongodb/src/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-stream-tls-openssl-bio.c:31:
/usr/include/openssl/bio.h:608:8: note: previous declaration of 'BIO_get_data' was here
 void  *BIO_get_data(BIO *a);
        ^~~~~~~~~~~~
/mnt/testing/php7-mongodb/src/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-stream-tls-openssl-bio.c:70:1: error: static declaration of 'BIO_set_init' follows non-static declaration
 BIO_set_init (BIO *b, int init)
 ^~~~~~~~~~~~
In file included from /mnt/testing/php7-mongodb/src/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-stream-tls-openssl-bio-private.h:27:0,
                 from /mnt/testing/php7-mongodb/src/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-stream-tls-openssl-bio.c:31:
/usr/include/openssl/bio.h:610:7: note: previous declaration of 'BIO_set_init' was here
 void  BIO_set_init(BIO *a, int init);
       ^~~~~~~~~~~~
make: *** [Makefile:465: src/libmongoc/src/mongoc/mongoc-stream-tls-openssl-bio.lo] Error 1
make: *** Waiting for unfinished jobs....
/mnt/testing/php7-mongodb/src/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-stream-tls-openssl.c:50:1: error: static declaration of 'BIO_meth_free' follows non-static declaration
 BIO_meth_free (BIO_METHOD *meth)
 ^~~~~~~~~~~~~
In file included from /mnt/testing/php7-mongodb/src/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-stream-tls-openssl.c:25:0:
/usr/include/openssl/bio.h:339:6: note: previous declaration of 'BIO_meth_free' was here
 void BIO_meth_free(BIO_METHOD *biom);
      ^~~~~~~~~~~~~
make: *** [Makefile:467: src/libmongoc/src/mongoc/mongoc-stream-tls-openssl.lo] Error 1
>>> ERROR: php7-mongodb: all failed

**Comment by TBK** [comment]
LibreSSL patch needed.

**Comment by andypost** [comment]
Added patch for version string prodly found elsewhere `&& LIBRESSL_VERSION_NUMBER < 0x2070000fL`

**Pull request closed without merging**
