### PR TITLE
main/protobuf: upgrade to 3.8.0

### PR DESCRIPTION
**Pull request by andypost**
Ref https://github.com/protocolbuffers/protobuf/releases
https://abi-laboratory.pro/?view=timeline&l=protobuf
Tests https://github.com/google/googletest/releases

php https://github.com/alpinelinux/aports/pull/6846
py https://github.com/alpinelinux/aports/pull/6847

### CODE REVIEW

**Comment by andypost** [comment]
ABI changed so dependencies needs bump
```diff
-usr/lib/libprotobuf.so.17
-usr/lib/libprotobuf.so.17.0.0 
...
+usr/lib/libprotobuf.so.18
+usr/lib/libprotobuf.so.18.0.1  
```

**Comment by andypost** [comment]
Protobuf-c needs patch from https://github.com/protobuf-c/protobuf-c/pull/342
`>>> No soname differences for protobuf-c. `

**Comment by prspkt** [comment]
`community/mumble` will need [this patch](https://github.com/mumble-voip/mumble/commit/c014e04f44e66a41ad4a2ef12a4d4816726206f3).

**Comment by andypost** [comment]
> `community/mumble` will need [this patch](https://github.com/mumble-voip/mumble/commit/c014e04f44e66a41ad4a2ef12a4d4816726206f3).

@prspkt sadly it needs rework cos can't be applied

**Comment by andypost** [comment]
Filed https://github.com/alpinelinux/aports/pull/6850

**Comment by andypost** [comment]
Could have collision with https://github.com/alpinelinux/aports/pull/6558

**Comment by andypost** [comment]
@ncopa rebased all commits, please check

**Comment by andypost** [comment]
@ncopa does it make sense to wait for 3.8 for next release? https://github.com/protocolbuffers/protobuf/releases/tag/v3.8.0-rc1

**Comment by andypost** [comment]
I think it bad idea to clean-up in process of update other packages

**Comment by TBK** [comment]
3.8.0 is out - https://github.com/protocolbuffers/protobuf/releases/tag/v3.8.0

**Comment by andypost** [comment]
> google/protobuf/map_field_test.cc:306:25: error: expected constructor, destructor, or type conversion before '(' token 
looks it needs to dig deeper

**Comment by TBK** [comment]
Try to build with googletest master - https://github.com/google/googletest/archive/master.tar.gz I suspect that protobuf relies on some of the newer changes in googletest which so far have not been released.

**Comment by wenerme** [comment]
1. better use a commit release not master, because the checksum will fail.
  * like https://github.com/alpinelinux/aports/pull/9161/files#diff-d30a24dcc25ccf6c2607381359261269R6
2. the unreleased archive structure is different, you should ln to keep the same name.
  * like https://github.com/alpinelinux/aports/pull/9161/files#diff-d30a24dcc25ccf6c2607381359261269R32

**Comment by andypost** [comment]
Fixed in fdcf4755 and later

**Pull request closed without merging**
