### PR TITLE
main/haproxy: upgrade to 1.9.8

### PR DESCRIPTION
**Pull request by andypost**
Ref http://www.haproxy.org/download/1.9/src/CHANGELOG

### CODE REVIEW

**Comment by andypost** [comment]
armv7 fails https://www.mail-archive.com/freebsd-pkg-fallout@freebsd.org/msg1217066.html

**Comment by andypost** [comment]
Armv7 fails in drone
> /usr/lib/gcc/armv7-alpine-linux-musleabihf/8.3.0/../../../../armv7-alpine-linux-musleabihf/bin/ld: src/fd.o: in function `fd_rm_from_fd_list': 
> fd.c:(.text+0x2a4): undefined reference to `_HA_ATOMIC_DWCAS'

**Comment by tcely** [comment]
See http://git.haproxy.org/?p=haproxy-1.9.git;a=patch;h=a4d80f898f63614ee523b301ad3a66c6ff37ee0a

**Comment by tcely** [comment]
`master` has version 2.

**Comment by andypost** [comment]
Looks it could be closed, no idea how to move it to musl back

**Pull request closed without merging**
