### PR TITLE
testing/lxd: upgrade to 2.9.1; fix dependencies.

### PR DESCRIPTION
**Pull request by vifino**
Hello.

To actually use LXD, you need to have a few things installed at runtime, like iptables/ip6tables, dnsmasq and LXC.

### CODE REVIEW

**Comment by jirutka** [comment]
lxd depends on `lxc-libs` (this is not explicitly declared in APKBUILD, because this dependency is automatically resolved from so libs), isn’t that sufficient?

**Comment by vifino** [comment]
It is not. 

LXD requires `/usr/lib/lxc` and `lxc-monitord` for example. I just tried it with just `lxc-libs`, it needs the full `lxc`.

**Comment by vifino** [comment]
Ah, I forgot. It lacks other deps to be usable, too. iptables/ip6tables and dnsmasq for sure, otherwise the networking is broken, `lxd init` doesn't work when creating a bridge, etc..

**Comment by vifino** [comment]
I also took the liberty of bumping the package to 2.9.1. Hope that's fine by you.

**Comment by vifino** [comment]
Bumped to 2.9.3.

**Comment by ncopa** [comment]
looks like this was merged

**Pull request closed without merging**
