### PR TITLE
unmaintained/leveldb: move from community

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by ncopa** [comment]
looks like ceph uses leveldb. we may need rebuild ceph with leveldb disabled

**Comment by maxice8** [comment]
Or poke the ceph maintainer into adopting leveldb

**Comment by maxice8** [comment]
@dx9

**Comment by TBK** [comment]
I will adopt leveldb.

**Comment by maxice8** [comment]
On Sat, May 25, 2019 at 07:05:58PM -0700, TBK wrote:
> I will adopt leveldb.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7798#issuecomment-495962111

have fun

**Pull request closed without merging**
