### PR TITLE
community/tcllib: new aport

### PR DESCRIPTION
**Pull request by tcely**
https://core.tcl.tk/tcllib
Tcl Standard Library

This is data for Tcl (Tool Command Language) that passes its tests.

### CODE REVIEW

**Comment by tcely** [comment]
@clandmeter Setting USER should not be needed, but DroneCI failed check without it.

**Comment by Ikke** [comment]
New aports should start in testing, not directly in community.

**Comment by tcely** [comment]
@Ikke NACK. Don't be pedantic. I'm not going to change this to `testing` just to immediately move it to `community` so this can be used in `checkdepends`.

**Comment by Ikke** [comment]
@ncopa Your opinion?

**Comment by Ikke** [comment]
@tcely FYI, I even adhere to this myself as well. I never add new packages directly to community, but first add them in testing, and when everything is alright, move it to community. This is something ncopa reaffirmed to me as policy.

**Comment by tcely** [comment]
@ikke you are welcome to add this to testing yourself. Get back to me when you decide it is worthy of community and it becomes useful. If you feel so strongly about gatekeeping then you do this pointless work and leave me out of it!

This hiearchy of repositories is ridiculous in my opinion and is a large source of problems in this project. I will not be participating in the pointless exercise of guiding this process!

**Comment by ncopa** [comment]
I guess we need to write a FAQ entry for this.

The original idea with testing was to give people a chance to test packages early. A user would ask for a package, a developer would build the package but would not test if it actually worked. So it was pushed to testing repository so the user who requested it could test if it actually ran.

This also helped us with the problem "it works when i build it locally, but not when its built with the official build servers".

With this in mind, it has made it easier to merge patches quicker, because we don't necessarily need to review to careful of testing stuff. When we move it to community or main, we do a second, more careful review and need to verify that it actually works. We want avoid that users of `edge/community` gets clearly broken stuff.

It does happen that we make exception to this, for example in case some package already in `community` introduce a new dependency.

Instead of expect that the already overworked patch reviewers does the digging work to figure out what this is all about you could have mentioned that this is a check dependency for `fossil` in the commit message, and then added the commit that adds it to the `community/fossil`. That would have helped the reviewer to see that this is a case where it make sense to make an exception.

**Comment by tcely** [comment]
@ncopa Please do write this out. It may eliminate the contradictory requirements that seem to be coming from nowhere.

**Comment by tcely** [comment]
@Ikke A better approach would have been to ask a question rather than to declare this is wrong.

**Pull request closed without merging**
