### PR TITLE
main/dovecot: security upgrade to 2.3.6

### PR DESCRIPTION
**Pull request by J0WI**
https://dovecot.org/pipermail/dovecot-news/2019-April/000406.html

### CODE REVIEW

**Comment by J0WI** [comment]
:ping_pong: @ncopa
See also #7147 #7148

**Comment by J0WI** [comment]
https://dovecot.org/list/dovecot-news/2019-April/000409.html
https://dovecot.org/list/dovecot-news/2019-April/000410.html

**Comment by J0WI** [comment]
Previous CI was broken, but this one works for sure. So :ping_pong: @ncopa again :)

**Comment by rnalrd** [comment]
Merged

**Comment by J0WI** [comment]
Thanks!

**Pull request closed without merging**
