### PR TITLE
main/fish: modernize

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Cogitri** [comment]
While you're at it: Maybe you could fix the broken deps on fish-tools I've introduced? One can use mdoc instead of man-db

**Comment by maxice8** [comment]
On Sat, May 25, 2019 at 04:49:33AM -0700, Rasmus Thomsen wrote:
> While you're at it: Maybe you could fix the broken deps on fish-tools I've introduced? One can use mdoc instead of man-db
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/8038#issuecomment-495911847

Done

**Comment by Cogitri** [comment]
Ah, but that will break it for people who use man-db instead of mdoc. Maybe we can depend on `cmd:man`? Not quite sure if that's really a good option though.

**Comment by tcely** [comment]
Be sure to show results from `apk -U add fish-tools`

**Comment by maxice8** [comment]
WFM, was able to run their generate_manpages python script

**Pull request closed without merging**
