### PR TITLE
main/kbd: generate (binary) keymaps from X.org keyboard-config

### PR DESCRIPTION
**Pull request by Shizmob**

### CODE REVIEW

**Comment by Shizmob** [comment]
This seems to lead to a severe size increase for the replacement package (~780kB -> ~17MB), due to having way more keymaps that are also more featureful...

**Comment by kaniini** [comment]
I think we should compress the keymaps.  Can you handle the setup-keymap changes too?

**Comment by ncopa** [comment]
I don't think it is an issue that it is a couple of megs. setup-keymap should make a copy of the selected keymap and then uninstall the package with all alternatives.

**Comment by jirutka** [comment]
> setup-keymap should make a copy of the selected keymap

This is IMO quite bad approach. Wouldn't it be better to split each keymap into a subpackage?

**Comment by Shizmob** [comment]
Copying is what we already do, for what it's worth.

**Comment by jirutka** [comment]
Uh, there are so many keymaps?!

**Comment by Shizmob** [comment]
As in my first reply, 475 of them. :)

**Comment by jirutka** [comment]
Okay, then I agree that splitting all of them to separate subpackages is very bad idea. XD

**Comment by Shizmob** [comment]
Relevant `setup-keymap` changes handled here: https://github.com/alpinelinux/alpine-conf/pull/5

**Pull request closed without merging**
