### PR TITLE
community/flatpak: enable on aarch64

### PR DESCRIPTION
**Pull request by tcely**
Addresses the build failure for alpinelinux/aports#8028

### CODE REVIEW

**Comment by Ikke** [comment]
@Cogitri Is there something changed that flatpak is now working on ppc64le? I see no explanation in the commit message. 

It was disabled in d7ecd27f9f without any explanation either.

**Comment by Cogitri** [comment]
I think you're talking about aarch64?

**Comment by Ikke** [comment]
@Cogitri Yes, sorry, not sure how I got to ppcl64le :confused:. I wonder why it was disabled and now seems to work again.

**Comment by Cogitri** [comment]
Hm, Sadly the commit msg doesn't tell us why it was broken :c

**Pull request closed without merging**
