### PR TITLE
main/xen: upgrade to 4.10.0

### PR DESCRIPTION
**Pull request by Elizafox**
Removed some obsolete patches as well.

### CODE REVIEW

**Comment by Elizafox** [comment]
Build failed because it exceeded the length due to being a large package:

>The log length has exceeded the limit of 4 MB

**Comment by kaniini** [comment]
It fails to build:

```
checking build system type... Invalid configuration `x86_64-alpine-linux-musl': machine `x86_64-alpine-linux' not recognized
configure: error: /bin/bash ./config.sub x86_64-alpine-linux-musl failed
```

**Comment by Elizafox** [comment]
Works for me, but note `abuild build` is not sufficient.

**Comment by kaniini** [comment]
please flatten

**Comment by Elizafox** [comment]
Flattened.

**Comment by kaniini** [comment]
the build still fails, because of gmp tarball being extracted during the build process

a possible solution may be to repack the gmp tarball

**Comment by HRio** [comment]
@kaniini @Elizafox something wrong here? musl-support.patch still included but not listed in APKBUILD.

Is it a mistake to still include the file or is the mistake not to rebase it for xen-4.10?

**Pull request closed without merging**
