### PR TITLE
testing/php7-spx: new aport

### PR DESCRIPTION
**Pull request by andypost**
https://github.com/NoiseByNorthwest/php-spx

### CODE REVIEW

**Comment by andypost** [comment]
```
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   12
---------------------------------------------------------------------

Number of tests :   20                11
Tests skipped   :    9 ( 45.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    1 (  5.0%) (  9.1%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   10 ( 50.0%) ( 90.9%)
---------------------------------------------------------------------
Time taken      :    7 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Flat profile: cycle depth [tests/spx_013.phpt]
=====================================================================
```

Failed test 
```
/mnt/testing/php7-spx $ cat  src/php-spx-0.4.0/tests/spx_013.log 

---- EXPECTED OUTPUT
*** SPX Report ***

Global stats:

  Called functions    :    38.6K
  Distinct functions  :        3

  ZE error count      :    38.6K

Flat profile:

 ZE error count      |
 Inc.     | *Exc.    | Called   | Function
----------+----------+----------+----------
    38.5K |    36.1K |    36.1K | 2@foo
    38.6K |     2.4K |     2.4K | 2@bar
    38.6K |        1 |        1 | %s/spx_013.php
---- ACTUAL OUTPUT
*** SPX Report ***

Global stats:

  Called functions    :    38.6K
  Distinct functions  :        3

  ZE error count      :    38.6K

Flat profile:

 ZE error count      |
 Inc.     | *Exc.    | Called   | Function
----------+----------+----------+----------
    38.6K |    36.2K |    36.2K | 2@foo
    38.6K |     2.4K |     2.4K | 2@bar
    38.6K |        1 |        1 | /mnt/testing/php7-spx/src/php-spx-0.4.0/tests/spx_013.php
---- FAILED
```

**Comment by andypost** [comment]
Looks it needs to separate `assets` to own package

**Comment by andypost** [comment]
Added fix for web_ui install https://github.com/NoiseByNorthwest/php-spx/pull/87
I see no reason to manage assets(UI) in separate package
- they are small
-- extension allows to enable use them dynamically

**Comment by NoiseByNorthwest** [comment]
@andypost let me know once all is ok, I will create a new minor release.

**Comment by andypost** [comment]
@NoiseByNorthwest it works great! makes sense to release 0.4.2

**Comment by NoiseByNorthwest** [comment]
@andypost nice! 0.4.2 released https://github.com/NoiseByNorthwest/php-spx/releases/tag/v0.4.2

**Comment by andypost** [comment]
@NoiseByNorthwest Filed https://github.com/alpinelinux/aports/pull/5570 and gonna commit after builders will stabilize after openssl switch

**Pull request closed without merging**
