### PR TITLE
main/protobuf: upgrade to 3.4.1

### PR DESCRIPTION
**Pull request by TBK**
ABI is not backward compatibility - https://abi-laboratory.pro/tracker/timeline/protobuf/

### CODE REVIEW

**Comment by nmeum** [comment]
> ABI is not backward compatibility

In that case you should trigger a rebuild of all packages depending on protobuf by bumping their `pkgrel`.

**Comment by TBK** [comment]
@nmeum Thanks for the advice. I was in doubt of the procedure :)

I will fix that straight away.

**Comment by nmeum** [comment]
Sorry, for not being clear on this. When rebuild packages you should add a new commit for every rebuild. The commit message of the rebuild commits should be `${repository}/${pkgname}: rebuild against protobuf 3.4.1`

**Comment by jirutka** [comment]
If you don't have a strong reason for merging this before branching v3.7, I'd postpone this after v3.7, we're in freeze state now.

**Comment by ncopa** [comment]
we updated to 3.4.1. thanks!

**Pull request closed without merging**
