### PR TITLE
community/php7-pecl-couchbase: move from testing, rename, modernize

### PR DESCRIPTION
**Pull request by andypost**
Part of https://bugs.alpinelinux.org/issues/9277

`igbinary` is detected compile time so better to add dependency & get binary protocol bundled

`checking for igbinary support... /usr/include/php7`

`re2c` is needed mostly to every PECL extension https://github.com/docker-library/php/pull/88
```
checking for re2c... re2c
checking for re2c version... 1.0.2 (ok)
```

### CODE REVIEW

**Comment by andypost** [comment]
@nathanejohnson are you ok with this changes?

**Comment by andypost** [comment]
Probably it needs `provides="php7-couchbase"` for compatibility

**Comment by nathanejohnson** [comment]
@andypost this looks good to me, curious though why did you remove the running of the unit tests?

**Comment by andypost** [comment]
I did not removed) I just explained that unittests are not packaged in pecl so nothing to run

**Comment by jirutka** [comment]
> Probably it needs provides="php7-couchbase" for compatibility

This and also replaces:

```sh
provides="php7-couchbase=$pkgver-r$pkgrel"  # for backward compatibility
replaces="php7-couchbase"  # for backward compatibility
```

Also please split it into at least two commit - move into the community repo as a separate commit.

**Comment by andypost** [comment]
@jirutka please check fixes, it looks good to go

**Comment by andypost** [comment]
Commited as d8aaad54939a05f26bfcf4ea03b9523e74cdb56d 0b51cdda2778ca9fef1c3fe08bde9271179f2cdb

**Pull request closed without merging**
