### PR TITLE
testing/libbytesize: upgrade to 2.0

### PR DESCRIPTION
**Pull request by maxice8**
- Add !check
- Add libbytesize-tools
- Update dependencies to use pcre2
- Add missing py3-six to py-$pkgname

### CODE REVIEW

**Comment by maxice8** [comment]
@misery

**Comment by misery** [comment]
Looks good to me!

**Comment by Ikke** [comment]
@maxice8 Can you rebase this? Seems like @misery already pushed the upgrade to 2.0.

**Comment by maxice8** [comment]
On Fri, May 10, 2019 at 12:07:48PM -0700, Kevin Daudt wrote:
> @maxice8 Can you rebase this? Seems like @misery already pushed the upgrade to 2.0.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7441#issuecomment-491399036

Done, please wait until CI oks

**Comment by misery** [comment]
Oh, sorry. Ich forgit it. Will look into this later.

**Pull request closed without merging**
