### PR TITLE
testing/llvm6: new aport

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
Let's see if Drone can build it...

**Comment by J0WI** [comment]
@ncopa LLVM 8 is scheduled for tomorrow. Could you give this and #5717 a chance?

**Comment by ncopa** [comment]
fixed with db695fa462a77934f2c6f4ee835ad46963ad35c2

**Comment by ncopa** [comment]
fixed with db695fa462a77934f2c6f4ee835ad46963ad35c2

**Pull request closed without merging**
