### PR TITLE
main/py-sphinx_rtd_theme: upgrade to 0.4.0

### PR DESCRIPTION
**Pull request by misery**

### CODE REVIEW

**Comment by misery** [comment]
Any chance to get this merged before 3.8?

**Comment by misery** [comment]
@fabaff is it ok for you?

**Comment by misery** [comment]
Could it be merged to 3.8?

**Comment by ncopa** [comment]
> Could it be merged to 3.8?

yes. I have backported it: a8d28b4f94e1952cf075c355504af6bad87b4d81

**Pull request closed without merging**
