### PR TITLE
main/unfs3: modernize APKBUILD

### PR DESCRIPTION
**Pull request by HRio**

### CODE REVIEW

**Comment by HRio** [comment]
Travis problem
```
==> Downloading apk-tools-static
--2017-06-23 19:08:59--  http://nl.alpinelinux.org/alpine/v3.5/main/x86_64/apk-tools-static-2.6.8-r2.apk
Resolving nl.alpinelinux.org (nl.alpinelinux.org)... 88.159.20.184
Connecting to nl.alpinelinux.org (nl.alpinelinux.org)|88.159.20.184|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-06-23 19:09:00 ERROR 404: Not Found.
The command "sudo .travis/install-alpine" failed and exited with 8 during .
```

**Comment by jirutka** [comment]
Please rebase it against the current master and force push.

**Comment by HRio** [comment]
@jirutka, OK  but new problem

```
Saving to: `apk-tools-2.7.2-x86_64-linux.tar.gz'
100%[======================================>] 812,272     1.58M/s   in 0.5s    
2017-06-23 21:00:27 (1.58 MB/s) - `apk-tools-2.7.2-x86_64-linux.tar.gz' saved [812272/812272]
sha256sum: apk-tools-2.7.2-x86_64-linux.tar.gz): No such file or directory
apk-tools-2.7.2-x86_64-linux.tar.gz): FAILED open or read
sha256sum: WARNING: 1 listed file could not be read
```

**Comment by HRio** [comment]
@jirutka 

```
-wget "$APK_TOOLS_URI"
-echo "$APK_TOOLS_SHA256  $(basename "$APK_TOOLS_URI")" | sha256sum -c
-tar -xzf $(basename "$APK_TOOLS_URI")
+wget -T 10 "$APK_TOOLS_URI"
+echo "$APK_TOOLS_SHA256  ${APK_TOOLS_URI##*/})" | sha256sum -c
+tar -xzf ${APK_TOOLS_URI##*/}
+mv apk-tools-*/apk apk
```

extra )

**Comment by jirutka** [comment]
Uh, sorry for this mistake, I’ve fixed it now.

**Comment by HRio** [comment]
@jirutka thanks, now it passes.

**Pull request closed without merging**
