### PR TITLE
community/openjdk[9,10,11]: Enhance and unify APKBUILDs

### PR DESCRIPTION
**Pull request by bratkartoffel**
Enhance and unify APKBUILDs for java builds. Add patches to enable 32 bit builds sometime later.
Travis / drone will fail on this, as the builds take too long.

### CODE REVIEW

**Comment by Cogitri** [comment]
> openjdk11: Checking sha512sums...
jdk-11.0.4+11.tar.bz2: OK
build.patch: FAILED
sha512sum: WARNING: 1 of 1 computed checksums did NOT match

**Comment by Cogitri** [comment]
Mind fixing the merge conflict? Then I'll merge.

**Comment by bratkartoffel** [comment]
Sure, just give me a few minutes

**Comment by bratkartoffel** [comment]
Done, I've also indented the source and makedepends fields and updated the licence to match spdx licence format

**Comment by Cogitri** [comment]
Great, thanks. Just gonna let CI run/timeout again

**Comment by Cogitri** [comment]
I guess we should solve the aarch64 build failure of OpenJFX 11 first

**Comment by bratkartoffel** [comment]
> I guess we should solve the aarch64 build failure of OpenJFX 11 first
OpenJFX is not really related to this package here. I'd suggest the other way round, first enable all archs on openjdk, then taking care of openjfx

**Comment by ncopa** [comment]
Do we really want to enable 32 bit builds? It does not look like Oracle supports 32 bit.
https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms

I know for sure that I will not have the capacity to provide any support for it.

**Comment by bratkartoffel** [comment]
You're right, Natanael, it seems that oracle has finally dropped 32 bit support with all java releases greater than 8. There are other vendors, which still ship 32 bit builds (e.g. [adoptopenjdk](https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot)) but I think we can leave them out for now until someone wants them.
I'll change the commit and disable 32 bit again, but I still want the patches to be included here. They weren't that easy to write and may help someone later to add 32 bit builds.

**Pull request closed without merging**
