### PR TITLE
testing/nomad: new aport

### PR DESCRIPTION
**Pull request by mtneug**
Add [Nomad](https://www.nomadproject.io/).

### CODE REVIEW

**Comment by maxice8** [comment]
```
testing/nomad: new aport

$pkgdesc
$url
```

**Comment by maxice8** [comment]
Is python2 really  required ? it is soon to be EOL

**Comment by mtneug** [comment]
No, it's not. Python 3 also works fine. Thanks for pointing this out. I also updated the init script and removed the custom PID file.

**Comment by mtneug** [comment]
I spoke too soon. On `x86_64`, where I primarily test, it is working probably because the build output is downloaded instead of generated. For creating the build output on other platforms, however, the dependency [node-gyp](https://github.com/nodejs/node-gyp) currently only support Python 2.

**Pull request closed without merging**
