### PR TITLE
testing/grpc: upgrade to 1.19.1

### PR DESCRIPTION
**Pull request by andypost**
- https://github.com/grpc/grpc/releases/tag/v1.19.1
- https://github.com/grpc/grpc-java/releases

### CODE REVIEW

**Comment by andypost** [comment]
@wenerme are you ok with upgrade?

**Comment by andypost** [comment]
failure on travis expected

**Comment by wenerme** [comment]
Sorry for the delay, I lost my build env, I just setup and build success in my local. This is the same error as last time.

**Comment by andypost** [comment]
@wenerme please check java pr it looks strange that it require nss to build https://github.com/alpinelinux/aports/issues/6812

**Pull request closed without merging**
