### PR TITLE
testing/kde-frameworks: update to 5.59.0

### PR DESCRIPTION
**Pull request by PureTryOut**
I very much doubt this will succeed in the CI within the output or 1 hour time limit.

The previous `-DCMAKE_BUILD_TYPE=RelWithDebugInfo` was incorrect and an invalid value, it should be `-DCMAKE_BUILD_TYPE=RelWithDebInfo`.

### CODE REVIEW

**Comment by Ikke** [comment]
Current test failures don't seem to be due to time. It might be that the community package is causing trouble (while the rest is in testing).

**Comment by PureTryOut** [comment]
```
CMake Warning at CMakeLists.txt:7 (find_package):
  Could not find a configuration file for package "ECM" that is compatible
  with requested version "5.59.0".

  The following configuration files were considered but not accepted:

    /usr/share/ECM/cmake/ECMConfig.cmake, version: 5.58.0



-- 
 * ECM (required version >= 5.59.0), Extra CMake Modules., <https://projects.kde.org/projects/kdesupport/extra-cmake-modules>

CMake Error at /usr/share/cmake/Modules/FeatureSummary.cmake:457 (message):
  feature_summary() Error: REQUIRED package(s) are missing, aborting CMake
  run.
Call Stack (most recent call first):
  CMakeLists.txt:9 (feature_summary)
```

You're right, for some reason it doesn't pick up `extra-cmake-modules`. It did build that one successfully though, why would it matter being in a different repository? As long as it's not community depending on something from testing, this should work should it not?

**Comment by maxice8** [comment]
is it OK to have everything in a single commit ?

**Comment by PureTryOut** [comment]
I mean, we've done that with Qt updates and other stuff before. I'm not really willing to do 81 separate commits every month KDE Frameworks updates.

**Comment by maxice8** [comment]
> I mean, we've done that with Qt updates and other stuff before.

Sounds fine by me then.

**Pull request closed without merging**
