### PR TITLE
main/jsoncpp: upgrade to 1.8.3 and switch to meson

### PR DESCRIPTION
**Pull request by misery**

### CODE REVIEW

**Comment by misery** [comment]
Any chance for Alpine v3.7?

**Comment by jirutka** [comment]
I’d rather merge it after v3.7 is released. Do you have some strong reason to merge it into v3.7?

**Comment by misery** [comment]
Thanks.... no, it's fine for me! :-) Maybe someone could bump cmake to 3.9.6 for Alpine v3.7. It's a minor bugfix.

**Comment by misery** [comment]
https://github.com/alpinelinux/aports/pull/2864 for cmake 3.9.6

**Comment by misery** [comment]
Well, first changeset was added... but why not the others?

**Pull request closed without merging**
