### PR TITLE
testing/py-google-auth: new aport

### PR DESCRIPTION
**Pull request by Lunik**
Project: https://pypi.org/project/google-auth/
Source code: https://github.com/googleapis/google-auth-library-python

Require: "main/py-cachetools: new aport" #6388

### CODE REVIEW

**Comment by fcolista** [comment]
Hi @Lunik 
New aports go to testing first, not on main.
Thanks!

.: Francesco

**Comment by Lunik** [comment]
The requested change have been made

**Comment by maxwell-k** [comment]
I opened a pull request to add a similar package https://github.com/alpinelinux/aports/pull/7100 ; 

From first glance the differences are that one has checks enabled and includes all of the dependencies from https://github.com/googleapis/google-auth-library-python/blob/master/setup.py#L21

Sorry for any duplication of effort

**Comment by maxwell-k** [comment]
google-auth is now available as [py3-google-auth](https://pkgs.alpinelinux.org/packages?name=py3-google-auth&branch=edge), it was merged in #7100 . Sorry again about any duplication of effort.

I think this PR can be closed, as the package has effectively been merged.

Thank you for your help!

**Pull request closed without merging**
