### PR TITLE
testing/py-cachetools: new aport

### PR DESCRIPTION
**Pull request by Lunik**
Project: https://pypi.org/project/cachetools/
Source code: https://github.com/tkem/cachetools/

### CODE REVIEW

**Comment by fcolista** [comment]
Hi @Lunik 
New aports go to testing first, not on main.
Thanks!

.: Francesco

**Comment by Lunik** [comment]
The requested change have been made

**Comment by maxice8** [comment]
Added to the repos in the process of adding the `poetry` package.

Sorry i didn't notice this when adding the dependencies of `poetry`

**Comment by Ikke** [comment]
Closing this PR.

**Pull request closed without merging**
