### PR TITLE
testing/assimp: upgrade to 5.0.0

### PR DESCRIPTION
**Pull request by russkel**
Patched issue was reported last version, but it wasn't actually fixed. https://github.com/assimp/assimp/issues/2732

### CODE REVIEW

**Comment by Cogitri** [comment]
Feel free to request a review once you've fixed that

**Comment by russkel** [comment]
Hi @Cogitri - requesting that review. I couldn't see the button to request a review (if there is one)

**Comment by Cogitri** [comment]
Ah, sure. Will try to look at it in a bit, currently busy :)

**Comment by russkel** [comment]
Take your time :)

**Comment by Cogitri** [comment]
LGTM, can you take a look @maxice8 ?

**Pull request closed without merging**
