### PR TITLE
community/libreoffice: upgrade to 6.3.2

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by Cogitri** [comment]
Ah, didn't see this. Could you please do some style fixes (move `depends_dev` to makedepends since there's no -dev subpackage) and also do what `apkbuild-lint` wants?

**Comment by Cogitri** [comment]
Also, should we maybe add an `install_if` to libreoffice-gnome which automatically installs it if gtk3 is installed?

**Comment by Cogitri** [comment]
Thank you

**Comment by J0WI** [comment]
> Also, should we maybe add an `install_if` to `libreoffice-gnome` which automatically installs it if `gtk3` is installed?

Does Alpine Linux have a guideline for this? Maybe people just want to use the cli, even if `gtk3` is present on their system.

**Comment by Cogitri** [comment]
Possibly, it just annoyed me a bit that I thought we didn't have the gtk3 version enabled at first only to find out it's just not installed after a few hours.

**Comment by J0WI** [comment]
btw `libreoffice` depends on `libreoffice-common` which depends on `gtk+3.0`. So `libreoffice-gnome` would always be installed. Maybe `*-desktop` would be a better condition?

**Comment by Cogitri** [comment]
A -desktop doesn't really make sense since LO also offers a Qt5 and KDE5 interface so the desktop subpackage would be kind of confusing IMHO.

**Comment by Cogitri** [comment]
Maybe it'd make sense to not split the gnome (gtk3) since it's pretty small (compared to LO's size) and GTK3 is the default interface

**Comment by Cogitri** [comment]
Merged as c1bf371130005e3e21c7d9aa815aa7a33645bb03, e8aab477f3c8c716ddd3dde2e36c9154b7bd6e86, thank you

**Pull request closed without merging**
