### PR TITLE
main/memcached: upgrade to 1.5.15

### PR DESCRIPTION
**Pull request by andypost**
Ref https://github.com/memcached/memcached/wiki/ReleaseNotes1515

### CODE REVIEW

**Comment by andypost** [comment]
@maxice8 is it ok to remove builddir in main?

**Comment by maxice8** [comment]
Yes, cd "$builddir" is that is not ok.

cd "$builddir" is in version 3.3.0 of abuild
builddir="$srcdir/$pkgname-$pkgver" is in version 2.29.0

**Comment by andypost** [comment]
@tcely reverted `cd` lines

**Comment by ncopa** [comment]
superseded by 961a24b5c593b8e1ec018e6b0b4b195c0e1e4e66

**Pull request closed without merging**
