### PR TITLE
community/firefox-esr: security upgrade to 68.2.0, rebuild with clang 9, enable aarch64

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by Cogitri** [comment]
A bit busy compiling libreoffice right now, so does this work for you locally?

**Comment by J0WI** [comment]
Firefox is compatible with latest LLVM, but I don't have the capacity to build this locally.

**Comment by Cogitri** [comment]
Alrighty. Will test locally then now that LO is done.

**Comment by Cogitri** [comment]
Fails for me, maybe the same patch as for thunderbird will fix it:

```
error[E0506]: cannot assign to `self.input.cached_token` because it is borrowed
   --> /home/rasmus/aports/community/firefox-esr/src/firefox-68.1.0/third_party/rust/cssparser/src/parser.rs:584:17
    |
559 |     pub fn next_including_whitespace_and_comments(&mut self) -> Result<&Token<'i>, BasicParseError<'i>> {
    |                                                   - let's call the lifetime of this reference `'1`
...
572 |             Some(ref cached_token)
    |                  ---------------- borrow of `self.input.cached_token` occurs here
...
584 |                 self.input.cached_token = Some(CachedToken {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.input.cached_token` occurs here
...
596 |         Ok(token)
    |         --------- returning this value requires that `self.input.cached_token.0` is borrowed for `'1`

/usr/bin/gcc -std=gnu99 -o blend_a64_vmask_sse4.o -c  -I/home/rasmus/aports/community/firefox-esr/src/firefox-68.1.0/objdir/dist/system_wrappers -include /home/rasmus/aports/community/firefox-esr/src/firefox-68.1.0/config/gcc_hidden.h -DNDEBUG=1 -DTRIMMED=1 -DSTATIC_EXPORTABLE_JS_API -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -I/home/rasmus/aports/community/firefox-esr/src/firefox-68.1.0/media/libaom -I/home/rasmus/aports/community/firefox-esr/src/firefox-68.1.0/objdir/media/libaom -I/home/rasmus/aports/community/firefox-esr/src/firefox-68.1.0/media/libaom/config/linux/x64 -I/home/rasmus/aports/community/firefox-esr/src/firefox-68.1.0/media/libaom/config -I/home/rasmus/aports/community/firefox-esr/src/firefox-68.1.0/third_party/aom -I/home/rasmus/aports/community/firefox-esr/src/firefox-68.1.0/objdir/dist/include -I/usr/include/nspr -I/usr/include/nss -I/home/rasmus/aports/community/firefox-esr/src/firefox-68.1.0/objdir/dist/include/nss -I/usr/include/pixman-1 -fPIC -include /home/rasmus/aports/community/firefox-esr/src/firefox-68.1.0/objdir/mozilla-config.h -DMOZILLA_CLIENT -Os -fomit-frame-pointer -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Os -fomit-frame-pointer -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -fPIC -pipe -g -Os -fomit-frame-pointer -O2 -fomit-frame-pointer -funwind-tables -Wall -Wempty-body -Wignored-qualifiers -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Wduplicated-cond -Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=coverage-mismatch -Wno-error=free-nonheap-object -Wno-error=multistatement-macros -Wno-error=class-memaccess -Wno-error=deprecated-copy -Wformat -Wformat-security -Wformat-overflow=2 -Wno-sign-compare -Wno-unused-function  -MD -MP -MF .deps/blend_a64_vmask_sse4.o.pp  -msse4.1 /home/rasmus/aports/community/firefox-esr/src/firefox-68.1.0/third_party/aom/aom_dsp/x86/blend_a64_vmask_sse4.c
media/libaom/fft_avx2.o
error: aborting due to previous error

For more information about this error, try `rustc --explain E0506`.
error: Could not compile `cssparser`.
```

**Comment by J0WI** [comment]
@Cogitri could you give it a try?

**Comment by J0WI** [comment]
It's hard to backport the changes to `60.x`...

**Pull request closed without merging**
