### PR TITLE
testing/openjdk11: New aport

### PR DESCRIPTION
**Pull request by bratkartoffel**
This PR adds openjdk11 (LTS) to alpine.

### CODE REVIEW

**Comment by Ikke** [comment]
Duplicate of #6469

**Comment by J0WI** [comment]
WFM on x86_64

**Comment by bratkartoffel** [comment]
@Ikke Yes, this is a duplicate, but the patches are based on these from openjdk9 and 10. Will take a look at @hjaekel though.

**Comment by J0WI** [comment]
`v3.10.0_rc1` has been tagged, but so far without any new OpenJDK version in community

**Pull request closed without merging**
