### PR TITLE
testing/simple-scan: upgrade to 3.32.2

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by Cogitri** [comment]
Build fails because it can't pull in colord :c

**Comment by tcely** [comment]
`sane-dev` is in `testing` and would need to move to `community` to be used by `colord`

**Comment by Cogitri** [comment]
Oh right. Would be nice if abuild sanity check or smth would warn on this, I guess

**Comment by tcely** [comment]
```
sane: Analyzing dependencies...
--
39 | ERROR: unsatisfiable constraints:
40 | libieee1284-dev (missing):
41 | required by: .makedepends-sane-0[libieee1284-dev]
```

**Comment by Cogitri** [comment]
Fixed; thanks!

**Comment by TBK** [comment]
@Cogitri Should libieee1284 be added as a make depend to sane?

**Comment by Cogitri** [comment]
Eh? It already is a makedepend, see line 25 @TBK. I thinkthis is good to go, only simple-scan fails to compile and that only because it can't find colord VAPI (which I've enabled in this PR).

**Comment by tcely** [comment]
> I thinkthis is good to go, only simple-scan fails to compile and that only because it can't find colord VAPI (which I've enabled in this PR).

This is another case of https://github.com/alpinelinux/abuild/pull/53 problems. The package from `testing` won't use the packages built in `community` until that PR lands. So moving everything to `community` fixes the build.

**Comment by Cogitri** [comment]
Yup. I guess I can simplescan to community too.

**Comment by TBK** [comment]
> Eh? It already is a makedepend, see line 25 @TBK. I thinkthis is good to go, only simple-scan fails to compile and that only because it can't find colord VAPI (which I've enabled in this PR).

My bad, overlooked it.

**Comment by Cogitri** [comment]
Ah, alright :)

**Pull request closed without merging**
