### PR TITLE
testing/kubernetes: modernize

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
@fcolista

**Comment by fcolista** [comment]
What's the point of adding check() if the check is ignored due to  options="!check"  ?

**Comment by maxice8** [comment]
So in a future version you don't need to add it once someone fixes the tests, it is already there.

**Comment by fcolista** [comment]
It might happen, or not. Better to add the check when is actually used.
Avoids confusion.
Thanks.

**Comment by maxice8** [comment]
On Sun, May 26, 2019 at 11:25:07PM -0700, Francesco Colista wrote:
> It might happen, or not. Better to add the check when is actually used.
> Avoids confusion.
> Thanks.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/8115#issuecomment-496093558
Removed

**Pull request closed without merging**
