### PR TITLE
Move OCaml packages to community

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by jirutka** [comment]
@ncopa These packages have been merged into testing just few hours ago. Why so rush with moving them to community, evidently without proper testing before? It even does not build on all specified archs. :(

**Comment by ncopa** [comment]
i wanted them in for v3.5. i thought it built on armhf when it was in testing.

**Comment by avsm** [comment]
Sorry, these built for me under aarch64, but I didnt try x86_32.  What is the current test matrix failure?

**Comment by dysinger** [comment]
This is needed for raspberry pi ocaml (docker qemu or actual hardware)

**Pull request closed without merging**
