### PR TITLE
main/unbound: upgrade to 1.7.0

### PR DESCRIPTION
**Pull request by tcely**

### CODE REVIEW

**Comment by tcely** [comment]
> unbound-dev: libevent-dev needs to be rebuilt

**Comment by nmeum** [comment]
> unbound-dev: libevent-dev needs to be rebuilt

Why?

**Comment by tcely** [comment]
@nmeum It looks like something went wrong with tracing dependencies.

https://github.com/alpinelinux/abuild/blob/master/abuild.in#L1214

`libevent-dev` should have been found from what I can see for `pc:libevent` so that the else block shouldn't be emitting that message.

**Comment by tcely** [comment]
See https://github.com/alpinelinux/aports/pull/3814

**Pull request closed without merging**
