### PR TITLE
testing/openjdk9: new aport

### PR DESCRIPTION
**Pull request by hjaekel**
New aport OpenJDK 9. This is a prerequisite for #6468 as OpenJDK 9 is needed as a bootstrap JDK for building OpenJDK 10. 

As OpenJDK 9 does not receive security updates from upstream, this aport should be deleted as soon as OpenJDK 10 is successfully build on all platforms.

I could only test this build on x86_64, I hope that it builds on all other platforms.

### CODE REVIEW

**Comment by hjaekel** [comment]
I got some remarks from @clandmeter on IRC:

* [16:33:02] &lt;clandmeter&gt; hjaekel: you also need update_config_sub
[16:44:55] &lt;clandmeter&gt; normally in prepare
* [16:39:56] &lt;clandmeter&gt; hjaekel: do you need to overide the unpack function?
[16:46:47] &lt;clandmeter&gt; do that in prepare
[16:46:57] &lt;clandmeter&gt; and append default_prepare
* [16:48:27] &lt;clandmeter&gt; there are also some whitespace issues

**Comment by J0WI** [comment]
See also #6179

**Comment by ncopa** [comment]
This is a duplicate of #6179

**Comment by ncopa** [comment]
I merged #6179 due to it worked on more architectures. It would be nice if you could add your crypto testcases.

**Pull request closed without merging**
