### PR TITLE
community/alacritty: more arches

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by Cogitri** [comment]
What's holding this up?

**Comment by J0WI** [comment]
I was just waiting for CI to pass

**Comment by Cogitri** [comment]
Ah okie, since this was a Draft PR previously I didn't look at it.

**Comment by Cogitri** [comment]
8583b381ba6c7617d811af782748e7409b88476c huh, dunno what's up with algitbot

**Pull request closed without merging**
