### PR TITLE
testing/thunderbird: upgrade to 60.9.0

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by Cogitri** [comment]
Seems like the patches don't apply

**Comment by Cogitri** [comment]
I don't mean to sound rude, but could you please ensure that the package works for you before you make a PR (or make it a draft first)

**Comment by J0WI** [comment]
Sorry, the last commit contained some garbage. This is now fixed.

**Comment by J0WI** [comment]
You may prefer #11916 which contains additional changes.

**Comment by Cogitri** [comment]
Yup, closing

**Pull request closed without merging**
