### PR TITLE
main/protobuf: upgrade to 3.8.0 &  testing/grpc: upgrade to 1.21.3 &  community/grpc: move from testing & community/gflag: move from testing

### PR DESCRIPTION
**Pull request by wenerme**

### CODE REVIEW

**Comment by wenerme** [comment]
Build grpc failed because 

Installing protobuf (3.6.1-r1)

Need to install newer version in this pr.

**Comment by ncopa** [comment]
dupe of #6848

**Comment by wenerme** [comment]
should I close this pr ?

**Comment by ncopa** [comment]
I get the following error:
````
[INSTALL] Installing libgrpc_unsecure.a
[STRIP]   Stripping libgrpcpp_channelz.a
make: execvp: /bin/sh: Argument list too long
make: *** [Makefile:2985: install-headers_cxx] Error 127
>>> ERROR: grpc*: package failed
>>> ERROR: grpc: rootpkg failed
````

**Comment by wenerme** [comment]
@ncopa this is the same error https://github.com/alpinelinux/aports/pull/5893#issuecomment-449621664 , the error is expected, not affect the real build.

**Comment by ncopa** [comment]
> @ncopa this is the same error [#5893 (comment)](https://github.com/alpinelinux/aports/pull/5893#issuecomment-449621664) , the error is expected, not affect the real build.

I think it affects real build. I added a simple patch for it: ae758ca47680934eb757dc1a3e28740097dd3695

I merged it and rebuilt the needed packages.

**Pull request closed without merging**
