### PR TITLE
community/openexr: re-add, add maintainer, clean up

### PR DESCRIPTION
**Pull request by Klowner**

### CODE REVIEW

**Comment by jirutka** [comment]
Do you use it? If you’ve checked that it works, then we should move it to the community repo.

**Comment by Klowner** [comment]
Yep, it works. I built Blender against it and successfully rendered to an EXR file.

**Comment by Klowner** [comment]
Changed to community/openexr

**Comment by Klowner** [comment]
moving testing/ilmbase to community as well, since it is a dependency

**Pull request closed without merging**
