### PR TITLE
community/cmark: upgrade to 0.29.0

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
@maribu

**Comment by maribu** [comment]
@maxice8: Sorry, I do not have any permission to merge or review to the alpine repos. However, I can confirm that `APKBUILD` works and it looks good to me (whatever this is worth).

I'm no longer using `cmark` personally and would have to rely on users flagging it out of date to update the package. So if you would like to adopt the package, this would be wonderful.

**Comment by maxice8** [comment]
>  Sorry, I do not have any permission to merge or review to the alpine repos. However, I can confirm that APKBUILD works and it looks good to me (whatever this is worth).

No worries, i just tag the maintainer whether i update.

> I'm no longer using cmark personally and would have to rely on users flagging it out of date to update the package. So if you would like to adopt the package, this would be wonderful.

Sure i'll push with adoption changes.

**Comment by maxice8** [comment]
re-pushed with change of maintainership

**Pull request closed without merging**
