### PR TITLE
testing/nginx-naxsi: update to 1.13.8

### PR DESCRIPTION
**Pull request by itoffshore**
* add `sysguard.conf` to the sysguard module
* fixes `${SVCNAME}` => `${RC_SVCNAME}` in `initd`
* add `server_tokens off;` to `default.conf`

https://nginx.org/en/CHANGES

### CODE REVIEW

**Comment by itoffshore** [comment]
please pull - `nginx-naxsi` has `PaX` protections enabled

**Comment by jirutka** [comment]
> nginx-naxsi has PaX protections enabled

I'm confused now, why did you mention this?

**Comment by itoffshore** [comment]
only because the previous  `PR` was waiting for 24 days - so long a rebase for the latest version included a massive merge to fix a merge conflict on github (hence the new clean `PR`)

Am just highlighting there is a major difference between `nginx-naxsi` & the version in main (I also have anonymization recommendations from caromel.org & some servers disabled)

**Comment by itoffshore** [comment]
ok - I understand the holdup now https://github.com/libressl-portable/portable/issues/307

**Comment by Shizmob** [comment]
Could you maybe bring this in line with the [current nginx APKBUILD](https://github.com/alpinelinux/aports/blob/master/main/nginx/APKBUILD), with the tests and the like?

**Comment by jirutka** [comment]
@Shizmob, I’d like to add the modules that @itoffshore actually needs to the main/nginx and eventually remove this package.

**Comment by itoffshore** [comment]
I'd like `PaX` **not** to be disabled on `main/nginx` - but I know it breaks the `lua` module

if `PaX` cannot be enabled I would like to continue with `nginx-naxsi` - or perhaps rename it to `nginx-pax` & track the latest version of `nginx` (not stable)

**Comment by Shizmob** [comment]
Can't we build the Lua module as a separate `.so` and apply the PaX mark to that specific file?

**Comment by jirutka** [comment]
It’s trivial to re-enable PaX MPROTECT for nginx binary after installation (just `paxmark M /usr/sbin/nginx`). Isn’t that sufficient for you? I’m not sure if it’s really worth it to overcomplicate this nginx package or maintain separate package just because of this.

> Can't we build the Lua module as a separate .so and apply the PaX mark to that specific file?

We build Lua module as a dynamic module, so it is a separate `.so` file. I’m not sure if it’d be sufficient to disable MPROTECT just for `ngx_http_lua_module.so`, but don’t remember if I’ve tried it or not.

**Comment by jirutka** [comment]
Hm, what about paxmarking nginx module after installation, using post-install script associated with the Lua module?

**Comment by Shizmob** [comment]
That would likely be better in my opinion, if just PaX-marking the Lua module does not suffice -- but I would like to try that approach first.

**Comment by jirutka** [comment]
@itoffshore Do I understand correctly that you don’t use any extra module from this package anymore, so we don’t need to add them into main/nginx? Not saying that I don’t wanna add them, but IIRC some of these modules were not in very good condition, some needs patching nginx etc.

**Comment by itoffshore** [comment]
I use `naxsi` & `sysguard` - both of these should be in good shape (I ported `sysguard` from the current `tengine` sources) - `ngx_cache_purge` is still maintained & the author of `upstream-fair` [sent a `PR` a few weeks ago with an `openssl` fix](https://github.com/itoffshore/nginx-upstream-fair/releases).

**Comment by itoffshore** [comment]
you could also just pull this - I am quite happy maintaining a lighter `nginx` with `PaX` enabled + anonymization patch

**Pull request closed without merging**
