### PR TITLE
main/openrc: allow rsa and ed25519 SSH keys in firstboot.init

### PR DESCRIPTION
**Pull request by tuan-hoang1**
The kernel parm could be like:
ssh_key=rsa:< key content >
ssh_key=ed25519:< key content >

### CODE REVIEW

**Comment by tuan-hoang1** [comment]
cc @clandmeter

**Comment by ncopa** [comment]
Why not just do: `ssh_key="ssh-rsa <key content>"` and `ssh_key="ssh-ed25519 <key content>"`

**Comment by tuan-hoang1** [comment]
don't close bot

**Comment by tuan-hoang1** [comment]
Will find some time to work on this ....

**Comment by maxice8** [comment]
ping

**Pull request closed without merging**
