### PR TITLE
main/gpsd fix PPS functionality

### PR DESCRIPTION
**Pull request by pavel-demin**
This patch fixes the PPS functionality that is currently broken in Alpine 3.8.

### CODE REVIEW

**Comment by pavel-demin** [comment]
Since you aren't accepting this pull request, do you have plans to fix this problem yourself?

**Comment by rnalrd** [comment]
Sorry I forgot to comment.
I did not realize it was for AL3.8. How about 3.9 and edge? Does it work? The patch does not apply, that's why I closed it.

**Comment by pavel-demin** [comment]
The PPS functionality is still broken in 3.9 and edge.

Looks like there were some commits to main/gpsd after I created this pull request. I've just merged them to my fork and updated the patch: https://github.com/pavel-demin/aports/commit/c442025b06b3d8d2461adf02d1e0c9dc0661d877.

Should I create a new pull request with the updated patch?

**Comment by rnalrd** [comment]
If it applies to all branches affected there's no need for that. Otherwise please create a separate PR for each branch.

Thanks!

--
Sent from mobile

Il giorno 8 feb 2019, 13:13, alle ore 13:13, Pavel Demin <notifications@github.com> ha scritto:

**Comment by pavel-demin** [comment]
Thanks for the instructions.

I've just created two new pull requests for master and 3.9-stable:

https://github.com/alpinelinux/aports/pull/6262
https://github.com/alpinelinux/aports/pull/6263

**Comment by rnalrd** [comment]
Can you pls bump pkgrel? Thanks!

**Pull request closed without merging**
