### PR TITLE
testing/nim: upgrade to 0.20.0

### PR DESCRIPTION
**Pull request by filalex77**
This change is [Reviewable](https://reviewable.io/reviews/alpinelinux/aports/11927)

### CODE REVIEW

**Comment by Cogitri** [comment]
Seems like the patch doesn't apply, please test your changes before making a PR.

**Comment by filalex77** [comment]
I'm in the process of updating all the patches. Thanks for pointing out!

**Comment by Cogitri** [comment]
:+1:

**Comment by maxice8** [comment]
pkgrel needs to be reset

**Pull request closed without merging**
