### PR TITLE
ADD: README.md with contributing instructions.

### PR DESCRIPTION
**Pull request by 7heo**

### CODE REVIEW

**Comment by andypost** [comment]
Would be great to add more links to contributor guide

**Comment by 7heo** [comment]
@andypost What Contributor Guide? https://wiki.alpinelinux.org/wiki/Alpine_Linux:Contribute?

**Comment by andypost** [comment]
Yep, just one more link to this page

**Comment by 7heo** [comment]
@andypost done.

**Comment by 7heo** [comment]
@jirutka I upper-cased the names in the README.md file. Please let me know if there is anything else left to do.

**Comment by ncopa** [comment]
LGTM :+1:

**Pull request closed without merging**
