### PR TITLE
LLVM 6.0

### PR DESCRIPTION
**Pull request by xentec**
Building LLVM components as standalone packages becomes more painful as more of them rely directly on LLVM's source code. I suggest putting packages without reverse dependencies, like `compiler-rt` and `llvm-libunwind` back to testing until a satisfying way is found to build all of them (including `lldb` and `libc++`) in one package.

Needless to say all packages in this PR passed their tests.

### CODE REVIEW

**Comment by jirutka** [comment]
> Building LLVM components as standalone packages becomes more painful as more of them rely directly on LLVM's source code.

And it even breaks some components (IIRC lldb). LLVM’s build system is really crappy. We (me and @kaniini) have already decided to resign on it and merge all (or some) LLVM components into a single abuild, so we can build it as a single unit. It seems that this is the only approach the LLVM build system is tested on. 😿
However, I’m not keen into doing this job, I’ve already wasted quite a lot of time on this LLVM insanity…

If you’re willing to do it, I’d be very happy!

> I suggest putting packages without reverse dependencies, like compiler-rt and llvm-libunwind back to testing…

`llvm-libunwind` is needed for `rust`, so it cannot be moved to testing!

**Comment by xentec** [comment]
>If you’re willing to do it, I’d be very happy!

I am and will try to but my expertise, time and CPU cores are limited o this could take a while. Because of that I'd like you to merge this PR first for a guarantee that a working LLVM 6.0 package will land in next Alpine release.

**Comment by am11** [comment]
@jirutka, sorry for the long delay on https://github.com/alpinelinux/aports/pull/2342. Last time I tried building LLDB, I was running into errors from one of the dependency (can't remember which one, but it was not of LLVM family and `abuild -R` in lldb directory with tip of alpinelinux/aport's master branch wasn't even building for me). If @xentec wants to try out building LLDB 6 instead, we can close my PR. Otherwise, I will try to dig into it with LLDB release_60 sources over the coming weekend. 😊

**Comment by andypost** [comment]
> llvm-libunwind is needed for rust, so it cannot be moved to testing!
Yes rust 1.25 require it

**Comment by drmoose** [comment]
The APKBUILD doesn't list `diffutils` among its `makedepends`, but fails without it:

```
[100%] Running the LLVM regression tests
FAIL: LLVM :: MC/AsmParser/preserve-comments-crlf.s (16245 of 23267)
******************** TEST 'LLVM :: MC/AsmParser/preserve-comments-crlf.s' FAILED ********************
Script:
--
/aports/main/llvm6/src/llvm-6.0.0.src/build/bin/llvm-mc -preserve-comments -n -triple i386-linux-gnu < /aports/main/llvm6/src/llvm-6.0.0.src/test/MC/AsmParser/preserve-comments-crlf.s > /aports/main/llvm6/src/llvm-6.0.0.src/build/test/MC/AsmParser/Output/preserve-comments-crlf.s.tmp
diff --strip-trailing-cr /aports/main/llvm6/src/llvm-6.0.0.src/test/MC/AsmParser/preserve-comments-crlf.s /aports/main/llvm6/src/llvm-6.0.0.src/build/test/MC/AsmParser/Output/preserve-comments-crlf.s.tmp
--
Exit Code: 1

Command Output (stderr):
--
diff: unrecognized option: strip-trailing-cr
BusyBox v1.27.2 (2017-12-12 10:41:50 GMT) multi-call binary.

Usage: diff [-abBdiNqrTstw] [-L LABEL] [-S FILE] [-U LINES] FILE1 FILE2

Compare files line by line and output the differences between them.
This implementation supports unified diffs only.

	-a	Treat all files as text
	-b	Ignore changes in the amount of whitespace
	-B	Ignore changes whose lines are all blank
	-d	Try hard to find a smaller set of changes
	-i	Ignore case differences
	-L	Use LABEL instead of the filename in the unified header
	-N	Treat absent files as empty
	-q	Output only whether files differ
	-r	Recurse
        --no-dereference Don't follow symlinks
	-S	Start with FILE when comparing directories
	-T	Make tabs line up by prefixing a tab when necessary
	-s	Report when two files are the same
	-t	Expand tabs to spaces in output
	-U	Output LINES lines of context
	-w	Ignore all whitespace

--

********************
Testing Time: 756.94s
********************
Failing Tests (1):
    LLVM :: MC/AsmParser/preserve-comments-crlf.s

  Expected Passes    : 21353
  Expected Failures  : 135
  Unsupported Tests  : 1778
  Unexpected Failures: 1
make[3]: *** [test/CMakeFiles/check-llvm.dir/build.make:58: test/CMakeFiles/check-llvm] Error 1
make[2]: *** [CMakeFiles/Makefile2:69290: test/CMakeFiles/check-llvm.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:69297: test/CMakeFiles/check-llvm.dir/rule] Error 2
make: *** [Makefile:13381: check-llvm] Error 2
>>> ERROR: llvm6: all failed
```

With `apk add diffutils` to get GNU diff instead of the busybox one, `abuild -r` with this package works as expected. Being very new to Alpine, I don't know whether this is actually a problem with this PR or with [my build procedure](https://stackoverflow.com/questions/50258121/building-llvm-6-under-linux-alpine/50298320#50298320), but I'm noting it here anyway for others like me, who need this package, find this PR, but don't know what they're doing.

**Comment by xentec** [comment]
Fixed, thanks for the report @drmoose!
I've updated the PR to latest `master` and also enabled dynamic linking for Clang and LLD (cc @am11)

**Comment by am11** [comment]
Thanks, this is progressing nicely @xentec!
As per https://github.com/alpinelinux/aports/pull/2342#issuecomment-387156817, v6 toolchain of LLVM will probably go in once Alpine Linux v3.8 is out.

A question regarding patch number prefix convention: should those be renumbered (`001-`, `002-`) without gaps?

**Comment by matteomonti** [comment]
Hello! I have just used this pull request to successfully install llvm6 and clang6 on my Alpine Linux Docker container. I tried to go ahead, build and install libc++6 as well, but I couldn't find it. I naively tried to install libc, but it obviously didn't help. Does anyone have suggestions on how I could get libc++6 installed on Alpine Linux?

**Comment by jeannich** [comment]
Hi @matteomonti,
Would you mind explaining a bit how you did this please? (Having alpine container with this PR)
Thanks!

**Comment by xentec** [comment]
@jirutka Friendly reminder that this PR is ready and waiting.

**Comment by m3talstorm** [comment]
Would be great to have this applied and in a release.

**Comment by Kronuz** [comment]
I've added a few commits towards that end, on top of the pr-llvm-6 branch: https://github.com/xentec/aports/compare/pr-llvm-6...Kronuz:pr-llvm-6

This could be compiled with something like:

```sh
# gcloud container --project=dubalu-io-cloud clusters create builder --enable-ip-alias --enable-autoupgrade --cluster-version=latest --num-nodes=1 --machine-type=n1-highcpu-96
# kubectl run -it builder --image=alpine:3.8 -- sh
# Temporary workaround for there not being an llvm6 apk yet
# Open PR for llvm6 package: https://github.com/alpinelinux/aports/pull/3583
# See https://stackoverflow.com/questions/50258121/building-llvm-6-under-linux-alpine
RUN export BUILD_DEPS='alpine-sdk git diffutils patchelf' \
  && apk update \
  && apk add $BUILD_DEPS \
  && adduser -D apk \
  && adduser apk abuild \
  && sudo -iu apk abuild-keygen -a \
  && cp /home/apk/.abuild/*.rsa.pub /etc/apk/keys \
  && sudo -iu apk git clone --depth=1 -b pr-llvm-6 https://github.com/Kronuz/aports \
  \
  # For faster builds in multi-processor boxes:
  # && sudo -iu apk sh -xec 'cd aports/main/llvm6; sed -i "s@\bmake\b@make -j128@g" APKBUILD' \
  # && sudo -iu apk sh -xec 'cd aports/main/clang; sed -i "s@\bmake\b@make -j128@g" APKBUILD' \
  # && sudo -iu apk sh -xec 'cd aports/main/compiler-rt; sed -i "s@\bmake\b@make -j128@g" APKBUILD' \
  # && sudo -iu apk sh -xec 'cd aports/community/lld; sed -i "s@\bmake\b@make -j128@g" APKBUILD' \
  # && sudo -iu apk sh -xec 'cd aports/community/llvm-libunwind; sed -i "s@\bmake\b@make -j128@g" APKBUILD' \
  # && sudo -iu apk sh -xec 'cd aports/testing/libc++; sed -i "s@\bmake\b@make -j128@g" APKBUILD' \
  \
  # Build the needed components using gcc (libc++ is build last, using the built clang):
  && sudo -iu apk sh -xec 'cd aports/main/llvm6; abuild -r' \
  && apk add /home/apk/packages/main/$(uname -m)/*.apk \
  && sudo -iu apk sh -xec 'cd aports/main/clang; abuild -r' \
  && apk add /home/apk/packages/main/$(uname -m)/*.apk \
  && sudo -iu apk sh -xec 'cd aports/main/compiler-rt; abuild -r' \
  && apk add /home/apk/packages/main/$(uname -m)/*.apk \
  && sudo -iu apk sh -xec 'cd aports/community/lld; abuild -r' \
  && sudo -iu apk sh -xec 'cd aports/community/llvm-libunwind; abuild -r' \
  && apk add /home/apk/packages/community/$(uname -m)/*.apk \
  && sudo -iu apk sh -xec 'cd aports/testing/libc++; abuild -r' \
  && apk add /home/apk/packages/testing/$(uname -m)/*.apk \
  \
  # Build and install new llvm6 (with libc++), but patch current clang and lld so they keep working afterwards:
  && sudo -iu apk cp -R /usr/lib lib \
  && patchelf --set-rpath '/home/apk/lib:/home/apk/lib/llvm6/lib:$ORIGIN/../lib:/usr/lib/llvm6/lib' /usr/bin/clang \
  && patchelf --set-rpath '/home/apk/lib:/home/apk/lib/llvm6/lib:$ORIGIN/../lib:/usr/lib/llvm6/lib' /usr/bin/lld \
  && sudo -iu apk sh -xec 'export CC="clang"; export CXX="clang++"; cd aports/main/llvm6; abuild clean cleanpkg; abuild -r' \
  && apk add /home/apk/packages/main/$(uname -m)/*.apk \
  \
  # Build and install new clang:
  && sudo -iu apk sh -xec 'export CC="clang"; export CXX="clang++"; cd aports/main/clang; abuild clean cleanpkg; abuild -r' \
  && apk add /home/apk/packages/main/$(uname -m)/*.apk \
  # Rebuild and install the rest using clang:
  && sudo -iu apk sh -xec 'export CC="clang"; export CXX="clang++"; cd aports/main/compiler-rt; abuild clean cleanpkg; abuild -r' \
  && apk add /home/apk/packages/main/$(uname -m)/*.apk \
  && sudo -iu apk sh -xec 'export CC="clang"; export CXX="clang++"; cd aports/testing/libc++; abuild clean cleanpkg; abuild -r' \
  && apk add /home/apk/packages/testing/$(uname -m)/*.apk \
  && sudo -iu apk sh -xec 'export CC="clang"; export CXX="clang++"; cd aports/community/lld; abuild clean cleanpkg; abuild -r' \
  && sudo -iu apk sh -xec 'export CC="clang"; export CXX="clang++"; cd aports/community/llvm-libunwind; abuild clean cleanpkg; abuild -r' \
  && apk add /home/apk/packages/community/$(uname -m)/*.apk \
  && deluser --remove-home apk \
  && rm -rf /var/cache/apk/APKINDEX* \
  && apk del --no-cache $BUILD_DEPS
```

**Comment by xentec** [comment]
@Kronuz Big thanks! 
But does your libc++ package use the same ABI as libstd++? Because otherwise it breaks all C++ libraries compiled with `g++`.
Also I noticed some `curl` calls in your patches. Please put the URL into `sources=` definition.

**Comment by aw1621107** [comment]
@Kronuz From what I understand, libc++ is only partially ABI compatible with libstdc++. For example, `std::string` isn't ABI compatible between libc++ and libstdc++, but memory allocated in libc++ can be deallocated in libstdc++.

For what it's worth, Debian's `clang-6.0` package appears to use libstdc++ by default, presumably so things built with clang will be more or less guaranteed to work with other things installed using `apt`. I don't know whether this is considered to be behavior that Alpine should copy; at the very least it's a tradeoff between the convenience of using prebuilt C++ packages and the correctness of having all C++ code built using the same compiler. I think more binary distros go with the former, but I'm not that familiar with the Linux ecosystem.

Also, have you tried using the current version of your Docker script recently? I've been trying to use it and builds are failing on the second build of clang (on the `make clang-tblgen` target) due to the linker being unable to find a definition for the symbol `_Unwind_Resume`:

```
Linking CXX executable ../../bin/clang-tblgen                                                                                                                
cd /home/apk/aports/main/clang/src/cfe-6.0.1.src/build/utils/TableGen && /usr/bin/cmake -E cmake_link_script CMakeFiles/clang-tblgen.dir/link.txt --verbose=1
/usr/bin/clang++  -Os -fomit-frame-pointer -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -
Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor 
-Wstring-conversion -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -pedantic -Wno-long-long -Wno-nested-anon-types -Os -fomit-frame-poi
nter -Os -DNDEBUG  -Wl,--as-needed -stdlib=libc++ -Wl,--as-needed  -Wl,-rpath-link,/home/apk/aports/main/clang/src/cfe-6.0.1.src/build/./lib  -Wl,-O3 -Wl,--g
c-sections CMakeFiles/obj.clang-tblgen.dir/ClangASTNodesEmitter.cpp.o CMakeFiles/obj.clang-tblgen.dir/ClangAttrEmitter.cpp.o CMakeFiles/obj.clang-tblgen.dir/
ClangCommentCommandInfoEmitter.cpp.o CMakeFiles/obj.clang-tblgen.dir/ClangCommentHTMLNamedCharacterReferenceEmitter.cpp.o CMakeFiles/obj.clang-tblgen.dir/Cla
ngCommentHTMLTagsEmitter.cpp.o CMakeFiles/obj.clang-tblgen.dir/ClangDataCollectorsEmitter.cpp.o CMakeFiles/obj.clang-tblgen.dir/ClangDiagnosticsEmitter.cpp.o
 CMakeFiles/obj.clang-tblgen.dir/ClangOptionDocEmitter.cpp.o CMakeFiles/obj.clang-tblgen.dir/ClangSACheckersEmitter.cpp.o CMakeFiles/obj.clang-tblgen.dir/Neo
nEmitter.cpp.o CMakeFiles/obj.clang-tblgen.dir/TableGen.cpp.o  -o ../../bin/clang-tblgen  -L/usr/lib/llvm6/lib -Wl,-rpath,"\$ORIGIN/../lib:/usr/lib/llvm6/lib
" /usr/lib/llvm6/lib/libLLVMSupport.a /usr/lib/llvm6/lib/libLLVMTableGen.a /usr/lib/llvm6/lib/libLLVMSupport.a -lz -lrt -ldl -lm /usr/lib/llvm6/lib/libLLVMDe
mangle.a
/usr/bin/ld.lld: error: undefined symbol: _Unwind_Resume
>>> referenced by ClangASTNodesEmitter.cpp
>>>               CMakeFiles/obj.clang-tblgen.dir/ClangASTNodesEmitter.cpp.o:(clang::EmitClangASTNodes(llvm::RecordKeeper&, llvm::raw_ostream&, std::__1::bas
ic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocato
r<char> > const&))

/usr/bin/ld.lld: error: undefined symbol: _Unwind_Resume
>>> referenced by ClangASTNodesEmitter.cpp
>>>               CMakeFiles/obj.clang-tblgen.dir/ClangASTNodesEmitter.cpp.o:(clang::EmitClangDeclContext(llvm::RecordKeeper&, llvm::raw_ostream&))

<snip: more "undefined symbol: _Unwind_Resume" errors>
```

**Comment by tylerhale** [comment]
Is there work on the LLVM side to make it easier for alpine builds? and is there an ETA on when this might be accessible through apk?

**Comment by xentec** [comment]
I'm in the middle of testing LLVM 7.0 right now. New PR is coming when everything works well _enough_.
You can see the progress here: https://github.com/xentec/aports/commits/pr-llvm-7

**Comment by Kronuz** [comment]
@xentec, I think we should have all the other bits I added (such as `crtbegin`/`crtend` and whatnot) to make clang to not depend on GCC at all. Clang could still be (maybe) compiled with `libstdc++` as the default stdlib for building stuff (by not setting `CLANG_DEFAULT_CXX_STDLIB`) but nonetheless still building all clang it’s dependencies and tools with `libc++`, so it doesn’t depend on GCC (it really shouldn’t).

The goal should also be to build all the sanitizers with `compiler-rt` and the instrumented `libc++`

**Comment by xentec** [comment]
@Kronuz, I will add your patches, once 7.0 runs, but whether or not clang should compile against compile-rt is for the Alpine Maintainers to decide. cc @ncopa

**Comment by Kronuz** [comment]
Clang should have no GCC dependencies, it could use `libstdc++` as it’s default standard library when compiling stuff, but clang itself should not have GCC dependencies IMHO.

**Comment by am11** [comment]
@xentec, regarding lldb, this locale patch is not required if we go from 5.0.1 to 7.0: https://github.com/xentec/aports/commit/fc12123a861578e58a908cf6649769615ce123e2#diff-af86b066296def851ee48fd7c9a8e5d3; missing `#include <locale.h>` is in 6.0.1 branch.

**Comment by raja** [comment]
Any updates on this?

**Comment by xentec** [comment]
@hayd Yes, but not mine. https://github.com/alpinelinux/aports/pulls?q=is%3Apr+is%3Aopen+LLVM

I don't have much time these days to maintain one.

**Pull request closed without merging**
