### PR TITLE
community/dunst: update to 1.4.0

### PR DESCRIPTION
**Pull request by maxice8**
@ncopa

### CODE REVIEW

**Comment by Ikke** [comment]
See also #7245

**Comment by maxice8** [comment]
Test will fail as long as CI doesn't take changes in packages in the same PR into account

**Comment by tcely** [comment]
> Test will fail as long as CI doesn't take changes in packages in the same PR into account

See https://github.com/alpinelinux/abuild/pull/53 for the reason why a package building in community is not using the packages previously built in the PR from main.

**Comment by ncopa** [comment]
we need to verify that we don't introduce any circular deps here

**Pull request closed without merging**
