### PR TITLE
main/curl: enable check()

### PR DESCRIPTION
**Pull request by andypost**
https://curl.haxx.se/changes.html#7_64_1

Initially
Adds patch from https://github.com/curl/curl/commit/754ae103989a6ad0869d23a6a427d652b5b4a2fe

Details 
- https://github.com/curl/curl/issues/3629
- https://github.com/drupal-composer/drupal-scaffold/issues/102

### CODE REVIEW

**Comment by prspkt** [comment]
It appears to have been addressed in [7.64.1](https://curl.haxx.se/changes.html#7_64_1)

**Comment by andypost** [comment]
btw it pass tests now

**Comment by rnalrd** [comment]
Sorry saw this too late

**Comment by andypost** [comment]
Still makes sense to enable check

**Pull request closed without merging**
