### PR TITLE
testing/dnssec-tools: add missing dependencies

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
Rebased.

**Comment by rnalrd** [comment]
Other than the depends update everything is already included. If it's needed please rebase.
Thanks

**Comment by J0WI** [comment]
@rnalrd rebased as requested.

**Comment by J0WI** [comment]
Fixed in a06d9656057407eb152a6e333b7c9b34f921bb08

**Pull request closed without merging**
