### PR TITLE
community/erlang: upgrade to 20.2

### PR DESCRIPTION
**Pull request by gmile**

### CODE REVIEW

**Comment by TBK** [comment]
Hash (sha512) is incorrect according to Travis. Plus the APKBUILD file could use an overhaul (tab/space mix, return 1...).

I have attached my version of an modernized APKBUILD file:
[APKBUILD.zip](https://github.com/alpinelinux/aports/files/1559831/APKBUILD.zip)

**Comment by gmile** [comment]
@TBK thank for the heads up! I've pushed an updated sha512. Not sure how did the incorrect sha happen the first time...

Regarding an APKBUILD refresh, maybe a separate PR will do? I'd rather have this one merged first, and then overhaul APKBUILD separately.

**Comment by TBK** [comment]
You do it in one PR or as two. It is up to you.

**Comment by gmile** [comment]
Looks like a patch to erlang source code will be required to fix the build.

**Comment by gmile** [comment]
This is an issue in erlang (see [1](https://trac.macports.org/ticket/55570) and [2](https://bugs.erlang.org/browse/ERL-546)), it was fixed upstream 6 days ago https://github.com/erlang/otp/commit/2309ce0c8b44f8176a6ab7139aa2de3ab98c07ec

**Comment by gmile** [comment]
@jirutka I have added the respective patch, the build is now green

**Comment by fabled** [comment]
Superceded by #3136

**Pull request closed without merging**
