### PR TITLE
testing/kismet: new aport

### PR DESCRIPTION
**Pull request by Fusl**

### CODE REVIEW

**Comment by Fusl** [comment]
@jirutka 
I reported on IRC back in 2018 that implementing your changes as requested above doesn't work. When installing the package on a fresh Alpine Linux installation, the group of the kismet_capture file is not correctly reassigned to the `kismet` group but with an unknown group that the build system had when building the package:
```
-r-xr-x---    1 root     103         465352 Sep 14 10:36 /usr/bin/kismet_capture*
```

**Comment by Ikke** [comment]
@Fusl 

> @jirutka
> I reported on IRC back in 2018 that implementing your changes as requested above doesn't work. When installing the package on a fresh Alpine Linux installation, the group of the kismet_capture file is not correctly reassigned to the `kismet` group but with an unknown group that the build system had when building the package:
> 
> ```
> -r-xr-x---    1 root     103         465352 Sep 14 10:36 /usr/bin/kismet_capture*
> ```

This can be fixed by supplying [pkgusers][] and [pkggroups][] variables. This makes sure those groups exist during buildtime, and with the aid of tar, ensure that the files/directories have the same user/group.

[pkgusers]:https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#pkgusers
[pkggroups]:https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#pkggroups

**Comment by Fusl** [comment]
@Ikke That's literally what I tried, here are my original messages from IRC:

```
2018-09-14 10:20:08     Fusl    jirutka[m]: are you on?
2018-09-14 10:51:51     Fusl    or maybe someone else on who can help me make this PR compliant to the aports repo? https://github.com/alpinelinux/aports/pull/4438
2018-09-14 10:53:01     Fusl    i did
2018-09-14 10:53:24     Fusl    i did not, i tried the changes locally and they dont work as expected
2018-09-14 10:53:53     Fusl    more specifically, when i install the package on another system, the group of the kismet_capture file is not correctly reassigned to the `kismet` group
2018-09-14 10:55:11     Fusl    removed `$pkgname.post-install`, replaced `-g root` with `-g kismet` for the `install` command and added `pkggroups="kismet"`
2018-09-14 10:55:42     Fusl    on a freshly installed alpine system, the file gets created with an unknown group: -r-xr-x---    1 root     103         465352 Sep 14 10:36 /usr/bin/kismet_capture*
2018-09-14 10:59:08     Fusl    i can push the changes i made locally to the repo so you can try it out on your side, _ikke_
```

**Comment by Ikke** [comment]
This [patch][] works for me:

> $ ls -l /usr/bin/kismet_capture
-r-xr-x---    1 root     kismet      465312 Mar 17 13:32 /usr/bin/kismet_capture

[patch]:http://tpaste.us/Erwg

**Comment by clandmeter** [comment]
Hi, Ikke and jirutka are right, please correct those issues and rebase with master to make CI build.
You can check with some other packages which have proper usage of pkguser and pkggrous.
They will also include a proper post-install script to create the user, this info should also be on the wiki.
Why are you changing the group owner of kismet_capture? 

Also please limit lines on 80 chars.

**Pull request closed without merging**
