### PR TITLE
testing/gomplate: new aport

### PR DESCRIPTION
**Pull request by hairyhenderson**
for https://github.com/hairyhenderson/gomplate

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Comment by fabled** [comment]
Seems to download unversioned stuff from internet during build.

> >>> gomplate: Unpacking /var/cache/distfiles/gomplate-1.3.0.tar.gz...
> [INFO]	Downloading dependencies. Please wait...
> [INFO]	--> Fetching github.com/aws/aws-sdk-go.
> [INFO]	--> Fetching github.com/blang/vfs.
> [INFO]	--> Fetching github.com/urfave/cli.
> [INFO]	--> Fetching github.com/go-ini/ini.
> [INFO]	--> Fetching github.com/jmespath/go-jmespath.
> [INFO]	--> Fetching gopkg.in/yaml.v2.
> [INFO]	--> Fetching github.com/davecgh/go-spew.
> [INFO]	--> Fetching github.com/stretchr/testify.
> [INFO]	--> Fetching github.com/pmezard/go-difflib.

**Comment by clandmeter** [comment]
@hairyhenderson can you take a look at how we do it for example here:

https://github.com/alpinelinux/aports/blob/master/testing/gitea/APKBUILD#L24

Fetching sources should happen before build, and doing it in prepare you are still able to apply patches at the end of prepare.

ps can you also cleanup the whitespace?

**Comment by clandmeter** [comment]
@hairyhenderson seems you are also the developer of this project. It looks like you are using git in your makefile to fetch COMMIT_FLAG  and VERSION_FLAG. In the case you are using a tarball from github (which does not have git metadata) it will get this information from the parent git repo (aports).

Would be nice if one could overide this by settings something like VERSION=$pkgver

**Comment by hairyhenderson** [comment]
Thanks for the feedback @fabled and @clandmeter! I'll see about addressing it 🙂

**Comment by hairyhenderson** [comment]
Ok. I think I've addressed everything - good call on overriding the version, @clandmeter - I've updated the gomplate Makefile so it'll accept environment variables.

PTAL @clandmeter & @fabled

**Pull request closed without merging**
