### PR TITLE
testing/zimwriterfs: upgrade to 1.3.1

### PR DESCRIPTION
**Pull request by OTLabs**
- https://github.com/openzim/zimwriterfs/releases 1.3.1
- Modernize
- License clarification

### CODE REVIEW

**Comment by TBK** [comment]
Please clarify the license: `GPL-3.0-or-later`
https://github.com/openzim/zimwriterfs/blob/master/LICENSE
https://spdx.org/licenses/

**Comment by OTLabs** [comment]
@TBK I have updated the license. Thank you!

How can I differentiate between GPL-3.0 and GPL-3.0-or-later?

**Comment by TBK** [comment]
@OTLabs There is no generic "GPL-3.0" it is either GPL-3.0-or-later or GPL-3.0-only following the SPDX license identifier.

From my experience very few projects are GPL-3.0-only.

For the GPL-3.0-or-later the "standard license header would be worded:
> This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, **_either version 3 of the License, or (at your option) any later version._** 


and the GPL-3.0-only:
> This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, _**version 3.**_

**Comment by OTLabs** [comment]
@TBK Thanks a lot!

**Comment by Ikke** [comment]
This has been merged as 98a0284d, closing PR.

**Pull request closed without merging**
