### PR TITLE
Use generic travis image

### PR DESCRIPTION
**Pull request by micw**
Simple change to travis.yml to use a "generic" image - saves a minute per build, see https://docs.travis-ci.com/user/languages/minimal-and-generic/ for details.

### CODE REVIEW

**Comment by andypost** [comment]
Interestig idea, can you update description with alink to docs?

**Comment by micw** [comment]
Sure, done.

**Comment by andypost** [comment]
Looking at instal&setup files it could be https://docs.travis-ci.com/user/languages/minimal-and-generic/#minimal

**Comment by andypost** [comment]
there some packages that lack of disk while bulding and that's why there no tests/check

**Comment by jirutka** [comment]
Great catch! I think that `minimal` will be even better for our use case.

**Comment by andypost** [comment]
@micw can you `commit --amend` with `minimal`?

**Pull request closed without merging**
