### PR TITLE
main/py-setuptools: remove depends on python2

### PR DESCRIPTION
**Pull request by dimon222**
https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v4080

### CODE REVIEW

**Comment by ncopa** [comment]
this look like a dupe of #6432. Can you please rebase?

**Comment by dimon222** [comment]
@ncopa @fabaff applied rebase and renamed the PR. Please confirm if it even makes sense.

**Comment by ncopa** [comment]
Why is the `python2` dependency removed?

**Comment by dimon222** [comment]
Makes sense, closing

**Pull request closed without merging**
