### PR TITLE
September Adélie merge: Desktop libraries

### PR DESCRIPTION
**Pull request by awilfox**
This modernises and add test suites to four libraries used for X11 desktops.

### CODE REVIEW

**Comment by tmpfile** [comment]
You forgot to run `abuild checksum` during the modernization.
That would ensure packages with old checksums (md5 and sha256) are updated to display only the new hashes (sha512).

Actually... could we run `abuild checksum` on every single package?
That would update all APKBUILD with old hashes + show us if any packages have wrong hashes.
And there's no side-effect, because APKBUILD with correct checksums will remain that way.

Opinions?

**Comment by ncopa** [comment]
I dont think we need to stress with the checksums. We can update those when convenient.

**Comment by ncopa** [comment]
i updated the checksums and pushed.

**Comment by awilfox** [comment]
@tmpfile actually there have been a few checksum mismatches for me, especially with some GNOME packages, that turned out to be their FTP server dying in the middle of the transfer.  So I am very glad that the checksums are there.  I wouldn't want to blanket-rewrite them, because then it could be corrupted...

**Pull request closed without merging**
