### PR TITLE
main/protobuf: upgrade to 3.10.0

### PR DESCRIPTION
**Pull request by andypost**
Ref https://github.com/protocolbuffers/protobuf/releases/tag/v3.9.0

https://abi-laboratory.pro/?view=timeline&l=protobuf

### CODE REVIEW

**Comment by andypost** [comment]
Last upgrade https://github.com/alpinelinux/aports/pull/9161

**Comment by andypost** [comment]
https://github.com/protocolbuffers/protobuf/releases/tag/v3.9.1

**Comment by andypost** [comment]
```diff
-usr/lib/libprotobuf-lite.so.19
-usr/lib/libprotobuf-lite.so.19.0.0
-usr/lib/libprotobuf.so.19
-usr/lib/libprotobuf.so.19.0.0
-usr/lib/libprotoc.so.19
-usr/lib/libprotoc.so.19.0.0
+usr/lib/libprotobuf-lite.so.20
+usr/lib/libprotobuf-lite.so.20.0.1
+usr/lib/libprotobuf.so.20
+usr/lib/libprotobuf.so.20.0.1
+usr/lib/libprotoc.so.20
+usr/lib/libprotoc.so.20.0.1
```

**Comment by maxice8** [comment]
bd5f040a849d08e2ef29f742e34d6a601adac682

**Pull request closed without merging**
