### PR TITLE
unmaintained/ipmitool: update to version 1.8.18

### PR DESCRIPTION
**Pull request by mmlb**

### CODE REVIEW

**Comment by mmlb** [comment]
I'll be looking to move back to testing or preferably community.

**Comment by ncopa** [comment]
does it build? if it does then move it to testing. nothing will build anything in unmaintained.

**Comment by mmlb** [comment]
@ncopa yup it does build, thanks for the note about moving to testing. travis actually did build it, probably not what you meant, but I figured that would probably get the ball rolling.

**Comment by mmlb** [comment]
Also I have a question about an `abuild` warning: 
```
ipmitool: ipmievd.initd is not an openrc #!/sbin/openrc-run
```

Looks like I just need to update the shebang?

**Comment by ncopa** [comment]
Yes, you you need update the shebang.

Can you do that and merge your commits into one, with a commit message: `testing/ipmitool: move from unmaintained and upgrade to 1.8.18` or similar.

 Thanks!

**Comment by mmlb** [comment]
@ncopa done

**Comment by mmlb** [comment]
Hey @ncopa any thoughts on when I can expect the package to be out on the mirrors?

**Comment by mmlb** [comment]
whoops and thanks for fixing the missing checksum update

**Pull request closed without merging**
