### PR TITLE
testing/wkhtmltopdf: bump version to latest stable (0.12.4)

### PR DESCRIPTION
**Pull request by efx**
I calculated the checksums locally as the project does not provide them.

### CODE REVIEW

**Comment by ncopa** [comment]
In addition to the checksum error it also failed with this error:
````bash
g++ -c -pipe -Os -fomit-frame-pointer -Wall -W -D_REENTRANT -fPIC -DVERSION=0.12.4 -DFULL_VERSION=0.12.4 -DBUILDING_DLL -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../../include -isystem /usr/include/QtWebKitWidgets -isystem /usr/include/QtWebKit -isystem /usr/include/QtSvg -isystem /usr/include/QtPrintSupport -isystem /usr/include/QtWidgets -isystem /usr/include/QtGui -isystem /usr/include/QtXmlPatterns -isystem /usr/include/QtNetwork -isystem /usr/include/QtCore -I. -I/usr/lib/qt5/mkspecs/linux-g++ -o image_c_bindings.o ../lib/image_c_bindings.cc
../lib/multipageloader.cc: In constructor 'wkhtmltopdf::ResourceObject::ResourceObject(wkhtmltopdf::MultiPageLoaderPrivate&, const QUrl&, const wkhtmltopdf::settings::LoadPage&)':
../lib/multipageloader.cc:219:10: error: 'class wkhtmltopdf::MyQWebPage' has no member named 'setDevicePixelRatio'
  webPage.setDevicePixelRatio(devicePixelRatio); // Fix CSS media queries (does not affect anything else).
          ^~~~~~~~~~~~~~~~~~~
/usr/lib/qt5/bin/rcc -name wkhtmltopdf ../../wkhtmltopdf.qrc -o qrc_wkhtmltopdf.cpp
````

**Comment by efx** [comment]
ah interesting, thanks for checking. It turns out `wkhtmltopdf` bundles QT, so I'd guess that failure comes from a clash between which method the newer version relies upon. I've commented on that issue (https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3335). I can see about compiling the package from source and/or waiting if the author responds.

**Comment by jirutka** [comment]
> It turns out wkhtmltopdf bundles QT,

That’s very nasty, please remove the bundled Qt and compile it against the system-provided Qt.

**Comment by ncopa** [comment]
It is a fork of qt with various patches.
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3217

I don't think we want all those patches in our system qt.

**Comment by efx** [comment]
Thanks for the feedback, I completely agree about problems caused by a bundled qt. I will close this for now pending better source organization from the upstream project.

**Pull request closed without merging**
