### PR TITLE
main/llvm: fix typo in pkgdesc

### PR DESCRIPTION
**Pull request by centromere**

### CODE REVIEW

**Comment by jirutka** [comment]
Please change commit message to `main/llvm: fix typo in pkgdesc` (`git commit --amend; git push - f`).

**Comment by centromere** [comment]
@jirutka Done.

**Comment by jirutka** [comment]
You’ve messed something, now your pull request and commit contains changes in 33 files…

Nevermind, I’ve extracted the patch to http://tpaste.us/2zXv. @alpinelinux/gh-core, please merge it.

**Comment by jirutka** [comment]
Merged in 0b450586288e6511ae6746736cea46ae84deed4d. Thanks!

**Pull request closed without merging**
