### PR TITLE
community/go: update to 1.12.1

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by nmeum** [comment]
Build fails, I upgraded it locally without including the patch and in that case it build fine.

**Comment by J0WI** [comment]
Looks even worse without the patch

**Comment by nmeum** [comment]
Well…fetch fails now so it doesn't even attempt to build it. No idea why though.

**Comment by nmeum** [comment]
Could you rebase your branch against master? This should make the fetch stage pass.

**Comment by J0WI** [comment]
This fails on 32bit arches again.

**Comment by nmeum** [comment]
That's good to know because I only tested it on x86_64 would be probably be a good idea to investigate why this tests passed with go 1.11 but no longer pass with go 1.12. That being sad the current check() for this package is pretty hacky especially since the testsuite is not really intended to be run with a pie default buildmode.

**Comment by nmeum** [comment]
Superseded by 9130ec9f2a50285c35b4cd060788d797cc38b497

**Pull request closed without merging**
