### PR TITLE
 testing/softhsm: upgrade to 2.5.0

### PR DESCRIPTION
**Pull request by tcely**
~~Depends on #6555~~

For https://bugs.alpinelinux.org/issues/10066

### CODE REVIEW

**Comment by tcely** [comment]
@Ikke @andypost @fcolista Please commit this.

**Comment by Ikke** [comment]
@tcely This APKBUILD still has a todo regarding running the actual test suite?

**Comment by tcely** [comment]
@Ikke I can't make any sense of your comment. What is your question??

**Comment by tcely** [comment]
Merged in https://github.com/alpinelinux/aports/commit/21b6f939ac7e8da2c96fcfa9481aaa93a6b978fa, https://github.com/alpinelinux/aports/commit/dca992785e1534c3bd8e0971aed453c42f954e53, and https://github.com/alpinelinux/aports/commit/a06ffff95a8af09252e8acb149121c0707b2d54e by @Ikke

**Pull request closed without merging**
