### PR TITLE
main/links: upgrade to 2.13

### PR DESCRIPTION
**Pull request by liqa**

### CODE REVIEW

**Comment by jirutka** [comment]
Please change commit message to: `main/links: upgrade to 2.13` (hint: commit --amend && git push -f).

**Comment by liqa** [comment]
I don't have git on this computer (at work) - sorry
next times I'll do it right

**Comment by jirutka** [comment]
> I don't have git on this computer (at work) - sorry

So how did you send this PR? o.O

**Comment by liqa** [comment]
github interface

**Comment by jirutka** [comment]
And checksums? You’ve updated it them by hand?

**Comment by liqa** [comment]
by hand
is there any automatic way?

**Comment by jirutka** [comment]
Of course there is: `abuild checksum` ([see wiki](https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package#source)). ;)

Okay, we’ll fix the commit messages when merging.

**Comment by liqa** [comment]
thanks, I'll read that page for next upgrades
waiting for these commits to merge :-)

**Comment by jirutka** [comment]
@ncopa, could you please merge http://tpaste.us/2rmx? (patch from this PR with fixed commit message)

**Comment by jirutka** [comment]
Francesco Colista already upgraded the links package to 2.13, independent of this PR.

**Pull request closed without merging**
