### PR TITLE
main/protobuf: upgrade to 3.6.1

### PR DESCRIPTION
**Pull request by prspkt**

### CODE REVIEW

**Comment by andypost** [comment]
There's also `testing/py-protobuf` looks could be updated in separate PR

PS from closed PR https://abi-laboratory.pro/?view=timeline&l=protobuf

**Comment by andypost** [comment]
Filed https://github.com/alpinelinux/aports/pull/4934

**Comment by andypost** [comment]
bitcoin package needs update cos https://github.com/alpinelinux/aports/pull/4876

**Comment by andypost** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by ncopa** [comment]
this has been merged/rebased. Thank you very much!

**Comment by andypost** [comment]
3.7.1 is out https://github.com/alpinelinux/aports/pull/6848

**Pull request closed without merging**
