### PR TITLE
community/gomplate: moving from testing

### PR DESCRIPTION
**Pull request by hairyhenderson**
I'd like for `gomplate` to be in the `community` repo, if possible. Thank you!

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Comment by jirutka** [comment]
This abuild needs some changes, I'll write more later.

**Comment by hairyhenderson** [comment]
Thanks @jirutka - I'll await your instructions 🙂

**Comment by jirutka** [comment]
I’ve fixed it in 26b900cced22747cbf6884f3d4edf9fdfdc1130b, fca60d7c73c8a8634fbb3a4df739ecb9dc8f0350 and 9c02765c70f461cbf77c4ba35a294b53894a52d0.

**Comment by hairyhenderson** [comment]
Thanks @jirutka!

**Pull request closed without merging**
