### PR TITLE
testing/firefox: upgrade to 68.0

### PR DESCRIPTION
**Pull request by liqa**

### CODE REVIEW

**Comment by liqa** [comment]
the package nss must be upgraded to 3.45
then this PR can be merged

**Comment by maxice8** [comment]
I assume this supersedes #9373

**Comment by maxice8** [comment]
Can we drop gconf ?

**Comment by liqa** [comment]
done
for those wondering why: https://bugzilla.mozilla.org/show_bug.cgi?id=1433685
firefox doesn't depend on gconf anymore starting from version 68

**Comment by maxice8** [comment]
gconf is also deprecated in favour of gsettings and dconf so i'm trying to remove it from all packages and then remove gconf itself.

Hopefully in time for 3.11

**Pull request closed without merging**
