### PR TITLE
testing/mame: Upgrade to 0.206

### PR DESCRIPTION
**Pull request by tanertas**
* Use default compiler for armhf.

### CODE REVIEW

**Comment by tanertas** [comment]
Travis CI fails due to:
`The job exceeded the maximum time limit for jobs, and has been terminated.`
Which is expected.

**Comment by andypost** [comment]
it fails on
- https://build.alpinelinux.org/buildlogs/build-edge-armhf/testing/mame/mame-0.206-r0.log
- https://build.alpinelinux.org/buildlogs/build-edge-s390x/testing/mame/mame-0.206-r0.log

**Comment by tanertas** [comment]
What is the proper way to handle this? New PR with updating local release number, or just provide fix?

**Comment by tanertas** [comment]
I created a new PR #6217

**Comment by tanertas** [comment]
> it fails on
>     * https://build.alpinelinux.org/buildlogs/build-edge-s390x/testing/mame/mame-0.206-r0.log
@andypost  armhf fixed with -r1 but s390x seems faked us as it looks like mame already successfully build on -r0 according to log above. What should we do in this circumstances? A new PR with -r3 (and revert s390x related changes at -r1) to trigger a new build for s390x?

**Comment by andypost** [comment]
@tanertas nice plan

**Comment by tanertas** [comment]
#6222

**Pull request closed without merging**
