### PR TITLE
testing/vault: upgrade to 1.1.0

### PR DESCRIPTION
**Pull request by mtneug**
Upgrade to newly released 1.1.0.

### CODE REVIEW

**Comment by Ikke** [comment]
@mtneug Do you think this package is stable enough to move to community? Means that go-bindata-assetfs would also need to be moved.

**Comment by Ikke** [comment]
So the maintainer apparently disappeared and now they setup an unmaintained copy, looking for a maintainer.

Do you think this project is stable enough that it would not need a lot of updates for it to still work?

**Comment by mtneug** [comment]
I think it is very likely it will continue to work. The purpose of go-bindata is to generate Go code to embed non-go files. Go 1.x [promises backwards compatibility](https://golang.org/doc/go1compat). The generated files as well as the code of go-bindata itself therefore will continue to be valid Go code. Additionally, since projects like Vault and Traefik relay on it, I assume there will be some fixes if incompatibilities arise.

**Comment by Ikke** [comment]
Alright, sounds good. I will apply this update. Can you prepare a new PR to move these 3 packages to community?

**Comment by mtneug** [comment]
Yes, I will do that.

**Pull request closed without merging**
