### PR TITLE
main/syslog-ng: upgrade to 3.12.1

### PR DESCRIPTION
**Pull request by andypost**

### CODE REVIEW

**Comment by jirutka** [comment]
Build fails and it doesn’t look like a Travis-related issue.

**Comment by andypost** [comment]
yes, it looks like openssl incompatibility
```
librabbitmq/.libs/librabbitmq.a(librabbitmq_librabbitmq_la-amqp_openssl.o): In function `amqp_ssl_socket_delete':
amqp_openssl.c:(.text+0x3fd): undefined reference to `FIPS_mode_set'
amqp_openssl.c:(.text+0x435): undefined reference to `SSL_COMP_free_compression_methods'
librabbitmq/.libs/librabbitmq.a(librabbitmq_librabbitmq_la-amqp_openssl_bio.o): In function `amqp_openssl_bio_init':
amqp_openssl_bio.c:(.text+0x56): undefined reference to `BIO_meth_set_write'
amqp_openssl_bio.c:(.text+0x6b): undefined reference to `BIO_meth_set_read'
collect2: error: ld returned 1 exit status
```

**Comment by adrianguenter** [comment]
The undefined reference to `FIPS_mode_set` is caused by LibreSSL not supporting FIPS: https://marc.info/?l=openbsd-misc&m=139819485423701&w=2


The other undefined references are related to the `OPENSSL_VERSION_NUMBER` macro in LibreSSL: https://forums.gentoo.org/viewtopic-p-8033892.html#8033892

**Comment by ncopa** [comment]
fixed with #3206

**Pull request closed without merging**
