### PR TITLE
testing/firefox: upgrade to 52.0

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Comment by jirutka** [comment]
It fails in the configure phase, please see [the log](https://travis-ci.org/alpinelinux/aports/builds/213199664#L834).

**Comment by pickfire** [comment]
Guess you need to wait for https://github.com/alpinelinux/aports/pull/1051/commits/6efe253182395fe1998ae445e42fcc0fe9903a01

**Comment by pickfire** [comment]
If nss builds, then I guess firefox should build as well.

**Comment by kaniini** [comment]
mozconfig needs to enable alsa and disable pulseaudio.  while a temporary solution, it is the one we need for now.

**Comment by ncopa** [comment]
firefox 52 seems to be in aports. thanks.

**Pull request closed without merging**
