### PR TITLE
testing/php7-lzf: upgrade to 1.6.7

### PR DESCRIPTION
**Pull request by andypost**
Ref https://pecl.php.net/package-changelog.php?package=lzf&release=1.6.7

### CODE REVIEW

**Comment by andypost** [comment]
@fabiorphp I think it makes sense to rename package and move to community

**Comment by fabiorphp** [comment]
Absolutely!

**Comment by andypost** [comment]
@fabiorphp renamed, are you fine with changes in "modernize"?

**Comment by fabiorphp** [comment]
Yes! I'm fine!

**Comment by andypost** [comment]
Commited as bc6c63f9 6c274e46 4fb55cb0

**Pull request closed without merging**
