### PR TITLE
main/libuv: upgrade to 1.29.1

### PR DESCRIPTION
**Pull request by OTLabs**
- https://github.com/libuv/libuv/releases 1.29.1
- Add $pkgname-static to subpackages

### CODE REVIEW

**Comment by tcely** [comment]
```

not ok 110 - get_memory
--
907 | # exit code 134
908 | # Output from process `get_memory`:
909 | # free_mem=3420033024, total_mem=2837901312, constrained_mem=9223372036854771712
910 | # Assertion failed in test/test-get-memory.c on line 37: total_mem > free_mem

FAIL: test/run-tests
--
1163 | ======================================================
1164 | 1 of 1 test failed
1165 | Please report to https://github.com/libuv/libuv/issues
1166 | ======================================================
1167 | make[1]: *** [Makefile:5040: check-TESTS] Error 1
1168 | make[1]: Leaving directory '/home/buildozer/aports/main/libuv/src/libuv-v1.29.0'
1169 | make: *** [Makefile:5300: check-am] Error 2
1170 | >>> ERROR: libuv: check failed


```

**Comment by OTLabs** [comment]
`libuv` was upgraded to 1.29.1. Now the build fails on Drone for x86 with following error:

```
not ok 137 - ipc_closed_handle
--
955 | # timeout
956 | # Output from process `ipc_closed_handle`:
957 | # Assertion failed in test/test-ipc.c on line 601: status == 0



FAIL: test/run-tests
--
1180 | ======================================================
1181 | 1 of 1 test failed
1182 | Please report to https://github.com/libuv/libuv/issues
1183 | ======================================================
1184 | make[1]: *** [Makefile:5040: check-TESTS] Error 1
1185 | make[1]: Leaving directory '/home/buildozer/aports/main/libuv/src/libuv-v1.29.1'
1186 | make: *** [Makefile:5300: check-am] Error 2
1187 | >>> ERROR: libuv: check failed
```

**Comment by tcely** [comment]
That error was seen in the previous version also.

**Comment by OTLabs** [comment]
There is a warning about static lib:
`>>> WARNING: libuv-dev*: Found static archive on usr/lib/libuv.a but name doesn't end with -static`

Should I add a `$pkgname-static` to `subpackages`?

**Comment by tcely** [comment]
> There is a warning about static lib:
> `>>> WARNING: libuv-dev*: Found static archive on usr/lib/libuv.a but name doesn't end with -static`
> 
> Should I add a `$pkgname-static` to `subpackages`?

You can. If you do be sure to include it before `-dev` in the list. https://github.com/alpinelinux/abuild/pull/72#issuecomment-488233269

**Comment by OTLabs** [comment]
Ok, done.

**Pull request closed without merging**
