### PR TITLE
scripts/bootstrap.sh: Changes required to bootstrap ARM on x86

### PR DESCRIPTION
**Pull request by trixpan**
Introduce changes required to perform successful bootstrap of v3.10 ARMv7 environment on x86_64 hosts.

### CODE REVIEW

**Comment by trixpan** [comment]
@fabled any feedback regarding this PR?

**Comment by trixpan** [comment]
@fabled ?

**Comment by fabled** [comment]
Removing  `community/go` and `community/ghc` seems unacceptable to me. Those need to be cross-compiled as they are "self-hosting" compilers. Do their cross-compile fail? Is it possible to fix that instead? Also, please file the fix against edge first and then request backport. We don't merge directly to stable branches if the issue affects edge too (unless the fix needs to be completely different).

The other hunk looks ok, but seems I bumped into it too, and had fixed it individually in edge. I cherry-picked that commit. Sorry for the overlapping work, and thank you for your effort on this.

**Comment by fabled** [comment]
The sensible hunks were merged in other commit. No response on the bits that we consider not appropriate. Please reopen with alternate plan or additional explanation if problem persists. Closing for now.

**Pull request closed without merging**
