### PR TITLE
community/mpv: enable Vulkan support

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
@ncopa

**Comment by maxice8** [comment]
A sore point to fix is that the user needs to install the proper mesa-vulkan-\<vendor> package, for my machine it is intel and there is AMD

**Comment by PureTryOut** [comment]
> A sore point to fix is that the user needs to install the proper mesa-vulkan-<vendor> package, for my machine it is intel and there is AMD

Does the `setup-xorg-base` script handle this yet?

**Comment by maxice8** [comment]
On Thu, Jun 27, 2019 at 01:28:27PM -0700, Bart Ribbers wrote:
> > A sore point to fix is that the user needs to install the proper mesa-vulkan-<vendor> package, for my machine it is intel and there is AMD
> 
> Does the `setup-xorg-base` script handle this yet?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/9162#issuecomment-506498627

Apparently not

http://ix.io/1MX7

**Pull request closed without merging**
