### PR TITLE
community/mdds: update to 1.4.3

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
See also #4657 for boost 1.69

**Comment by Ikke** [comment]
Is now part of #6548, so his PR can be closed.

**Comment by andypost** [comment]
@Ikke I think it could be commited separately no big changes https://gitlab.com/mdds/mdds/blob/master/CHANGELOG

**Comment by andypost** [comment]
Btw why there is `community/mdds1.0/APKBUILD:3:pkgname="mdds1.0"`

**Comment by ncopa** [comment]
> Btw why there is `community/mdds1.0/APKBUILD:3:pkgname="mdds1.0"`

Probably because there was an ABI and API breaking change in mdds at some point and some applications/libs needed old api and some needed new.

It could also have been a temporarily thing while upgrading to ABI breaking change. It is not always possible to rebuild evertying in one go. (for example for toolchain depenendencies)

The git log will probably give you more details.

**Comment by J0WI** [comment]
It has been added in https://github.com/alpinelinux/aports/commit/d322d06839fa00d9beb331f4768b958a4eeabee1. I didn't found any package depending on it.

**Comment by andypost** [comment]
@J0WI sorry, mixed packages - grep shows that packages depends on `mdds` (not `mdds1.0`)
```
community/libetonyek/APKBUILD:11:makedepends="$depends_dev gperf doxygen mdds-dev"
community/libixion/APKBUILD:12:makedepends="$depends_dev boost-dev mdds-dev"
community/liborcus/APKBUILD:10:makedepends="$depends_dev boost-dev mdds-dev libixion-dev zlib-dev libixion-dev"
community/libreoffice/APKBUILD:14:      libxslt-dev postgresql-dev mdds-dev glm-dev glu-dev glew-dev vigra-dev
```

**Comment by andypost** [comment]
But about need to support 1.0 better to ask @fabled

**Comment by J0WI** [comment]
Fixed in a96b58432bcc2d41ccdf87c81d09f4f2e5b0b92e

**Pull request closed without merging**
