### PR TITLE
main/libwebp: upgrade to 1.0.2

### PR DESCRIPTION
**Pull request by jbergstroem**

### CODE REVIEW

**Comment by jbergstroem** [comment]
(jesus christ did my editor mess with me - apologies)

**Comment by andypost** [comment]
There's ABI changes so all dependent packages will need bump
```
 usr/lib/libwebp.so.7
-usr/lib/libwebp.so.7.0.3
+usr/lib/libwebp.so.7.0.4
 usr/lib/libwebpdecoder.so.3
-usr/lib/libwebpdecoder.so.3.0.3
+usr/lib/libwebpdecoder.so.3.0.4
 usr/lib/libwebpdemux.so.2
-usr/lib/libwebpdemux.so.2.0.5
+usr/lib/libwebpdemux.so.2.0.6
 usr/lib/libwebpmux.so.3
-usr/lib/libwebpmux.so.3.0.3
+usr/lib/libwebpmux.so.3.0.4
```

**Comment by prspkt** [comment]
This is a minor, [ABI safe](https://abi-laboratory.pro/?view=timeline&l=libwebp), upgrade.

> - 1/14/2019: version 1.0.2
  This is a binary compatible release.

**Comment by jbergstroem** [comment]
> This is a minor, [ABI safe](https://abi-laboratory.pro/?view=timeline&l=libwebp), upgrade.

I was actually meaning to ask if Alpine really linked against minor/patch abi's. Guessing by your comment you're not.

**Comment by prspkt** [comment]
> > This is a minor, [ABI safe](https://abi-laboratory.pro/?view=timeline&l=libwebp), upgrade.
> 
> I was actually meaning to ask if Alpine really linked against minor/patch abi's. Guessing by your comment it isn't.

It is. We do link against both minor and major ABI levels.

**Comment by jbergstroem** [comment]
> It is. We do link against both minor and major ABI levels.

Ok. So, would the normal procedure be to bump the downstream packages via the same pull request? Happy to get it done.

**Comment by prspkt** [comment]
>Ok. So, would the normal procedure be to bump the downstream packages via the same pull request? 

The upgrade from `libwebp-1.0.1` to `libwebp-1.0.2` (this PR) does not introduce breakage to the binary interface which means there is no need to bump packages depending on the (`libwebp`) library.

**Comment by jbergstroem** [comment]
> The upgrade from libwebp-1.0.1 to libwebp-1.0.2 (this PR) does not introduce breakage to the binary interface which means there is no need to bump packages depending on the (libwebp) library.

Thanks for clarifying. I'll wait for a review/land then!

**Comment by jbergstroem** [comment]
ping!

**Comment by ncopa** [comment]
This was duped by #7244 which got merged with 0e776a422ea9019bcbcb054cf5745e5e3010fab4

I didn't check for dupes when I applied that. Sorry! (and sorry for the rude bot)

**Pull request closed without merging**
