### PR TITLE
main/abiword: add patch from upstream to fix black-screen regression

### PR DESCRIPTION
**Pull request by tmpfile**

### CODE REVIEW

**Comment by jirutka** [comment]
This patch does not apply, see the build log:

```
patching file src/af/xap/gtk/xap_UnixFrameImpl.cpp
Hunk #1 succeeded at 1208 with fuzz 1.
Hunk #2 FAILED at 1243.
1 out of 2 hunks FAILED -- saving rejects to file src/af/xap/gtk/xap_UnixFrameImpl.cpp.rej
patching file src/af/xap/gtk/xap_UnixFrameImpl.h
Hunk #1 FAILED at 152.
1 out of 1 hunk FAILED -- saving rejects to file src/af/xap/gtk/xap_UnixFrameImpl.h.rej
```

**Comment by ncopa** [comment]
can you also please merge the commits?

**Comment by tmpfile** [comment]
Fixed

**Comment by tmpfile** [comment]
Merged in https://github.com/alpinelinux/aports/commit/716d75cde8d7a694a98ef9fcc2f866b3f99e4857 but the issue wasn't auto-closed by https://github.com/jirutka/github-pr-closer so I'm closing manually.
A bug with the pr closer? cc @jirutka

**Pull request closed without merging**
