### PR TITLE
main/redis: upgrade to 4.0.12

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by andypost** [comment]
Maybe better to upgrade to 5.0.3? What @TBK thinks?

**Comment by J0WI** [comment]
`5.0.3` did not pass all checks out of the box.

**Comment by andypost** [comment]
Yep, I did quick check and not clear why it fails, that's why asked maintainer

**Comment by J0WI** [comment]
Fixed in 1be9716845f52b2d1035c9217b579899e580f4db, again without getting notified.

**Comment by TBK** [comment]
@andypost I am working on getting the 5.0.3 tests to pass. Will hopefully get it done this weekend.

**Comment by andypost** [comment]
Filed another upgrade https://github.com/alpinelinux/aports/pull/6701

**Pull request closed without merging**
