### PR TITLE
main/libinput: upgrade to 1.13.2

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by TBK** [comment]
`cd $builddir` can be removed.

**Comment by maxice8** [comment]
On Wed, May 22, 2019 at 08:01:09AM -0700, TBK wrote:
> `cd $builddir` can be removed.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7751#issuecomment-494841409

ncopa asked to not remove cd "$builddir" on default package functions on packages in main since the old versions of Alpine Linux doesn't have an abuild new enough (v3.3.0) to handle it.

apkbuild-lint ignores packages in main/ when doing such checks. (https://github.com/maxice8/atools/blob/master/apkbuild-lint#L198)

**Comment by TBK** [comment]
@maxice8 My comment was a mistake, thought it was in community.

**Comment by maxice8** [comment]
On Wed, May 22, 2019 at 06:53:42PM +0000, TBK wrote:
> @maxice8 My comment was a mistake, thought it was in community.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7751#issuecomment-494922247

No worries.

**Pull request closed without merging**
