### PR TITLE
main/samba: upgrade to 4.10.2

### PR DESCRIPTION
**Pull request by kr0k0**
Upgrade also talloc, tevent, cmocka, tdb and ldb to required/latest version.
Remove python2, as it will be EOL january next year.

### CODE REVIEW

**Comment by Ikke** [comment]
CI fails with the following error:

> ERROR: System library pyldb-util.cpython-37m-i386-linux-gnu of version 1.5.4 not found, and bundling disabled

**Comment by kr0k0** [comment]
Fix ldb test on 32bit arch with a patch which fedora uses.

Fix samba build with removing of include of "unistd.h" in "$builddir/lib/replace/replace.h", as it was also not included in past samba versions. Maybe you have a better solution.
Error was:
source4/heimdal/lib/asn1/asn1_err.c:47:23: error: 'link' redeclared as different kind of symbol
 static struct et_list link = { 0, 0 };
                              ^~~~
In file included from /usr/include/fortify/unistd.h:22,
                 from ../../lib/replace/../replace/replace.h:166,
                 from ../../source4/heimdal_build/config.h:10,
                 from source4/heimdal/lib/asn1/asn1_err.c:1:
/usr/include/unistd.h:56:5: note: previous declaration of 'link' was here
 int link(const char *, const char *);
     ^~~~

travis-ci build failed because of source download error:
curl: (16) Error in the HTTP2 framing layer
 Maybe you can restart the build.

Please review and merge if it's ok for you.

**Comment by rnalrd** [comment]
The samba makedepends on dbus is strictly needed?

**Comment by kr0k0** [comment]
Not strictly, but without the snapper vfs module isn't built.
Should I put it in a subpackage?

**Comment by rnalrd** [comment]
I have not investigated but if it saves pulling in multiple dependencies when installing samba or if it saves a significative amount of space (several hundreds KBs or more) probably it's worthy to move it into a subpkg.

**Comment by ncopa** [comment]
looks like samba depends on `cups` who depends on `avahi` who depends on `dbus` so the dbus libs will be pulled in regardless

**Comment by rnalrd** [comment]
Then I have no objections in merging this. It would be nice to have this in 3.10.

**Pull request closed without merging**
