### PR TITLE
main/imagemagick: build perlmagick packages and upgrade to 7.0.8.43

### PR DESCRIPTION
**Pull request by timlegge**
Build the PerlMagick perl modules of imagemagick

### CODE REVIEW

**Comment by TBK** [comment]
You forgot the ":" in the PR and commit name:

```
main/imagemagick build perlmagick packages
                ^
```

**Comment by timlegge** [comment]
commit message and PR title changed

**Comment by J0WI** [comment]
You need to bump `pkgrel` or update to `7.0.8.40+` (test suite [was broken](https://github.com/alpinelinux/aports/pull/6869#issuecomment-480949541) in `7.0.8.39`, not sure if it's already fixed).

**Comment by timlegge** [comment]
> You need to bump `pkgrel` or update to `7.0.8.40+` (test suite [was broken](https://github.com/alpinelinux/aports/pull/6869#issuecomment-480949541) in `7.0.8.39`, not sure if it's already fixed).

Thanks.  I keep forgetting that pkgrel.  I decided to bump the version it looks like the test suite is fixed.

**Comment by timlegge** [comment]
> > You need to bump `pkgrel` or update to `7.0.8.40+` (test suite [was broken](https://github.com/alpinelinux/aports/pull/6869#issuecomment-480949541) in `7.0.8.39`, not sure if it's already fixed).
> 
> Thanks. I keep forgetting that pkgrel. I decided to bump the version it looks like the test suite is fixed.

Apparently test suites are still broken on some arch reverting to 7.0.8.38

**Comment by timlegge** [comment]
> > > You need to bump `pkgrel` or update to `7.0.8.40+` (test suite [was broken](https://github.com/alpinelinux/aports/pull/6869#issuecomment-480949541) in `7.0.8.39`, not sure if it's already fixed).
> > 
> > 
> > Thanks. I keep forgetting that pkgrel. I decided to bump the version it looks like the test suite is fixed.
> 
> Apparently test suites are still broken on some arch reverting to 7.0.8.38

and missed the pkgrel again

**Comment by timlegge** [comment]
Closing new with current version - clean

**Pull request closed without merging**
