### PR TITLE
testing/proj4: upgrade to 6.1.0

### PR DESCRIPTION
**Pull request by hjaekel**
testing/proj4: upgrade to 6.1.0
* rename proj4 to proj
* add check()
* add subpackage for java bindings
* add subpackage for utilities
* add subpackage for datum grids
* fixes bug #10434

testing/libgeotiff: upgrade to 1.5.1 

testing/postgis: upgrade to 2.5.2

### CODE REVIEW

**Comment by hjaekel** [comment]
@ncopa this is a substantial change to the proj4 package, so I want to ask you as the maintainer of this package for a review.

**Comment by hjaekel** [comment]
@maxice8 I integrated the comments from your review to the PR. Thank you for the review.

**Comment by hjaekel** [comment]
I did as you requested in your review, but generally I think it is not a good idea to mention license issues in a depending package in a review for an upgrade of a package. For example, pdal was modified 2 months ago by the package maintainer, and license issues or empty variables were not mentioned in the review.

> for file testing/mapserver/APKBUILD:
> Are the depends necessary ? i think they should be auto-detected by so:

I cannot answer this question, please ask the package maintainer of mapserver.

> for file testing/pdal/APKBUILD:
> isn't the mv in the dev() wrong ? it will move the .so symlink to the main package

I cannot answer this question, please ask the package maintainer of pdal. But the `mv` is standing there since the first commit of pdal.

**Comment by MiniCodeMonkey** [comment]
The `libspatialite` package is currently broken. Looks like this change might fix it.

```
Step 6/32 : RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing libspatialite-dev
 ---> Running in 9a2a4293f8ab
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  so:libproj.so.13 (missing):
    required by: libspatialite-4.3.0a-r1[so:libproj.so.13]
```

**Comment by hjaekel** [comment]
You are right, Mathias, libspatiallite has to be rebuild against the new proj library with a small change in the build process. Commit 9874f32 includes those changes.

**Comment by hjaekel** [comment]
Closing this, will create smaller PRs instead.

**Pull request closed without merging**
