### PR TITLE
September Adélie merge: Development packages

### PR DESCRIPTION
**Pull request by awilfox**
This add test information and modernises 16 development-related packages, and also bumps a few to use Python 3 when building instead of Python 2 where available.  This does not actually change any Python bindings or py-* packages, which may be pushed later if desired (we have about 10 of these).

### CODE REVIEW

**Comment by awilfox** [comment]
* gobject-introspection cannot be migrated to Python 3 yet because it gets confused when Python 2 and 3 are both present on the build system, and its deps still pull in Python 2.
* CMake needed `file` which I didn't realise because my Alpine test box already had that installed for development purposes.
* Likewise, my Alpine test box had `diffutils` already so I didn't realise libidn needed it.

**Comment by awilfox** [comment]
It looks like libidn isn't passing because of a [missing patch in main/musl](http://git.musl-libc.org/cgit/musl/commit/?id=947d330f68c49680dcc54439f56da2a297228962).  We ship this in Adélie already; would a PR for that be welcome here?  All builds would pass then.

**Comment by kaniini** [comment]
Yes.

**Comment by ncopa** [comment]
merged. thanks!

**Pull request closed without merging**
