### PR TITLE
community/docker-edge: new aport providing docker edge releases (currently 18.02.0)

### PR DESCRIPTION
**Pull request by BernhardGruen**
Pack, ship and run any application as a lightweight container
http://www.docker.io

Heavily based on aport community/docker

### CODE REVIEW

**Comment by BernhardGruen** [comment]
Currently I don't check for an already installed docker apk. There should be some form of provide and conflict management. Don't know yet what would be the best way.

**Comment by ncopa** [comment]
Do we want both `docker` and `docker-edge` packages? Can't we just upgrade `community/docker` to 18.02.0? People who wants stable will use stable alpine branch (currently v3.7) and people who wants latest and greatest will use alpine edge.

**Comment by BernhardGruen** [comment]
The current stable version of Alpine (3.7) also had an edge release in it (17.10.0). Therefore I thought it would be nice to surely have both to choose from. At the moment one has to use a combination of edge and stable to get a stable docker release (17.12.1 vs. 17.10.0).

**Comment by ncopa** [comment]
I have pushed the docker stable to alpine 3.7.

**Comment by BernhardGruen** [comment]
As agreed Alpine Linux Edge versions can contain Docker Edge releases without fear. Stable Alpine Linux versions get the most current Docker CE stable version.

**Pull request closed without merging**
