### PR TITLE
main/openldap: add pbkdf2 subpackage

### PR DESCRIPTION
**Pull request by jbguerraz**
Provide a new subpackage for openldap in order to support pbkdf2 passwd

### CODE REVIEW

**Comment by andypost** [comment]
I think title should be `main/openldap: add pbkdf2 subpackage`

**Comment by jirutka** [comment]
Please squash your commits (i.e. effectively remove the move to testing), change commit message to `main/openldap: add pbkdf2 subpackage` and force push to this PR.

**Comment by andypost** [comment]
Looks ready! except `pkgrel=1` probably should be incremented

**Comment by jbguerraz** [comment]
thx @andypost :+1: 
@jirutka  : done :)

**Pull request closed without merging**
