### PR TITLE
main/argon2: upgrade to 20190702

### PR DESCRIPTION
**Pull request by andypost**
Ref https://github.com/P-H-C/phc-winner-argon2/releases

PHP adds dependency https://github.com/alpinelinux/aports/pull/9267

### CODE REVIEW

**Comment by ncopa** [comment]
Build fails with:
````
>>> argon2-libs*: Running split function libs...
>>> argon2-libs*: Preparing subpackage argon2-libs...
/usr/bin/abuild: cd: line 2293: can't cd to /home/ncopa/aports/main/argon2/pkg/argon2-libs: No such file or directory
>>> ERROR: argon2-libs*: prepare_package failed
````

It seems like it installs the libs in wrong location:
````
pkg/argon2
pkg/argon2/usr
pkg/argon2/usr/lib
pkg/argon2/usr/lib/x86_64-linux-gnu
pkg/argon2/usr/lib/x86_64-linux-gnu/libargon2.so
pkg/argon2/usr/lib/x86_64-linux-gnu/pkgconfig
pkg/argon2/usr/lib/x86_64-linux-gnu/pkgconfig/libargon2.pc
pkg/argon2/usr/lib/x86_64-linux-gnu/libargon2.so.1
pkg/argon2/usr/bin
pkg/argon2/usr/bin/argon2
````

Another thing I noticed was that the `subpackages` has duplicate `-dev`:
````sh
subpackages="$pkgname-dev $pkgname-dev $pkgname-libs"
````

**Comment by ncopa** [comment]
looking at the above file list, it also seems that we dont need to ship our own `libargon2.pc`.

**Comment by ncopa** [comment]
fixed with 7155035b6f2096543de30afe8ad25a4f017864b3

**Comment by acasademont** [comment]
Thank you all :)

**Pull request closed without merging**
