### PR TITLE
community/wlroots: upgrade to 0.8.1

### PR DESCRIPTION
**Pull request by Danct12**
Can you review this? @ddevault

Signed-off-by: Danct12 <danct12@disroot.org>

### CODE REVIEW

**Comment by ddevault** [comment]
Thanks!

**Comment by Ikke** [comment]
@ddevault @Danct12 There is a soname change. Do sway and cage need to be rebuilt for this as well?

**Comment by ddevault** [comment]
Yes, wlroots releases do not guarantee ABI compatibility.

**Comment by Ikke** [comment]
@Danct12 Can you add commits to this PR that bumps the pkgrel for sway and cage? Then this can be merged.

**Pull request closed without merging**
