### PR TITLE
main/py-setuptools: upgrade to 36.6.0

### PR DESCRIPTION
**Pull request by TBK**

### CODE REVIEW

**Comment by TBK** [comment]
@nmeum Is there an official guide line in terms of running Python test cases (check())?

Forgot when pushing this PR that py-tex is in testing.

**Comment by nmeum** [comment]
> Is there an official guide line in terms of running Python test cases (check())?

As fair as I know there isn't one, sorry! :(

**Comment by TBK** [comment]
@nmeum Okay, I took a look at https://github.com/alpinelinux/aports/pull/2607 and it also uses the tox test format.

Is there a Alpine Python master that can say if tox is the de facto standard test format?

**Comment by nmeum** [comment]
Well iirc @jirutka has done a lot of work on the python aports in the past. Maybe he can help out here...

**Comment by ncopa** [comment]
looks like this was superseeded by cb4892511d8e2b19aa36f1981b01f6981b541af2

**Pull request closed without merging**
