### PR TITLE
main/llvm5: upgrade to 5.0.2

### PR DESCRIPTION
**Pull request by J0WI**
See also #5317

### CODE REVIEW

**Comment by J0WI** [comment]
@ncopa is there a chance to get this merged or will there be an upgrade to LLVM 7 for Alpine 3.9 anyway?

**Comment by J0WI** [comment]
Remark: just run into the issue that `creduce` depends on LLVM 6.

**Comment by martell** [comment]
hmm, it seems difficult to get stuff merged upstream into alpine.
I presume devs don't have the bandwidth to review and merge community submissions.
I am going to cherrypick this commit along with others into one larger PR

**Comment by martell** [comment]
I did an effective cherrypick in https://github.com/alpinelinux/aports/pull/5717

**Comment by J0WI** [comment]
@martell if you cherry-pick this, you should also consider #5317

**Comment by martell** [comment]
I think that is mergable as is.
I didnt know you would be this responsive :)
can you update this also to address the conflict as it has a better chance of being merged alone faster.

**Comment by J0WI** [comment]
Rebased.

**Comment by ncopa** [comment]
we probably also want to upgrade lld and compiler-rt

**Comment by J0WI** [comment]
Fixed in b077914399313e45efe6d24a0fab0affbde1db21, thanks!

**Pull request closed without merging**
