### PR TITLE
testing/perl-spreadsheet-xlsx: modernize, fix license

### PR DESCRIPTION
**Pull request by maxice8**
@timlegge

### CODE REVIEW

**Comment by maxice8** [comment]
On Sun, May 26, 2019 at 02:13:34PM -0700, Timothy Legge wrote:
> timlegge approved this pull request.
> 
> @maxice8  LGTM.  BTW, if it will save you some time I can run back through the packages I submitted and make these changes...
> 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/8158#pullrequestreview-242055655

Would be super nice, i only check packages already in the repos

**Comment by timlegge** [comment]
> On Sun, May 26, 2019 at 02:13:34PM -0700, Timothy Legge wrote: timlegge approved this pull request. @maxice8 LGTM. BTW, if it will save you some time I can run back through the packages I submitted and make these changes... -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#8158 (review)](https://github.com/alpinelinux/aports/pull/8158#pullrequestreview-242055655)
> Would be super nice, i only check packages already in the repos

@maxice8 whats best one PR per package or one PR with one commit per package?

**Comment by maxice8** [comment]
On Sun, May 26, 2019 at 02:20:26PM -0700, Timothy Legge wrote:
> > On Sun, May 26, 2019 at 02:13:34PM -0700, Timothy Legge wrote: timlegge approved this pull request. @maxice8 LGTM. BTW, if it will save you some time I can run back through the packages I submitted and make these changes... -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#8158 (review)](https://github.com/alpinelinux/aports/pull/8158#pullrequestreview-242055655)
> > Would be super nice, i only check packages already in the repos
> 
> @maxice8 whats best one PR per package or one PR with one commit per package?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/8158#issuecomment-496032405

Any of them works really. Best is the one that suits your workflow better

**Comment by timlegge** [comment]
> On Sun, May 26, 2019 at 02:20:26PM -0700, Timothy Legge wrote: > On Sun, May 26, 2019 at 02:13:34PM -0700, Timothy Legge wrote: timlegge approved this pull request. @maxice8 LGTM. BTW, if it will save you some time I can run back through the packages I submitted and make these changes... -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#8158 (review)]([#8158 (review)](https://github.com/alpinelinux/aports/pull/8158#pullrequestreview-242055655)) > Would be super nice, i only check packages already in the repos @maxice8 whats best one PR per package or one PR with one commit per package? -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#8158 (comment)](https://github.com/alpinelinux/aports/pull/8158#issuecomment-496032405)
> Any of them works really. Best is the one that suits your workflow better

@maxice8 Done for all my submitted(in repos) packages in #8170 (at least I think I got them all)

**Pull request closed without merging**
