### PR TITLE
main/unbound - updated to v1.6.2

### PR DESCRIPTION
**Pull request by archey**
Corrected build issues with flex 2.6.3

### CODE REVIEW

**Comment by jirutka** [comment]
I’d be IMO better to backport fix from the flex’s master into our flex package, instead of switching to bundled flex.

**Comment by archey** [comment]
@jirutka Sure Ill make a patch for the flex 2.6.3 pkg to fix the issue and submit a pr

**Comment by archey** [comment]
@jirutka The issue that I see with patching flex, is there isnt a clear patch to fix this. We would have to pull in git master and patch from there, Im not sure thats the best idea. It might be better to hold off until the flex dev releases 2.6.4. 


https://github.com/westes/flex/issues/162
This commit may fix it https://github.com/westes/flex/commit/f5d87f1a26f4a5c3402497008ae10e9a1345d327 but as the dev states there maybe more thats needed.

**Comment by archey** [comment]
@jirutka this is fixed per https://github.com/alpinelinux/aports/pull/1363 by upgrading flex to 2.6.4 the issue is resolved

**Comment by jirutka** [comment]
This abuild was already updated in cba505e540efe9e4bd1ab73d0c11d504d10ab44e, but it misses some of your changes. If you like to apply them, please rebase it and open a new PR.

**Pull request closed without merging**
