### PR TITLE
main/luajit: add support for s390x

### PR DESCRIPTION
**Pull request by J0WI**
https://github.com/alpinelinux/aports/pull/7223#issuecomment-489543894
There are currently many other packages disabled for s390x because of this. Let's see if it works with nginx first.

### CODE REVIEW

**Comment by J0WI** [comment]
@jirutka could you have a look at this?

**Comment by J0WI** [comment]
@jirutka Could you review this please? This would make a lot of packages available on s390x.

**Comment by Cogitri** [comment]
What's the status of this upstream? I don't feel comfortable merging a 40k LOC patch.

**Comment by J0WI** [comment]
The upstream is not really maintained. There is a fork that contains the patch: https://github.com/siddhesh/LuaJIT
See https://github.com/LuaJIT/LuaJIT/pull/395#issuecomment-484036548

**Comment by Cogitri** [comment]
Maybe we could use that then? I don't want Alpine to become the one that has to support that patch.

**Comment by tuan-hoang1** [comment]
@J0WI : I would appreciate if you could split the patch into small ones, maybe like Fedora does : https://src.fedoraproject.org/rpms/luajit/tree/master. I believe current "upstream" fork  of LuaJIT also made them into small chunks.

**Comment by tuan-hoang1** [comment]
Or at least we can consider using the released version ? https://github.com/siddhesh/LuaJIT/releases

**Comment by tuan-hoang1** [comment]
@J0WI : I'm considering picking up patchsets from Fedora, where the maintainer frequently sends patches to. And also write things down in more details. Do you mind if I do that and open another PR ?

**Comment by tuan-hoang1** [comment]
https://gitlab.alpinelinux.org/alpine/aports/merge_requests/468

**Comment by J0WI** [comment]
Would be great to have this (respectively [this](https://gitlab.alpinelinux.org/alpine/aports/merge_requests/468)) before 3.11

**Comment by Cogitri** [comment]
Best to ask _ikke_ then, ncopa is busy preparing the release

**Comment by Cogitri** [comment]
Oops

**Pull request closed without merging**
