### PR TITLE
main: update checksums & modernize

### PR DESCRIPTION
**Pull request by refacto**
This is what `tmpfile` wanted to do in GitHub PR #1933, but redone,
and in a single commit. I used this script to do it:

```
for dir in $(grep -l md5sums $(find . -name APKBUILD) | sed 's/\/APKBUILD//')
do
        cd $dir
        sed -i 's/_builddir/builddir/g' APKBUILD
        sed -i 's/ || return 1//g' APKBUILD
        sed -i 's/|| return 1//g' APKBUILD
        sed -i 's/[ \t]*$//' APKBUILD
        sed -i ':a;N;$!ba;s/ \\\n\n/\n/g' APKBUILD
        sed -i 's/[ \t]*$//' APKBUILD
        abuild checksum
        cd ..
done
```

### CODE REVIEW

**Comment by refacto** [comment]
CI fails due to many, many rebuilds.

**Comment by ncopa** [comment]
are you sure this does not break anything? the v3.8 builders has built ~80% of the packages at this point and we dont want introduce any unexpected breakages at this point.

Can it wait til after v3.8 release?

**Comment by refacto** [comment]
Of course. No pressure. Will update once 3.8 is out.

**Comment by ncopa** [comment]
I am closing this meanwhile.

**Pull request closed without merging**
