### PR TITLE
testing/openjdk10: New aport

### PR DESCRIPTION
**Pull request by bratkartoffel**
This PR adds openjdk10 (patches based on #6179, should be preferred over #6468)

### CODE REVIEW

**Comment by J0WI** [comment]
Tested successfully on `x86_64`.

**Comment by J0WI** [comment]
I wonder if there are any blockers left to just merge this. Since this is in testing and just required to build `openjdk11` it should not harm anything.

**Comment by bratkartoffel** [comment]
As 3.10 release approaches we really need to get this merged: https://lists.alpinelinux.org/alpine-devel/6565.html

OpenJDK11 is still waiting and we have to move everything to community repo.

**Comment by bratkartoffel** [comment]
@Ikke Could you please merge this?

**Comment by J0WI** [comment]
> OpenJDK11 is still waiting and we have to move everything to community repo.

This should really get pushed into community now to be able to test it before the 3.10 release :alarm_clock:

**Comment by Ikke** [comment]
Merged as e320790, closing PR.

**Pull request closed without merging**
