### PR TITLE
testing/rippled: new aport

### PR DESCRIPTION
**Pull request by misery**

### CODE REVIEW

**Comment by misery** [comment]
Upstream PR: https://github.com/ripple/rippled/pull/2158

Issues:
 - https://github.com/ripple/rippled/issues/2159
 - https://github.com/ripple/rippled/issues/2160

**Comment by misery** [comment]
build at 98 %:

> The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by MarkusTeufelberger** [comment]
Why using cmake and not scons? Also I doubt that rippled does support libressl.

**Comment by misery** [comment]
Switched to scons ... unittests passed with libressl. Should it work then?

**Comment by MarkusTeufelberger** [comment]
No idea, openssl is listed by Ripple as required, libressl is not even mentioned. As far as I remembered, LibreSSL does not intend to stay a drop-in replacement of OpenSSL, it is at least not listed as a project goal there.

While you're updating stuff: The current version is 0.70.0

**Comment by misery** [comment]
Yeah, libressl removes a lot of stuff.

by the way.... looks like I should switch back to cmake

```
/usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lboost_context

/usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lboost_thread
```

**Comment by MarkusTeufelberger** [comment]
Seems weird that only these 2 libraries can't be found. Maybe something Alpine specific?

**Comment by MarkusTeufelberger** [comment]
I've pinged them about tagging them "properly" on Github, see https://github.com/ripple/rippled/issues/2174

In general, these are final and don't change.

**Comment by misery** [comment]
Something I need to change here?

**Pull request closed without merging**
