### PR TITLE
main/protobuf: upgrade to 3.1.0

### PR DESCRIPTION
**Pull request by yzlin**
protobuf 3.1.0 released.

### CODE REVIEW

**Comment by yzlin** [comment]
I've tested on alpine 3.2, 3.3, and 3.4. Logs show all built successfully and passed unit tests.

[3.2.txt](https://github.com/alpinelinux/aports/files/543657/3.2.txt)
[3.3.txt](https://github.com/alpinelinux/aports/files/543659/3.3.txt)
[3.4.txt](https://github.com/alpinelinux/aports/files/543658/3.4.txt)

Not sure why getting segfault in travis-ci env (in chrooted alpine?)

**Comment by jirutka** [comment]
I’ve reproduced the segfault even on my machine, so it’s not a Travis issue. Updates are merged to edge, so you should develop and test on edge. Could you please try to reproduce it on edge?

**Comment by jirutka** [comment]
Most probably it’s related to gcc version. I’ll try something…

**Comment by jirutka** [comment]
I’ve fixed it in 81689657d7f23ab9dadf666d03efe32bfa8137cd.

**Pull request closed without merging**
