### PR TITLE
[WiP] testing/ton-node: new aport

### PR DESCRIPTION
**Pull request by OTLabs**
https://test.ton.org
Telegram Open Network (TON) full node and validator

### CODE REVIEW

**Comment by maxice8** [comment]
Please find a way to properly install binaries your current packaging install a massive amount of garbage like:

```
+ usr/bin/
+ usr/bin/adnl-pong
+ usr/bin/adnl-proxy
+ usr/bin/benchmark
+ usr/bin/benchmark-fec
+ usr/bin/blockchain-explorer
+ usr/bin/create-state
+ usr/bin/dht-server
+ usr/bin/fift
+ usr/bin/func
+ usr/bin/generate-random-id
+ usr/bin/generate_common
+ usr/bin/generate_mime_types_gperf
+ usr/bin/io-bench
+ usr/bin/json2tlo
+ usr/bin/libtonlibjson.so.0.5
+ usr/bin/lite-client
+ usr/bin/tcp_ping_pong
+ usr/bin/test-adnl
+ usr/bin/test-block
+ usr/bin/test-catchain
+ usr/bin/test-cells
+ usr/bin/test-db
+ usr/bin/test-dht
+ usr/bin/test-ed25519
+ usr/bin/test-ed25519-crypto
+ usr/bin/test-fec
+ usr/bin/test-fift
+ usr/bin/test-hello-world
+ usr/bin/test-net
+ usr/bin/test-rldp
+ usr/bin/test-tdactor
+ usr/bin/test-tddb
+ usr/bin/test-tdutils
+ usr/bin/test-ton-collator
+ usr/bin/test-tonlib
+ usr/bin/test-tonlib-offline
+ usr/bin/test-validator-session-state
+ usr/bin/test-vm
+ usr/bin/tlbc
+ usr/bin/tonlib_generate_java_api
+ usr/bin/udp_ping_pong
+ usr/bin/validator-engine
+ usr/bin/validator-engine-console
```

**Comment by maxice8** [comment]
also please disable the static libraries

**Comment by OTLabs** [comment]
I will check how to solve this issues modifying CMake. Taggin WiP for now. Thank you.

**Comment by OTLabs** [comment]
Source files are not available any more from original location, they have been moved to https://github.com/ton-blockchain/ton.

Closing this PR in waiting for first release at new location.

**Pull request closed without merging**
