### PR TITLE
community/py3-yarl: new aport

### PR DESCRIPTION
**Pull request by fabaff**
The module provides handy URL class for url parsing and changing.

http://yarl.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by jirutka** [comment]
New aports must go into the testing repository first.

**Comment by fabaff** [comment]
If a package needs to go to `testing` first, how is the update of aiohttp handled? In the past packages in `main` and I assume that this would cover `community` too shouldn't depend on those in `testing`.

**Comment by jirutka** [comment]
> If a package needs to go to `testing` first, how is the update of aiohttp handled?

If this package is needed for another one, that is already in the community repository, then you should write this in the commit message.

**Comment by fabaff** [comment]
My bad. Seems that referencing GitHub PRs doesn't work well in that case.

**Comment by jirutka** [comment]
My bad, I overlooked that you’ve referenced it. However, it still should be mentioned in the commit message, because comments on GitHub are not visible in git log.

**Pull request closed without merging**
