### PR TITLE
main/gnupg: update to 2.2.15

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by tcely** [comment]
Merged in https://github.com/alpinelinux/aports/commit/bb802757b7bc796ddad58f348d9bc91580c1e64b by @nmeum ?

**Comment by nmeum** [comment]
Yep, somehow @algitbot doesn't seem to autoclose @J0WI's PRs :man_shrugging:

Anyway: Thanks!

**Comment by tcely** [comment]
It looks like the change from `update` to `upgrade` could be confusing @algitbot

**Comment by nmeum** [comment]
It shouldn't, algitbot identifies commits using the authors email, name and commit date [\[1\]][1]. Besides this issues also applies to other PRs created by @J0WI and merged by myself, e.g. #6830. In fact I am unsure if @algitbot ever correctly closed a PR opened by @J0WI.

[1]: https://github.com/jirutka/github-pr-closer#why

**Pull request closed without merging**
