### PR TITLE
testing/crypto++: upgrade to 8.2.0

### PR DESCRIPTION
**Pull request by russkel**
This package has been out of date for quite a long time and didn't correctly package the shared libraries.

Upgraded to latest version released in April, added check and now uses provided install make targets to correctly install all soversioned libs.

### CODE REVIEW

**Comment by maxice8** [comment]
This problably applies:

- Needs to bump revision on packages that link to crypto++ since the library soname has changed.

**Comment by maxice8** [comment]
Yep.

```
crypto++-8.2.0-r0 provides:
so:libcryptopp.so.8=8.2.0

crypto++-5.6.5-r1 provides:
so:libcryptopp.so.5.6=0
```

**Comment by russkel** [comment]
> Needs to bump revision on packages that link to crypto++ since the library soname has changed.

Do I need to do this or is it automated?

**Comment by maxice8** [comment]
On Mon, Jun 03, 2019 at 01:02:21AM -0700, Russ wrote:
> > Needs to bump revision on packages that link to crypto++ since the library soname has changed.
> 
> Do I need to do this or is it automated?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/8441#issuecomment-498154379

You need to include 2 other commits, one that bumps pkgrel for entropybuker and the other that bumps pkgrel for amule

**Comment by russkel** [comment]
Okay will do.

Also, I wasn't able to find where to report this, but on https://pkgs.alpinelinux.org/package/edge/testing/x86_64/crypto++ when you click package contents it fails to work due to the dicky package name containing pluses.

**Comment by maxice8** [comment]
On Mon, Jun 03, 2019 at 01:05:28AM -0700, Russ wrote:
> Okay will do.
> 
> Also, I wasn't able to find where to report this, but on https://pkgs.alpinelinux.org/package/edge/testing/x86_64/crypto++ when you click package contents it fails to work due to the dicky package name containing pluses.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/8441#issuecomment-498155346

You can use apk info -P to see what a package provides.

apk info -P crypto++ will show what each version of crypto++ found provide.

**Comment by russkel** [comment]
Thanks, I am aware of that, I just wanted that bug to get to the right place :)

**Comment by tcely** [comment]
> Thanks, I am aware of that, I just wanted that bug to get to the right place :)

Please file the bug at: https://bugs.alpinelinux.org/projects/alpine-infra/issues/new

**Comment by tcely** [comment]
See also alpinelinux/aports#8223.

**Comment by russkel** [comment]
Ugh, entropybroker is at the most recent version but doesn't compile.

**Comment by russkel** [comment]
Should I merge the amule PR #8223 commits into this PR?

**Comment by maxice8** [comment]
Feel free

**Comment by russkel** [comment]
I raised the error with the entropybroker author, but he seems uninterested in fixing it. And I don't have time to patch -what seems to be- abandonware.

**Comment by maxice8** [comment]
Feel free to drop it, projects that don't follow the API are not worth the investment to keep going

**Comment by maxice8** [comment]
I moved to unmaintained it won't cause problems anymore

**Comment by tcely** [comment]
@russkel please rebase this beyond https://github.com/alpinelinux/aports/commit/134a01279b0dd3fbabd7f81fe28fabcee64adfc6

**Comment by russkel** [comment]
Rebased & removed entropybroker commits.

**Pull request closed without merging**
