### PR TITLE
testing/proj4: upgrade to 6.1.0

### PR DESCRIPTION
**Pull request by kelvinn**

### CODE REVIEW

**Comment by maxice8** [comment]
Duplicate of #7938

**Comment by kelvinn** [comment]
Thank you @maxcnunes for the review! I tried to specify just sqlite-dev, but abuild (with a -r) failed specifying that sqlite was needed, so I explicitly added it. The remaining APKBUILD is unchanged.

**Comment by maxice8** [comment]
Please ignore that then, sqlite-dev is correctly depending on sqlite-libs while sqlite just holds the binary

**Comment by kelvinn** [comment]
@maxice8 - squashed commits. Thanks!

**Comment by andypost** [comment]
It is ok to commit it before #7938 just require to bump related packages because of soname change
```diff
-usr/lib/libproj.so.13
-usr/lib/libproj.so.13.1.1 
+usr/lib/libproj.so.15 
+usr/lib/libproj.so.15.1.0 
```
So `libgeotiff` needs bump

**Pull request closed without merging**
