### PR TITLE
community/qt5: upgrade to 5.12.4

### PR DESCRIPTION
**Pull request by PureTryOut**

### CODE REVIEW

**Comment by maxice8** [comment]
Needs to update checksum

**Comment by PureTryOut** [comment]
I know, working on it :wink:

**Comment by fcolista** [comment]
How to deal with these kind of errors?

**TravisCI:** `The job exceeded the maximum time limit for jobs, and has been terminated.`
**DroneCI:** `warning: maximum output exceeded`

**Comment by fcolista** [comment]
How to deal with builds that requires time, since CIs have this kind of limits?
Any possible workaround?

**TravisCI:** `The job exceeded the maximum time limit for jobs, and has been terminated.`
**DroneCI:** `warning: maximum output exceeded`

**Comment by ncopa** [comment]
> How to deal with builds that requires time, since CIs have this kind of limits?
> Any possible workaround?

I'm test building it in my dev env.

**Pull request closed without merging**
