### PR TITLE
main/fsarchiver: upgrade to 0.8.4, fix license

### PR DESCRIPTION
**Pull request by dai9ah**
~~added support for zstd compression~~
package built without zstd support, until further notice.

### CODE REVIEW

**Comment by nmeum** [comment]
zstd is currently in `community/` packages from `main/` can't depend on packages from `community/`.  If you really need to depend on zstd you either need to move zstd from `community/` to `main/` or move fsarchiver from `main/` to `community/`. I would personally prefer the later.

**Comment by dai9ah** [comment]
@nmeum since zstd isn't a hard dependency, fsarchiver 0.8.4 can be successfully built without zstd support. is this preferable?

**Comment by nmeum** [comment]
It didn't depend on zstd before, so yeah that's probably preferable. Anyway, @jirutka is the maintainer of this aport he might have an opinion on this.

**Comment by jirutka** [comment]
I dunno, I don’t use this package myself, so don’t know if/how useful is support for zstd in fsarchiver.

**Comment by nmeum** [comment]
> I dunno, I don’t use this package myself, so don’t know if/how useful is support for zstd in fsarchiver.

Well…in that case, not adding zstd support for now seems to be a good idea. Merged it, thanks for the patch @dai9ah!

**Pull request closed without merging**
