### PR TITLE
community/composer: upgreade to 1.8.4

### PR DESCRIPTION
**Pull request by andypost**
https://github.com/composer/composer/releases/tag/1.8.4

### CODE REVIEW

**Comment by andypost** [comment]
@skwashd another update

**Comment by skwashd** [comment]
@andypost LGTM. I'm sure there's another one just around the corner.

**Comment by andypost** [comment]
@skwashd do you mean 1.9? cos I see no activity after this release

**Comment by skwashd** [comment]
I meant another patch release.

**Pull request closed without merging**
