### PR TITLE
main/py3-urwid: drop py2

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Ikke** [comment]
Dependencies are missing.

**Comment by maxice8** [comment]
On Thu, 26 Sep 2019 10:48:20 -0700
Kevin Daudt <notifications@github.com> wrote:

> Dependencies are missing.
> 

Which dependencies ?

**Comment by Ikke** [comment]
> \>\>\> py3-urwid: Analyzing dependencies...
> ERROR: unsatisfiable constraints:
>   py3-pyhamcrest (missing):
>     required by: py3-twisted-19.2.1-r2[py3-pyhamcrest]
>   py3-hyperlink (missing):
>     required by: py3-twisted-19.2.1-r2[py3-hyperlink]
>   py3-automat (missing):
>     required by: py3-twisted-19.2.1-r2[py3-automat]

**Comment by maxice8** [comment]
@Ikke

**Pull request closed without merging**
