### PR TITLE
testing/zbar: drop support for py2 bindings

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
@ncopa

**Comment by TBK** [comment]
0.23 released - https://github.com/mchehab/zbar/blob/0.23/ChangeLog

Issue tracking py3 support - https://github.com/mchehab/zbar/pull/44

**Comment by maxice8** [comment]
On Fri, May 24, 2019 at 08:54:55PM -0700, TBK wrote:
> 0.23 released - https://github.com/mchehab/zbar/blob/0.23/ChangeLog
> 
> Issue tracking py3 support - https://github.com/mchehab/zbar/pull/44
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7699#issuecomment-495842944

Updated with py3-zbar

**Comment by TBK** [comment]
@diequeiroz please review

**Pull request closed without merging**
