### PR TITLE
main/perl: upgrade to 5.28.1

### PR DESCRIPTION
**Pull request by andypost**
https://metacpan.org/pod/release/XSAWYERX/perl-5.28.0/pod/perldelta.pod

### CODE REVIEW

**Comment by ncopa** [comment]
this is an upgrade from 5.26 and will require rebuild of alot of packages. I don't think we should wait til after v3.9.

**Comment by ncopa** [comment]
we should upgrade to 5.26.3 for now.

**Comment by andypost** [comment]
Makes a lot of sense - better to delay upgrade til next minor because there's a lot of changes (unicode is main one)

**Comment by andypost** [comment]
@ncopa any idea how to identify packages which needs rebuild?

**Comment by andypost** [comment]
@ncopa guess it should wait for 3.10 now?

**Comment by andypost** [comment]
Fixed with 86b5b86c35 6d70352d3a

**Pull request closed without merging**
