### PR TITLE
main/bluez: upgrade to 5.50

### PR DESCRIPTION
**Pull request by J0WI**
Depends on #5790

### CODE REVIEW

**Comment by andypost** [comment]
Packages from main can't depends on testing ones

**Comment by J0WI** [comment]
WFM locally, but Travis builds them in the wrong order.

**Comment by J0WI** [comment]
Do I need to split the PR to fix the build?

**Comment by andypost** [comment]
@ncopa are you fine with dependency for main in community repo?

**Comment by J0WI** [comment]
Fixed in 750ba06cdd17ab77ab47dc68d42bd9d16136b1f1

**Pull request closed without merging**
