### PR TITLE
/community/fortune: Provide support for aarch64

### PR DESCRIPTION
**Pull request by ossdev07**
Architecture specific condition has been added for aarch64.

### CODE REVIEW

**Comment by TBK** [comment]
Here is a modernized version:
```
# Contributor: Andrew Hills <ahills@ednos.net>
# Maintainer: Andrew Hills <ahills@ednos.net>
pkgname=fortune
pkgver=0.1
pkgrel=0
pkgdesc="Fortune cookie program ported from OpenBSD"
url="https://github.com/ahills/fortune"
arch="all"
license="BSD-3-Clause"
options="!check" # No test suite
makedepends="libbsd-dev"
subpackages="$pkgname-doc"
source="$pkgname-$pkgver.tar.gz::https://github.com/ahills/fortune/archive/v$pkgver.tar.gz"

build() {
	make PREFIX=/usr
}

package() {
	make PREFIX=/usr DESTDIR="$pkgdir" install
}

sha512sums="11c883aef8fafea6237fcd1b45fbbb169d6996a253f1def720dd9379c4bfe1bad050789c6e89eb7f1960abde54fe04d85fd13148bd0af8528de630611c0e6e48  fortune-0.1.tar.gz"

```

**Comment by ossdev07** [comment]
Sure @TBK @maxice8 I agree with you.

I have checked the APKBUILD file with the changes you suggested if you want I can update the PR.

**Comment by TBK** [comment]
@ossdev07 You can just squash the commits if you have several and the force push to update the PR.

**Comment by ossdev07** [comment]
@TBK  I have done changes in the APKBUILD file and committed the code. 
If anything else is required from my side, please let me know.

**Pull request closed without merging**
