### PR TITLE
community/tor: upgrade to 0.4.0.5

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by Ikke** [comment]
Test failed on x86:

> FAIL src/test/test_prob_distr.c:426: assert(ok)
> [logit_logistics FAILED]

**Comment by maxice8** [comment]
Any progress on this ?

**Comment by maxice8** [comment]
This can be closed

**Comment by Ikke** [comment]
This was merged in 5e48a5a.

Closing

**Pull request closed without merging**
