### PR TITLE
testing/lua-uuid: remove, present in main/

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by andypost** [comment]
The one in testing is a fork added in 7346ec2ebc

**Comment by maxice8** [comment]
How to proceed ? merge the changes of the fork (which i assume has bugfixes and other stuff) ?

**Comment by andypost** [comment]
Probably, as I see in testing 3 lua versions are supported

**Comment by maxice8** [comment]
On Sun, May 12, 2019 at 03:27:05PM -0700, Andy Postnikov wrote:
> Probably, as I see in testing 3 lua versions are supported
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7852#issuecomment-491634590

Pushed new version, please re-check

**Comment by andypost** [comment]
Looks good to go but needs @clandmeter to approve/commit

**Pull request closed without merging**
