### PR TITLE
main/ldns: fixed pkgconfig file variables resolving

### PR DESCRIPTION
**Pull request by sergey-safarov**

### CODE REVIEW

**Comment by ncopa** [comment]
I'm not sure what problem this solves? How is variables resolving broken? any test case?

**Comment by sergey-safarov** [comment]
Please check [FreeSwitch build logs](https://cloud.drone.io/alpinelinux/aports/9821)
As you can see
```
making all mod_enum
--
4790 | make[4]: Entering directory '/home/buildozer/aports/main/freeswitch/src/freeswitch-1.8.7/src/mod/applications/mod_enum'
4791 | CC       mod_enum_la-mod_enum.lo
4792 | CCLD     mod_enum.la
4793 | /home/buildozer/aports/main/freeswitch/src/freeswitch-1.8.7/libtool: cd: line 1: can't cd to xec_prefix/lib: No such file or directory
4794 | libtool:   error: cannot determine absolute directory name of 'xec_prefix/lib'
4795 | make[4]: *** [Makefile:663: mod_enum.la] Error 1
4796 | make[4]: Leaving directory '/home/buildozer/aports/main/freeswitch/src/freeswitch-1.8.7/src/mod/applications/mod_enum'
4797 | make[3]: *** [Makefile:695: mod_enum-all] Error 1
4798 | make[3]: Leaving directory '/home/buildozer/aports/main/freeswitch/src/freeswitch-1.8.7/src/mod'
4799 | make[2]: *** [Makefile:598: all-recursive] Error 1
4800 | make[2]: Leaving directory '/home/buildozer/aports/main/freeswitch/src/freeswitch-1.8.7/src'
4801 | make[1]: *** [Makefile:3658: all-recursive] Error 1
4802 | make[1]: Leaving directory '/home/buildozer/aports/main/freeswitch/src/freeswitch-1.8.7'
4803 | make: *** [Makefile:1413: all] Error 2
```
That because freeeswitch cannot resolve variable `exec_prefix=\$prefix` using automake/autoconf creates `Makefiles` with unresolved pkg-config variables.

Please, make FreeSwitch abuild when this PR is applied.

**Comment by tcely** [comment]
Was this merged in 2c7b31c?

**Comment by sergey-safarov** [comment]
yes, this PR is merged.
I close PR

**Pull request closed without merging**
