### PR TITLE
testing/py-google-apputils: new aport

### PR DESCRIPTION
**Pull request by little-dude**
Decription: collection of utilities for building Python applications
Project URL: https://github.com/google/google-apputils

### CODE REVIEW

**Comment by little-dude** [comment]
Needed for https://github.com/alpinelinux/aports/pull/76

**Comment by jirutka** [comment]
You’re author of this apkbuild, aren’t you? Then you should add yourself as a contributor – `# Contributor: Corentin Henry <corentinhenry@gmail.com>` at the first line. Otherwise this PR is okay.

**Comment by jirutka** [comment]
You’re author of this apkbuild, aren’t you? Then you should add yourself as a contributor – `# Contributor: Corentin Henry <corentinhenry@gmail.com>` at the first line. Besides that this PR is okay.

**Comment by jirutka** [comment]
Merged in 759d4ff57352f891b00f6b073883b8d12a43b0cc, thanks!

**Comment by little-dude** [comment]
Thank you!

**Pull request closed without merging**
