### PR TITLE
community/mongodb: upgrade to 4.0.1, modernize

### PR DESCRIPTION
**Pull request by andypost**
https://docs.mongodb.com/manual/release-notes/4.0/#minor-releases

Closes #9245

### CODE REVIEW

**Comment by jirutka** [comment]
Build failed, please see the log.

**Comment by andypost** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

Build time is not enough to build

**Comment by jirutka** [comment]
It has failed before running out of time when I checked it first. Now it looks ok.

**Comment by jirutka** [comment]
I’ve tried to build it locally:

```
...
Install file: "build/opt/mongo/mongos" as "mongos"
scons: done building targets.
>>> mongodb: Entering fakeroot...
make: *** No rule to make target 'test'.  Stop.
>>> ERROR: mongodb*: check failed
>>> ERROR: mongodb: all failed
```

**Comment by andypost** [comment]
Yep, looks we need to skip tests here https://github.com/mongodb/mongo/wiki/Test-The-Mongodb-Server

**Comment by ncopa** [comment]
@andypost can you please rebase it? It also seems to fail on my dev machine due it tries build a bundled version of gperftools.

**Comment by TBK** [comment]
Version 3.6.3 was released on February 23, 2018 - https://docs.mongodb.com/manual/release-notes/3.6/

**Comment by TBK** [comment]
Would also be great if more archs could be supported.

**Comment by andypost** [comment]
Closes #9245

**Comment by andypost** [comment]
@jirutka or @clandmeter please check the PR package is not working in edge

**Comment by andypost** [comment]
x86-64 build wend fine except 
```
>>> mongodb*: Running postcheck for mongodb
>>> WARNING: mongodb*: Found OpenRC directory (/etc/conf.d or /etc/init.d) but name doesn't end with -openrc
```

**Pull request closed without merging**
