### PR TITLE
community/go: upgrade to 1.12.1

### PR DESCRIPTION
**Pull request by clstb**
https://golang.org/doc/devel/release.html#go1.12.minor

### CODE REVIEW

**Comment by andypost** [comment]
armfhf/armv7 fails on test
```
# plugin.test
/home/buildozer/drone/aports/community/go/src/go/pkg/tool/linux_arm/link: running gcc failed: exit status 1
collect2: fatal error: cannot find 'ld' compilation terminated. 
```

**Comment by clstb** [comment]
Thanks, I am aware. Will investigate soon.

**Comment by ncopa** [comment]
this is a duplicate of #6519

**Comment by nmeum** [comment]
The problem seems to be that go uses gold ld on ARM and ARM64. See https://github.com/golang/go/blob/master/src/cmd/link/internal/ld/lib.go#L1228-L1247 gold is packaged in a binutils subpackage and not installed by default. Adding binutils-gold to checkdepends fixes this.

See: #6838 

The only remaining question is whether binutils-gold should also be added to depends instead of checkdepends on ARM*.

**Pull request closed without merging**
