### PR TITLE
testing/neko: move to community

### PR DESCRIPTION
**Pull request by andyli**
neko has been in testing for some time and it is quite stable. I will take care of maintaining it in the long run.

### CODE REVIEW

**Comment by jirutka** [comment]
Why does `neko` package depend on mariadb-client-libs, sqlite-libs and gtk+2.0? Could be libs linked with these separated into subpackages?

**Comment by andyli** [comment]
A typical neko installation comes with database and ui supports (in the form of APIs in the neko standard library). They are isolated in the mysql.ndll, sqlite.ndll, and ui.ndll files. It is possible to separate the ndll files into subpackages.

However, I wonder if is it normally done for other alpine packages? e.g. python3 also depends on sqlite-lib.
Another question, what does a user suppose to depend on when creating a neko program? In case mysql support is needed, depend on both neko and neko-mysql?

**Comment by ncopa** [comment]
We normally make subpackages for "plugins" which are optional, so for example, you can normaly chose if you want use postgresql or mariadb(mysql) as database backend. It may make sense to have a minimal default, like sqlite, so package works out of the box, but can be extended.

An example package is [main/apr-util](https://github.com/alpinelinux/aports/blob/master/main/apr-util/APKBUILD).

I did a scanelf to find what may make sense:
````console
ncopa-edge-x86_64:~/aports/testing/neko$ scanelf -Rn pkg/neko
 TYPE   NEEDED FILE 
ET_DYN libneko.so.2,libmbedtls.so.10,libmbedcrypto.so.0,libmbedx509.so.0,libc.musl-x86_64.so.1 pkg/neko/usr/lib/neko/ssl.ndll 
ET_DYN libneko.so.2,libgtk-x11-2.0.so.0,libgdk-x11-2.0.so.0,libc.musl-x86_64.so.1 pkg/neko/usr/lib/neko/ui.ndll 
ET_DYN libneko.so.2,libsqlite3.so.0,libc.musl-x86_64.so.1 pkg/neko/usr/lib/neko/sqlite.ndll 
ET_DYN libneko.so.2,libz.so.1,libc.musl-x86_64.so.1 pkg/neko/usr/lib/neko/zlib.ndll 
ET_DYN libneko.so.2,libpcre.so.1,libc.musl-x86_64.so.1 pkg/neko/usr/lib/neko/regexp.ndll 
ET_DYN libapr-1.so.0,libc.musl-x86_64.so.1 pkg/neko/usr/lib/neko/mod_tora2.ndll 
ET_DYN libneko.so.2,libmysqlclient.so.18,libc.musl-x86_64.so.1 pkg/neko/usr/lib/neko/mysql.ndll 
ET_DYN libneko.so.2,libc.musl-x86_64.so.1 pkg/neko/usr/lib/neko/std.ndll 
ET_DYN libneko.so.2,libc.musl-x86_64.so.1 pkg/neko/usr/lib/neko/mysql5.ndll 
ET_DYN libneko.so.2,libapr-1.so.0,libc.musl-x86_64.so.1 pkg/neko/usr/lib/neko/mod_neko2.ndll 
ET_DYN libneko.so.2,libc.musl-x86_64.so.1 pkg/neko/usr/bin/nekoc 
ET_DYN libneko.so.2,libc.musl-x86_64.so.1 pkg/neko/usr/bin/neko 
ET_DYN libneko.so.2,libc.musl-x86_64.so.1 pkg/neko/usr/bin/nekotools 
ET_DYN libneko.so.2,libc.musl-x86_64.so.1 pkg/neko/usr/bin/nekoml 
````

I think it may make sense to have `usr/lib/neko/mysql.ndll`, `usr/lib/neko/ui.ndll` and possibly `usr/lib/neko/mod_tora2.ndll` in their own subpackages so you can save some space if you dont need any of those.

**Comment by andyli** [comment]
Alright, I think it makes sense since alpine is meant to be small. I've just added 3 subpackages for the mysql, ui, and apache2 supports as suggested.

**Comment by andyli** [comment]
Hmm... the CI build fails now since it is not able to install mpfr3:
```
(27/69) Installing mpfr3 (3.1.5-r1)
ERROR: mpfr3-3.1.5-r1: package mentioned in index not found (try 'apk update')
```

I successfully built neko in my Alpine VM though.

**Comment by andyli** [comment]
The [build over my fork](https://travis-ci.org/andyli/aports/builds/341334988) succeed. It failed with the same error as here before, so I think that was a temp issue.

**Comment by andyli** [comment]
Just did a rebase and the CI is green now.

**Pull request closed without merging**
