### PR TITLE
py-mongo: reverted py-mongo

### PR DESCRIPTION
**Pull request by sergey-safarov**
py-mongo: reverted part of 8a901de31fa055ed591d487e12f8bb9ffcc0df21 commit
py-mongo use [Apache 2.0 license](https://github.com/mongodb/mongo-python-driver/blob/master/LICENSE)

### CODE REVIEW

**Comment by maxice8** [comment]
Please use our commit naming scheme for moving packages

also have a second commit that bumps pkgrel

**Comment by sergey-safarov** [comment]
Could you give me link to `commit naming scheme for moving packages`.

**Comment by maxice8** [comment]
Examples are on the git tree

**Comment by sergey-safarov** [comment]
Commit messaged updated like ff536b4ae1096012a5bb613360a32dfaba6470e8

**Pull request closed without merging**
