### PR TITLE
testing/libtorrent-rasterbar: downgrade to 1.0.9

### PR DESCRIPTION
**Pull request by AmatCoder**
1) Fix arm build
2) Version 1.1.0 is not supported by deluge: http://forum.deluge-torrent.org/viewtopic.php?f=7&t=53939

### CODE REVIEW

**Comment by jirutka** [comment]
Please update also deluge package – specify version range `libtorrent-rasterbar<1.1.0`; add it to this PR.

**Comment by AmatCoder** [comment]
Done.

**Comment by jirutka** [comment]
It seems that @ncopa already solved the issue with ARM, look at 1e34267.

**Comment by ncopa** [comment]
yes the problem should be fixed. they also fixed it upstream.

**Comment by ncopa** [comment]
whoops i didnt notice that deluge don't support 1.1.0.

**Comment by AmatCoder** [comment]
Does this PR need to be redone?

**Comment by jirutka** [comment]
Not needed, I’ve already done it: http://tpaste.us/Gx6D.

**Comment by jirutka** [comment]
Merged in e6a93067628ddaebc53c01a34632287aeb0f30c7. Sorry for unintentional squashing into a single commit.

Thanks for your pull request!

**Pull request closed without merging**
