### PR TITLE
main/py-certifi: upgrade to 2019.3.9

### PR DESCRIPTION
**Pull request by dimon222**
https://github.com/certifi/python-certifi/commits/master

### CODE REVIEW

**Comment by andypost** [comment]
@dimon222 do you wanna take over maintainer?

**Comment by dimon222** [comment]
@andypost sure, no problem. I can rebase with new name

**Comment by dimon222** [comment]
@andypost added maintainer, good now

**Comment by dimon222** [comment]
Closing because its been already merged into master.

**Pull request closed without merging**
