### PR TITLE
community/perl-io*: fix URL&License

### PR DESCRIPTION
**Pull request by Cogitri**
* modernize

### CODE REVIEW

**Comment by Cogitri** [comment]
Maintainer-ping: @fcolista @itoffshore @rnalrd @fabled @ncopa

**Comment by maxice8** [comment]
Please rebase

**Comment by Cogitri** [comment]
Rebased

**Comment by ncopa** [comment]
merged all except `main/perl-io-async` which needs another rebase. sorry

**Comment by Cogitri** [comment]
No worries, will rebase when home.

**Comment by Cogitri** [comment]
Kind of forgot about this, sorry. Rebased.

**Comment by rnalrd** [comment]
package() is broken. There's no files actually installed in $pkgdir

**Comment by Cogitri** [comment]
Ah, rebasing went wrong, will correct after a nap

**Comment by Cogitri** [comment]
Fixed

**Pull request closed without merging**
