### PR TITLE
main/libuv: upgrade to 1.28.0

### PR DESCRIPTION
**Pull request by OTLabs**
https://github.com/libuv/libuv/releases 1.28.0

### CODE REVIEW

**Comment by TBK** [comment]
100% BC - https://abi-laboratory.pro/index.php?view=objects_report&l=libuv&v1=1.26.0&v2=1.27.0

**Comment by TBK** [comment]
Drone on x86_64:
```
not ok 130 - ipc_closed_handle
--
```

**Comment by OTLabs** [comment]
Test failing on Drone x86 too.

Same time Travis is ok. And Dron arm* are ok.

**Comment by OTLabs** [comment]
Upgraded to 1.28.0.
Travis CI is ok.
Drone x86 and x86_64 both fail for same test `not ok 135 - ipc_closed_handle`.
Drone arm archies are ok.

**Pull request closed without merging**
