### PR TITLE
testing/libtickit: upgrade to 0.3.2

### PR DESCRIPTION
**Pull request by maxice8**
- Use modern style
- Enable check again
- Split $pkganme-static

### CODE REVIEW

**Comment by maxice8** [comment]
@rgdoliveira

**Comment by Ikke** [comment]
@maxice8 libtickit is currently failing in [x86_64][] and [x86][]. Looks like some error during testing.

[x86_64]:https://build.alpinelinux.org/buildlogs/build-edge-x86_64/testing/libtickit/libtickit-0.3.2-r0.log
[x86]:https://build.alpinelinux.org/buildlogs/build-edge-x86/testing/libtickit/libtickit-0.3.2-r0.log

**Comment by maxice8** [comment]
Noted but won't be available for 10 to 12 hours

**Comment by Ikke** [comment]
ncopa disabled this lib in x86(_64) for now to unblock the builders.

**Pull request closed without merging**
