### PR TITLE
community/virtualbox-guest-additions: upgrade to 5.2.22

### PR DESCRIPTION
**Pull request by gena01**

### CODE REVIEW

**Comment by andypost** [comment]
Looks like duplicate of https://github.com/alpinelinux/aports/pull/5644

**Comment by gena01** [comment]
@andypost this is actually a different piece/project code. I'd love to see both done. The other PR is the kernel modules. This is the management service and utils. (for which I need to get updated kbuild to land first)

**Comment by gena01** [comment]
@andypost if you going to merge things you might want to merge #5644 and #5683 first. Newer kbuild should unblock this PR which should build right after and should be good to merge.

**Comment by gena01** [comment]
Looks like @ncopa upgraded to 6.0.0. Closing this one.

**Pull request closed without merging**
