### PR TITLE
testing/proftpd: disable wtmp

### PR DESCRIPTION
**Pull request by xpecex**

### CODE REVIEW

**Comment by ncopa** [comment]
Thank you! You need to bump `pkgrel` or the builder will not pick up the change.

Please also update the commit message: `testing/proftpd: ....`

**Comment by jirutka** [comment]
I guess that this is related to the recent CVE…?

**Comment by jirutka** [comment]
Why do you want to disable `wtmp`? For security reasons? Please write a reason to the commit message.

**Comment by ncopa** [comment]
I fixed the commit message and pushed. thanks!

**Pull request closed without merging**
