### PR TITLE
community/rust: upgrade to 1.31.1

### PR DESCRIPTION
**Pull request by jeizsm**

### CODE REVIEW

**Comment by jeizsm** [comment]
@jirutka review, pls
cargo-tests-fix-package-include-exclude.patch can be removed in next version of rust
rust-lang/cargo#6479

**Comment by ncopa** [comment]
This should probably be merged with #5781

**Comment by andypost** [comment]
Locally build passes
```
Build completed successfully in 1:31:32
real	1h 31m 32s
user	2h 53m 35s
sys	1m 33.95s
```
So it will not run in travis

**Comment by andypost** [comment]
Package builds and pass checks on x86-64
```
>>> rust: Signing the index...
real	1h 35m 36s
user	3h 13m 07s
sys	3m 23.06s
```

**Pull request closed without merging**
