### PR TITLE
testing/libtorrent-rasterbar: upgrade to 1.2.1

### PR DESCRIPTION
**Pull request by J0WI**
`libtorrent-rasterbar` is required by `qbittorrent-nox`.

### CODE REVIEW

**Comment by J0WI** [comment]
Rebased

**Comment by J0WI** [comment]
qbittorrent has been update in #7871, so I've rebased this PR to just upgrade libtorrent-rasterbar to 1.2.1 and rebuild all packages depending on it.

**Comment by TBK** [comment]
Just for ref https://abi-laboratory.pro/index.php?view=timeline&l=libtorrent

**Comment by maxice8** [comment]
I updated deluge to 2.0.2 which now supports libtorrent-rasterbar-1.2.x

**Comment by J0WI** [comment]
0bdcae650bdede4e201d68c06d94875028a18365

**Pull request closed without merging**
