### PR TITLE
main/postgresql: add support for PL/Perl, PL/Python and PL/Tcl (refactoring of #624)

### PR DESCRIPTION
**Pull request by jirutka**

### CODE REVIEW

**Comment by GJRTimmer** [comment]
Really awesome. I've just learned a lot. I will take this concept and apply it to postgres-xl.

**Comment by jirutka** [comment]
The previous approach for py2/py3 actually didn’t work, so I changed it a bit. And also ported the rest of changes, now it should be complete. Please check out.

**Comment by GJRTimmer** [comment]
I'm starting up my laptop.

Op za 28 jan. 2017 15:26 schreef Jakub Jirutka <notifications@github.com>:

**Comment by GJRTimmer** [comment]
Running build

**Comment by GJRTimmer** [comment]
@jirutka I've verified everything and it all look beautifull.

Last night I found out (including in the documentation) that it's up to the database administrator to create 2 tables for the unknown extension of PL/Tcl to work. To make things more pleasant for an end user I've extracted the create statements from the pltcl_loadmod script, and turned it into a separate psql script which can be used by a database administrator.

Because this awesome work of yours is on your branch and I don't yet know to to push to it. here's the script. I would like it if it can be added to ```postgresql-pltcl/usr/share/postgresql```

```sql
-- PL/Tcl System administrator create table template
-- Author: G.J.R. Timmer
-- Date: 2017/01/28
-- Created from pltcl_loadmod

-- PL/Tcl create table pltcl_modules
create table pltcl_modules (modname	name, modseq int2, modsrc text);
create index pltcl_modules_i on pltcl_modules using btree (modname name_ops);

-- PL/Tcl create table
create table pltcl_modfuncs (funcname name, modname name);
create index pltcl_modfuncs_i on pltcl_modfuncs using hash (funcname name_ops);

```

Finally a bold request, as you know I'm getting ready to get ```postgres-xl``` into alpine testing, reason: it will allow for creating small docker images with a scalable postgres cluster.
However both ```main/postgresql``` and the future ```testing/postgresql-xl``` both provide a library ```libpq```. After some study and testing I've found a solution to avoid conflicts between these libraries.

Solution:
- Rename current ```libpq``` of ```main/postgresql``` to ```postgresql-libpq```
- Add the APKBUILD REPLACE tag on this library with a link to libpq so the distribution knows the library has been renamed.
- Add postgresql-libpq as HARDCODED ```depends``` 
   I know that you don't like it, but when you hardcode the ```depends``` to postgresql-libpq and if I do the same on ```postgresql-xl``` it turn out that ```apk``` will install the correct library when installing either postgresql or the future psotgresql-xl. If you do not hardcode the ```depends``` I've had the situation where libpq of ```main/postgresql``` is installed while I was installing my testing build of postgresql-xl.

This is only a request, and you are free to ignore it we can think about this when we're crossing this bridge when we get there working on ```postgresql-xl```

Finally I want to say that I gave great respect for your programming skills, the solution you created for this double pass compilation is very elegant.

**Comment by GJRTimmer** [comment]
@jirutka check PR https://github.com/jirutka/alpine-aports/pull/2 on your personal dev branch for postgresql, send you the final additon. We are now complete :-) I will start working on using your template to update ```testing/postgresql-xl```.

**Comment by GJRTimmer** [comment]
@jirutka I have a problem with using the current build

```bash
Error loading shared library libpq.so.5: No such file or directory (needed by /usr/bin/pg_ctl)
```

I'm working on it

**Comment by GJRTimmer** [comment]
@jirutka fixed the issue, my apk / abuild tools where updated on my docker sdk image.
I suffered from alpine bug #4727 https://bugs.alpinelinux.org/issues/4727 no relation to postgresql package, just a build issue.

**Comment by GJRTimmer** [comment]
@jirutka completed some testing.

Attached some screenshots for PL/Tcl function

postgresql-pltcl
easter-tcl


Everything works and is complete.

**Comment by jirutka** [comment]
Thanks for kind words. :) I’ve added your script and merged this PR. Let’s solve the issue with libpq in a separate PR.

> However both main/postgresql and the future testing/postgresql-xl both provide a library libpq.

Are these libs really different?

**Comment by GJRTimmer** [comment]
@jirutka I will try to find out, if the libs are different, I will submit a request with the postgres-xl team and get back to you.

**Pull request closed without merging**
