### PR TITLE
testing/telegraf: upgrade to 1.10.3

### PR DESCRIPTION
**Pull request by andypost**
Ref https://github.com/influxdata/telegraf/releases

### CODE REVIEW

**Comment by Ikke** [comment]
@andypost Any idea why CI is failing/

**Comment by andypost** [comment]
Looks can't find dependencies

**Comment by andypost** [comment]
It needs to change how build works https://github.com/influxdata/telegraf/blob/master/scripts/alpine.docker

**Comment by andypost** [comment]
https://github.com/influxdata/telegraf/releases/tag/1.11.0

**Comment by maxice8** [comment]
ping

**Comment by maxice8** [comment]
Updated to a newer version by #9858

**Pull request closed without merging**
