### PR TITLE
main/sudo: upgrade to 1.8.27

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
One test is failing.

**Comment by TBK** [comment]
I have posted a bug report on sudo.ws regarding cvtsudoers/test32 failing - https://bugzilla.sudo.ws/show_bug.cgi?id=881

I tested build this locally with the disabled regress test 19 enabled and test 19 did not fail.
```
sudoers/test19 (parse): OK
sudoers/test19 (toke): OK
sudoers/test19 (json): OK
sudoers/test19 (ldif): OK
sudoers/test19 (reparse): OK
sudoers/test19 (ldif2sudo): OK
```

**Comment by TBK** [comment]
A patch has been provided to fix test32 - https://patchwork.alpinelinux.org/patch/4846/

**Comment by J0WI** [comment]
Closing due #7918

**Pull request closed without merging**
