### PR TITLE
main/linux-vanilla: add config-virt.aarch64

### PR DESCRIPTION
**Pull request by tomalok**
Adding an initial 'linux-virt' configuration for aarch64, intended to be used with AWS EC2 a1.* instances.

### CODE REVIEW

**Comment by tomalok** [comment]
@ncopa

**Comment by ncopa** [comment]
seems half finished/untested. not all config questions are answered:
````
    Shamelessly allow leaking of fbdev physical address (DANGEROUS) (DRM_FBDEV_LEAK_PHYS_SMEM) [N/y/?] (NEW) 
````

**Comment by ncopa** [comment]
it also blocked on usb role switch support

**Comment by tomalok** [comment]
odd, compiled successfully without those issues last night.  I'll double check later today.

**Comment by ncopa** [comment]
also, i dont think we need bump pkgrel since it introduces a new subpackage and does not modify any of the existing ones. None of the existing packages needs update after this change.

I have a successful build here that i can push, but I wonder if its worth delay the v3.9 release for this. Might be better to aim for 3.10 instead (May 2019).

**Comment by ncopa** [comment]
Here is the diff:
````diff
diff --git a/main/linux-vanilla/APKBUILD b/main/linux-vanilla/APKBUILD
index ad25dd3a30..21f8c29857 100644
--- a/main/linux-vanilla/APKBUILD
+++ b/main/linux-vanilla/APKBUILD
@@ -7,7 +7,7 @@ case $pkgver in
        *.*.*)  _kernver=${pkgver%.*};;
        *.*) _kernver=$pkgver;;
 esac
-pkgrel=1
+pkgrel=0
 pkgdesc="Linux vanilla kernel"
 url="http://kernel.org"
 depends="mkinitfs"
@@ -227,7 +227,7 @@ d4c60ff52b83a490293a4cc0b5ddf53c3f15c4b0f28f67c7c0279eb2e6d5de3fa17041c3eaa8e43a
 96651aca476c905c04d616565a2dd08066167c1d4887e2ddc86c4b7cdda44257ef633a9bcf745a91f00f88023dde8f1804c56b258e7e99232bb8bfa25d0ba4db  config-vanilla.ppc
 c7e146b33460b4ff69adffb680e794536038c8a6bf5af90a6474fc7dfafeea80a6659f4f4bfe2fd6285a17c39db49f1420636ea1512131edec8ac1d7ab31e7ef  config-vanilla.ppc64le
 c6dc137c3b0518284da53a8876c18a58bd299be4980b3c183949c7e57bef97570d73f3c568888fa392a769226dacc5558082b44b388f79d9a7daa677bbc5f9f4  config-vanilla.s390x
-e448a129f457904352485310572976332e414b1a4d328ef2834d34f79442870611dc87abb63b40766604e42712cc69b237f482f9ccb20a298b5fe21d4dce806f  config-virt.aarch64
+2f4b32df9f0168dd3388443ca8aa8e77a2e061ce68d4227d651fe6a6dec06e7b55d94fec135f6f5b64d573b2c7327d454e98199290b6c720fa5eb47b4bfe143b  config-virt.aarch64
 0fbe2986a564664c4081267c10c51f14e7cbf416c2812e898a4b31260a64eebcc11da75e155af099b9e409aba275e7a67dac6ef1147e9fd856f65778a3a62a49  config-virt.x86
 0a3d194ccd06df7dda28775608b23e79a6641be9d545b623bffdeccc66e1f4de224dc419b84fa640b21b1badbffcd1eb33fc52f35a261b9a049699ac3569bbde  config-virt.x86_64
 f7a6539d0cc957ba5293e27ed2c0e3847be3704bd1cab1a1f271f3924c73abcf8220aa813d9f034b60701291a700e5d5ac779043f7e32562ce037e5db6832008  patch-4.19.18.xz"
diff --git a/main/linux-vanilla/config-virt.aarch64 b/main/linux-vanilla/config-virt.aarch64
index d2cfc11c33..06aca58588 100644
--- a/main/linux-vanilla/config-virt.aarch64
+++ b/main/linux-vanilla/config-virt.aarch64
@@ -4,7 +4,7 @@
 #
 
 #
-# Compiler: gcc (GCC) 8.2.1 (Alpine 8.2.0) 8.2.0
+# Compiler: gcc (Alpine 8.2.0) 8.2.0
 #
 CONFIG_CC_IS_GCC=y
 CONFIG_GCC_VERSION=80200
@@ -631,7 +631,6 @@ CONFIG_CRYPTO_AES_ARM64_CE_BLK=m
 CONFIG_CRYPTO_AES_ARM64_NEON_BLK=m
 CONFIG_CRYPTO_CHACHA20_NEON=m
 CONFIG_CRYPTO_AES_ARM64_BS=m
-CONFIG_CRYPTO_SPECK_NEON=m
 
 #
 # General architecture-dependent options
@@ -2891,6 +2890,7 @@ CONFIG_DRM_KMS_HELPER=m
 CONFIG_DRM_KMS_FB_HELPER=y
 CONFIG_DRM_FBDEV_EMULATION=y
 CONFIG_DRM_FBDEV_OVERALLOC=100
+# CONFIG_DRM_FBDEV_LEAK_PHYS_SMEM is not set
 # CONFIG_DRM_LOAD_EDID_FIRMWARE is not set
 # CONFIG_DRM_DP_CEC is not set
 CONFIG_DRM_TTM=m
@@ -3285,6 +3285,7 @@ CONFIG_USB_UAS=m
 # CONFIG_USB_ULPI is not set
 # CONFIG_USB_GADGET is not set
 # CONFIG_TYPEC is not set
+# CONFIG_USB_ROLE_SWITCH is not set
 # CONFIG_USB_ULPI_BUS is not set
 # CONFIG_UWB is not set
 # CONFIG_MMC is not set
@@ -4121,7 +4122,6 @@ CONFIG_CRYPTO_CHACHA20=m
 CONFIG_CRYPTO_SEED=m
 CONFIG_CRYPTO_SERPENT=m
 CONFIG_CRYPTO_SM4=m
-CONFIG_CRYPTO_SPECK=m
 CONFIG_CRYPTO_TEA=m
 CONFIG_CRYPTO_TWOFISH=m
 CONFIG_CRYPTO_TWOFISH_COMMON=m
````

**Comment by tomalok** [comment]
I’d like to get this into 3.9 if at all possible, as a part of removing all edge dependencies from mainline https://github.com/mcrute/alpine-ec2-ami and make a 3.9 aarch64 available, too.

iSent from my iPhone

**Comment by tomalok** [comment]
This is not too far off from where I ended up after squinting at .config diffs all weekend.  If you like I can run it through one more round of builds/tests on my end tonight (pacific TZ) just to be sure.

iSent from my iPhone

**Comment by ncopa** [comment]
I saw there was some differences from the x86_64 config that is not directly arch related. For example kvm was compiled into kernel instead of module etc. I would like to have the x86_64 and aarch64 kernels be somewhat similar, unless there is good reason.

**Comment by tomalok** [comment]
I agree, and had been planning to take a look at that, too.

iSent from my iPad

**Comment by tomalok** [comment]
It looks like KVM isn't configurable as a module for arm (and powerpc) for some reason, unlike x86_64 (and x86, ia64, and s390) per https://cateee.net/lkddb/web-lkddb/KVM.html

**Pull request closed without merging**
