### PR TITLE
testing/pdal: enable PCL

### PR DESCRIPTION
**Pull request by chambbj**

### CODE REVIEW

**Comment by chambbj** [comment]
@clandmeter Pinging you as you helped me with the PCL package itself (#3887). This PR enables PCL in the PDAL package. I don't quite understand the CI failure as everything appears to build just fine. As with PCL, I can confirm that things build and test just fine with `abuild rootbld`.

**Comment by chambbj** [comment]
Tried submitting this to the aports mailing list but I can find no record of it, so I must be doing something wrong there. Reopening here.

**Comment by chambbj** [comment]
@ncopa I hate to ping folks directly. Unfortunately, I can't seem to get any eyes on this through IRC or the mailing list (though it appears as though the mailing list post just never made it through). If you could take a look when you get a chance or delegate to another maintainer, I'd greatly appreciate it. Thanks for your time!

**Comment by andypost** [comment]
Upgrade in https://github.com/alpinelinux/aports/pull/4277 may affect this

**Comment by chambbj** [comment]
Absolutely. I'm planning to update this PR after #4277 is merged. I appreciate you taking a look at both!

**Comment by andypost** [comment]
would be great to get @clandmeter eyes on it

**Comment by chambbj** [comment]
@clandmeter @ncopa Just rebased this against recent changes in master. Still building fine. Would appreciate a review when you get a chance. Thanks!

**Pull request closed without merging**
