### PR TITLE
community/firefox-esr: enable on armhf, ppc64le and x86

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by Cogitri** [comment]
Could you maybe file this and thunderbird as MR on https://gitlab.alpinelinux.org/alpine/aports ? There we don't have CI restrictions (as long as you set a higher timeout for your project)

**Comment by Cogitri** [comment]
Oh, you did, oops :sweat_smile:

**Comment by J0WI** [comment]
They are not more reliable. Even the existing architectures do not pass there.

**Comment by Cogitri** [comment]
Huh, odd

**Comment by J0WI** [comment]
Could you try to build them on real hardware and post the logs if they fail?

**Comment by Cogitri** [comment]
Ah, I only have a aarch64 on hand, let me check if I can get the other arches too...

**Comment by Cogitri** [comment]
On armv7: http://arvanta.net/ff-esr.log.gz tested by mps

**Pull request closed without merging**
