### PR TITLE
community/py-opencl: upgrade to 2018.2.5 / move py-pybind11 to community

### PR DESCRIPTION
**Pull request by itoffshore**
community/py-opencl: upgrade to `2018.2.5`

### CODE REVIEW

**Comment by Ikke** [comment]
Might it be a better way to get the dependency moved to community instead? That way users of this package won't be surprised from it disappearing (packages aren't meant to live too long in testing anyway).

**Comment by itoffshore** [comment]
@Ikke - I fixed both packages to community

**Comment by Ikke** [comment]
@itoffshore This PR currently as conflicts. Can you rebase this PR?

**Comment by itoffshore** [comment]
@Ikke @tcely - `PR` rebased

**Comment by itoffshore** [comment]
@tcely - commit message changed

**Pull request closed without merging**
