### PR TITLE
testing/lightdm: depend on standard themes and use elogind

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by Ikke** [comment]
Could you add in the commit message the rational behind it, if only for future reference? Thanks.

**Comment by Cogitri** [comment]
Sure.

**Comment by Cogitri** [comment]
Edited commit msg

**Comment by Cogitri** [comment]
From CI: `ERROR: accountsservice-0.6.50-r1: BAD signature`

**Comment by Ikke** [comment]
Sorry about that, fixed now.

**Comment by Cogitri** [comment]
Thank you :)

**Pull request closed without merging**
