### PR TITLE
main/nss: upgrade to 3.43

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by Ikke** [comment]
CI fails because `all.sh` is not available in the check() function.

**Comment by J0WI** [comment]
It is when I build it locally.

**Comment by andypost** [comment]
```
$ head main/nss/src/nss-3.43/nss/tests/all.sh 
#!/bin/bash
```
so kinda that may work
```diff
diff --git a/main/nss/APKBUILD b/main/nss/APKBUILD
index 3e6881fb84..6af80926ca 100644
--- a/main/nss/APKBUILD
+++ b/main/nss/APKBUILD
@@ -56,8 +56,7 @@ build() {
 }
 
 check() {
-       cd "$builddir/nss/tests"
-       ./all.sh
+       sh "$builddir/nss/tests/all.sh"
 }
 
 package() {
```

**Comment by andypost** [comment]
Locally works
```diff
+check() {
+       HOST=localhost DOMSUF=localdomain sh "$builddir/nss/tests/all.sh"
+}
```

**Comment by J0WI** [comment]
Thanks!
I disabled the checks for now, so this can be reviewed.
A lot of packages depend on `nss` and may need to be rebuild.

**Comment by andypost** [comment]
ABI changed so dependencies needs rebuild
```diff
-usr/lib/libnss3.so.41
+usr/lib/libnss3.so.43
```

**Comment by TBK** [comment]
> 
> 
> ABI changed so dependencies needs rebuild
> 
> ```diff
> -usr/lib/libnss3.so.41
> +usr/lib/libnss3.so.43
> ```

libnss3.so is a symlink to latest libnss3.so.xx. 3.43 is 100% BC https://abi-laboratory.pro/index.php?view=timeline&l=nss

**Comment by J0WI** [comment]
Is this in the scope for the 3.10 release?

**Comment by J0WI** [comment]
Update committed in d1b194204c0c42ae5de44a5fdc1daca3abbe2da4, but without any checks.

**Comment by ncopa** [comment]
> Update committed in [d1b1942](https://github.com/alpinelinux/aports/commit/d1b194204c0c42ae5de44a5fdc1daca3abbe2da4), but without any checks.

sorry I didnt check if there were duplicates when merging that.

**Pull request closed without merging**
