### PR TITLE
testing/xterm: Enable SIXEL support

### PR DESCRIPTION
**Pull request by 7heo**

### CODE REVIEW

**Comment by jirutka** [comment]
Have you already tried the modified package that it actually works as expected?

**Comment by 7heo** [comment]
The build works, the xterm binary too, but there is no added sixel support, strangely. Or I can't find it. I guess I'll have to dig deeper.

**Comment by saitoha** [comment]
@7heo Have you set `decTerminalID` resource?

- Example 1

    ```
    $ echo "XTerm*decTerminalID: vt340" >> $HOME/.Xresources
    $ echo "XTerm*numColorRegisters: 256" >>  $HOME/.Xresources
    $ xrdb $HOME/.Xresources
    $ xterm
    ```

- Example 2

    ```
    $ xterm -xrm "XTerm*decTerminalID: vt340" -xrm "XTerm*numColorRegisters: 256"
    ```

- Example 3

   Build with  ./configure option `--with-terminal-id=vt340`.
   Note this way has side effects: `-ti vt420` option is needed to use VT class 4 features.

**Comment by 7heo** [comment]
@saitoha Thanks for the hints, and yes, I have tried to start `xterm` with the `-ti 340` as documented in [saitoha/PySixel#requirements](https://github.com/saitoha/PySixel#requirements) page.

I will try the rest and report, though.

**Comment by saitoha** [comment]
> in saitoha/PySixel#requirements page.

@7heo Oops, It's misspelled...
wrong) `-ti 340`
correct) `-ti vt340`

**Pull request closed without merging**
