### PR TITLE
testing/jdupes: new aport

### PR DESCRIPTION
**Pull request by tcely**
https://github.com/jbruchon/jdupes
jdupes is a program for identifying and taking actions upon duplicate files.

This fork known as 'jdupes' is heavily modified from and improved over the
original 'fdupes'.

### CODE REVIEW

**Comment by fcolista** [comment]
@tcely the APKBUILD is missing both maintainer and contributor.
check() should stay netween build() and package()
you can remove the variable not used like makedepends, depends_dev, depends and install.
Thanks
.: Francesco

**Comment by tcely** [comment]
@fcolista Done

**Comment by tcely** [comment]
@fcolista it appears you committed the older patch. Was there a reason for that?

**Comment by tcely** [comment]
@fcolista I created https://github.com/alpinelinux/aports/pull/4261 with the requested changes and the upgrade to `1.10.1` and will be closing this one.

**Pull request closed without merging**
