### PR TITLE
main/musl: Include patch to musl to getgr, getpw, and getspnam to set errno on error

### PR DESCRIPTION
**Pull request by r0p0s3c**
Without this, shadow utilities (user/group add/mod) do not cope with
groups that have large numbers of members, as the memory reallocation
code assumes errno will be set to ERANGE in such cases.

My plan is to also push this upstream to musl, so this is should only be required in the meantime

### CODE REVIEW

**Comment by ncopa** [comment]
LGTM, but I want hear what musl devs says about it first.

**Comment by jirutka** [comment]
Also pkgrel must be incremented.

**Comment by r0p0s3c** [comment]
Apologies, done. I haven't heard back from the musl devs yet, btw.

**Comment by r0p0s3c** [comment]
This has been resolved upstream in commit [2d7d05f](https://git.musl-libc.org/cgit/musl/commit/?id=2d7d05f031e014068a61d3076c6178513395d2ae) so no longer required

**Comment by ncopa** [comment]
do we need to back port that to alpine `3.6-stable`?

**Comment by r0p0s3c** [comment]
Good point. I presume even edge only brings in official musl releases also? Since I am not sure of the timing of that, is the best strategy to submit PRs/patches for both stable and edge?

**Pull request closed without merging**
