### PR TITLE
main/ldb: upgrade to 1.3.5

### PR DESCRIPTION
**Pull request by andypost**
Needed for https://github.com/alpinelinux/aports/pull/5005

Minimal required version 1.3.5

### CODE REVIEW

**Comment by andypost** [comment]
Upgrade to 1.4.x needs upgrade lmdb or configure without it `ldb build (unless --without-ldb-lmdb) requires lmdb 0.9.16 or later`

**Comment by tanertas** [comment]
ldb-1.4.x is for 4.9 branch. We have to figure out why ldb-1.3.x test suite fails with abuild.

**Comment by tanertas** [comment]
Following same phases on shell doesn't fail. Maybe requires bash? Any idea? @ncopa 
```
$ abuild checksum deps unpack prepare

$ cd src/ldb-1.3.5

$ ./configure --prefix=/usr --disable-rpath --disable-rpath-install --builtin-libraries=replace --bundled-libraries=NONE --with-modulesdir=/usr/lib/ldb/modules --extra-python=/usr/bin/python3

$ make

$ make check
.
.
.
[ RUN      ] test_ldb_unique_index_duplicate_with_guid
[       OK ] test_ldb_unique_index_duplicate_with_guid
[==========] 52 test(s) run.
[  PASSED  ] 52 test(s).
[==========] Running 2 test(s).
[ RUN      ] test_ldb_msg_find_duplicate_val
[       OK ] test_ldb_msg_find_duplicate_val
[ RUN      ] test_ldb_msg_find_common_values
[       OK ] test_ldb_msg_find_common_values
[==========] 2 test(s) run.
[  PASSED  ] 2 test(s).
```

**Comment by andypost** [comment]
Just tested locally
```
[ RUN      ] test_ldb_add_unique_value_to_unique_index
Could not run the test - check test fixtures
[  ERROR   ] test_ldb_add_unique_value_to_unique_index
[ RUN      ] test_ldb_add_duplicate_value_to_unique_index
Could not run the test - check test fixtures
[  ERROR   ] test_ldb_add_duplicate_value_to_unique_index
[ RUN      ] test_ldb_add_to_index_duplicates_allowed
Could not run the test - check test fixtures
[  ERROR   ] test_ldb_add_to_index_duplicates_allowed
[ RUN      ] test_ldb_add_to_index_unique_values_required
Could not run the test - check test fixtures
[  ERROR   ] test_ldb_add_to_index_unique_values_required
[ RUN      ] test_ldb_unique_index_duplicate_logging
Could not run the test - check test fixtures
[  ERROR   ] test_ldb_unique_index_duplicate_logging
[ RUN      ] test_ldb_duplicate_dn_logging
Could not run the test - check test fixtures
[  ERROR   ] test_ldb_duplicate_dn_logging
[ RUN      ] test_ldb_guid_index_duplicate_dn_logging
[       OK ] test_ldb_guid_index_duplicate_dn_logging
[ RUN      ] test_ldb_unique_index_duplicate_with_guid
[       OK ] test_ldb_unique_index_duplicate_with_guid
[==========] 52 test(s) run.
[  PASSED  ] 46 test(s).
make: *** [Makefile:15: test] Error 6
```
bash install does not help

**Comment by tanertas** [comment]
ok, until find out the real cause of the problem, maybe devs can build packages with manual intervention for each arch by following same steps as mine above.

With additional `abuild rootpkg index` step of course:

```
>>> ldb-dev*: Running split function dev...
>>> ldb-dev*: Preparing subpackage ldb-dev...
>>> ldb-dev*: Stripping binaries
>>> ldb-dev*: Running postcheck for ldb-dev
>>> py2-ldb*: Running split function _py2...
>>> py2-ldb*: Preparing subpackage py2-ldb...
>>> py2-ldb*: Stripping binaries
>>> py2-ldb*: Running postcheck for py2-ldb
>>> py3-ldb*: Running split function _py3...
>>> py3-ldb*: Preparing subpackage py3-ldb...
>>> py3-ldb*: Stripping binaries
>>> py3-ldb*: Running postcheck for py3-ldb
>>> ldb-tools*: Running split function tools...
>>> ldb-tools*: Preparing subpackage ldb-tools...
>>> ldb-tools*: Stripping binaries
>>> ldb-tools*: Running postcheck for ldb-tools
>>> ldb*: Running postcheck for ldb
>>> ldb*: Preparing package ldb...
>>> ldb*: Stripping binaries
>>> ldb-dev*: Scanning shared objects
>>> ldb-tools*: Scanning shared objects
>>> ldb*: Scanning shared objects
>>> py2-ldb*: Scanning shared objects
>>> py3-ldb*: Scanning shared objects
>>> ldb-dev*: Tracing dependencies...
	ldb=1.3.5-r0
	pc:talloc
	pc:tdb
	pkgconfig
	py2-ldb=1.3.5-r0
	py3-ldb=1.3.5-r0
>>> ldb-dev*: Package size: 144.0 KB
>>> ldb-dev*: Compressing data...
>>> ldb-dev*: Create checksum...
>>> ldb-dev*: Create ldb-dev-1.3.5-r0.apk
>>> ldb-tools*: Tracing dependencies...
	so:libc.musl-x86_64.so.1
	so:libldb.so.1
	so:libpopt.so.0
	so:libtalloc.so.2
>>> ldb-tools*: Package size: 124.0 KB
>>> ldb-tools*: Compressing data...
>>> ldb-tools*: Create checksum...
>>> ldb-tools*: Create ldb-tools-1.3.5-r0.apk
>>> ldb*: Tracing dependencies...
	so:libc.musl-x86_64.so.1
	so:libtalloc.so.2
	so:libtdb.so.1
	so:libtevent.so.0
>>> ldb*: Package size: 428.0 KB
>>> ldb*: Compressing data...
>>> ldb*: Create checksum...
>>> ldb*: Create ldb-1.3.5-r0.apk
>>> py2-ldb*: Tracing dependencies...
	so:libc.musl-x86_64.so.1
	so:libldb.so.1
	so:libpython2.7.so.1.0
	so:libtalloc.so.2
>>> py2-ldb*: Package size: 128.0 KB
>>> py2-ldb*: Compressing data...
>>> py2-ldb*: Create checksum...
>>> py2-ldb*: Create py2-ldb-1.3.5-r0.apk
>>> py3-ldb*: Tracing dependencies...
	so:libc.musl-x86_64.so.1
	so:libldb.so.1
	so:libpython3.6m.so.1.0
	so:libtalloc.so.2
>>> py3-ldb*: Package size: 128.0 KB
>>> py3-ldb*: Compressing data...
>>> py3-ldb*: Create checksum...
>>> py3-ldb*: Create py3-ldb-1.3.5-r0.apk
>>> ldb: Updating the main/x86_64 repository index...
>>> ldb: Signing the index...

```

**Comment by tanertas** [comment]
I discovered that if any compiler flags set, test suite fails. I created a new PR along with other changes that I provisioned before. See  #5035

**Pull request closed without merging**
