### PR TITLE
community/openblas: upgrade to 0.2.20, add s390x support

### PR DESCRIPTION
**Pull request by tmh1999**
2 patches based on commits:
7543e578a4c0fc1e23193ea10571d307f0076c28
63cfa32691680505e6b9daf0997755178ddd3144

### CODE REVIEW

**Comment by TBK** [comment]
CI fails because:
```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```

**Comment by tmh1999** [comment]
After building fine on s390x I assumed it should work on x86_64. Turned out it doesn't. This needs some more work.

**Comment by tmh1999** [comment]
This commit works on x86_64 and s390x. The CI might/might not be correct.

**Comment by tmh1999** [comment]
I'm going to submit PRs for openblas-0.3.0 and its reverse dependencies soon and close this PR.

**Pull request closed without merging**
