### PR TITLE
Add py-six and py-futures as dependencies

### PR DESCRIPTION
**Pull request by jaustinpage**
I didn't get these, this should make the package good. py-futures is edge, so this cannot be backported...

### CODE REVIEW

**Comment by jaustinpage** [comment]
I think this package is also a candidate for community/edge at this point, let me know what I should do to make that happen. Thanks!

**Comment by jirutka** [comment]
> I didn't get these…

Yes, because you haven’t added them and I haven’t verified it.

The futures package is needed only for Python 2.

> I think this package is also a candidate for community/edge at this point

Have you verified that it really works?

**Comment by jaustinpage** [comment]
"works on my machine" :-)

**Comment by jaustinpage** [comment]
Ohh, it occurs to me that I have not tested python3.

**Pull request closed without merging**
