### PR TITLE
community/libreoffice: update to 6.2.3

### PR DESCRIPTION
**Pull request by J0WI**
depends on #6542 #6543 #6544

### CODE REVIEW

**Comment by Ikke** [comment]
@J0WI Dependencies should be handled in the same PR. Can you bundle all the upgrades this upgrade depends on in this PR? Then this can be pushed in 1 go.

Thanks

**Comment by J0WI** [comment]
@Ikke done

**Comment by Ikke** [comment]
Built it locally, but it failed with the following error:

> [CXX] idlc/source/astservice.cxx                                                                                                                                         
Building lxml version 4.1.1.                                                                                                                                             
Traceback (most recent call last):                                                                                                                                       
  File "setup.py", line 67, in <module>                                                                                                                                  
    deps = [str(req) for req in pkg_resources.parse_requirements(f)]                                                                                                     
AttributeError: module 'pkg_resources' has no attribute 'parse_requirements'                                                                                             
make[1]: *** [/home/build/aports/community/libreoffice/src/libreoffice-6.1.4.2/external/lxml/ExternalProject_lxml.mk:25: /home/build/aports/community/libreoffice/src/libreoffice-6.1.4.2/workdir/ExternalProject/lxml/build] Error 1
make[1]: *** Waiting for unfinished jobs....                                                                                                                             
In file included from /home/build/aports/community/libreoffice/src/libreoffice-6.1.4.2/idlc/source/idlccompile.cxx:39:                                                    
/usr/include/wait.h:1:2: warning: #warning redirecting incorrect #include <wait.h> to <sys/wait.h> [-Wcpp]                                                                
 #warning redirecting incorrect #include <wait.h> to <sys/wait.h>                                                                                                         
  ^~~~~~~                                                                                                                                                                 
/home/build/aports/community/libreoffice/src/libreoffice-6.1.4.2/instdir/sdk/include/osl/thread.h:198: warning: argument 'name' from the argument list of osl_setThreadName has muliple @param documentation sections
a00521:116: warning: explicit link request to 'com::sun::star::uno::Sequence< E >' could not be resolved   

Any idea?

**Comment by J0WI** [comment]
This is 6.1.4.2 and not 6.2.1.2.

**Comment by Ikke** [comment]
With this patch, it compiles for me (it needs py-setuptools as makedeps).

```diff
diff --git a/community/libreoffice/APKBUILD b/community/libreoffice/APKBUILD
index 546287f83d..c1edd4dc57 100644
--- a/community/libreoffice/APKBUILD
+++ b/community/libreoffice/APKBUILD
@@ -20,7 +20,8 @@ depends_dev="cups-dev libjpeg-turbo-dev boost-dev clucene-dev libe-book-dev icu-
        liborcus-dev openjdk8 apache-ant junit xmlsec-dev gpgme-dev libepubgen-dev
        libqxp-dev liborcus-dev libnumbertext-dev"
 makedepends="$depends_dev autoconf automake tar coreutils findutils ucpp gperf
-       bison flex zip perl perl-archive-zip sed tar libxml2-utils doxygen paxmark"
+       bison flex zip perl perl-archive-zip sed tar libxml2-utils doxygen paxmark
+       py-setuptools"
 # GNU sed is needed for in i18npool/CustomTarget_localedata.mk
 install=""
 subpackages="$pkgname-base $pkgname-calc $pkgname-common $pkgname-draw
```

**Pull request closed without merging**
