### PR TITLE
community/keepassx: purge, has alternative in keepassx

### PR DESCRIPTION
**Pull request by maxice8**
- Uses Qt4, Qt5 support but no release
- Has community fork in the form of keepassxc

### CODE REVIEW

**Comment by maxice8** [comment]
@AmatCoder

**Comment by andypost** [comment]
As I see keepassxc is in testing

**Comment by maxice8** [comment]
On Sat, May 11, 2019 at 03:31:09AM -0700, Andy Postnikov wrote:
> As I see keepassxc is in testing
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7723#issuecomment-491499465

Can we promote it to community ?

**Comment by andypost** [comment]
Sure, same pr makes sense, is it full replacement?

**Comment by maxice8** [comment]
On Sat, May 11, 2019 at 05:30:24AM -0700, Andy Postnikov wrote:
> Sure, same pr makes sense, is it full replacement?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7723#issuecomment-491507120

It is a community oriented fork that has a release with Qt5 support, not a full bit-by-bit replacement

**Comment by TBK** [comment]
Is the move of keepassxc going to be included in this PR?

Would it make sense to add `provides="keepassx"` to keepassxc?

**Comment by maxice8** [comment]
On Fri, May 24, 2019 at 08:27:05PM -0700, TBK wrote:
> Is the move of keepassxc going to be included in this PR?
> 
> Would it make sense to add `provides="keepassx"` to keepassxc?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7723#issuecomment-495838405

keepassxc is a fork so it may cause incompatibility if we just start replacing, i expect users to change it on the next version, or if they are on edge to just change themselves.

**Pull request closed without merging**
