### PR TITLE
main/sshfs: upgrade to 3.0.0

### PR DESCRIPTION
**Pull request by tmpfile**

### CODE REVIEW

**Comment by tmpfile** [comment]
Depends on https://github.com/alpinelinux/aports/pull/1902 to be merged before.

**Comment by nmeum** [comment]
sshfs 3.0 probably needs fuse 3

**Comment by nmeum** [comment]
This needs to be build against `testing/fuse3`.

**Comment by nmeum** [comment]
@tmpfile gentle reminder ☺️

**Comment by jirutka** [comment]
> This needs to be build against `testing/fuse3`.

sshfs is in main, so it cannot be rebuilt against testing/fuse3. I suggest to postpone this until v3.7 is released, then try to rebuild all fuse packages against fuse 3.x, update main/fuse to 3.x and add fuse2 if needed.

**Comment by nmeum** [comment]
> sshfs is in main, so it cannot be rebuilt against testing/fuse3

Sure, it needs to be moved first. 

> I suggest to postpone this until v3.7 is released

:+1:

> then try to rebuild all fuse packages against fuse 3.x, update main/fuse to 3.x and add fuse2 if needed.

fuse2 and fuse3 aren't API compatible, there will probably be many packages that do not work with fuse 3.X.

**Comment by jirutka** [comment]
>> then try to rebuild all fuse packages against fuse 3.x, update main/fuse to 3.x and add fuse2 if needed.
>>
> fuse2 and fuse3 aren't API compatible, there will probably be many packages that do not work with fuse 3.X.

I know, that’s why I wrote “and add fuse2 [aport] if needed”. ;)

**Comment by andypost** [comment]
Newer release is out https://github.com/libfuse/sshfs/releases/tag/sshfs-3.4.0

**Comment by andypost** [comment]
Filed follow-up https://github.com/alpinelinux/aports/pull/5098

**Pull request closed without merging**
