### PR TITLE
main/gstreamer: upgrade to 1.16.0

### PR DESCRIPTION
**Pull request by ad-m**

### CODE REVIEW

**Comment by maxice8** [comment]
as far as i remember this needs updates to lots of other gstreamer-* gst-* packages.

**Comment by ad-m** [comment]
Package history does not confirm that: https://github.com/alpinelinux/aports/commits/2054bb96b40e0b86576709d492e2565ca66046c1/main/gstreamer/APKBUILD

**Comment by maxice8** [comment]
Because the search is wrong.

419ac983077c627870d34d3ad4812f9ceaa50f87 is the last gstreamer update.

```
$ git log --pretty=oneline 419ac983077c627870d34d3ad4812f9ceaa50f87..HEAD
1ac7d3e5a9cd31f663ff726d77b319315c5b9890 community/py-gst: upgrade to 1.14.4
dbde2c50e6bc62c832ed593a32c184893d2cdfab testing/gst-rtsp-server: upgrade to 1.14.4
1df2bf80d59518f0b422c3338d8e361827f23188 testing/gstreamer-vaapi: upgrade to 1.14.4
c536ede5b3f75673c91c61bae18618060bdf6b2b community/gst-libav: upgrade to 1.14.4
3a68811e75f955cca0a125c8971576028fc05ee0 community/gst-plugins-ugly: upgrade to 1.14.4
3fc21aee594398cc03a38e68bf23f6bd1241decb community/gst-plugins-bad: upgrade to 1.14.4
4dbe418a4b665e13e02a1e1a9d8135202ffee0c3 community/gst-plugins-good: upgrade to 1.14.4
bc0dfac16789ceafa58687224fe7278f86e9eaa1 main/gst-plugins-base: upgrade to 1.14.4
419ac983077c627870d34d3ad4812f9ceaa50f87 main/gstreamer: upgrade to 1.14.4
```

Regardless you need to check the other gst-* and gstreamer-* packages to see if they also have updates.

**Comment by maxice8** [comment]
Duplicate of #7665

**Comment by ncopa** [comment]
Lets follow up this in #7665

**Pull request closed without merging**
