### PR TITLE
testing/py3-sstash: modernize

### PR DESCRIPTION
**Pull request by maxice8**
- Use modern style
- Explain why check is disabled

### CODE REVIEW

**Comment by maxice8** [comment]
@fabaff

**Comment by Ikke** [comment]
@maxice8 This needs a `pkgrel` dump (due to makedepends change).

**Comment by maxice8** [comment]
But makedepends don't affect the final product, do we need to pkgrel if it is going to build the same package again ?

**Comment by Ikke** [comment]
I suppose it wouldn't in this case. There are cases where `makedepends` determine whether features are enabled or not.

**Comment by maxice8** [comment]
On Sun, May 05, 2019 at 09:29:01PM -0700, Kevin Daudt wrote:
> I suppose it wouldn't in this case. There are cases where `makedepends` determine whether features are enabled or not.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/alpinelinux/aports/pull/7569#issuecomment-489497504

This isn't this case, also changing makedepends to enable/disable a feature warrants a message.

**Pull request closed without merging**
