### PR TITLE
main/linux-vanilla: support xen_pvh boot via grub

### PR DESCRIPTION
**Pull request by HRio**
Patches from Debian Buster (backport from Linux 4.20)

### CODE REVIEW

**Comment by HRio** [comment]
Tested both linux-vanilla and linux-virt from xen_pvh grub.

**Comment by ncopa** [comment]
if we start add patches to our kernel, can we really call it "vanilla" then?

**Comment by ncopa** [comment]
I think the proper thing to do is to ask upstream backport those for linux-4.19.y

**Comment by HRio** [comment]
> if we start add patches to our kernel, can we really call it "vanilla" then?

OK, understand.

**Comment by HRio** [comment]
@jgross1 what would you say, are the "RSDP address" patches LTS 4.19 "material" or should we wait for the next LTS? i.e. do you think it could be accepted for stable backport?

**Comment by jgross1** [comment]
On 05/04/2019 17:45, Henrik Riomar wrote:
> @jgross1 <https://github.com/jgross1> what would you say, are the "RSDP
> address" patches LTS 4.19 "material" or should we wait for the next LTS?
> i.e. do you think it could be accepted for stable backport?

You'd need to ask the stable maintainer (Greg), not me. :-)

Basically they add a feature, so in theory they are no backport
candidates. But maybe Greg will take them nevertheless, who knows?


Juergen

**Comment by HRio** [comment]
> You'd need to ask the stable maintainer (Greg), not me. :-) Basically they add a feature, so in theory they are no backport candidates.

Thanks.

Found some rules now after after some more searching for how an end user could possibly request a Linux LTS backport :smile: 

https://www.kernel.org/doc/html/v4.19/process/stable-kernel-rules.html seems they are way too big for the stable series.

**Pull request closed without merging**
