### PR TITLE
main/ninja: Move gtest to checkdepends

### PR DESCRIPTION
**Pull request by neuschaefer**
There is a rather long cyclic dependency chain:

```
cmake
`-> makedepends jsoncpp-dev
    `-> makedepends meson, which depends on ninja
        `-> makedepends gtest
	    `-> makedepends cmake
```

Fortunately, this cycle can easily be broken by declaring ninja's dependency on
gtest as checkdepends instead of makedepends.

### CODE REVIEW

**Comment by tmpfile** [comment]
Speaking of ninja there's a new implementation out there that might be worth checking out.
https://github.com/michaelforney/samurai implements the ninja build language with a focus on simplicity, speed, and portability.
It's used in the https://github.com/michaelforney/oasis distribution and works as a drop-in replacement there.

**Comment by neuschaefer** [comment]
3k lines (samurai) instead of 15k lines (ninja). Neat!

**Comment by TBK** [comment]
I have created a package for samurai - https://github.com/alpinelinux/aports/pull/3895

**Comment by neuschaefer** [comment]
This patch is somewhat obsoleted by commit 27a7784306 ("main/cmake: use bundled jsoncpp to avoid circular dependency")

**Comment by neuschaefer** [comment]
Thanks, @jirutka!

**Pull request closed without merging**
