### PR TITLE
main/cython: update to 0.25.1

### PR DESCRIPTION
**Pull request by itoffshore**
https://github.com/cython/cython/blob/master/CHANGES.rst

### CODE REVIEW

**Comment by jirutka** [comment]
This is an alpha version, isn’t it?

**Comment by itoffshore** [comment]
The `[changelog` showed some bugs as fixed](https://github.com/cython/cython/blob/master/CHANGES.rst) in version 0.25

perhaps lets wait a week or so to see if there is a new version, it is simple to update the pull request

**Comment by jirutka** [comment]
Version 0.25.1 has been released, so you can update this PR.

**Comment by itoffshore** [comment]
updated to `0.25.1`

**Pull request closed without merging**
