### PR TITLE
testing/hplip: upgrade to 3.16.11

### PR DESCRIPTION
**Pull request by vakartel**
add scanner (sane backend) support, close #6520
make lite install (libs and drivers only)
remove fax-, hal-, systemd-, dbus- related trash
remove python dependency
move libs to subpackage

### CODE REVIEW

**Comment by vakartel** [comment]
checks have failed because travis do not see unmaintained/sane package. 
https://github.com/alpinelinux/aports/pull/631

**Comment by clandmeter** [comment]
Did you read our guidelines? It should be provided when you create a new PR:

https://github.com/alpinelinux/aports/blob/master/.github/CONTRIBUTING.md

* Please bundle deps into the same PR so travis can build it properly.
* Also move sane directly to testing (in a separate commit) same PR.
* Add your changes commit to sane also to this PR (easier for us to read changes when split from the move).
* Add your hplip upgrade/changes commit.

This way travis will work and we will be able to apply it to aports in one shot.

**Comment by vakartel** [comment]
It builds well on my localhost but travis check failed.
I think travis ignores packs from unmaintained for its checks.

**Comment by vakartel** [comment]
close/open to trigger travis check

**Pull request closed without merging**
