### PR TITLE
testing/blender: new aport

### PR DESCRIPTION
**Pull request by Klowner**
Lots of subpackages in this one. I'm not sure what the preferred way for handling alternate binaries is; for the headless build I renamed the binary to `blender-headless`, although I'm not sure why someone would want headless and regular builds installed at the same time. Is this maybe a use-case for `provides`?

Thanks!

(depends on openimageio)

### CODE REVIEW

**Comment by Klowner** [comment]
Probably also want to have opensubdiv http://graphics.pixar.com/opensubdiv/docs/intro.html and CUDA support.

**Comment by Klowner** [comment]
Waiting on `opensubdiv`, `ilmbase`, and `openexr`, otherwise it should be all good to go.

**Comment by Klowner** [comment]
#226 is the opensubdiv pr, for reference

**Comment by fabled** [comment]
Committed, with follow-up upgrade and minor fixes.

**Pull request closed without merging**
