### PR TITLE
main/monkeysphere: move to 'community' and fix runtime dependencies

### PR DESCRIPTION
**Pull request by myhro**
Needed by the `openpgp2ssh` command.

Otherwise it fails with the following errors:

```
Can't locate Crypt/OpenSSL/RSA.pm in @INC (you may need to install the Crypt::OpenSSL::RSA module) (@INC contains: /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl
 /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /usr/bin/openpgp2ssh line 54.
 BEGIN failed--compilation aborted at /usr/bin/openpgp2ssh line 54.

Can't locate Crypt/OpenSSL/Bignum.pm in @INC (you may need to install the Crypt::OpenSSL::Bignum module) (@INC contains: /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /usr/bin/openpgp2ssh line 55.
BEGIN failed--compilation aborted at /usr/bin/openpgp2ssh line 55.
```

### CODE REVIEW

**Comment by myhro** [comment]
The build has failed because `perl-crypt-openssl-bignum` is part of the `community` repository and not `main`.

Is there a way to fix this other than moving this dependency to `main`?

**Comment by nmeum** [comment]
> Is there a way to fix this other than moving this dependency to `main`?

Dependencies of a package in `main/` cannot be in `community/`. However, I would rather prefer to move `monkeysphere` from `main/` to `community/` as it doesn't seem that essential to me.

**Comment by myhro** [comment]
Makes sense. What about `perl-crypt-openssl-rsa`? Is it ok to have cross-dependencies to `main`?

Also, what's the procedure? Can I just send another PR moving it between repos?

**Comment by nmeum** [comment]
> What about `perl-crypt-openssl-rsa`? Is it ok to have cross-dependencies to `main`?

Yes packages in `community/` can depend on packages in `main/`.

> Also, what's the procedure? Can I just send another PR moving it between repos?

The best thing would be to add the commits moving the packages to this PR. They should have the commit message "${repo}/${pkgname}: move to ${new-repo}" where `$repo, $newrepo ∈ {main,community,testing}`.

**Pull request closed without merging**
