### PR TITLE
testing/flawfinder: upgrade to 2.0.7

### PR DESCRIPTION
**Pull request by HRio**
add check()

### CODE REVIEW

**Comment by HRio** [comment]
@fabaff @rgdoliveira please check, should we not move this package to community as well?

**Comment by fabaff** [comment]
I would like to suggest that instead of disabling Python 3 we do it the other way around and do it for Python 2.

Can be moved to community from my point of view.

**Comment by HRio** [comment]
@fabaff OK, I will switch to python3.

**Comment by HRio** [comment]
@fabaff OK if I commit as in d049ee1 and a move to community/ ?

**Pull request closed without merging**
