### PR TITLE
community/psmisc: move to community & update to 22.21

### PR DESCRIPTION
**Pull request by itoffshore**
community/psmisc: move to community / take ownership & update to 22.21

### CODE REVIEW

**Comment by jirutka** [comment]
Why have you closed this PR? o.O

**Comment by itoffshore** [comment]
`psad` did not build because it relies on `psmisc` & `perl-net-ip4addr` - am splitting each package into a seperate pull request

**Comment by jirutka** [comment]
It’s actually better to push them into single pull request, then CI can build them in required order to satisfy dependencies.

**Comment by itoffshore** [comment]
build passes in https://github.com/alpinelinux/aports/pull/259

**Pull request closed without merging**
