### PR TITLE
main/samba: Upgrade to 4.8.5

### PR DESCRIPTION
**Pull request by tanertas**
* Corrected samba.confd
 * Adjust winbind_krb5_locator.so file new path
 * Re-arrange depends,makedepends,source

### CODE REVIEW

**Comment by tanertas** [comment]
Module path hierarchy seems changed. APKBUILD needs to revise.

**Comment by tanertas** [comment]
> Module path hierarchy seems changed. APKBUILD needs to revise.

Fixed. Only `winbind_krb5_locator.so` file path changed on upstream.

**Comment by andypost** [comment]
please, squash commits `git rebase -i HEAD~2`

**Comment by tanertas** [comment]
> please, squash commits git rebase -i HEAD~2
Done.

**Pull request closed without merging**
