### PR TITLE
Fix reloading of existings ipsets.

### PR DESCRIPTION
**Pull request by liske**
This fixes issue [#9149](https://bugs.alpinelinux.org/issues/9149).

### CODE REVIEW

**Comment by jirutka** [comment]
Please bump `pkgrel` and update checksums (`abuild checksum`).

**Comment by liske** [comment]
I've updated the PR accordingly @jirutka

**Comment by ncopa** [comment]
@kunkku can you please have a look at this?

**Comment by kunkku** [comment]
The sets are created using a single `ipset restore` command due to performance reasons. This is significant when the number of sets is big. I suggest splitting the loop into two: first collect the names of the existing sets, then generate the creation commands in the second loop.

**Comment by liske** [comment]
I was not aware of the performance impact. I've split the loop as prefered by @kunkku.

**Comment by kunkku** [comment]
Thank you. Seems all right to me.

**Comment by liske** [comment]
Is this fixed to be merged into alpine 3.8? For me this issue looks a little bit serious since ipset is mostly used by iptables rules. *Silently* failing to update the firewall policy might be a security related?

**Comment by kunkku** [comment]
Now backported to all supported releases.

**Pull request closed without merging**
