### PR TITLE
Move C Suite to community repository

### PR DESCRIPTION
**Pull request by rahmanshaber**
Move this packages to community repo

### CODE REVIEW

**Comment by rahmanshaber** [comment]
@maxice8 please help me on this. I want them in the future release.

**Comment by Cogitri** [comment]
Please use the standard commit messages:

`$new_repo/$pkgname: move from $old_repo`

**Comment by rahmanshaber** [comment]
@Cogitri  Please check the changes out.
I don't know why there is a conflict.

**Comment by rahmanshaber** [comment]
So it is ready to merge?

**Comment by Cogitri** [comment]
> Also build failed in arch64 because of
ERROR: Failed to create usr/lib/libQt5Gui.so.5.12.5: I/O error

Ah, I guess the CI had a hiccup there, don't worry about it.

>  don't know why there is a conflict.

Please rebase your changes upon git master

**Comment by rahmanshaber** [comment]
So it is ready to merge?

> 
> 
> > Also build failed in arch64 because of
> > ERROR: Failed to create usr/lib/libQt5Gui.so.5.12.5: I/O error
> 
> Ah, I guess the CI had a hiccup there, don't worry about it.
> 
> > don't know why there is a conflict.
> 
> Please rebase your changes upon git master

did this
`
[asd@asd-pc aports]$ git rebase master
Current branch newmessport is up to date.
[asd@asd-pc aports]$ git rebase master
Current branch newmessport is up to date.
[asd@asd-pc aports]$ git force push
git: 'force' is not a git command. See 'git --help'.
[asd@asd-pc aports]$ git push
Username for 'https://github.com': rahmanshaber
Password for 'https://rahmanshaber@github.com': 
Everything up-to-date

`

**Comment by Cogitri** [comment]
You might have to fetch master first, otherwise git can't know what changed in this repo:

e.g. if you have `https://github.com/alpinelinux/aports.git` as `upstream` remote configured do:

`git pull upstream master --rebase` OR `git fetch upstream master && git rebase upstream/master`

**Comment by Cogitri** [comment]
Merged, thanks!

**Pull request closed without merging**
