### PR TITLE
update Haxe and Neko

### PR DESCRIPTION
**Pull request by andyli**
Update testing/haxe to 3.4.4. Add check(), change arch to all.
Add myself as maintainer. (I'm a member of the Haxe Foundation, which is the org behind Haxe and Neko. I'm also the Haxe/Neko package maintainer of Debian/Fedora/openSUSE)

### CODE REVIEW

**Comment by kaniini** [comment]
hi,

i did these, but the neko compiler is crashing on x86.  so i am reopening this.

**Comment by andyli** [comment]
I've just fixed the neko x86 segfault by disabling jit, which is optional and only enabled in x86 by default.
I'm not sure if there is any problem on archs other than x86 and x86_64, if so, please share the build log and I will look into that.

**Comment by kaniini** [comment]
arm build fails due to unknown CFLAGS.

**Comment by andyli** [comment]
ummm... Was that something about `-mincoming-stack-boundary`?

**Comment by andyli** [comment]
Just tested with a arm alpine docker image, it was indeed `-mincoming-stack-boundary`. I've added an upstream patch to fix it. Hopefully it is now buildable in all arches.

**Comment by andyli** [comment]
May I know if there is any remaining issue?

**Comment by ncopa** [comment]
Seems like it builds on all arches now. Thank you!

**Pull request closed without merging**
