### PR TITLE
main/wpa_supplicant: upgrade to 2.8 

### PR DESCRIPTION
**Pull request by J0WI**
Follow up of https://github.com/alpinelinux/aports/pull/7769

### CODE REVIEW

**Comment by maxice8** [comment]
please make sure https://bugs.archlinux.org/task/61848?project=1&string=wpa_supplicant and https://github.com/void-linux/void-packages/issues/5413 doesn't happen

**Comment by J0WI** [comment]
Fixed in 43c8f8a8f1a15295d3639577e4b8d50292b28225

**Comment by J0WI** [comment]
@maxice8 I can't verify this due the lack of hardware.

**Comment by J0WI** [comment]
This has been fixed in e37cabf47a6ea953c728606fe97981b9f4c8792f

**Pull request closed without merging**
