### PR TITLE
gawk5 fixes for libgpg-error 1.36

### PR DESCRIPTION
**Pull request by djazo**
Taken from 
https://github.com/alpinelinux/aports/commit/f19e074bc6ed6e3be8a13869d0e94dce1f4cad56

### CODE REVIEW

**Comment by tcely** [comment]
A better commit message would be:

`main/libgpg-error: gawk5 fixes for 1.36`

**Comment by ncopa** [comment]
`pkgrel` needs to be bumped or builder will not pick it up. I can fix that for you. Thanks!

**Comment by tcely** [comment]
@djazo what is the reason this patch is needed.

It only renames a variable and unescapes '#' from what I can tell.

**Comment by djazo** [comment]
> @djazo what is the reason this patch is needed?
> 
> It only renames a variable and unescapes '#' from what I can tell.

Without unescaping, build fails using gawk5, which is now at least on edge.

**Comment by tcely** [comment]
I can't find a reason for gawk to be installed while this package is building.

See https://build.alpinelinux.org/buildlogs/build-edge-x86_64/main/libgpg-error/libgpg-error-1.36-r0.log

**Comment by maxice8** [comment]
Your PR seems to be missing the patch and has merge commits

**Comment by tcely** [comment]
This was merged by @ncopa in https://github.com/alpinelinux/aports/commit/3497c40f75c25eabecb8252764a4ce1fe3fd9494#diff-4ddc72d2e139bc373dd40f47d7f53011.

**Pull request closed without merging**
