### PR TITLE
community/namecoin: upgrade to 0.18.0

### PR DESCRIPTION
**Pull request by andypost**
Ref https://github.com/namecoin/namecoin-core/releases/tag/nc0.18.0

### CODE REVIEW

**Comment by andypost** [comment]
@itoffshore are you ok with upgrade?

**Comment by itoffshore** [comment]
@andypost - yes ok with me.

it was on my `TODO` list but I've not had time

**Comment by andypost** [comment]
It looks the failed test affected by https://github.com/bitcoin/bitcoin/issues/14948#issuecomment-488385462

**Comment by ncopa** [comment]
The error is:
````
unknown location(0): fatal error: in "fs_tests/fsbridge_fstream": boost::system::system_error: boost::filesystem::path codecvt to string: error
````

**Comment by andypost** [comment]
Fixed in fd94f146

**Pull request closed without merging**
