### PR TITLE
community/rust: upgrade to 1.33.0

### PR DESCRIPTION
**Pull request by Cogitri**
@Ikke

### CODE REVIEW

**Comment by Cogitri** [comment]
I'd very much like to take maintainership on this, but I think that can wait until I do the 1.35 bump, let's get this tested&merged and sort of sprint to 1.35 if possible :)

**Comment by Cogitri** [comment]
Currently building Rust 1.34.2 with this.

**Comment by Cogitri** [comment]
FWIW, I've added Rust 1.34.2 to this PR too.

**Comment by Cogitri** [comment]
Both Rusts build fine for me, pass the tests and are able to build my fairly complex app (gxi).

**Comment by Ikke** [comment]
Sadly, this cannot go in a single PR. Only the end result is built, not individual commits, so it would try to build 1.34 with 1.32, which apparently would not work. So we have to split this into two separate pull requests.

**Comment by Cogitri** [comment]
Fixed, thanks for the info :)

**Pull request closed without merging**
