### PR TITLE
main/czmq: backport from master to fix tests on s390x

### PR DESCRIPTION
**Pull request by tuan-hoang1**
zproc/zsp tests seem to be fixed in master

zdigest and SHA1 functions fail when building with CMake
Use normal/official build scripts instead

### CODE REVIEW

**Comment by ncopa** [comment]
fails on ppc64le:
````
 * zauth: OK
 * zbeacon: OK
 * zgossip: OK
 * zmonitor: OK
 * zproxy: OK
 * zrex: OK
 * zargs: OK
Assertion failed: !zproc_running (self) (src/zproc.c: zproc_test: 1263)
 * zproc: make[2]: *** [Makefile:2363: check-local] Aborted
make[2]: Leaving directory '/home/ncopa/aports/main/czmq/src/czmq-4.1.1'
make[1]: *** [Makefile:2073: check-am] Error 2
make[1]: Leaving directory '/home/ncopa/aports/main/czmq/src/czmq-4.1.1'
make: *** [Makefile:1626: check-recursive] Error 1
````

**Comment by ncopa** [comment]
@jirutka are you ok with the change to autotools or should we try fix cmake build?

**Comment by jirutka** [comment]
I don’t mind changing to autohells.

**Comment by ncopa** [comment]
I had to revert since it broke builds on the other arches

**Comment by tuan-hoang1** [comment]
Yes... I will fix this, soon.

**Comment by tuan-hoang1** [comment]
Yes... I will fix this, soon.

**Pull request closed without merging**
