### PR TITLE
[WIP] main/libevent: upgrade to 2.1.11

### PR DESCRIPTION
**Pull request by maxice8**
Tracking local builds

- [ ] ameba
- [x] bitcoin
- [x] chromium
- [x] coturn
- [ ] crystal
- [x] evince
- [x] firefox
- [x] firefox-esr
- [x] fstrm
- [x] gearmand
- [x] kamailio
- [x] libcouchbase
- [x] libevhtp
- [x] libreswan
- [x] libverto
- [x] lldpd
- [x] memcached
- [x] namecoin
- [x] netatalk
- [x] nfs-utils
- [x] nsd
- [x] opensmtpd
- [x] pgbouncer
- [x] php7-pecl-event
- [x] qt5-qtwebengine
- [x] redsocks
- [x] rspamd
- [x] samba
- [x] scanssh
- [ ] seamonkey
- [x] sems
- [ ] shards
- [x] tg
- [x] tmate
- [x] tmux
- [x] tor
- [x] transmission
- [x] unbound
- [x] zabbix

### CODE REVIEW

**Comment by maxice8** [comment]
@ncopa this will be a BIG Rebuild

**Comment by Cogitri** [comment]
Chromium builds.

**Comment by Cogitri** [comment]
FF works too

**Comment by Cogitri** [comment]
qtwebengine works too

**Pull request closed without merging**
