### PR TITLE
main/cmake: Update to 3.8.1 and clean up APKBUILD

### PR DESCRIPTION
**Pull request by pbregener**
Remove obsolete/outdated/wrong comment from APKBUILD, remove explicit `--system-...` flags, as `--system-libs` should do the trick.

### CODE REVIEW

**Comment by pbregener** [comment]
I know that you added the explicit `--system` flags as part of bd86165d1a5e2da18463ef50479741c1464241c7 @ncopa, but I guess it was done to point out the (previous) difference regarding `jsoncpp` more clearly. Are you fine with these changes?
The Alpine `jsoncpp` package does not depend on `cmake` anymore (but uses `scons` instead).

BTW: As per https://github.com/open-source-parsers/jsoncpp#building-and-testing-with-scons using scons to build jsoncpp is actually deprecated.

**Comment by ncopa** [comment]
> BTW: As per https://github.com/open-source-parsers/jsoncpp#building-and-testing-with-scons using scons to build jsoncpp is actually deprecated.

Then we should probably build jsoncpp with cmake and cmake with bundled jsoncpp so we avoid bootstrap issue?

**Comment by pbregener** [comment]
Updated accordingly to use bundled jsoncpp again. Now someone should probably update the jsoncpp package to actually use cmake for building.

**Comment by pbregener** [comment]
Pushed an additional commit updating to cmake 3.8.1.

cc @ncopa @jirutka

**Comment by pbregener** [comment]
ping

**Comment by pbregener** [comment]
ping @ncopa

**Comment by pbregener** [comment]
This also needs to be picked into `3.6-stable`. Thanks! :)

**Comment by pbregener** [comment]
Just a quick reminder that this should also be backported to 3.6 @ncopa @jirutka

**Comment by ncopa** [comment]
why is this needed for `3.6-stable`?

**Comment by pbregener** [comment]
Because it's a patch release with regression fixes for cmake 3.8.0 which is included in Alpine 3.6.

**Pull request closed without merging**
