### PR TITLE
community/vips: upgrade to 8.8.3

### PR DESCRIPTION
**Pull request by andypost**
Ref https://github.com/libvips/libvips/releases/tag/v8.8.3

PS https://github.com/alpinelinux/aports/pull/11938

### CODE REVIEW

**Comment by andypost** [comment]
Fails because of https://github.com/libvips/libvips/issues/1426

**Comment by andypost** [comment]
@wjordan disabling orc allows to build but not sure it ok

**Comment by andypost** [comment]
Could be changed to use new orc https://github.com/libvips/libvips/issues/1426#issuecomment-549030339

**Comment by maxice8** [comment]
I have an MR for updating orc to it https://gitlab.alpinelinux.org/alpine/aports/merge_requests/1035 , after that i can look into vips-orc integration

**Comment by andypost** [comment]
@maxice8 filed follow-up https://github.com/alpinelinux/aports/pull/12094

**Pull request closed without merging**
