### PR TITLE
testing/py2-linecache2: modernize and fix build

### PR DESCRIPTION
**Pull request by maxice8**
- lighten dependency load
- Add missing dependencies
- Work around pbr git problems
- Explain why check is disabled

### CODE REVIEW

**Comment by Ikke** [comment]
@itoffshore Can you review?

**Comment by itoffshore** [comment]
@Ikke - yes `PR` is ok

**Comment by Ikke** [comment]
PSF is not a valid SPDX identifier. I've checked the source, but could not find any indication of a license either.

I see testing-cabal/linecache2#10 is still open. The author specifies it's in the setup.py metadata. The only relevant license I could find in the SPDX list is [Python License 2.0][Python-2.0], in which case the license identifier is: 'Python-2.0'.

If that's correct, could that be updated in the same PR?

[Python-2.0]:https://spdx.org/licenses/Python-2.0.html

**Comment by maxice8** [comment]
Thanks for noticing, somehow i messed up my abuild

**Pull request closed without merging**
