### PR TITLE
update RethinkDB to latest stable version (2.3.4)

### PR DESCRIPTION
**Pull request by 1ma**
Nothing more than what the title says, really.

### CODE REVIEW

**Comment by 1ma** [comment]
Apparently the RethinkDB obj files are built fine, but the building of one of the external dependencies (the v8 JS engine) fails.

I tried to build the project on my own workstation so I could get my hands on the ```./build/external/v8_3.30.33.16_install.log``` file referenced by the Travis build (it can be found [here](https://gist.github.com/1ma/2a2e69c9a18749f5f8a0d3a0da5594b4)), but I'm afraid I'm not very familiar with Python and I am unable to figure out how to fix this.

I'm sorry to ping you out of the blue @clandmeter, but I saw that you are the one who originally ported RethinkDB to Alpine (https://github.com/rethinkdb/rethinkdb/issues/4437). Do you happen to know what might have broke since the 2.3.1 release?

**Comment by dalanmiller** [comment]
Also CC'ing @atnnn who might have some knowledge on this.

**Comment by AtnNn** [comment]
It looks like shared memory isn't setup properly. Perhaps mounting `/dev/shm` would fix the issue.

This issue has a similar error  https://github.com/docker/docker/issues/1683

**Comment by jirutka** [comment]
This package has been updated in dddfa696dcbef80b8169cb1079eef23cbbd25491.

**Pull request closed without merging**
