### PR TITLE
testing/litespeed: upgrade to 1.4.27

### PR DESCRIPTION
**Pull request by vakartel**

### CODE REVIEW

**Comment by jirutka** [comment]
Where is this libressl patch from? Have you written it or is it copied from somewhere?

**Comment by vakartel** [comment]
I wrote it myself

**Comment by andypost** [comment]
Fixes in "snmp_monitoring" fixed upstream

@vakartel why not try to promote patch to upstream https://github.com/litespeedtech/openlitespeed

**Comment by vakartel** [comment]
@andypost 
Good idea. I pushed it

**Comment by andypost** [comment]
Refs
- https://github.com/litespeedtech/openlitespeed/pull/77
- https://github.com/litespeedtech/openlitespeed/pull/78

**Comment by fabled** [comment]
There's new release that apparently contains the fixes?

**Comment by vakartel** [comment]
@fabled 
Ok, I upgrade squash it

**Pull request closed without merging**
