### PR TITLE
main/tar: upgrade to 1.32

### PR DESCRIPTION
**Pull request by J0WI**
This replaces https://github.com/alpinelinux/aports/pull/6449

### CODE REVIEW

**Comment by ncopa** [comment]
Dot bother create PRs for the stable branches. I can cherry-pick this commit myself.

Thanks!

**Comment by J0WI** [comment]
> Dot bother create PRs for the stable branches. I can cherry-pick this commit myself.

Does this also apply to packages where the version in stable braches differs from master (e.g. `main/mariadb` or `community/tor`)?

**Comment by ncopa** [comment]
> > Dot bother create PRs for the stable branches. I can cherry-pick this commit myself.
> 
> Does this also apply to packages where the version in stable braches differs from master (e.g. `main/mariadb` or `community/tor`)?

No. It only applies for this specific PR, because I already started with the backporting.

**Comment by J0WI** [comment]
Fixed in e14f30776ab55c428f268da628c29a97fe8885af, thanks!

**Pull request closed without merging**
