### PR TITLE
main/strace: upgrade to 4.21

### PR DESCRIPTION
**Pull request by andypost**

### CODE REVIEW

**Comment by andypost** [comment]
Added `gawk` otherwise make fails with 
`checking whether mpers.sh m32 -m32 works... ./mpers.sh: line 77: gawk: not found`

**Comment by nmeum** [comment]
Build fails on ppc64le and aarch64:

* http://build.alpinelinux.org/buildlogs/build-edge-ppc64le/main/strace/strace-4.21-r0.log
* http://build.alpinelinux.org/buildlogs/build-edge-aarch64/main/strace/strace-4.21-r0.log

**Comment by andypost** [comment]
Looking through logs I can't find any errors, all 3 build passes & package

**Comment by nmeum** [comment]
That's because it was fixed in 69d6896b7d57d5e7dc9596fd3b4721205cb7bca8

**Comment by andypost** [comment]
Ah, thanx! Good to know

**Pull request closed without merging**
