### PR TITLE
community/z: new aport

### PR DESCRIPTION
**Pull request by icyphox**
Adds the [`z`](https://github.com/rupa/z) package.

### CODE REVIEW

**Comment by maxice8** [comment]
Should start in testing/

**Comment by icyphox** [comment]
@maxice8 ah my bad. Shall I fix it in this PR, or should I open a new one?

**Comment by maxice8** [comment]
On Mon, 23 Sep 2019 10:02:26 -0700
Anirudh <notifications@github.com> wrote:

> @maxice8 ah my bad. Shall I fix it in this PR, or should I open a new
> one?
> 

Please fix in the PR by amending the commit and force pushing. Never
open a new PR

**Comment by icyphox** [comment]
> Please fix in the PR by amending the commit and force pushing. Never
open a new PR

Done and noted. Thanks.

**Comment by maxice8** [comment]
Merged with a few important changes that you should make next time:

- Replaced spaces with tabs
- removed doc() { default_doc ; }
- set to noarch

**Pull request closed without merging**
