### PR TITLE
community/gitea: upgrade to 1.10.0

### PR DESCRIPTION
**Pull request by 6543**
as title

### CODE REVIEW

**Comment by 6543** [comment]
1.10.0 :tada: is out !!

**Comment by maxice8** [comment]
commit should be:

`<repository>/<pkgname>: upgrade to <pkgver>`

**Comment by 6543** [comment]
@maxice8 is alpine's CI doing something special since `make test-sqlite` PASS on your CI [link](https://drone.gitea.io/go-gitea/gitea/15841/1/14)?

**Comment by 6543** [comment]
Is anything blocking this?

**Pull request closed without merging**
