### PR TITLE
community/php7: Upgrade to 7.0.14

### PR DESCRIPTION
**Pull request by andypost**
Security release http://php.net/archive/2016.php#id2016-12-08-1

### CODE REVIEW

**Comment by jirutka** [comment]
It fails on aarch64 (see [log](http://build.alpinelinux.org/buildlogs/build-edge-aarch64/community/php7/php7-7.0.14-r1.log)), could you please try to fix it?

**Comment by andypost** [comment]
will check asap

**Comment by andypost** [comment]
```
/bin/bash /home/buildozer/aports/community/php7/src/php-7.0.14/libtool --silent --preserve-dup-deps --mode=compile gcc  -Isapi/phpdbg/ -I/home/buildozer/aports/community/php7/src/php-7.0.14/sapi/phpdbg/ -DPHP_ATOM_INC -I/home/buildozer/aports/community/php7/src/php-7.0.14/include -I/home/buildozer/aports/community/php7/src/php-7.0.14/main -I/home/buildozer/aports/community/php7/src/php-7.0.14 -I/home/buildozer/aports/community/php7/src/php-7.0.14/ext/date/lib -I/usr/include/libxml2 -I/usr/include/enchant -I/usr/X11 -I/usr/include/freetype2 -I/usr/include/imap -I/home/buildozer/aports/community/php7/src/php-7.0.14/ext/mbstring/oniguruma -I/home/buildozer/aports/community/php7/src/php-7.0.14/ext/mbstring/libmbfl -I/home/buildozer/aports/community/php7/src/php-7.0.14/ext/mbstring/libmbfl/mbfl -I/usr/include/mysql -I/usr/include/pspell -I/home/buildozer/aports/community/php7/src/php-7.0.14/TSRM -I/home/buildozer/aports/community/php7/src/php-7.0.14/Zend  -Os  -I/usr/include -Os -fvisibility=hidden   -c /home/buildozer/aports/community/php7/src/php-7.0.14/sapi/phpdbg/phpdbg_webdata_transfer.c -o sapi/phpdbg/phpdbg_webdata_transfer.lo 
/tmp/ccbaoFgl.s: Assembler messages:
/tmp/ccbaoFgl.s:570: Error: operand 3 should be an integer register -- `mul x0,x0,1048576'
/tmp/ccbaoFgl.s:571: Error: operand 3 should be an integer register -- `smulh x1,x0,1048576'
```

Looking at [docs](https://developer.arm.com/docs/den0024/latest/6-the-a64-instruction-set/62-data-processing-instructions/622-multiply-and-divide-instructions) I guess problem in that both instructions work with registers only but direct data given

Maybe it needs some compiler flags to put this _1048576_ into some register before operation

**Comment by andypost** [comment]
The only similar bug https://bugs.php.net/bug.php?id=70015

**Pull request closed without merging**
