### PR TITLE
community/certbot: run test instead of check

### PR DESCRIPTION
**Pull request by ganwell**
* python2 setup.py check does nothing

### CODE REVIEW

**Comment by ganwell** [comment]
This is definitely not happen on my test machine.

**Comment by ganwell** [comment]
@andypost It is generally not allowed to write to tmp during check? Where should the tests write to? Or is it just a travis issue.

**Comment by andypost** [comment]
I got the same locally but tests are passed & after them I see
```
Ran 877 tests in 38.403s

OK
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 154, in shouldRollover
    self.stream = self._open()
  File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/tmp/tmpk2TC_6/logs/letsencrypt.log'
...
```

**Comment by ganwell** [comment]
Thanks, I'll investigate.

**Comment by nmeum** [comment]
Try:

`options="!checkroot"`

Additionally, I noticed that the `check()` downloads stuff from the internet:

```
…
Downloading https://files.pythonhosted.org/packages/93/3b/90c057508e2ce82d8700051e49ef537ccbd5d6bbad5bd0fb72cb6c0a6b69/acme-0.27.1-py2.py3-none-any.whl#sha256=0d42cfc9050a2e1d6d4e6b66334df8173778db0b3fe7a2b3bcb58f7034913597
…
```

Didn't investigate this further but in case it's downloading a python dependency it would be nice to package that dependency instead and add it to `checkdepends`. To make the build pass in an `abuld rootbld` environment `options="net"` is required as well otherwise.

**Comment by andypost** [comment]
There's a lib https://pkgs.alpinelinux.org/packages?name=py-acme&branch=edge
```
>>> certbot: Entering fakeroot...
running test
Searching for acme>=0.26.0
Reading https://pypi.org/simple/acme/
Downloading https://files.pythonhosted.org/packages/93/3b/90c057508e2ce82d8700051e49ef537ccbd5d6bbad5bd0fb72cb6c0a6b69/acme-0.27.1-py2.py3-none-any.whl#sha256=0d42cfc9050a2e1d6d4e6b66334df8173778db0b3fe7a2b3bcb58f7034913597
Best match: acme 0.27.1
Processing acme-0.27.1-py2.py3-none-any.whl
Installing acme-0.27.1-py2.py3-none-any.whl to /home/travis/build/alpinelinux/aports/community/certbot/src/certbot-0.27.1/.eggs
writing requirements to /home/travis/build/alpinelinux/aports/community/certbot/src/certbot-0.27.1/.eggs/acme-0.27.1-py2.7.egg/EGG-INFO/requires.txt
Installed /home/travis/build/alpinelinux/aports/community/certbot/src/certbot-0.27.1/.eggs/acme-0.27.1-py2.7.egg
running egg_info
```

**Comment by andypost** [comment]
btw `py-acme` is the subpackage of this one

**Comment by andypost** [comment]
Checked locally `options="net !checkroot"` does not solve issue with log files

**Comment by ganwell** [comment]
It's this magic at play: https://github.com/pyscaffold/pyscaffold/issues/71

In my opinion magic should always be optional. And it is very strange magic, it seems to download its own (sub)package from somewhere. In theory all the source code to test it is already there, no download needed.

I lost motivation, when I write software, I always have a way to run tests for developers, with all the magic and convenience-functions and way for distributions that only tests the code that is built.

**Comment by ganwell** [comment]
I wanted the test to detect if the right versions of dependencies are present in alpine and there are no API mismatches. The test downloading its dependencies, makes it useless.

Unless somebody has an idea how to solve this, I will close the PR in few days.

**Comment by andypost** [comment]
@ganwell  needs rebase after 0d21931f

**Comment by ganwell** [comment]
Sorry, I forgot to close this one.

**Pull request closed without merging**
