### PR TITLE
main/ghostscript: upgrade to 9.50

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
Packages depending on `ghostscript` should be rebuild against the new version.

**Comment by Cogitri** [comment]
Why? The soname hasn't changed.

**Comment by J0WI** [comment]
https://www.ghostscript.com/doc/9.50/News.htm
https://abi-laboratory.pro/index.php?view=objects_report&l=ghostscript&v1=9.27&v2=9.50

There are some breaking changes. Especially `imagemagick` makes use of the changed `-dSAFER` option.

**Comment by Cogitri** [comment]
Ugh and they didn't increase the soname, that's a bit annoying...

Anyway, mind bumping the deps in this PR then too?

**Comment by J0WI** [comment]
I'm a bit worried that this will lead in merge conflicts, but if you're going to merge it right now I can do this.

**Comment by Cogitri** [comment]
Well, I don't have access to main, but I'll review it tomorrow and hopefully someone with the magic bits can take a look soon then.

**Comment by J0WI** [comment]
Done

**Comment by Cogitri** [comment]
FWIW one of imagemagick6's tests fails:

`FAIL: tests/validate-composite.tap 1`

**Pull request closed without merging**
