### PR TITLE
main/linux-vanilla: support NFS 4.1/4.2

### PR DESCRIPTION
**Pull request by tomalok**
AWS Elastic File System works best with NFS v4.1, Docker's cloudstor:aws plugin is
not able to start without it.

This commmit simply brings all the config files in sync with config-vanilla.s390x,
which already enables NFS v4.1/4.2.

### CODE REVIEW

**Comment by tomalok** [comment]
@ncopa I guess I didn't get this here in time for your latest kernel update...  Will update soon.

**Comment by tomalok** [comment]
going to start again with a fresh branch

**Comment by myhro** [comment]
@tomalok You not only don't need to re-create a PR to reorganize its commits, [as this is discouraged by the contribution documentation][1]. Please rebase the commits instead.

[1]: https://github.com/alpinelinux/aports/blob/master/.github/CONTRIBUTING.md#clean-up-a-pull-request-pr

**Comment by tomalok** [comment]
Thanks, I'll be sure to remember for next time.

**Pull request closed without merging**
