### PR TITLE
community/py-watchdog: split into py2- and py3- packages

### PR DESCRIPTION
**Pull request by maxice8**
- py3- is required for testing py3-werkzeug

### CODE REVIEW

**Comment by Ikke** [comment]
Only py-sphinx-watchdog seems to depend on this package. It might be possible to switch to just python3.

**Comment by maxice8** [comment]
Nothing depends on py-sphinx-watchdog, are there any pointers i can take to see if it is better to switch to python3 or provide both ?

**Comment by prspkt** [comment]
@maxice8 [This](https://wiki.alpinelinux.org/wiki/APKBUILD_examples:Python) will probably cover any missing points related to Python. You can use the last 2 commits from [here](https://github.com/prspkt/aports/commits/py-watchdog) to upgrade `py-watchdog` to python3 only.

**Comment by maxice8** [comment]
Thanks

**Pull request closed without merging**
