### PR TITLE
[3.7] community/imagemagick6: security upgrade to 6.9.10-68

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
:ping_pong: @jirutka

**Comment by J0WI** [comment]
:ping_pong: @ncopa

**Comment by ncopa** [comment]
```
  CCLD     utilities/stream         
make[1]: Leaving directory '/home/ncopa/aports/community/imagemagick6/src/ImageMagick6-6.9.10-68'
>>> imagemagick6: Entering fakeroot...         
make: *** No rule to make target 'check'.  Stop.
>>> ERROR: imagemagick6*: check failed
```

**Comment by J0WI** [comment]
I reverted the removal of `cd "$builddir"`

**Comment by jirutka** [comment]
Could you please confirm that it works locally when you build it on Alpine v3.7? The Travis script is not designed for testing on stable branches, it always runs on `edge`, and I currently don’t have a testing environment with v3.7 installed.

**Comment by J0WI** [comment]
All tests pass locally on Alpine 3.7 `x86_64`

**Comment by jirutka** [comment]
I’ve merged it in 0f7ecd696d28f3be16555aca8525bf57ed8a0669. Thanks!

**Comment by ncopa** [comment]
> I’ve merged it in [0f7ecd6](https://github.com/alpinelinux/aports/commit/0f7ecd696d28f3be16555aca8525bf57ed8a0669). Thanks!

Thanks!

**Pull request closed without merging**
