### PR TITLE
community/rethinkDB: add register settings for aarch64

### PR DESCRIPTION
**Pull request by ossdev07**
added register settings for AARCH64 platform

Signed-off-by: ossdev07 <ossdev@puresoftware.com>

### CODE REVIEW

**Comment by ossdev07** [comment]
@maxice8 @rnalrd Please have a look on this PR ..
Arm Version #41 will be fixed by these changes ..

**Comment by maxice8** [comment]
The commit title is wrong

**Comment by maxice8** [comment]
It is missing a pkgrel= bump

**Comment by ossdev07** [comment]
> The commit title is wrong

i could not understand completely ..
can you please suggest ?

**Comment by ossdev07** [comment]
> It is missing a pkgrel= bump

you mean my branch is not debased with alpine master ?

**Comment by maxice8** [comment]
`community/rethinkdb: add register settings for aarch64`

**Comment by maxice8** [comment]
> you mean my branch is not re based with alpine master ?

you need to rebase against master and add 1 to the value of the variable `pkgrel`, you can use `apkgrel -a community/rethinkdb`

**Comment by ossdev07** [comment]
> > you mean my branch is not re based with alpine master ?
> 
> you need to rebase against master and add 1 to the value of the variable `pkgrel`, you can use `apkgrel -a community/rethinkdb`

done
 please verify ..

**Comment by ossdev07** [comment]
@maxice8 @rnalrd please integrate this path if things looks good to you

**Comment by maxice8** [comment]
Please use a proper commit `community/rethinkdb: add register settings for aarch64`

**Comment by ossdev07** [comment]
> Please use a proper commit `community/rethinkdb: add register settings for aarch64`

done , please merge
Thanks ..

**Comment by maxice8** [comment]
Done

**Pull request closed without merging**
