### PR TITLE
main/lighttpd: upgrade to 1.4.52

### PR DESCRIPTION
**Pull request by andypost**
Ref http://www.lighttpd.net/2018/11/28/1.4.52/

Closes https://bugs.alpinelinux.org/issues/9725

### CODE REVIEW

**Comment by tcely** [comment]
It is probably not important, but this is a security upgrade since 1.4.51 was, correct?

**Comment by andypost** [comment]
As I see by ref link only bugfixes and no CVEs found

**Comment by tcely** [comment]
I agree no CVE was listed in the announcement, but it does say "security fixes" right near the top.

https://www.lighttpd.net/2018/10/14/1.4.51/

**Comment by andypost** [comment]
Thanks, missed this 2
- [core,security] process headers after combining folded headers
- [mod_userdir] security: skip username “.” and “..”

**Pull request closed without merging**
