### PR TITLE
testing/audiocd-kio: new aport

### PR DESCRIPTION
**Pull request by PureTryOut**

### CODE REVIEW

**Comment by PureTryOut** [comment]
Hmm, for some reason CI tries to build `audiocd-kio` _before_ `libkcompactdisc` which then obviously fails as it's a depdency...

**Comment by maxice8** [comment]
I also get

```
ERROR: unsatisfiable constraints:
  libkcddb-dev (missing):
    required by: .makedepends-audiocd-kio-20190625.144120[libkcddb-dev]
```

**Comment by PureTryOut** [comment]
Huh, I've seem to have lost that aport in my Git foo. Fixed it.

**Comment by PureTryOut** [comment]
This package now builds correctly, it's ready for merging.

**Comment by maxice8** [comment]
Will do when I get home

**Comment by maxice8** [comment]
@PureTryOut mind closing this ? algitbot seems to have choked, the PR is actually merged

**Comment by PureTryOut** [comment]
Thanks!

**Pull request closed without merging**
