### PR TITLE
community/py3-ruamel.yaml: upgrade to 0.16.5

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
@maxwell-k

**Comment by maxwell-k** [comment]
Before this PR a few tests fail and they are disabled with `pytest --deselect`

After this PR a few more tests fail and all of the tests are disabled with `options="!check"`

I would prefer to be consistent; for me the best approach is to keep disabling tests that cause a problem with `--deselect`.

I hope to have more time to look at this tomorrow.

**Comment by maxice8** [comment]
Deselect the offending tests

**Comment by maxwell-k** [comment]
LGTM! 🎉

**Pull request closed without merging**
