### PR TITLE
AVR GCC toolchain

### PR DESCRIPTION
**Pull request by stwa**

### CODE REVIEW

**Comment by stwa** [comment]
I'm closing this pull request because travis can not build it (compiling gcc exceeds the maximum logfile size) and I do not want to burn resources.

**Comment by ScrumpyJack** [comment]
Can you email the patches to alpine mailing list? They get manged by patchwork.
Also, see http://bugs.alpinelinux.org/issues/5194

**Comment by stwa** [comment]
Please let me rework the patches to improve some minor parts (coding style etc.)
Are there any advantages posting them to the list over committing them here? What's the preferred „alpine-way“?

**Comment by ScrumpyJack** [comment]
Posting to the mailng list is prefered. It's sort of old skool but it work well within the Alpine Linux dev env. The patches get automatically pulled into patchwork http://patchwork.alpinelinux.org/project/aports/list/ and managed from there. Thanks again for these.

**Pull request closed without merging**
