### PR TITLE
main/redis: upgrade to 4.0.8

### PR DESCRIPTION
**Pull request by TBK**

### CODE REVIEW

**Comment by ncopa** [comment]
I have noticed that the test suite leaves a lot of redis-server processes. I have mulitple times needed to `killall -9 redis-server` on the build servers. Do you think you could have a look at that and maybe report it upstream?

**Comment by TBK** [comment]
Sure, I will look into the issue.

**Comment by fabled** [comment]
I fixed the testsuite zombie processes too. It needed `procps` in `checkdepends`.

**Comment by TBK** [comment]
@fabled Thanks 👍

**Pull request closed without merging**
