### PR TITLE
main/ceph: upgrade to 14.2.4

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by iggy** [comment]
I'm trying to move ceph to `main/` first. Then I'll upgrade it.

**Comment by iggy** [comment]
You will need to rebase this now that ceph was moved to `main` please.

**Comment by J0WI** [comment]
Done

**Comment by J0WI** [comment]
0e7c9762c76cad2e17887f55f89fd6fdd5ffe68b

**Pull request closed without merging**
