### PR TITLE
testing/php7: new aport

### PR DESCRIPTION
**Pull request by andypost**
http://php.net/archive/2016.php#id2016-12-01-3
New version of PHP language

### CODE REVIEW

**Comment by andypost** [comment]
Removed `tidy-buffio.patch` and updated `tidy-buffio.patch`

**Comment by andypost** [comment]
upgraded API version to `20160303`

**Comment by andypost** [comment]
There's misunderstanding with https://bugs.alpinelinux.org/issues/6524

**Comment by dvejmz** [comment]
Can anyone provide an update as to what's going to happen with this PR? Is it waiting until 3.5 gets released as pointed out [here](https://bugs.alpinelinux.org/issues/6524)?

**Comment by clandmeter** [comment]
This PR will be merged after 3.5 is branched/released as it was released to late to do proper testing for 3.5.

**Comment by jirutka** [comment]
What is this? We already have php7, in community.

**Comment by clandmeter** [comment]
It should go to community ones we branch.

**Comment by dvejmz** [comment]
@jirutka This PR is or PHP 7.1 though, which is currently unavailable in all of the repositories. I guess the PR title could've specified that :)

**Comment by andypost** [comment]
There's big rewrite proposed, so I think better to close this one in favour of https://github.com/alpinelinux/aports/pull/639

Also 3.5 released so edge can have 7.1 now

**Comment by andypost** [comment]
Closing in favour of #639

**Pull request closed without merging**
