### PR TITLE
comunity/geany-plugins: check if .so exist before moving it

### PR DESCRIPTION
**Pull request by rgdoliveira**
Check if .so exist before trying to move it

### CODE REVIEW

**Comment by jirutka** [comment]
Why it doesn’t exist? Some plugins are not built on ppc64le or are never built on any arch, because they are not in the upstream source anymore…?

**Comment by ncopa** [comment]
Seems to happen on x86_64 as well
````
>>> geany-plugins-gproject*: Running split function gproject...
mv: cannot stat '/home/ncopa/aports/community/geany-plugins/pkg/geany-plugins/usr/lib/geany/gproject.so': No such file or directory
>>> ERROR: geany-plugins-gproject*: gproject failed
>>> ERROR: geany-plugins*: prepare_subpackages failed
>>> ERROR: geany-plugins: all failed
````

**Comment by ncopa** [comment]
i think this is fixed with the geany/geany-plugins update

**Comment by ncopa** [comment]
fixed with commit 9bb70c50838ddc33d379e25b41c70688b2051f5e

**Pull request closed without merging**
