### PR TITLE
community/rust: update to 1.32.0

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by Cogitri** [comment]
This is just so we can bootstrap 1.34 afterwards and isn't actually meant to compile other packages with it.

**Comment by Ikke** [comment]
CI Failed because it took >1h

**Comment by J0WI** [comment]
I was able to compile `1.32.0` and `1.33.0` with these patches, but not `1.34.0`

**Comment by Cogitri** [comment]
What do you mean?

**Comment by andypost** [comment]
@Cogitri I bet @J0WI mean that 1.34.1 released

**Comment by Cogitri** [comment]
Ah. We can't use that immediately though, we have to cycle 1.32->1.34.1 (hopefully, maybe we have to hop onto 1.33 before) due to Rust not really minding backwards compatibility with old compilers for rustc.

**Comment by Ikke** [comment]
This is a duplicate of #6071

**Pull request closed without merging**
