### PR TITLE
php5-suhosin / php5-apcu: restore to community

### PR DESCRIPTION
**Pull request by itoffshore**
Both of these packages were removed due to being [non core extensions](https://github.com/alpinelinux/aports/commit/71d024f91830436d4007f82ec37a25da282dbca9). I've been using them both for almost a year without any problems.

[suhosin](https://suhosin.org) improves the security of `php5`.

### CODE REVIEW

**Comment by jirutka** [comment]
php5 is outdated, why you don’t use php7 instead?

**Comment by itoffshore** [comment]
[suhosin7](https://github.com/sektioneins/suhosin7) is alpha at the moment

**Comment by andypost** [comment]
php5 has security support til Dec'18 http://php.net/supported-versions.php
It makes sense to keep it while a lot of docker images using it & a lot of environments still not possible to migrate to php7.

btw php5-apcu is very needed without it we have to stick on 3.5 alpine but somehow updates stuck in https://github.com/alpinelinux/aports/pull/2634

**Comment by andypost** [comment]
Also would be great to return php5-xdebug

**Pull request closed without merging**
