### PR TITLE
main/gtk+2.0: upgrade to 2.24.32

### PR DESCRIPTION
**Pull request by xpecex**
ref http://ftp.gnome.org/pub/gnome/sources/gtk+/2.24/gtk+-2.24.32.news

### CODE REVIEW

**Comment by ncopa** [comment]
the commit message looks weird:
````
commit 6a0c196b23a4c39ab3f5a2cbc0420afcc6548350 (HEAD -> master)
Author: Pedro Filipe ...
Date:   Mon Sep 24 20:29:37 2018 -0300

    main/gtk+2.0: upgrade to 2.24.32
    
    main/gtk+2.0: add pango

````

There are no signs of added pango in the commit.
Please read [this](https://github.com/alpinelinux/aports/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request-pr) on how to write good commit messages.

**Comment by tanertas** [comment]
Good to see gtk-2 is still getting updates. I still don't know why gtk-3 considered as an upgrade.

**Comment by ncopa** [comment]
i fixed the commit message for you this time. thanks!

**Comment by ncopa** [comment]
> Good to see gtk-2 is still getting updates.

Surprised me too.

**Pull request closed without merging**
