### PR TITLE
community/apk-file: move from testing

### PR DESCRIPTION
**Pull request by drebrez**

### CODE REVIEW

**Comment by Cogitri** [comment]
Mind force pushing to restart CI?

**Comment by Cogitri** [comment]
Also, maintainer ping @drebrez

**Comment by drebrez** [comment]
@Cogitri I've rebased on master and force pushed but the build still fails and I can't understand why

**Comment by kaey** [comment]
CI fails because go build downloads all dependecies, puts them in $GOPATH/mod and then builds. Go unsets `w` flag on downloaded modules to prevent their corruption (from text editors or running tests).
Easy fix there would be to use vendor dir
`export GOFLAGS="-mod=vendor"` or `make GOFLAGS=-mod=vendor`

**Comment by Cogitri** [comment]
Seems like it's still failing with the same error.

**Comment by drebrez** [comment]
@Cogitri Found another commit (https://github.com/alpinelinux/aports/commit/bda9fed96df73fbcb57f586aa89d859541653e43) fixing the same error and applied the same changes, now build works fine.

**Pull request closed without merging**
